### ISSUE TITLE
function waitFor() and waitForSelector(), there is one problem, code as follow:

### ISSUE THREAD

**Issue by andypeker** [casperjs/casperjs#1008]
this.waitForSelector('#addPas888senger',
	      	   function OK_continue(){
	      	   	   this.echo("After less than 8s, Continue ...");
	      	   },
	      	   function oops_timeout(){this.then(
	      	   	   function(){
	      	   	   	   this.captureSelector(“__SomeException__.png", '#addPassenger');
	      	   	   	   this.echo("I will wait 8s for some button, but it does not appear~");
	      	   	   })
	      	   },
	      	   8000);
this.echo("Good News~");
		  this.captureSelector("__Article__.png", '#addPassenger');

i found that: file __Article__.png was created before file __SomeException__.png. Is there some solution for this situation ?

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:** 
Looks to be a stale help request. Assuming you've moved on to better and cooler things.  Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
