### ISSUE TITLE
In CasperJS, Is this.wait() considered same as this.then() ?

### ISSUE THREAD

**Issue by andypeker** [casperjs/casperjs#1010]
var casper = require("casper").create({
    logLevel: "info",
    verbose: true,
    onError: function(self, _msg){
      this.capture("error.png");  
      console.log("onError===========================\nFATAL:" + _msg);  
      self.exit();
    }
});

casper.start("./test_test.html", function(){
   this.echo("Ok, Start ~");
})

function _Test(){
    this.waitForSelector('#addPas888senger',
        function OK_continue(){
            this.echo("After less than 8s, Continue ...");
        },
  	function oops_timeout(){
            this.capture("SomeException.png");
            this.echo("I will wait 8s for some button, but it does not appear~");
   	},
    	8000);

    this.echo("Good News~");
    this.wait(5000, function(){
    	this.capture("Article.png");
    });
}
//As a conclusion, Article.png will executed after SomeException.png for 8s and 5s.

function _Test2(){
    this.waitForSelector('#addPas888senger',
        function OK_continue(){
            this.echo("After less than 8s, Continue ...");
        },
 	function oops_timeout(){
   		this.then(function(){
            		this.capture("SomeException.png");
           	 	this.echo("I will wait 8s for some button, but it does not appear~");
   		});
   	},
    	8000);

    this.echo("Good News~");
    this.wait(3000, function(){
    	this.capture("Article.png");
    });
}
//As a conclusion, Article.png will executed after SomeException.png for 8s and 3s.

/*
casper.then(function (){
    this.waitForSelector('#addPas888senger',
        function OK_continue(){
            this.echo("After less than 8s, Continue ...");
        },
   	function oops_timeout(){
   		this.then(function(){
        	    	this.capture("SomeException.png");
           	 	this.echo("I will wait 8s for some button, but it does not appear~");
   		});
   	},
    	8000);

    this.echo("Good News~");
    this.capture("Article.png");
})
//As a conclusion, Article.png will executed before SomeException.png for 8s, 
//and Article.png will be executed immediately.
*/

casper.then(function(){
    this.waitForSelector('#addPas888senger',
        function OK_continue(){
            this.echo("After less than 8s, Continue ...");
        },
   	function oops_timeout(){
            this.capture("SomeException.png");
            this.echo("I will wait 8s for some button, but it does not appear~");
   	},
    	8000);

    this.echo("Good News~");
    this.wait(2000, function(){
    	this.capture("Article.png");
    });
});
//As a conclusion, Article.png will executed after SomeException.png for 8s and 2s.

//casper.then(_Test);

casper.run(function(){
   this.echo("Ok, Finished~");
   this.exit();
})

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:** 
Looks to be a stale help request. Assuming you've moved on to better and cooler things.  Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
