### ISSUE TITLE
Error while loading route : TypeError :'undefined' is not a function.

### ISSUE THREAD

**Issue by ramasamykanna** [casperjs/casperjs#1014]
Hi i am testing web application using casperjs.

I am testing 2 navigation in a javascript file.I am testing navigation like below

casper.test.begin('condos clicking page navigation', 1, function suite(test) {
     casper.start('http://localhost:3000')
     .thenClick("a[href*='/condos']")
     .thenOpen('http://localhost:3000/firstpage', function() {
      this.test.assertHttpStatus(200);
})
.run(function() {
       test.done();
});
});

casper.test.begin('browser back click from condos', 1, function suite(test) {
       casper.start('http://localhost:3000/condos')
       .back()
       .thenOpen('http://localhost:3000', function() {
        this.echo(this.getCurrentUrl());
        this.test.assertHttpStatus(200);
})
.run(function() {
        test.done();
});
});

casper.test.begin('condo-search clicking page navigation', 1, function suite(test) {
       casper.start('http://localhost:3000')
      .thenClick("a[href*='/condo-search']")
      .thenOpen('http://localhost:3000/secondpage', function() {
      this.test.assertHttpStatus(200);
})
.run(function() {
      test.done();
});
});

casper.test.begin('browser back click from condo-search', 1, function suite(test) {
       casper.start('http://localhost:3000/condo-search')
       .back()
       .thenOpen('http://localhost:3000', function() {
       this.echo(this.getCurrentUrl());
       this.test.assertHttpStatus(200);
})
.run(function() {
       test.done();
});
});

Then i am getting like below

Site console.log:  init

Site console.log:  Error while loading route: TypeError: 'undefined' is not a function (evaluating 'this.send.bind(this,
'find')')

Site console.log:  init

Site console.log:  Error while loading route: TypeError: 'undefined' is not a function (evaluating 'this.send.bind(this,
'find')')

If i am testing only one navigation then no problem.If more than one navigation test if i am doing iam getting this error.

Please give some solution for this

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:** 
Looks to be a stale help request. Assuming you've moved on to better and cooler things.  Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
