### ISSUE TITLE
support static html snapshot output format

### ISSUE THREAD

**Issue by requiredfield** [casperjs/casperjs#1015]
From ariya/phantomjs#12459:

> Currently phantomjs can output rendered snapshots as various image formats (png, jpg, pdf). Is there any interest in adding support for a static html output format, à la [archive.today](https://archive.today/) (which is built on phantomjs but closed source :cry:)? "static html" just means that the snapshot of the DOM taken after rendering the page is saved as plain old static html, with dynamic elements like `<script>`, `<object>`, `<canvas>`, etc. either stripped or replaced with embedded images of their rendered results as appropriate. CSS could be inlined à la [premailer](http://premailer.dialect.ca/), and images could be embedded with data: urls if desired, so that a single .html file could be saved containing everything it needed to render the page without referring to any external resources. Also, a custom `rewrite_link` function could be provided so that links in any `<a href>` elements could be rewritten to preserve navigability between multiple html snapshots. If there is interest in this I'd be happy to try to contribute!

Ariya [replied](https://github.com/ariya/phantomjs/issues/12459#issuecomment-52475366) that this is outside PhantomJS's scope. Is there interest in this from CasperJS?

Thanks, and thanks for the great work on CasperJS.

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:** 
Looks to be a stale request. Assuming you've moved on to better and cooler things.  Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
