### ISSUE TITLE
"page.resource.requsted" event is never emmited on urlencoded URLs

### ISSUE THREAD

**Issue by hver** [casperjs/casperjs#1025]
You can find the full description of this bug on the pull request page: https://github.com/n1k0/casperjs/pull/1024

In short, on the urls with russian symbols (they are mostly urlencoded, look at ru.wikipedia.org) **"page.resource.requsted"** event is never fired, because the _page.onResourceRequested()_ function should urldecode requsted URL before comparison.

I've added the code for decoding the URL before the comparison.

But the tests has detected a problem with not correctly urlencoded urls: the event **"page.resource.requsted"** is not fired on URLs which were created with _escape()_ function. Also the **"page.resource.received"** event is not fired.

I have commented the unit test which checks the escaped URL, so the PR could be merged, but the problem with escaped URLs is still there.
I have not so much experience with PhantomJS or CasperJS to fix it directly, but would like to discuss it to find the way to do it.

**Comment by kensoh** [comment]
@hver bumping up, this has been some time ago but not sure whether it now works. This sounds like will affect many websites using Cyrillic alphabets in URL.

**Comment by kensoh** [comment]
Closing this issue for now as it hasn't gotten new replies or discussion for 2+ years. But do reopen if anything!
