### ISSUE TITLE
Added assertJsonResponse/assertXmlResponse/assertHTMLResponse assertions

### ISSUE THREAD

**Issue by mickaelandrieu** [casperjs/casperjs#1028]
Hi everyone,

I test some of my REST APIs with CasperJS and I believe some assertions could be added to Tester API to help:
- assertJsonResponse()
- assertXmlResponse()
- assertHTMLResponse()

Maybe this could be added to a specific module called api-tester for instance...

What do you think @n1k0 @laurentj @mduvall

**Comment by kensoh** [comment]
Closing this issue for now as it hasn't gotten new replies or discussion for 2+ years. But do reopen if anything!
