### ISSUE TITLE
Casperjs not loading/executing external javascript

### ISSUE THREAD

**Issue by JanGrond** [casperjs/casperjs#1042]
Hi all,

I made a simple Casperjs script that tries to parse all links on the test website below.

However it seems that some links are created by an external javascript (http://start.be/_lis/js/start-js-2011-02.js). Concretely divs are enriched with a elements.
If I use this.getHTML(), I see clearly that the a elements aren't yet created. 
However if in Firefox I use the show generated source of I inspect with Firebug, I clearly see those hyperlinks.

The javascript turns this:
<div id="l456752"><span>Smet Boring</span> <i>(Dessel) </i></div>
into
this
<div id="l456752"><a title="" target="_blank" href="http://start.be/j?456752">Smet Boring</a> <i>(Dessel) </i><i></i></div>

I would suppose Casperjs also loads + executes external javascripts. Or am I missing something?

Jan

Used:
casperjs-1.1-beta3-0
phantomjs-1.9.7
testwebsite: http://grond-en-afbraak.start.be/

----------------------

var links = [];
var casper = require('casper').create();

function getLinks() {
    var links = document.querySelectorAll('div#measure_content a');
    return Array.prototype.map.call(links, function(e) {
        return e.getAttribute('href');
    });
}

casper.start('http://grond-en-afbraak.start.be/', function() {
});

casper.then(function() {
	this.wait(2000);
    links = this.evaluate(getLinks);
});

casper.run(function() {
    // echo results in some pretty fashion
    this.echo(links.length + ' links found:');
    this.echo(' - ' + links.join('\n - ')).exit();
});

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:** 
Looks to be a stale help request. Assuming you've moved on to better and cooler things.  Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.

**Comment by masud-technope** [comment]
Facing exactly the same problem with yahoo finance pages. Can you guys lead me to a fix?

**Comment by frankred** [comment]
Having the same issue.  On linux arch 64-bit `npm@3.10.8` `node@v6.9.1`.
