### ISSUE TITLE
casper.fill causes error: '/%[sdj%]/g' is not a function

### ISSUE THREAD

**Issue by gaboom** [casperjs/casperjs#1044]
The following simple step that works perfectly well on Linux fails on Windows:

    casper.then(function() {
        casper.fill('form[action="/search"]', {
            q: 'casperjs'
        }, true);
    });

With a cryptic error message:

```
[info] [phantom] waitFor() finished in 40ms.
[info] [phantom] Step anonymous 5/6 http://www.google.hu/ (HTTP 200)
FAIL TypeError: '/%[sdj%]/g' is not a function (evaluating 'casper.fill('form[ac
tion="/search"]', {
        q: term
      }, true)')
#    type: uncaughtError
#    file: C:\DEV\src\casperjs-maven-starter\src\test\TestSearch.js:14
#    error: '/%[sdj%]/g' is not a function (evaluating 'casper.fill('form[action
="/search"]', {
        q: term
      }, true)')
#           TypeError: '/%[sdj%]/g' is not a function (evaluating 'casper.fill('
form[action="/search"]', {
#                   q: term
#                 }, true)')
#               at C:/DEV/src/casperjs-maven-starter/src/test/pages/SearchPage.j
s:14
#               at runStep (C:/Users/XXX/AppData/Local/npm/node_modules/casp
erjs/modules/casper.js:1553)
#               at checkStep (C:/Users/XXX/AppData/Local/npm/node_modules/ca
sperjs/modules/casper.js:399)
#    stack: not provided
```

The cryptic **/%[sdj%]/g** is in utils.js

casperjs 1.1.0-beta3
phantomjs 1.9.7
python portable 2.7.5

Full example available: https://github.com/gaboom/casperjs-maven-starter I removed all other code, moved only this statement into the test, removed arguments, still, repeatedly same error.
Works at Ubuntu@home, fails at Windos@work. Please advise. What am I doing wrong?

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:** 
Looks to be a stale help request. Assuming you've moved on to better and cooler things.  Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
