### ISSUE TITLE
exists('*') sometimes incorrectly returns null

### ISSUE THREAD

**Issue by jswu** [casperjs/casperjs#1045]
When loading some urls (I know of only this one so far), `exists()` seems to incorrectly return `null`. Reproduce with:
```
var casper = require('casper').create();

var badUrl = 'http://www.10four.org/';
var goodUrl = 'http://www.casperjs.org/';

casper.start(badUrl, function() {
  var val = this.exists('*');
  console.log(badUrl + ' exists?: ' + val);
});

casper.thenOpen(goodUrl, function() {
  var val = this.exists('*');
  console.log(goodUrl + ' exists?: ' + val);
});

casper.run();
```
Output:
```
http://www.10four.org/ exists?: null
http://www.casperjs.org/ exists?: true
```
Calling `document.querySelectorAll` indicates that the selector does in fact exist. `debugHTML()` also correctly outputs the HTML.

My ultimate goal was to take screenshots with `captureSelector`, but traced it down to this issue (I gave up after tracing it to the call to `page.evaluate`). I'm currently working around it by directly querying `page` for the page dimensions.

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:** 
Looks to be a stale help request. Assuming you've moved on to better and cooler things.  Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
