### ISSUE TITLE
Do you plan to integrate TAP reporter in the future?

### ISSUE THREAD

**Issue by matenadasdi** [casperjs/casperjs#1047]
You have xunit report right now, but do you plan any other reports like TAP, html, etc?

**Comment by soundyogi** [comment]
What is the status of this? TAP would be really nice

**Comment by chipironcin** [comment]
+1

**Comment by tchia04** [comment]
+1

**Comment by jefleponot** [comment]
@chipironcin  @tchia04 

Could you propose a PR ?
I have no idea about TAP reporter ...

**Comment by chipironcin** [comment]
So, afaik, it is basically creating a file similar to the xml output CasperJS already creates (xunit) but with a TAP format so other tools can read that file directly.

I may be able to work on a PR on my free time, but that would be in a couple of weeks at least

**Comment by kensoh** [comment]
Archiving issue using **ARCHIVE** label as CasperJS, like PhantomJS, is not actively maintained for now.
