### ISSUE TITLE
parallel runs of casperjs

### ISSUE THREAD

**Issue by retorquere** [casperjs/casperjs#1051]
I have a script like this (on windows) that starts multiple `casperjs` processes in parallel

    start casperjs test out/test-01.js
    start casperjs test out/test-02.js
    start casperjs test out/test-03.js
    start casperjs test out/test-04.js
    start casperjs test out/test-05.js
    start casperjs test out/test-06.js
    start casperjs test out/test-07.js
    start casperjs test out/test-08.js
    start casperjs test out/test-09.js
    start casperjs test out/test-10.js
    start casperjs test out/test-11.js
    start casperjs test out/test-12.js
    start casperjs test out/test-13.js
    start casperjs test out/test-14.js
    start casperjs test out/test-15.js
    start casperjs test out/test-16.js
    start casperjs test out/test-17.js
    start casperjs test out/test-18.js
    start casperjs test out/test-19.js
    start casperjs test out/test-20.js

The tests however appear to be serialized; this is a simple test that logs in and changes a password (https://gist.github.com/fd32e6e50ebfd2301c61), and the script dutifully launches 20 console windows, the casper output appears in each *in turn*, and the next (random) casperjs only seems to start when the previous one finishes (console goes away).

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:** 
Looks to be a stale help request. Assuming you've moved on to better and cooler things.  Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
