### ISSUE TITLE
content type in sendAJAX

### ISSUE THREAD

**Issue by hasanyousuf** [casperjs/casperjs#1054]
Hi!

I am having issue with content-type in sendAJAX function. my rest interface is expecting a json file while as sendAJAX is sending header as "text/html".

  var response2 = this.evaluate(function(myUrl) {
    try{
        return JSON.parse(__utils__.sendAJAX(myUrl, 'POST', JSON.stringify({"username": "username", "password": "password"}), false,
					      {"Content-Type": "application/json"}
	));
    }catch(e){
      console.log(e);
    }
    }, {myUrl: myUrl});

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:** 
Looks to be a stale help request. Assuming you've moved on to better and cooler things.  Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
