### ISSUE TITLE
encoding issue with sendAJAX

### ISSUE THREAD

**Issue by hasanyousuf** [casperjs/casperjs#1055]
Hi!
I am having issue with reading json object and it donot display correct characters. It should display "Toftenäs" but it shows "Toftens". This problem was resolved before but it appeared again. It works fine with Phantomjs for your ready reference.

casper.test.begin('my testing', 1, function suite(test) {
casper.start(function(){
//Browser agent is defined
	casper.userAgent('Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.66 Safari/537.36');
});

var url ="http://www.google.com";
casper.open(url, function(){
});

casper.then(function(){
	var myvar="http://api.openweathermap.org/data/2.5/weather?lat=57.9900&lon=11.31";
	jsonObject_fields = this.evaluate(function(myvar) {
		try {
			return JSON.parse(__utils__.sendAJAX(myvar, 'GET', null, false));
		} catch (e) {
			console.log("Error in fetching json object");
		}
	}, {
		myvar : myvar
	});
	try{
	//require('fs').write('result.json',JSON.stringify(jsonObject_fields));
	require("utils").dump(JSON.stringify(jsonObject_fields.name));
	}
	catch(e)
	{
		console.log("Error is: "+e);
	}
});
casper.run(function(){
	test.done();
});
});

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:** 
Looks to be a stale help request. Assuming you've moved on to better and cooler things.  Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
