### ISSUE TITLE
Status code handler for page resources...

### ISSUE THREAD

**Issue by tohann** [casperjs/casperjs#1056]
Hello!

I'm trying to use a status handler to detect broken images. I added an event listener for 404s:

```
casper.on('http.status.404', function(resource) {
    casper.test.error('Resource not found: '+resource.url);
});
```

But that didn't seem to work. The message was never shown for images I knew were broken.

I dug into the CasperJs code and found what I think is causing it in casper.js. In `Casper.prototype.handleReceivedResource`, _I think_ the following `if` is causing all page resources to not get processed. It appears to only allow the page URL itself to pass.

```
if (utils.decodeUrl(resource.url) !== this.requestUrl) {
    return;
}
```

Once I commented out that `if`, all the resources were getting processed and status codes were being emitted.

Is this the intended behavior, to only emit status code events for the page itself and not resources in the page?

**Comment by kensoh** [comment]
@tohann not sure if this is now supported. Is this still an important use case for you? I'm a CasperJS user browsing through some past issues. Also PhantomJS is in a transition period, plus headless Chrome/Firefox coming. Exciting times for web automation!

**Comment by tohann** [comment]
Thank you for the follow-up @kensoh ! We are no longer using CasperJS so this is no longer a use case for us.

It seems like it could still be a valid use case for CasperJS users. My thought was to either 1) log any missing images or resources when a test runs, or 2) have scripts written specifically for monitoring images that go missing (particularly for category or product pages on e-commerce websites). These could be missing from a bad deployment, a misconfiguration, or any number of causes.

**Comment by kensoh** [comment]
Thanks @tohann for your quick reply and sharing your thoughts! I'm a CasperJS user for couple of years, now browsing through open issues to see if anything I can help.

I see.. That's true, existing users can still benefit from your inputs above. Bumping this for current maintainer Jef's thoughts.

**Comment by kensoh** [comment]
Bumping up and copying maintainer @jefleponot

**Comment by kensoh** [comment]
Archiving issue using **ARCHIVE** label as CasperJS, like PhantomJS, is not actively maintained for now.
