### ISSUE TITLE
basic auth failures 

### ISSUE THREAD

**Issue by jorahood** [casperjs/casperjs#1057]
I'm creating a new issue after [1023](https://github.com/n1k0/casperjs/issues/1023) got closed because nobody thought it was a bug I guess...

The problem occurs when trying to reset the http basic auth credentials with setHttpAuth() or page.customHeaders('Authorization': 'Basic '+...) in subsequent test files, but not if you embed the new authentication parameters in the url itself.

Interestingly, when using the Casper onResourceRequested callback to look at the request headers with

casper.options.onResourceRequested = function(C, requestData, request) {
    console.log(require('utils').dump(requestData.headers));
};
the Authorization header looks correct in the requestData.headers object, but it does not match the actual sniffed Authorization header. So Casper thinks it is sending the correct Authorization header when it isn't. We can get setHttpAuth() to provide the correct authorization header after a previous setHttpAuth() if we provide incorrect credentials embedded in the url in an open() statement somewhere in between. Otherwise the old headers persist.

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:** 
Looks to be a stale help request. Assuming you've moved on to better and cooler things.  Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
