### ISSUE TITLE
Odd behavior sending keys to an input with capitalized "type" attribute

### ISSUE THREAD

**Issue by justinklemm** [casperjs/casperjs#1058]
I happen to be running a test on a site with some invalid HTML. Specifically, the "type" attribute of some of the input elements is capitalized, like this: `<input type="Password" name="pwd">`. That `Password` should technically be lowercase. Casper checks for only the lowercase version to validate the element -- which is ok. However, it's behavior is strange. Since the `type` attribute is not valid, it [skips the clicking step](https://github.com/n1k0/casperjs/blob/bc1a5ba6440c60081b2cf444030107c6801c0153/modules/casper.js#L1616) (which focuses the element), but still sends the keys... This results in the keys being sent to the last field that was in focus.

It seems like a more appropriate behavior might be to make the validity check case-insensitive (as it is in most browsers), or to perform the focusing click regardless of validity. (Note: that [options.reset](https://github.com/n1k0/casperjs/blob/bc1a5ba6440c60081b2cf444030107c6801c0153/modules/casper.js#L1621) works regardless of input validity, and even clicks). Or perhaps, some other alternative... However, skipping the focus, but still sending the keys seems like a dangerous combination.

I'm happy to send one or more pull requests with some options. Thanks for your time!

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:**
Looks to be a stale help request. Assuming you've moved on to better and cooler things.  Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
