### ISSUE TITLE
Modulated testing

### ISSUE THREAD

**Issue by cablegunmaster** [casperjs/casperjs#1060]
Trying to build up a modulated Casper JS for behaviour driven development I noticed a small bug.

Whenever I run my test one by one nothing seems to be wrong.
If I run my test all together it will result in a error of asserts not working anymore. ( elements not being waited upon or elements not being shown) while one by one it works.

Update: It seems if multiple instances of casperJS in 1 file is creating this issue. testing if seperated files makes a difference.

this goes for the Tester module of Casper.

**Comment by paazmaya** [comment]
Can you provide a minimal working example?

**Comment by cablegunmaster** [comment]
Ah, just close this one as it's at the moment not possible to recreate. Please close down.
Its because of the linear problem with CasperJS. 

It has to go through a while loop and does the while echo's first and after that it execute the tasks within the while loop, as just once with the last variable number.

On the top of my head:
     for(i = 0; i < 10; i++)
     { 
      console.log('Test:'+i );
      dosomething(i); //could be anything with the variable i ( variable i is always last value of the while or for loop)
     }

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:** 
Looks to be a stale help request. Assuming you've moved on to better and cooler things.  Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
