### ISSUE TITLE
Support tags to run only part of your suite

### ISSUE THREAD

**Issue by jorgetutor** [casperjs/casperjs#1063]
Is there any way to run only a part of the test like behat does? If not it could be really helpful.

Behat groups test with tags, this way you can run a subset of test on your site.

The aim:

$ casperjs --tags '@orm,@database'
$ casperjs --tags 'ticket,723'
$ casperjs --tags '@orm&&@fixtures'
$ casperjs --tags '~@javascript'
$ casperjs --name 'number has'

The first command will run only features or scenarios which have either the @orm or the @database tag.

The second command will run only features or scenarios which have either the @ticket or the @723 tag.

The third command will run only features or scenarios with both the @orm and the @fixtures tags.

The forth command will run all features or scenarios except those, that marked with @javascript tag. In other terms, ~ means excluding.

The fifth command will run only features and scenarios that contain "number has" in their title.

Behat doc: http://behat.readthedocs.org/en/v2.5/guides/6.cli.html

**Comment by paazmaya** [comment]
Would you like to create a pull request for adding this feature?

**Comment by rdpanek** [comment]
+1

**Comment by kensoh** [comment]
Bumping up.. I guess a lot have developed past 2 years in test automation space. Ariya also discouraged using PhantomJS for testing due to differences from actual user browsers.

I solely use CasperJS for my automation purpose (more for process automation), but don't know how prevalent it is used for test automation.

**Comment by kensoh** [comment]
Closing this issue for now as it hasn't gotten new replies or discussion for 2+ years. But do reopen if anything!
