### ISSUE TITLE
.click function

### ISSUE THREAD

**Issue by cablegunmaster** [casperjs/casperjs#1069]
tried a         this.click('input[type="submit"]');  
Failed miserably and kept failing for some reason assert says it exists.
Fix: this.click("input[type='submit']");

somehow it didnt want to click with single quotes.

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:** 
Looks to be a stale help request. Assuming you've moved on to better and cooler things.  Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
