### ISSUE TITLE
client scripts for popup

### ISSUE THREAD

**Issue by partus** [casperjs/casperjs#1070]
seems like currently there is no way to inject scripts by default  into all popups, like they are injected into main window (by passing `{clientScripts: ['clientscript.js']}` ).

I used `this.page.injectJs("allClientScripts.js");` to overcome it, but it's suitable only when the page is not reloaded, or they must be  injected  again on each  page change.
so, it would be great  to have a mechanism to inject certain scripts into all popup windows.

**Comment by paazmaya** [comment]
Can you provide a minimal working example in which such popups appear?

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:** 
Looks to be a stale help request. Assuming you've moved on to better and cooler things.  Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
