### ISSUE TITLE
for in behaviour

### ISSUE THREAD

**Issue by cablegunmaster** [casperjs/casperjs#1072]
*Working testcaseexample shall be shortly included.*

I created a test in which the casperjs would scrape a webpage for links check if its a xls file and download it.

Now I wanted to make it for multiple webpages. So I created a for loop around it
The odd behaviour is I created a normal for in and one that includes casperJS. The one with CasperJS failed miserably. (always output everything at once and not synchronious) Anyway to serialize it? to make it run one variable at the time?

// runs good without casperJS but with casperJS it becomes a mess. 
var url = {'folder1': 'http://websiteonetoscrape.com', 'folder2': 'http://websitetwotoscrape.com'};
for(var key in url) {
this.echo( key +" " +url[k]);
}

Casper array output:
folder2 http://websiteonetoscrape.com
folder2 http://websitetwotoscrape.com

Normal expected behaviour just running it to the console log:
folder1 http://websiteonetoscrape.com
folder2 http://websitetwotoscrape.com

I know casperJS is asynchronious but can there be parts which be synchroniously written? to ensure consistency of the script? Or is this just a bug?

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:** 
Looks to be a stale help request. Assuming you've moved on to better and cooler things.  Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
