### ISSUE TITLE
Writing xunit file for dir of tests not working on linux

### ISSUE THREAD

**Issue by alexhancock** [casperjs/casperjs#1075]
I'm aware this issue has been raised before, but I haven't found a conclusive answer as to why something like this would happen differently on different systems.

Background Info...
* Using `1.1.0-beta3` version of casperjs
* On my machine, I'm using OSX Yosemite. On the jenkins build slave, I am using Ubuntu.
* Using coffee-script for all tests

When I have a repo with three test files under a dir called `tests` I run...

`casperjs test tests/ --xunit=results.xml`

I get the output xunit file working fine on OSX every time, and it never works on linux.

Things I have tried...

* Changing the order of command line arguments
* Using all debug options for casper and phantom to try to gain insight into what's happening
* Using a full file path instead of a relative path

The only thing I have noticed which causes it to work on linux reliably is only running the test command with one of the test files, instead of a dir. (ie... `casperjs test tests/one.coffee --xunit=results.xml).

When I do that, it correctly outputs the reports.xml file for all three of my files. It just never works on linux when I run `casperjs test` for the entire dir.

**Comment by BIGjuevos** [comment]
We've recently solved lots of bugs with xunit, please check out the latest version 1.1.1
