### ISSUE TITLE
DOM click() does not work in evaluate()

### ISSUE THREAD

**Issue by vporton** [casperjs/casperjs#1080]
HTML DOM click() inside evaluate() does not work.

The message
remote message caught: TypeError: 'undefined' is not a function (evaluating 'document.body.click()')
is produced by the following script.

var casper = require('casper').create();

casper.on('remote.message', function(msg) {
//     console.log('remote message caught: ' + msg);
  this.echo('remote message caught: ' + msg);
})

casper.start("http://google.com", function() {
  this.evaluate(function() {
    try {
      document.body.click();
    }
    catch(e) {
      console.log(e);
    }
  });
});

casper.run();

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:** 
Looks to be a stale help request. Assuming you've moved on to better and cooler things.  Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
