### ISSUE TITLE
casper.visible doesn't report true for "display: flex"

### ISSUE THREAD

**Issue by ryanfields** [casperjs/casperjs#1085]
I'm not sure if this is an issue with casper's code, or with PhantomJS itself.  It doesn't appear that the casper.visible test works for elements with a display setting of ```flex```.

**Comment by paazmaya** [comment]
I started doing PR for this, but added tests seem to pass without any changes to `clientutils.js`....

Do I need to do something else besides running `make selftest` for testing that?

(and of course creating the fixture with `display: flex` and `inline-flex`)

**Comment by nchase** [comment]
looks like this was fixed by #1668, can this be closed?
