### ISSUE TITLE
Casperjs not able to open certain URLs

### ISSUE THREAD

**Issue by surenderthakran** [casperjs/casperjs#1086]
I tried using casper's minimal script to get the title of a page for "http://india.gov.in/" but it never printed the title. The network showed an almost continous download.
The script works for other URLs but not for india.gov.in.
I am using phantomjs 1.9.8 and casperjs 1.1.0-beta3.

**Comment by BIGjuevos** [comment]
According to the related phantomjs issue, it looks like a version above 2.0 solves this.

**As part of a cleanup effort:** 
Looks to be a stale help request. Assuming you've moved on to better and cooler things.  Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
