### ISSUE TITLE
what is the difference between casper.options.remoteScript and casper.options.clientScript ?

### ISSUE THREAD

**Issue by andypeker** [casperjs/casperjs#1087]
in my auto test, where will be many function that will be called in every steps; and those function are implemented in some files(.js), i want to "require" those files(.js) and call functions in them.

and now i "require" those files(.js) by this method: casper test --include=xx/yy/zz/file1.js,zz/yy/xx/file2.js,xx/zz/file3.js  testcase/testcase2.js  --xunit=file333.xml, but i am not satisfied with this method. so ,how could i do ?

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:** 
Looks to be a stale help request. Assuming you've moved on to better and cooler things.  Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
