### ISSUE TITLE
Selector with xPath and namespaces

### ISSUE THREAD

**Issue by isholgueras** [casperjs/casperjs#1088]
Hi,

Maybe that's not a bug, and it's only ignorance :S. 

I'm having some troubles selecting a tag in a RSS+XML file which is defined by a namespace.

With xPath you can access any element by the string "//tagName". xPath will find wherever the tag is placed. With tags defined by namespaces is similar "//foo:singers".

The problem it that with CasperJS (I'm running 1.1.0-DEV - ab8f3ded3a30919165869e9d2a3ab85e571916f9) I cannot access the element "atom:link"

```
//This code works
test.assertExists({
    type: 'xpath',
    path: "//item"
}, "item element exists.");

//This don't work
test.assertExists({
    type: 'xpath',
    path: "//atom:link"
}, "atom:link element exists.");
```

I've explained my concrete trouble it in stackoverflow (http://stackoverflow.com/questions/26931073/how-to-select-tags-with-namespaces-in-casperjs), but happens with other tags defined by namespaces

Am I doing anything wrong? Is it a bug in CasperJS's xPath module?

Thanks

**Comment by kensoh** [comment]
@isholgueras this is an interesting thread! I have used XPath a lot but haven't come across the type of selectors you demonstrated. I'm a CasperJS user for 2 years, not sure if this is now supported.

**Comment by kensoh** [comment]
Closing this issue for now as it hasn't gotten new replies or discussion for 2+ years. But do reopen if anything!
