### ISSUE TITLE
Casperjs sometimes cannot proceed to next step

### ISSUE THREAD

**Issue by sklyukin** [casperjs/casperjs#1089]
I have a pretty simple script: 
```coffee
casper.start 'http://www.media.net', ->
  this.fill 'form#userloginform',
    username: params.username
    password: params.password
  , true

thenStep = ->
  console.log 'then called'
timeoutStep = ->
  console.log 'timeout called'
check = ->
  console.log 'check called'
  res = this.getCurrentUrl().indexOf('home') > 0
  console.log res
  res
casper.waitFor check, thenStep, timeoutStep, 5000
```

In 100% of cases I see `[debug] [phantom] url changed to "https://control.media.net/home"`
In 100% of cases just after I see something like this: 
```
true
[info] [phantom] waitFor() finished in 2735ms.
``` 

Then I have in 50% of cases  `then called` (that is expected of course). 
But in 50% of cases behavior is very strange -  neither thenStep neither timeoutStep is called. I just got this in 30 seconds: 
```
[debug] [phantom] url changed to "https://control.media.net/home"
check called
[debug] [phantom] Successfully injected Casper client-side utilities
true
[info] [phantom] waitFor() finished in 2167ms.
[error] [phantom] Script timeout of 30000ms reached, exiting.
Script timeout of 30000ms reached, exiting.
```

I've tried a lot of combinations with then / waitForUrl etc - in any solutions it is the same - it correctly open 'home' page, but then casperjs seems lose understanding where he is (in 50% of cases), he cannot proceed to next step or timeout step of wait function. That is of course related somehow to this particular website and how login page is working here.

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:** 
Looks to be a stale help request. Assuming you've moved on to better and cooler things.  Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
