### ISSUE TITLE
Casper crashes with WithPopup function

### ISSUE THREAD

**Issue by jefleponot** [casperjs/casperjs#1095]
WithPopup crash findByURL

CasperError: Couldn't find popup with url containing 'https://"'
  /usr/share/casperjs/modules/pagestack.js:138 in findByURL
  /usr/share/casperjs/modules/pagestack.js:90 in find
  /usr/share/casperjs/modules/casper.js:2353 in _step
  /usr/share/casperjs/modules/casper.js:1553 in runStep
  /usr/share/casperjs/modules/casper.js:399 in checkStep

This function requires url parameter, it's not convenient : window's title or name could be better.

**Comment by kensoh** [comment]
Closing as Popup commits in #1354 are in and also with recent wave of Popup fixes.
