### ISSUE TITLE
how can i find the file throw click the a link

### ISSUE THREAD

**Issue by zxscj** [casperjs/casperjs#1102]
html code:  demo.html

<a id="download" href="http://***/demo.exe">download demo</a>

casperjs code
//...
casper.start('demo.html').then(function() {
    this.click('#download');
});
//...

issue
does it down load the demo.exe? if so, and where is the demo.exe download to?

**Comment by paazmaya** [comment]
Can you provide a miminal working example?

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:**
Looks to be a stale help request. Assuming you've moved on to better and cooler things.  Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
