### ISSUE TITLE
DOM selection fails when the query is too long

### ISSUE THREAD

**Issue by Forethinker** [casperjs/casperjs#1103]
On http://textofvideo.nptel.iitm.ac.in/indiv_courses.php?id=101
`document.querySelectorAll("body > table > tbody > tr:nth-child(2) > td > table > tbody > tr:nth-child(1) > td:nth-child(2) > table > tbody > tr:nth-child(3) > td > table > tbody > tr > td:nth-child(2) > table > tbody > tr:nth-child(4) > td:nth-child(2) > table > tbody > tr > td > table > tbody > tr:nth-child(3) > td")`

would not return be any results via casperjs, even though it works fine on the web browser.

The problem seems to be with the length of the query because

`document.querySelectorAll("body > table > tbody > tr:nth-child(2) > td > table > tbody > tr:nth-child(1) > td:nth-child(2) > table > tbody > tr:nth-child(3) > td > table > tbody > tr")`
works fine.

I found a similar bug with `__utils__.getElementByXPath`

The workaround for me was to first use `querySelector()` and then use `getElementsByTagName()`

**Comment by paazmaya** [comment]
Could you share a minimal working example?

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:**
Looks to be a stale help request. Assuming you've moved on to better and cooler things.  Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
