### ISSUE TITLE
click button using casperjs

### ISSUE THREAD

**Issue by nimishseraphim** [casperjs/casperjs#1104]
My html for "Add to cart" look like below:

<div ng-show="item.Allowed=='true' && item.RequiresApproval=='false'" class="">

  <button class="smallbutton" ng-click="addToCart()" ng-disabled="!canAddToCart()">Add to Cart</button>

   </div>

I am using casperjs to click on Add to cart ,please suggest how can we click it.

I used below, but it is not working:

casper.then(function() {

casper.clickLabel('Add to Cart', 'button');

casper.wait(3000);

casper.emit('take.snapshot');

});

**Comment by iolloyd** [comment]
You need to provide more information. Do you have a case using similar code for a different selector that does work, for example?

**Comment by erikmontes** [comment]
What error are you getting?

**Comment by jr-duboc** [comment]
Maybe you're clicking before phantomJS or SlimeJS has loaded the label.
I suggest using [Waitforselector ](http://casperjs.readthedocs.org/en/latest/modules/casper.html#waitforselector)  instead of just casper.then()

**Comment by lizjulien** [comment]
+1 We have the same problem, just a simple this.click('button'). Can't get it work.

Any suggestion ?

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:**
Looks to be a stale help request. Assuming you've moved on to better and cooler things. Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
