### ISSUE TITLE
Command line arguments always interpreted as integers

### ISSUE THREAD

**Issue by russss** [casperjs/casperjs#1105]
I need to pass a command line argument which has a leading zero, but this always gets stripped off by the argument parser. Both `--argument=01234` and `--argument="01234"` lead to `casper.cli.get("argument")` returning the integer "1234".

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:**
Looks to be a stale help request. Assuming you've moved on to better and cooler things.  Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
