### ISSUE TITLE
casper.test.[setUp, tearDown] memory through multiple test file

### ISSUE THREAD

**Issue by Grogdunn** [casperjs/casperjs#1109]
If i write multiple test file and i run its with:

```
casperjs test DIR_WITH_TESTS_FILE/
```

containing 

> a.js
> b.js

and in first test file i do:

```
casper.test.setUp(function(done){
  //do something
  casper.echo('setup')
})
casper.test.tearDown(function(done){
  //do something
  casper.echo('teardown')
 })
 //...tests...
```

in second file I don't want to perform no setup or teardown function I expect these function are "lost" with switching file but the echo is executed.

A work around is bind a noop function in second file, but this seems wrong for me..

**Comment by paazmaya** [comment]
Can you share the `a.js` and `b.js` with minimal working example code so this could be added to the tests?

**Comment by Grogdunn** [comment]
Sure!
this is my folder structure:
```
$ tree
.
└── test
    ├── a.js
    └── b.js
```
and from there i run the tests with the following command
> casperjs test test/

a.js file:
```javascript
casper.test.setUp(function(){
  casper.setupIsDone = true;
  casper.echo('setup')
})
casper.test.tearDown(function(){
  casper.setupIsDone = false;
  casper.echo('teardown')
 })


casper.test.begin("Hello from file A", 1, function(test) {
  test.assertTruthy(casper.setupIsDone);
  test.done();
});
```
b.js file:
```javascript
casper.test.begin("Hello from file B", 1, function(test) {
  test.assertFalsy(casper.setupIsDone); //should be false or undefined.
  test.done();
});
```

**Comment by paazmaya** [comment]
It would seem that you are writing the `setupIsDone` property to a global object (`casper`), which is available the given session.
Those probably should be done via file scoped variables, but not sure what is the further use case, is that even possible...

**Comment by bguerin** [comment]
http://docs.casperjs.org/en/latest/testing.html#advanced-techniques

a.js
```
casper.test.begin("Hello from file A", 1, {
  setUp: function(test) {
    this.setupIsDone = true;
    test.info('setup')
  },

  tearDown: function(test) {
    this.setupIsDone = false;
    test.info('teardown')
  },

  test: function(test) {
    test.assertTruthy(this.setupIsDone);
    test.done();
  }
});
```

**Comment by Grogdunn** [comment]
if you run the test you can see the echo line log.
the global variable "setupIsDone" isn't necessary.
Without the variable and with useless assertions the I've the following output:
```
Test file: /home/lcaenazzo/Desktop/casperJS test/test/a.js                      
# Hello from file A
setup
PASS Subject is truthy
teardown
Test file: /home/lcaenazzo/Desktop/casperJS test/test/b.js                      
# Hello from file B
setup
PASS Subject is falsy
teardown
PASS 2 tests executed in 0.041s, 2 passed, 0 failed, 0 dubious, 0 skipped.      
```
As you see the second test file is initializated with same setup/teardown procedure


p.s.
sorry for bad english

**Comment by bguerin** [comment]
nope ..

```
Test file: /tmp/casperjs/a.js                                                   
# Hello from file A
setup
PASS Subject is truthy
teardown
Test file: /tmp/casperjs/b.js                                                   
# Hello from file B
PASS Subject is falsy
PASS 2 tests executed in 0.042s, 2 passed, 0 failed, 0 dubious, 0 skipped.      
```

a.js
```
casper.test.begin("Hello from file A", 1, {
  setUp: function(test) {
    this.setupIsDone = true;
    test.info('setup')
  },

  tearDown: function(test) {
    this.setupIsDone = false;
    test.info('teardown')
  },

  test: function(test) {
    test.assertTruthy(this.setupIsDone);
    test.done();
  }
});
```

b.js
```
casper.test.begin("Hello from file B", 1, function(test) {
  test.assertFalsy(casper.setupIsDone); //should be false or undefined.
  test.done();
});
```

**Comment by Grogdunn** [comment]
ahh ok with config object with setup and teardown property runs ok, but if i would perform these procedure for every test in file a.js (but not for b.js)
```javascript
casper.test.begin("Hello from file A", 1, {
  setUp: function(test) {
    this.setupIsDone = true;
    test.info('setup')
  },

  tearDown: function(test) {
    this.setupIsDone = false;
    test.info('teardown')
  },

  test: function(test) {
    test.assertTruthy(this.setupIsDone);
    test.done();
  }
});

casper.test.begin("Hello from file A1", 1, function(test) {
  //I want this one wrapped in setup/teardown procedure
  test.done();
});
//a lot of other tests.
```
with config object I must write for each test the setup and tear down properties?

**Comment by bguerin** [comment]
I do not understand why you use several ```casper.test.begin``` ...

**Comment by rdpanek** [comment]
For each test file, in Grogdunn's case a and b test files. Right?

**Comment by Grogdunn** [comment]
because I've organized tests in some file (one for functionality) and in these file I've wrote tests (one single for feature) for clear and simple separation of tests.

Indeed in tests of casperjs there is a lot of "casper.test.begin" for single file for instance https://github.com/n1k0/casperjs/blob/master/tests/suites/tester/assert.js

**Comment by rdpanek** [comment]
Sorry, I thought, no test file, but test case

**Comment by kensoh** [comment]
Closing this issue for now as it hasn't gotten new replies or discussion for 2+ years. But do reopen if anything!
