### ISSUE TITLE
back button

### ISSUE THREAD

**Issue by MathiasLund** [casperjs/casperjs#1111]
Hi!
I know it has been addressed before, but I can't seem to get my page to go back and I'm not that good with casperjs yet...
My script is like this:

         casper.wait(15000, function() {
			if(this.exists(x("(//tr[@class='pager'])[1]//a[preceding-sibling::span[not(span)]][1]"))) {
				loop();
			} else {
				this.capture("billede1.png");
				this.then(function() {
					this.back();
					console.log("attempting to go back");
				});
				
				casper.wait(15000, function() {
					this.capture("billede2.png");
				});
				
			}
		});

and it works very well apart from the fact that it doesn't go back :( the two screenshots are identical..
does anyone have an idea what to do?
thanks in advance!
I appreciate your help :)

**Comment by noma4i** [comment]
CasperJS is built on top of PhantomJS so I believe that you are able utilize this: http://phantomjs.org/api/webpage/method/go-back.html

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:**
Looks to be a stale help request. Assuming you've moved on to better and cooler things.  Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
