### ISSUE TITLE
Casperjs won't execute on server

### ISSUE THREAD

**Issue by MathiasLund** [casperjs/casperjs#1114]
Hi there!
I've been trying to get casperjs to run on my ubuntu server, but I simply can't get it to work. 
It shows me the standard casperjs message when I type "casperjs" in console, and phantomjs seems to be working as well. However, my script won't run - even though it works on my home computer.

http://docs.casperjs.org/en/latest/installation.html
I install it through git because it is the only instance that doesn't give me errors.

"sudo npm -g install casperjs" gives me this error:

    sh: 1: node: not found
    npm WARN This failure might be due to the use of legacy binary "node"
    npm WARN For further explanations, please read
    /usr/share/doc/nodejs/README.Debian

    npm ERR! error rolling back Error: Refusing to delete: /usr/local/bin/casperjs not in      /usr/local/lib/node_modules/casperjs
    npm ERR! error rolling back     at clobberFail (/usr/share/npm/lib/utils/gently-rm.js:41:12)
    npm ERR! error rolling back     at next (/usr/share/npm/lib/utils/gently-rm.js:27:14)
    npm ERR! error rolling back     at /usr/share/npm/lib/utils/gently-rm.js:36:12
    npm ERR! error rolling back     at Object.oncomplete (fs.js:107:15)
    npm ERR! error rolling back  casperjs@1.1.0-beta3 { [Error: Refusing to delete: /usr/local/bin/casperjs not in /usr/local/lib/node_modules/casperjs] code: 'EEXIST', path: '/usr/local/bin/casperjs' }
    npm ERR! weird error 127
    npm ERR! not ok code 0

and homebrew gives me this error when it tries installing phantomjs:

     ==> Installing casperjs dependency: phantomjs
     ==> Downloading https://github.com/ariya/phantomjs/archive/1.9.8.tar.gz
     Already downloaded: /home/mathias/.cache/Homebrew/phantomjs-1.9.8.tar.gz
     ==> ./build.sh --confirm --jobs 1 --qt-config -openssl-linked
     /usr/bin/ld: cannot find -lfontconfig
     collect2: error: ld returned 1 exit status
     make[1]: *** [../bin/phantomjs] Error 1
     make[1]: Leaving directory `/tmp/phantomjs-lX6SMI/phantomjs-1.9.8/src'
     make: *** [sub-src-phantomjs-pro-make_default-ordered] Error 2

      READ THIS:       https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

I appreciate all help!

**Comment by paazmaya** [comment]
The Brew error is due to PhantomJS build dependencies missing, here `cannot find -lfontconfig`.
http://phantomjs.org/download.html states that:

```sh
sudo yum install fontconfig freetype libfreetype.so.6 libfontconfig.so.1 libstdc++.so.6
```

In Ubuntu you can most likely just replace the `yum` with `apt-get`...

For the `npm` error it is unclear. Which versions do you have installed?
```sh
npm --versions
```

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:**
Looks to be a stale help request. Assuming you've moved on to better and cooler things.  Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
