### ISSUE TITLE
Expose slimer.isExiting()

### ISSUE THREAD

**Issue by corford** [casperjs/casperjs#1119]
Is there any plan to expose the new slimer.isExiting() function (see: https://github.com/laurentj/slimerjs/commit/8015d76c4dfdb785d5f2af806c8c13d0ddbe107d ) ?

It would help fix an issue we have whereby a Casper script finishes correctly just before the script timeout limit but sometimes due to the lag of xulrunner shutting down the Casper onTimeout event fires a second or so after (even though technically the script finished all of its work before the timeout limit was reached). This is because for slimerjs, phantomjs.exit() is async (so while xulrunner shuts down the Casper script is still running).

With slimer.isExiting() we could add a check for this edge case inside the onTimeout callback of the Casper script so the commands inside the callback are only executed if slimer.isExiting() is false.

**Comment by mickaelandrieu** [comment]
hi @corford,

in my opionon this is not a good idea to expose method from slimer which don't exists in phantomjs or in triflejs.

Maybe can you extends casperjs ? http://casperjs.readthedocs.org/en/latest/extending.html

**Comment by corford** [comment]
That's a fair point.

As an alternative could Casper internally check slimer.isExiting() and not raise an onTimeout event if this is true. This internal check could be made a no-op or always return false for other engines.

**Comment by mickaelandrieu** [comment]
What do you think @laurentj ?

**Comment by kensoh** [comment]
Bumping up this issue.

**Comment by kensoh** [comment]
Closing this issue for now as it hasn't have new replies or discussion for a long while. But do reopen if anything!
