### ISSUE TITLE
Coding style, single or double quotes?

### ISSUE THREAD

**Issue by paazmaya** [casperjs/casperjs#1122]
Seems that there is general rule of using double quotes, but some of the JS files also use single quotes.
Which one would be the preference? I guess double...

How about switching from JSHint to ESLint, since the latter has much more options for setting up and validation code style rules?

**Comment by rdpanek** [comment]
I use single quotes for static value and double quotes for use string interpolation.

**Comment by paazmaya** [comment]
#1133 needs to be configured to handle this, but there is no way currently to distinguish between "static" and "interpolation"

**Comment by kensoh** [comment]
This looks to be already merged. For my personal bias I use ' and then " within ' for XPath '//*[@text="Continue"]'. Single quote much easier to type without hitting shift key.

**Comment by kensoh** [comment]
Closing this as there hasn't been new discussion or replies for a long while..
