### ISSUE TITLE
BUG: passing ampersand to slimerjs engine is not support

### ISSUE THREAD

**Issue by ensecoz** [casperjs/casperjs#1127]
reproduce:

cmd: casperjs.exe arg.js hello^&world --engine=slimerjs
arg.js: casper.cli.get(0);
actual: 'world' is not recognized as an internal or external command, operable program or batch file.
expect: hello&world

but if using phantomjs, it works.

**Comment by kensoh** [comment]
@ensecoz it's been a while, this seems to work now on macOS. Not sure if this is still happening for you on Windows? I'm running CasperJS v1.1.4 and SlimerJS v0.10.3.

**Comment by kensoh** [comment]
@ensecoz I've just borrowed a Windows laptop to run his and this still happens for Windows.

**Comment by kensoh** [comment]
Archiving issue using **ARCHIVE** label as CasperJS, like PhantomJS, is not actively maintained for now.
