### ISSUE TITLE
HTTP Header Content-Type is ignored

### ISSUE THREAD

**Issue by kento6453** [casperjs/casperjs#1128]
casperjs may ignore HTTP Header "Content-Type".

I found this problem when I implement casperjs script for the Japanese web pages.

There are 2 different pages. 
first one has <meta http-equiv="Content-Type" content="text/html; charset=shift_jis"> ,
another one does not have <meta> above.

Both of them send HTTP Header 

Content-Type: text/html; charset=Windows-31J

As the result , 
casperjs can work fine for first one .
but cannot work for another one. and japanese word in the page which I fetched via casper.getHTML(). 
is completely crashed.

I guess casperjs should read "HTTP Header Content Type"  as same as usual browser.

**Comment by paazmaya** [comment]
Can you please provide a minimal working example?

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:**
Looks to be a stale help request. Assuming you've moved on to better and cooler things.  Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
