### ISSUE TITLE
Crashes when call clear on onStepTimeout

### ISSUE THREAD

**Issue by Nina-Nasura** [casperjs/casperjs#1129]
To skip a step when it takes long and jump to the next step, I used the following code: 

``` javascript
var casper = require("casper").create({
        verbose: true,
        stepTimeout: 6000,
        onStepTimeout: function() {
                this.echo("Step " + this.step +"timed out ");
                this.clear();
                this.mainPage.stop(); 
         }
});
casper.start('http://desktop.google.com/?hl=en', function() {
    this.echo(this.getTitle());
});
casper.thenOpen('http://google.com', function() {
    this.echo(this.getTitle());
});
casper.run();
```

But it cannot  clear the current page and makes phantomjs to crash.
Using:
- Casperjs 1.1.0-beta3
- phantomjs 1.9.0
- Ubuntu 14.04

**Comment by kanxue660** [comment]
great, i works for me

**Comment by Nina-Nasura** [comment]
Dose it work for the same urls I provided above? 
If yes,  would you pleade tell me the version of cadper and phanton you used? 
It works for some urls,  but for the urls in the above code it mskes cadper to crash.

**Comment by kanxue660** [comment]
i copy your code and not change anything,it run ok
There are different is i use windows7

the screenshot
http://i2.tietuku.com/0be718d37d61099e.png

**Comment by kensoh** [comment]
@Nina-Nasura @kanxue660 this seems to be working now too. Works for me on macOS.

```
Step 1timed out 

Google
```

**Comment by kensoh** [comment]
Thanks @kanxue660 ! Hi @Nina-Nasura closing this issue as current versions seem to be ok. But do ping on GitHub here if you still have this crash with CasperJS v1.1.4 and PhantomJS v2.1.1. or at email ken@tebel.org

**Comment by kensoh** [comment]
No probs @Raminsadeghi - guys, following is my run output using the code above from @Nina-Nasura 

```
111-222:Desktop kensoh$ casperjs --version
1.1.4
111-222:Desktop kensoh$ phantomjs --version 
2.1.1
111-222:Desktop kensoh$ casperjs t.js
Blogger
Google
```
