### ISSUE TITLE
clientutils.sendAJAX() does not send HTTP PUT request body

### ISSUE THREAD

**Issue by arjona** [casperjs/casperjs#1142]
Currently the sendAJAX() only sends the data if it's HTTP POST which breaks sending update requests to a REST webservice.

**Comment by n1k0** [comment]
That'd be matter of supporting other verbs in https://github.com/n1k0/casperjs/blob/bb706acdf38f30d2380ebd3897ba1d4cee74430c/modules/clientutils.js#L787

Who can take care of addressing this?

**Comment by n1k0** [comment]
Bah, just seen your PR. Could you please add support for at least DELETE, and write unit tests? Thanks.

**Comment by arjona** [comment]
Hello,

I tested DELETE with my webservices and it works ok since it doesn't require a body. About the unit tests I'd love to but I need some orientation with your test suite. How should I go about writing tests for HTTP requests? I don't see a similar example and stuff like find* uses a fake html document as a test fixture.

**Comment by n1k0** [comment]
Bah, there's indeed no test for sendAJAX :(

I could see a test setting up a local webserver (builtin phantom/slimer module one) then performing assertions on what has been sent to test endpoints. That's a bunch of work, but if you feel like trying I can probably answer any question you have.

**Comment by arjona** [comment]
I'll see what I can do. I'm on IRC so I'll probably ping you there :)

**Comment by arjona** [comment]
Hello,
I'm pasting my last question from IRC here so it's more permanent:

NiKo`: I've made progress with the unit test for sendAJAX() but I've hit a problem: https://gist.github.com/arjona/6d0520542867c84d3233
I made a webserver instance that just echoes a json of the request object
it works great with thenOpen() for example
but when I try to use the sendAJAX() method to send a request to that server I get the error that is on the commnents of the gist
it also happens when I run the tests with bin/casperjs selftest tests/suites/clientutils.js --web-security=no

**Comment by kensoh** [comment]
Hi @arjona bumping this up, not sure if this is still happening?

**Comment by kensoh** [comment]
Closing this issue for now as there hasn't been replies, but do reopen if anything!
