### ISSUE TITLE
Be able to specify test order in a config file

### ISSUE THREAD

**Issue by amerikan** [casperjs/casperjs#1147]
If I have the following directory structure:

```
mytests/
      a.js
      b.js
      c.js
      d.js
```

Currently if you run `casperjs test mytests/` it will run all tests in **alphabetical** order such as `a.js`, then `b.js`, then `c.js` and finally `d.js`.

What if I want to specify the priority order? For example maybe I want `c.js` to be the first one to get executed followed by `b.js`. How can I do that?

I tried looking for docs, but I don't think there is a way, I'm not sure. I found this [StackOverlfow comment](http://stackoverflow.com/questions/16371091/cant-split-casperjs-tests-across-multiple-files#comment23622654_16436493) by @n1k0 but I really don't want to do that.

> name your files accordingly: 01_login.js, 02_otherpage.js –  NiKo May 9 '13 at 15:33

I was thinking maybe there can be some sort of _config_ file that is placed in the directory that specifies the order, maybe a .js or .json file, idk.

For example: 

```
mytests/
      a.js
      b.js
      c.js
      d.js
      casperconfig.js
```

`casperconfig.js`:

``` js
{
    'priority': ['c','b'], // the .js extension can be ignored
    'log-level': 'debug',  // maybe we can even set the options here like this
    'engine': 'phantomjs' // and this
}
```

Now with this when I run `casperjs test mytests/` it'll first read `casperconfig.js` then execute `c.js`, `b.js` since the order was specified and the rest in alphabetical order last ones would be `a.js` and finally `d.js`.

Any thoughts, or is there something like this already?

**Comment by rdpanek** [comment]
I think, that doesn't. But it's important. My idea is, that I can run specify test via gulp watcher, because i work on small method or class and with save file I would like result from frontend. 

Second thing. Sort of run test is important for suites and dependency.

You can send pull-request with you idea? :-)

**Comment by davidlinse** [comment]
Imho, test should always be able to run in _ANY_ order. 
Beside from that you could give ``--pre` and ```--post``` [options](http://casperjs.readthedocs.org/en/latest/testing.html#options) a try..

~david

**Comment by vatsala** [comment]
:+1:  for @amerikan's suggestion. not only that, this config file could also take an exclusion list, i.e. a way to specify which tests to exclude for that execution.

**Comment by LJJCherry** [comment]
I met the same problem，I must execute login.js  first,how I can do that ？

**Comment by kensoh** [comment]
@LJJCherry you can try the --pre and --post options mentioned by @davidlinse it lets you run some pre-requisite script first before the actual testing. http://docs.casperjs.org/en/latest/testing.html

**Comment by kensoh** [comment]
Closing this issue for now but do reopen if there's anything!
