### ISSUE TITLE
a question about casper.test.on('fail', function(){})

### ISSUE THREAD

**Issue by kantjessica** [casperjs/casperjs#1148]
Hi,

what does this method do? registering a new listener for "fail" event? 

what happens, if I write two casper.test.on blocks in a same test suite? If sth fails, both of the registered functions will be executed, right?

Best wishes,
Huiying

**Comment by paazmaya** [comment]
It would look like an event listener for listening whenever http://docs.casperjs.org/en/latest/modules/tester.html#fail is called...

Since the `casper.test` refers to the global object, the event listener listens to all matching events.

**Comment by kensoh** [comment]
@kantjessica not sure if this is still relevant to you. I think the second defined block will overwrite the first one and only the second block will be triggered. I tried testing with onStepTimeout event handling.

**Comment by kensoh** [comment]
Hi @kantjessica closing this issue I believe you got the 2 answers that you are looking for.. In any case, kindly ping if you have any issues.. I'm on GitHub almost everyday these days. Or you can email at ken@tebel.org
