### ISSUE TITLE
About  cli parameter not recognize  \r\n 

### ISSUE THREAD

**Issue by paul2008** [casperjs/casperjs#1149]
My enviroment is .net and windows XP. in China.

This script is ok
C:\WebCrawler\mondeo\lj_main.js --disk-cache=true --cookies-file="C:\WebCrawler\mondeo\lj_main.cookie"  
--user="222" 
--pwd="111"  

But if show below.Casperjs is fail to use "disk-cache" and "cookies-file" paramenters,though utils.dump(capserjs.cli) contains "disk-cache" and "cookies-file" paramenters.
C:\WebCrawler\mondeo\lj_main.js 
--disk-cache=true 
--cookies-file="C:\WebCrawler\mondeo\lj_main.cookie"  
--user="222" 
--pwd="111

**Comment by paazmaya** [comment]
Most likely CasperJS should handle normalising those line endings.

Could you provide a minimal working example of your error case?
It could be then added to the test suite and fixed.

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:**
Looks to be a stale help request. Assuming you've moved on to better and cooler things.  Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
