### ISSUE TITLE
Can't handle error CasperError: Cannot upload nonexistent file

### ISSUE THREAD

**Issue by 3x14159265** [casperjs/casperjs#1151]
I'm trying to somehow handle errors in my casper.js script.
I've tried with 
```
try { ... } catch(e) {}
```
as well with
```
casper.on('error', function() {...})
```

the script stops when having an error like 
```CasperError: Cannot upload nonexistent file```

How to handle the errors on my own?

**Comment by rdpanek** [comment]
What is version of your phantomjs?

**Comment by rdpanek** [comment]
you can paste your script?

**Comment by 3x14159265** [comment]
phantomjs version: 1.9.0

```
casper.on('error', function(e) {
    sendError(e)
})

casper.start(...)

casper.then(function() {
	try {
		casper.then(function() {
		  	this.fill('form.add', {
		        'file': 'tmp/'+product.id+'/'+image.order+'.'+image.url.split('.').pop(),
		    }, false)
		})
	} catch(e) {
		sendError(e)
	}
})

```

if there's no image, I get the ```CasperError: Cannot upload nonexistent file```
any ideas to catch this error?

**Comment by paazmaya** [comment]
Have you looked at if PhantomJS had similar errors reported around the time of `1.9.0` ?

**Comment by zjiash** [comment]
I meet the same problem which I post in http://stackoverflow.com/questions/29158204/how-to-make-casperjs-continue-instead-of-exit-on-exception .
Could you give me some help? Thanks.

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:**
Looks to be a stale help request. Assuming you've moved on to better and cooler things. Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
