### ISSUE TITLE
CasperJS test won't return after execution

### ISSUE THREAD

**Issue by ymuzychyshyn** [casperjs/casperjs#1155]
I'm having a problem getting casperjs test to exit after execution, I have to hit CTL-C to exit execution. 
//misc.js
var require = patchRequire(require);

var site = {
    goToSite: function (url) {
        casper.start(url, function checkSite() {
                this.test.assert(this.getCurrentUrl() === url, 'Url is: ' + this.getCurrentUrl());
                this.test.assertHttpStatus(200, 'HTTP status code 200 OK');
            }
        );
    },

    login: function () {
        casper.then(function fillTheForm() {
                this.fill("form[action='/auth/login']", {
                    'email': 'login@email.com',
                    'password': 'pass'
                }, true);
            }
        );
    }
};

module.exports.site = site;

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// test.js
var system = require('system');
var misc = require('./misc');
casper.options.logLevel = "debug";
casper.options.verbose = true;

casper.test.begin('Cow can moo', 2, function suite(test) {
    var url = "http://ym.cms2cms/auth/login";
    misc.site.goToSite(url);
    misc.site.login();

    casper.run(function () {
        test.done();
    });
});

////////////////////////////////////////////////////////////////////////////////////////////////////////
// terminal
[info] [phantom] Starting...
[info] [phantom] Running suite: 3 steps
[debug] [phantom] opening url: http://ym.cms2cms/auth/login, HTTP GET
[debug] [phantom] Navigation requested: url=http://ym.cms2cms/auth/login, type=Other, willNavigate=true, isMainFrame=true
[debug] [phantom] url changed to "http://ym.cms2cms/auth/login"
[debug] [phantom] Successfully injected Casper client-side utilities
[info] [phantom] Step checkSite 2/3 http://ym.cms2cms/auth/login (HTTP 200)
PASS Url is: http://ym.cms2cms/auth/login
PASS HTTP status code 200 OK
[info] [phantom] Step checkSite 2/3: done in 1564ms.
[info] [phantom] Step fillTheForm 3/3 http://ym.cms2cms/auth/login (HTTP 200)
[info] [remote] attempting to fetch form element from selector: 'form[action='/auth/login']'
[debug] [remote] Set "email" field value to y.muzychyshyn+1001@magneticone.com
[debug] [remote] Set "password" field value to ******
[info] [remote] submitting form to /auth/login, HTTP POST
[warning] [remote] unable to submit form
[info] [phantom] Step fillTheForm 3/3: done in 1601ms.
[info] [phantom] Done 3 steps in 1602ms
PASS 2 tests executed in 1.596s, 2 passed, 0 failed, 0 dubious, 0 skipped.

**Comment by paazmaya** [comment]
Where is the `test` defined, of which the `done()` method is called in the `run` callback?

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:**
Looks to be a stale help request. Assuming you've moved on to better and cooler things.  Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
