### ISSUE TITLE
How to suspend casperjs's execution

### ISSUE THREAD

**Issue by zhyh1105** [casperjs/casperjs#1156]
How to suspend casperjs's execution, and then let the user input someting, and then continue the execution.
Such as the login process:
1、www.bar.com
2、www.bar.com/login 
3、download the captcha and send it to the user
4、suspend  and wait for the user inputs 
5、 continue the process with user inputs  (how to)

Just like Selenium, keep a WebDriver instance .
In fact, the question is how to keep a same casper instance in two or more different files.

**Comment by davidlinse** [comment]
Since it's based on phantomjs, which is headless, you will never see a ui to manually insert something..

**Comment by zhyh1105** [comment]
I know that phantomjs is headless.Sorry for my poor engilsh. 
I mean that if I can keep a same casperjs instance or not.
I  have two js file, bar.js and foo.js . I init the caseper in bar.js and then visit some website, my problem is that whether I can use the caseper in foo.js and continue the visiting , because I have to fill the captcha, before I can fill it, I have to download the captcha image.

**Comment by BIGjuevos** [comment]
You might want to look at #1513

**As part of a cleanup effort:**
Looks to be a stale help request. Assuming you've moved on to better and cooler things.  Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
