### ISSUE TITLE
null and NaN values in casperjs test suite

### ISSUE THREAD

**Issue by dtarda** [casperjs/casperjs#1157]
NaN values are rendered as null in the output of test results, so when null is expected and NaN is received, test suite yields a totally unintuitive message:

```
#    type: assertEquals
#    file: test.js:17
#    code: casper.test.assertEquals(NaN, null);
#    subject: null
#    expected: null
```

**Comment by paazmaya** [comment]
Have you come across a workaround?

PR welcome for adding a test case, and even a possible fix...

**Comment by kensoh** [comment]
Closing this issue as there hasn't been replies for a long while, but do reopen if anything, thanks @dtarda !
