### ISSUE TITLE
fill() is not submitting the form

### ISSUE THREAD

**Issue by Nuruddinjr** [casperjs/casperjs#1163]
fill() method is filling the form but i cant see the result of submitting
here is the code : 
```javascript
page.then(function(){
    this.echo(this.getCurrentUrl());
    page.onLoadFinished;
    this.fill('form[action^="/adm/crit"]', {
        'title':    'I am watching you',
       "dep":['1'],
        });
    this.click('.btn-primary');
            this.wait(500);
    this.capture('screen_logs/wee.png')
});

page.then(function(){
    this.echo(this.getCurrentUrl());
    this.capture('screen_logs/aslkd.png')
  
});

page.run();

**Comment by Nuruddinjr** [comment]
I tried it with true inside fill also

**Comment by goggelz** [comment]
try to work with casper.waitForSelector()

**Comment by BIGjuevos** [comment]
As part of a cleanup effort:
Looks to be a stale help request. Assuming you've moved on to better and cooler things. Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
