### ISSUE TITLE
How do I hook config.json file on casperjs

### ISSUE THREAD

**Issue by Nuruddinjr** [casperjs/casperjs#1168]
I want to implement url and username ,password to a json file, to change it easily, how can I write config that?

**Comment by erikmontes** [comment]
You can pass includes using command line:
http://casperjs.readthedocs.org/en/latest/testing.html#options

**Comment by paazmaya** [comment]
There is a pull request related to the topic #896

**Comment by kensoh** [comment]
@Nuruddinjr looks like the PR has not been implemented. Bumping up. For me, I read from a file the 'dataset' to be used for running the test or automation.

**Comment by kensoh** [comment]
Looks like there are conflicts now in the PR. Copying maintainer @jefleponot

**Comment by kensoh** [comment]
Archiving issue using **ARCHIVE** label as CasperJS, like PhantomJS, is not actively maintained for now.
