### ISSUE TITLE
Test Method

### ISSUE THREAD

**Issue by Nuruddinjr** [casperjs/casperjs#1170]
When I run the same test consecutively, some times i am getting pass sometimes not, code is as following : 
```javascript
casper.test.begin('Login test', 1, function(test){
    
    casper.then(function(){

    this.fill('form[action="/login"]', {
        "login": username,
        "password": password,
    },true);

    this.echo(this.getCurrentUrl(), 'PARAMETER');
    
    this.waitForUrl(base_url+'/adm/candidates',function(){

    test.assertUrlMatch(/\/adm\/candidates\/list/ , 'Login sucessfull');

    });
    
});

 casper.run(function(){
        test.done();
    });

});
```

**Comment by Nuruddinjr** [comment]
casperjs test s.js 
Test file: s.js                                                                 
# Login test
http://localhost:8080/login
PASS hey I am sucessfull

nuruddin@Ubuntu:~/Desktop$ casperjs test s.js 
Test file: s.js                                                                 
# Login test
http://localhost:8080/login

nuruddin@Ubuntu:~/Desktop$ casperjs test s.js 
Test file: s.js                                                                 
# Login test
http://localhost:8080/login
PASS hey I am sucessfull
PASS 1 test executed in 1.538s, 1 passed, 0 failed, 0 dubious, 0 skipped.       

nuruddin@Ubuntu:~/Desktop$

**Comment by cosmo0920** [comment]
This is because that you needs to wait to test login pages.

Try to use `casper.waitForselector(function() {..}) ` or `casper.wait(function() {..})`.

**Comment by Nuruddinjr** [comment]
Look at new code that i am trying now, 
i will edit my code above

**Comment by cosmo0920** [comment]
Ah, `waitForUrl` is also valid method. I didn't notice it. 

`waitForUrl` requires `onUrlChanged` event.
This event does not fired, `waitForUrl` is not work correctly, I think.

**Comment by Nuruddinjr** [comment]
i thnk it is working, but can't get to the end of the test, because it is printing PASS

**Comment by cosmo0920** [comment]
Hmm, it is curious for me.... :confounded:

**Comment by Nuruddinjr** [comment]
:+1:  for me too :octocat:

**Comment by cosmo0920** [comment]
FYI: Here is an issue tracker. You shouldn't register a question for Casperjs this issue tracker.
You should to post a question for Casper.js in [Google Group - CasperJS](https://groups.google.com/forum/#!forum/casperjs).

**Comment by Nuruddinjr** [comment]
Oh thanks

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:**
Looks to be a stale help request. Assuming you've moved on to better and cooler things. Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
