### ISSUE TITLE
Clicking a link in an iframe in a popup, that kills the popup, throws an error

### ISSUE THREAD

**Issue by skeletal** [casperjs/casperjs#1174]
I have a form I'm filling and one of the fields requires picking an object from a list in a popup window. The list is inside an iframe on the popup page, and clicking the link in the list closes the popup and places the value in the form on the original page.

My problem is with my setup I'm clicking the link within the iframe kills the popup, and then on exiting the `this.withFrame()` function I get the error

Error: cannot access member 'switchToParentFrame' of deleted QObject

Here's roughly what my code looks like.

```
this.withPopup(/popup/, function() {
    this.withFrame('listFrame', function() {
        // do stuff to get the right link selector
        this.click(link);
    });
});
```
If there's a way to click the link from outside the `withFrame()` function?

**Comment by jefleponot** [comment]
There are many bugs with Popups :

- Events are not sent as main page done
- Page settings (userAgent, ...) are default on popup (not clone of main page)
- Recursives calls of popups make crashes
- ...

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:**
Looks to be a stale help request. Assuming you've moved on to better and cooler things. Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
