### ISSUE TITLE
Are scripts inside iframes parsed ?

### ISSUE THREAD

**Issue by B2F** [casperjs/casperjs#1181]
I did the following:

Open http://api.jquery.com/fadein/, then:

          // Second demo from the page:
          this.page.switchToChildFrame(1);
          this.click('a');
          this.page.switchToParentFrame();
          this.wait(10000);

The link is correctly clicked inside the iframe (its color changes), but the jquery associated script seemed to be ignored. This is easily reproducible. So my question is, does PhantomJs or Casperjs has an issue loading script tags inside iframes ?

**Comment by jefleponot** [comment]
Hi B2F,

You code don't work, just try this one :
<pre>
var casper = require('casper').create();

casper.start('http://api.jquery.com/fadein/', function() {
   this.withFrame(1,function(){
        this.click('a');
   });
});
casper.wait(1000);

casper.run();
</pre>

**Comment by B2F** [comment]
See it for yourself:
```javascript
var casper = require('casper').create();

casper.start('http://api.jquery.com/fadein/', function() {
   this.viewport(1024, 768);
   this.withFrame(1,function(){
     this.click('a');
   });
   this.captureSelector('no-click.png', '#example-1 iframe');
   this.page.switchToChildFrame(1);
   this.click('a');
   this.page.switchToParentFrame();
   this.scrollTo(0, 0);
   this.captureSelector('click.png', '#example-1 iframe');
});

casper.wait(1000);

casper.run();
```

The click.png from my code shows the link colored as visited whereas yours (no-click.png) doesn't.
The issue is still there anyway and the screenshot from the snippet above illustrates the problem.

**Comment by jefleponot** [comment]
Hi,

There are 2 troubles with your code :

1/ The iframe on the jquery fadin site is no a really frame so the method "switchToChildFrame" is not efficient (just use : <b>document.querySelectorAll('iframe')[1].contentDocument.body.querySelector('a');</b>)

2/ What is your phantomjs version : under 2.00 there is a bug with Event  https://github.com/ariya/phantomjs/issues/11289

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:**
Looks to be a stale help request. Assuming you've moved on to better and cooler things. Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
