### ISSUE TITLE
 Can not download charset is UTF-16 files

### ISSUE THREAD

**Issue by machinewu** [casperjs/casperjs#1184]
If a response's 'Content-Type' is  'unknown; charset=UTF-16LE', casperjs can get the file, but the file's is garbled, and the file size is incorrect.

test server code(test.py):

```
#!/usr/bin/env python
#coding=utf-8

from BaseHTTPServer import BaseHTTPRequestHandler, HTTPServer
import subprocess
import urlparse


class MyHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        self.send_response(200)
        if '/' == self.path:
            self.end_headers()
            self.wfile.write('hello')
        else:
            self.send_header('Content-Disposition', 'attachment; filename=test.csv')
            self.send_header('Content-type', 'unknown; charset=UTF-16LE')
            self.send_header('Cache-Control', 'private, max-age=0')
            self.end_headers()
            self.wfile.write(u'你好github'.encode('utf-16'))

    def do_POST(self):
        self.do_GET()


def main(port=8000):
    try:
        server = HTTPServer(('', port), MyHandler)
        server.serve_forever()
    except KeyboardInterrupt:
        print '^C received, shutting down server'
        if server:
            server.socket.close()


if '__main__' == __name__:
    main()
```

test casperjs code:

```
var require = patchRequire(require);
var casper = require("casper").create({verbose:true, logLevel:'debug'});

casper.start().thenOpen('http://localhost:8000/');

casper.then(function (){
    casper.download('http://localhost:8000/csv', 'test.csv');
});

casper.run(function (){
    casper.exit();
});
```

I can download the correct file through a browser(URL: http://localhost:8000/csv). But if I use casperjs's download method to download the file, it becomes garbled.
The correct file size (download through a browser) should be 18 bytes, but only 8 bytes downloaded through casperjs.

**Comment by rpacheco-aa** [comment]
Could this be related to [this](https://github.com/n1k0/casperjs/issues/777) case?

**Comment by machinewu** [comment]
I don't think so. It can download UTF-8 characters. If the file encode UTF-8.
I download a report from Google Adsense, google encode the file with UTF-16.

**Comment by kensoh** [comment]
Closing this issue for now as there hasn't been progress or replies for a long while. But do reopen if anything! I just got an idea of using waitForExec and pass the download URL to curl to do the actual download. Not sure if that will work for you?
