### ISSUE TITLE
Default synthetic DOM mouse events 

### ISSUE THREAD

**Issue by jefleponot** [casperjs/casperjs#1185]
Casper uses by default synthetic DOM events and it works very well. 

But when you use casper.click for example, many events are not trigger like a true browsing will done (mousemove, mouseover , mouseout) and styles :hover aren't apply. 
So html menus page doesn't work correctly.

To fix that anoying trouble, could you had a true event mousemove before sending a default synthetic DOM event ?

Regards

**Comment by kensoh** [comment]
Closing this issue as it has been a while and without new replies.. Looks like this hasn't yet been implemented, to do the mouse.move.
