### ISSUE TITLE
Xunit xml generation not working when using slimerjs as engine

### ISSUE THREAD

**Issue by shaunthomas999** [casperjs/casperjs#1194]
Hi,

Xunit xml generation is not working when using slimerjs as engine. I get the following content in the generated xml.

```
[object HTMLUnknownElement]
```

But it works fine when with phantomjs.

**Comment by istr** [comment]
Could you please re-check if 1.1.1 fixes your issue? Thank you.

**Comment by shaunthomas999** [comment]
Issue is fixed in CasperJS version 1.1.1

Thanks :)
