### ISSUE TITLE
Clear doesn't clear session

### ISSUE THREAD

**Issue by guidobouman** [casperjs/casperjs#1197]
How can I clear my current session, making sure there's no trace of state from my previous tests?

**Comment by ewnd9** [comment]
Did you find any workaround?

**Comment by guidobouman** [comment]
I gave up and used a different approach in my tests...

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:**
Looks to be a stale help request. Assuming you've moved on to better and cooler things. Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.

**Comment by guidobouman** [comment]
This is just a functional by that should still be fixed, no?

**Comment by BIGjuevos** [comment]
Thanks for checking in.  I've re-opened the issue and added a label for tracking.

**Comment by kensoh** [comment]
@guidobouman can you share how you handle the situation? I wrap batch execution in [shell/batch](https://github.com/tebelorg/TagUI/blob/master/src/tagui) files so that for every iteration CasperJS + PhantomJS will be closed and re-initiated. I thought that is better for stability in running batch. But I don't know what's the drawback of this approach. Maybe results harder to compile? Now I just tee output of all iteration into 1 log file.

**Comment by guidobouman** [comment]
@kensoh Wow, that's a while ago. I had to check the source to be sure. We switched to making sure we always login with a fresh user. And clearing logins etc. after each test suite. Not what you had hoped for I'm afraid.

**Comment by kensoh** [comment]
@guidobouman thanks for replying. That happens, whatever works :) My team does that too in my previous job. Especially sometimes it is not straightforward for a user to start off in a clean slate. And test automation folks may not always have backend/db access to refresh the user data while at the same time it can be impossible to clear that data from GUI.

I'm a CasperJS user for couple of years, now browsing through open issues. If you have a script to share, I can try to replicate to see if it still happens. These days, many developments in web automation space (headless Chrome/Firefox etc). Wonder how that will turn out.

**Comment by kensoh** [comment]
I'm tempted to close this issue as there hasn't been progress. But this is a bug, so... copying maintainer @jefleponot

**Comment by guidobouman** [comment]
This can be closed if `clear` actually removes all traces of previous activity on a session.

**Comment by kensoh** [comment]
Archiving issue using **ARCHIVE** label as CasperJS, like PhantomJS, is not actively maintained for now.
