### ISSUE TITLE
response.redirectURL is blank for HTTP 302 responses

### ISSUE THREAD

**Issue by davidwhthomas** [casperjs/casperjs#1202]
I found that `response.redirectURL` is missing for `HTTP 302` responses. 

While I'm not sure if this is a bug in phantomJS or CasperJS, I'll post a workaround here for now:

```
casper.on('http.status.302', function(response) {
  // Find redirectURL from headers.
  if ( !response.redirectURL ) {
    this.echo('URL 302 detected: ' + response.url + ' - attempting to add missing response.redirectURL ', 'warning');
    for ( var i = 0; i<response.headers; i++ ){
      var header = response.headers[i];
      if ( header.name === "Location" ){
        redirectURL = data.source.parseData.hostname + header.value;
      }
    }
    if (redirectURL) {
      // Set on response.
      response.redirectURL = redirectURL;
    }
  }
});
```

See also: https://github.com/ariya/phantomjs/issues/13095
Note: This is testing with PhantomJS 2.0.0

**Comment by n1k0** [comment]
Could you please send a PR with this and tests?

**Comment by davidwhthomas** [comment]
Hi n1k0, 

Thanks for your reply.

I'm using this http.status.302 workaround in a test suite at the moment. 
Do you think it could be added to casperjs core somewhere?
If so, is there somewhere in particular you recommended adding it?

e.g, would it be phantomjs-2 branch in `Casper.prototype.handleReceivedResource` or perhaps in a default `casper.options.httpStatusHandlers[302]` handler?

I suppose a patch could be added while it's being fixed in upstream phantomjs.

Cheers,
David

**Comment by n1k0** [comment]
> e.g, would it be phantomjs-2 branch in Casper.prototype.handleReceivedResource or perhaps in a default casper.options.httpStatusHandlers[302] handler?

Adding it to `handleReceivedResource` sounds fine.

**Comment by kensoh** [comment]
Want to tag another 302 related issue - https://github.com/casperjs/casperjs/issues/1236

**Comment by kensoh** [comment]
Archiving issue using **ARCHIVE** label as CasperJS, like PhantomJS, is not actively maintained for now.
