### ISSUE TITLE
drop issue

### ISSUE THREAD

**Issue by ImaMiri** [casperjs/casperjs#1205]
I've tried to implement drag and drop in my project, the dragging is working fine but the drop is not working.

Here is my code:

in my page,

casper.then(function(){
        this.mouse.down('div.cq-cft-dataview > div'); // the image that needs to be dragged (it's working)
        this.page.switchToChildFrame(1);
        this.mouse.move('div#related-image'); // the position that image is going to be dropped (it's working)
        this.mouse.up('div#related-image'); // it's not working
        this.page.switchToMainFrame();
        this.wait(1000);
        this.capture('attachement.png');
        console.log("PASS: image is attached");
    });

Am I missed sth?

**Comment by jefleponot** [comment]
do it miss "this.mouse.down" call?

**Comment by ImaMiri** [comment]
this.mouse.down and this.mouse.move are working fine, but this.mouse.up is not working. I can see it when I'm running it with slimerjs that down and move events are working but not mouseup event.

**Comment by jefleponot** [comment]
Perhaps a trouble between Frames

**Comment by JohnnyQQQQ** [comment]
Did you try it with this workaround? https://github.com/n1k0/casperjs/issues/379#issuecomment-63871679

**Comment by ImaMiri** [comment]
I've tried that and it didn't work.

**Comment by Ima1120** [comment]
I used also native commands such as this.page.sendEvent('mousemove',500,500) and it didn't work. I think it is related to phantomjs which can not handle mosue move event properly.

**Comment by kensoh** [comment]
Hi @ImaMiri it's been a while not sure if this issue is still happening for you? I saw your other thread.

**Comment by kensoh** [comment]
Closing this issue for now, and cross-referencing the issue in https://github.com/casperjs/casperjs/issues/1242 as there are more specific examples to tackle the problem of drag. But do reopen here if anything or reply at 1242 thread!
