### ISSUE TITLE
Casper fails to load if a space exists in the casper path

### ISSUE THREAD

**Issue by nebruin** [casperjs/casperjs#1207]
The casper path is not enclosed in quotes which causes the loading to fail. I'm on windows 7, and casper was installed via npm in my user directory. My username had a space in it, and that caused it to fail.

All I did to fix it was simply to add double quotes around the path. I've included what I did to fix it below:

CASPER_COMMAND.extend([
    '"' + os.path.join(CASPER_PATH, 'bin', 'bootstrap.js') + '"',
    '--casper-path=%s' % '"' + CASPER_PATH + '"',
    '--cli'
])

**Comment by paazmaya** [comment]
Could you create a pull request with this fix?
It would allow to test it in different environments via CI.

**Comment by vatsala** [comment]
I attempted this by making the changes mentioned by @nebruin on my local - when I run casperjs selftest, 
    vatsala@vatsala-dell-vostro-2520:~/learning/casperjs/bin$ ./casperjs selftest
    Can't open '"/home/vatsala/learning/casperjs/bin/bootstrap.js"'

**Comment by FurryFur** [comment]
Bump, very annoying.

**Comment by kensoh** [comment]
It has been a while.. This seems to be fixed I guess? When I run ./casperjs selftest on a folder path with space it works. I'm using 1.1.4 on macOS.

**Comment by kensoh** [comment]
Linking to https://github.com/casperjs/casperjs/issues/1180 may have common causes.

**Comment by kensoh** [comment]
@nebruin @vatsala @FurryFur closing the issue and keeping 1180 open for now. But do reopen if you are still having the issue with latest CasperJS v1.1.4 and PhantomJS v2.1.1. Thanks!
