### ISSUE TITLE
Add getFieldValue to casper module

### ISSUE THREAD

**Issue by lmazuel** [casperjs/casperjs#1213]
Hi,

A little enhancement query:
Is it possible to export `getFieldValue` in the `casper` module, as made for `getFormValues`?

I'm currently using the workaround:

``` js
this.callUtils("getFieldValue", myselector);
```

It works well, but it's not very pretty.

Thanks!

**Comment by kensoh** [comment]
Hi @lmazuel closing this issue for now as it appears to be already added some time along the way. Thanks for raising this! I'm a CasperJS user for couple of years, now browsing through open issues.

http://docs.casperjs.org/en/latest/modules/clientutils.html#getfieldvalue
