### ISSUE TITLE
Casperjs missing out test files

### ISSUE THREAD

**Issue by ttback** [casperjs/casperjs#1218]
I am trying to run all the .js files under smoke dir with grunt-casper, but sometimes it runs only 2 of the js files. When all tests are run, it also fails the .open call randomly. Any hint on how to make sure all test files are run to completion would be appreciated.

Command
````
/node_modules/casperjs/bin/casperjs test test/smoke/*.js
````

Test code (the files share the same code to test out grunt-casper) I can't see anything wrong with it atm. I don't think it's related to the request to url, since the "running test" message is not even output for the missing test.

````
casper.test.begin(" test", 1, function(test) {
	casper.start();

	console.log("running test);
	casper.open(url, {
		method: 'head'
	});

	casper.then(function(response) {
		test.done();
	});

	casper.run(function() {
  		casper.exit();
	});
});

````

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:**
Looks to be a stale help request. Assuming you've moved on to better and cooler things. Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
