### ISSUE TITLE
ClientUtils' elementVisible should check for ancestor styles

### ISSUE THREAD

**Issue by n1k0** [casperjs/casperjs#1221]
Right now we're only checking for a given element visibility, though if it's wrapped in some hidden one it will still be declared as "visible", while it's obviously not.

**Comment by Rykus0** [comment]
Sorry, I just opened an issue about this same thing (I checked for similar issues yesterday, and didn't think to check again today).  I've almost got a PR ready, but wanted to run a few more tests.  Unless I'm overlooking something, it should be a pretty simple fix (see ref #1222).

**Comment by Rykus0** [comment]
I think the test also fails for `opacity: 0`.  Not sure if we want to also check if the element is hidden due to being obscured by another (e.g., z-index + position) or outside of the viewport.

**Comment by kensoh** [comment]
Archiving issue using **ARCHIVE** label as CasperJS, like PhantomJS, is not actively maintained for now.
