### ISSUE TITLE
clientutils.elementVisible() gives false positive when container has display:none

### ISSUE THREAD

**Issue by Rykus0** [casperjs/casperjs#1222]
I was putting some tests together, and noticed that an element was being reported as visible, even though it was not.  This happened when I checked an element (`<a>`) within a container that was hidden (`display:none`).

When the container's visibility is `hidden`, then `getComputedStyle` works.

We should also update the test cases in visible.js.  `waitWhileVisible is misleading because the element starts as hidden, and we're not testing that any waiting happened.  We could also add some more test cases, such as testing an element that is a child of a hidden container, zero width/height, opacity, and possibly others.

I began working on the code, but haven't had enough time to finish it, and it might be a while (maybe a week or two) before I get another opportunity.

**Comment by kensoh** [comment]
Bumping this. Don't think there is advance logic for handling elements not visible to eye due to various properties.

**Comment by Rykus0** [comment]
Sorry, I've had a lot come up since I started working on this, and it's dropped off my radar.
I will make it a priority to finish before next week!

**Comment by kensoh** [comment]
Thanks @Rykus0 for your quick reply! I'm a CasperJS user for couple of years. Now browsing through open issues to see if anything I can help. That's cool!

I saw a few related issues on advance handling of element visibility instead of taking them on surface value that they exist. Interesting but tricky topic.

**Comment by Rykus0** [comment]
I opened PR #1837 for this.  Most of that code was written years ago, so hopefully it's still good...  All of the tests pass, so that's something.

**Comment by kensoh** [comment]
Thanks @Rykus0 ! Tagging @jefleponot CasperJS current main maintainer.

**Comment by Rykus0** [comment]
I just realized that I missed some stuff - updates since I first worked on this.  I'm going to integrate those updates and clean things up.  Should have another PR ready tonight though :)

**Comment by Rykus0** [comment]
Ok, so it looks like the issue of ancestry had already been addressed.   I'm used to accommodating all the way back to IE8, so I started doing some extra work before I realized this is only for PhantomJS and SlimerJS.  

I ended up adding a bunch of test cases, and adding support for reporting out-of-viewport elements as invisible.  

Created PR #1837 for this.

**Comment by kensoh** [comment]
Thanks again @Rykus0 !  :smile: Tagging @jefleponot to keep in loop.

**Comment by kensoh** [comment]
Also tagging https://github.com/casperjs/casperjs/issues/1221 and https://github.com/casperjs/casperjs/issues/1736 again.

**Comment by kensoh** [comment]
Archiving issue using **ARCHIVE** label as CasperJS, like PhantomJS, is not actively maintained for now.
