### ISSUE TITLE
Way to control a pool of PhantomJS instances

### ISSUE THREAD

**Issue by ohenak** [casperjs/casperjs#1226]
Our team has written several thousand test cases based on CasperJS and now we are hitting an issue:
When we run all the test cases in one shot, somewhere during the run, casper just stuck before the `injectClientUtils` call.

We confirmed that the service did return `200` response to PhantomJS. We are suspecting that too many PhantomJS instances got created by the test cases and we are wondering if there is a way to control a pool of PhantomJS?

Correct me if I am wrong, it seems like every time when we do casper.start it will spin off a PhantomJS instance, right?

**Comment by jefleponot** [comment]
Hi,

An issue : How do you schedule yours tests ?
With my team, we don't have written thousand test cases but capture them with an addon of firefox. It's easiest, fastest and maintenance is simplify.
CasperJs is included in our program.

We haven't any trouble with our 452 tests, schedule each 5 mns.

**Comment by ohenak** [comment]
@jefleponot we are generating them based on a template test script and set of control parameters for the page we are testing.

You mentioned scheduling, is it part of your program? Or it is a feature in CasperJS?

**Comment by jefleponot** [comment]
No we use Nagios

**Comment by nathanboktae** [comment]
> We are suspecting that too many PhantomJS instances got created by the test cases

Casperjs runs within one phantomjs process, so that's not your issue.

**Comment by kensoh** [comment]
Interesting thread, I wonder how do people (or is it common) implement parallel execution of multiple CasperJS/PhantomJS instances. I'm still using LAMP VPS with 2GB and from memory/cpu usage it looks like it can handle at most 2 sessions at the same time.

I was once joking with my friends can use CasperJS / PhantomJS to load test websites. But the resource requirements are so large that LoadRunner's method looks more realistic. Or using Selenium to drive a farm of real laptops opening multiple tabs.

**Comment by kensoh** [comment]
Closing this issue as there isn't new replies for a while but do reopen if anything!
