### ISSUE TITLE
Can't access shadow DOM

### ISSUE THREAD

**Issue by benjiec** [casperjs/casperjs#1228]
Hello,

I am hoping to use casperjs to test some polymer based JS apps. However, I can't seem to get casperjs to find shadow DOM elements. E.g.

test.assertSelectorHasText('#main::shadow h3', 'Some Title');

Does not seem to be able to locate the h3 within a shadow DOM.

Is this something CasperJS has to support? Or this is a PhantomJs issue?

Thanks.

**Comment by jefleponot** [comment]
Hi,

Is "::shadow" a pseudo Element in css ?

If not you can try :

**Comment by nathanboktae** [comment]
> Or this is a PhantomJs issue?

A phantomjs issue. I highly doubt that the QT5 WebKit supports the shadow DOM.

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:**
Looks to be a stale help request. Assuming you've moved on to better and cooler things. Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
