### ISSUE TITLE
Incorrect line number in stack trace when test fails

### ISSUE THREAD

**Issue by mefiblogger** [casperjs/casperjs#1230]
Hello!

When a test fails, the test file's line number is incorrect in the stack trace.

As I see, the line number is somehow belongs to the casper.js file (line 1058) not to the test file (line129), which in this case is a file with 259 lines of code.

I marked the line numbers with bold in the output:

casper:

```
 [exec] Test file: autosuggestTest.js
 [exec] #    type: uncaughtError
 [exec] #    file: test/jsfunctional/casper/autosuggestTest.js:**1058**
 [exec] #    error: Cannot get informations from #sf_query: element not found.
 [exec] #           CasperError: Cannot get informations from #sf_query: element not found.
 [exec] #               at getElementInfo (/usr/lib/node_modules/casperjs/modules/casper.js:**1058**)
 [exec] #               at /usr/lib/node_modules/casperjs/modules/casper.js:1589
 [exec] #               at test/jsfunctional/utils/Autosuggest.js:48
 [exec] #               at test/jsfunctional/casper/autosuggestTest.js:129
 [exec] #               at runStep (/usr/lib/node_modules/casperjs/modules/casper.js:1553)
 [exec] #               at checkStep (/usr/lib/node_modules/casperjs/modules/casper.js:399)
 [exec] #    stack: not provided
 [exec] ⚠  --fail-fast: aborted all remaining tests
 [exec] FAIL 20 tests executed in 42.723s, 19 passed, 1 failed, 0 dubious, 0 skipped.
 [exec] 
 [exec] Details for the 1 failed test:
 [exec] 
 [exec] In test/jsfunctional/casper/autosuggestTest.js:**1058**
```

We are running CasperJS version 1.1.0-beta3 with Jenkins and ant but the problem still exists when running it locally without ant.

Thanks,
Mefi

**Comment by kensoh** [comment]
@mefiblogger bumping up. This still exists although the correct line # is also included in the test result above - `at test/jsfunctional/casper/autosuggestTest.js:129`. I guess people are living with this workaround with the misleading header/footer line # when running in test mode. When not in test mode there is no such header/footer to be misleading.

**Comment by kensoh** [comment]
@mefiblogger I had relook issue 570 and this looks like the same duplicated issue. I have bumped up that issue and closing this for now. Thanks for your feedback! I go copy you at that issue.
