### ISSUE TITLE
phantom js debugger does not load (casper master & phantomjs 2)

### ISSUE THREAD

**Issue by bughit** [casperjs/casperjs#1232]
`casperjs --remote-debugger-port=-1 googlelinks.js`
opens a blank phantomjs window

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:**
Looks to be a stale help request. Assuming you've moved on to better and cooler things. Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
