### ISSUE TITLE
Any way to pass variables into withFrame?

### ISSUE THREAD

**Issue by forgetso** [casperjs/casperjs#1233]
Hi,

Thanks for the awesome tool!

I need to access an iframe and pass a variable from outside the withFrame, something like follows:

`casper.withFrame(0,function(myVar) {
    this.echo(myVar);
});`

However, myVar is always undefined. Is there any way to pass the value in, perhaps with closures?

I tried creating a global window variable at the parent level and accessing it from within the iframe but it caused cross scripting errors.

**Comment by amerikan** [comment]
You can define a global variable
```js
var myVar = "foobarblah";
casper.withFrame(0,function() { this.echo(myVar); });
```

**Comment by kensoh** [comment]
That works ok for me too, since the globally defined variables are in CasperJS context, I find that they can be used in various blocks.

**Comment by kensoh** [comment]
Thanks @amerikan ! Hi @forgetso closing this issue as a global variable can be defined to be used. If you run into issues kindly ping, I'm on GitHub almost everyday these days. Otherwise you can email at ken@tebel.org
