### ISSUE TITLE
the method "scrollTo" doesn't work

### ISSUE THREAD

**Issue by qianjiahao** [casperjs/casperjs#1234]
I wanna fetch the image from other website , but it use the ajax to load the image , so i want to use "scrollTo" to simulate the client operation and load the image auto , but when i check the scrollHeight of the website , it was no change , and the image wasn't load as i wish , so please help me ~

code

casper.then(function(){
	this.scrollTo(1000,1000);

})
casper.then(function(){
	this.echo(document.documentElement.scrollHeight);
});

**Comment by qianjiahao** [comment]
and i try this way 

casper.viewport(1024, 768,function(){
	this.echo(document.documentElement.scrollWidth);	
});

but it has no change and return 400 as before ...

my casperjs version is 1.9.8

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:**
Looks to be a stale help request. Assuming you've moved on to better and cooler things. Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
