### ISSUE TITLE
[SlimerJS] Handling 302 Redirects - CasperJS hangs

### ISSUE THREAD

**Issue by ngotchac** [casperjs/casperjs#1236]
Hi,

I ran into an issue in the following use case:
- Using the **SlimerJS** engine
- I request an URL, receive a 302 to some location
- The next location sends a file where a _Javascript Redirect_ occurs

Running this with the **SlimerJS** engine makes CasperJS hangs.

To reproduce this issue, here is a sample server, a sample index.html file and a sample CasperJS script
- The NodeJS server:

``` javascript
var http = require('http'),
    fileSystem = require('fs'),
    path = require('path');

const PORT =  8088; 

function handleRequest(request, response){
    if (request.url === '/redirect') {
        response.writeHead(302, { 'Location': '/hello' });
        response.end();
    } else {
        var filePath = path.join(__dirname, 'index.html');
        var stat = fileSystem.statSync(filePath);

        response.writeHead(200, {
            'Content-Type': 'text/html',
            'Content-Length': stat.size
        });

        fileSystem.createReadStream(filePath).pipe(response);
    }
}

http.createServer(handleRequest).listen(PORT);
```
- The `index.html` file served:

``` html
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body>
    Hello CasperJS
    <script type="text/javascript">
        window.addEventListener('load', function() {
            window.location.hash = '#test';
        });
    </script>
</body>
</html>
```
- The CasperJS script:

``` javascript
var casper = require('casper').create({
    verbose: true,
    logLevel: 'debug'
});

casper
    .start('http://localhost:8088/redirect')
    .run();
```

CasperJS freezes because here's what SlimerJS sends (events):
- `NavigationRequest('/redirect')`
- `URLChanged('/hello')`
- `NavigationRequest('/hello#test')`

However, CasperJS changes it's inner `casper.requestURL` only on the `NavigationRequested` events. Thus, when SlimerJS sends the `URLChanged` event with `/hello`, CasperJS still has the previous `/redirect` URL in `casper.requestURL`. Then, on `NavigationRequest('/hello#test')`, the flag `casper.navigationRequested` is set to `true`, waiting for an `URLChanged` event that never occurs.

Here's what PhantomJS sends (events) for the same script:
- `NavigationRequest('/redirect')`
- `NavigationRequest('/hello')`
- `URLChanged('/hello')`
- `NavigationRequest('/hello#test')`
- `URLChanged('/hello#test')`
## Finally

I'm not sure if that's a CasperJS or a SlimerJS issue, but I managed to fix this in CasperJS. In the `modules/casper.js` file, [line 2612](https://github.com/n1k0/casperjs/blob/master/modules/casper.js#L2612), in the `page.onUrlChanged` handler, just add:

``` javascript
casper.requestUrl = url;
```

Why is that `requestUrl` only modified in the `page.onNavigationRequested` method? I think handling this in the `page.onUrlChanged` handler will work just fine. Waiting on feedbacks.

Thanks!

**Comment by sprak3000** [comment]
+1

**Comment by kensoh** [comment]
@ngotchac @sprak3000 bumping up. It's been almost 2 years, I don't see your commit in current code. But not sure if this scenario still fails for you? I'm a CasperJS user browsing through old open issues.

**Comment by sprak3000** [comment]
@kensoh 

It appears the [PR](https://github.com/casperjs/casperjs/pull/1237) for the change had some feedback that was not addressed. It was never merged in; however, the thread for the PR mentions @BIGjuevos possibly cloning the PR into a different one to resolve the issue. Not sure if that was seen through; the slimerjs tests I had an issue with have been shelved for some time. Would need to revisit them to see if the issue persists with latest code.

**Comment by kensoh** [comment]
@sprak3000 I see.. Oh yeah it has been a year ago. Now @jefleponot is maintaining the repo. Not sure if this issue is still happening with v1.1.4 and SlimerJS v0.10.3.

**Comment by lukeIam** [comment]
> Would need to revisit them to see if the issue persists with latest code.

With the current release it does.

I'm quite new to casperjs and it took me hours to find this issue.
But after inserting `casper.requestUrl = url;` in  `modules/casper.js` it works as expected (CasperJS does not hang)

**Comment by kensoh** [comment]
Thanks @lukeIam for checking and sharing your finding!

Copying @jefleponot the current main maintainer in the loop.

**Comment by kensoh** [comment]
Want to tag another 302 related issue - https://github.com/casperjs/casperjs/issues/1202

**Comment by kensoh** [comment]
Archiving issue using **ARCHIVE** label as CasperJS, like PhantomJS, is not actively maintained for now.
