### ISSUE TITLE
Drag and Drop with Angular-DragDrop

### ISSUE THREAD

**Issue by picheli20** [casperjs/casperjs#1242]
I was trying to make a test on my project, but the drag and drop its not working. I already tried the issues [#147](https://github.com/n1k0/casperjs/issues/147) and [#379](https://github.com/n1k0/casperjs/issues/379). Does anyone else have this problem? I don't know how to resolve this.

The directive is [Angular DragDrop](http://www.directiv.es/Angular-DragDrop).

**Comment by Ima1120** [comment]
I've faced with the same issue https://github.com/n1k0/casperjs/issues/1205. 
It looks like the issue comes up from phantomjs as you will face the same issues if you use phantomjs command such as this.page.sendEvent('mousemove',500,500) .

**Comment by picheli20** [comment]
I tried this 3 ways, and anyone works.

```javascript
casper.page.sendEvent('mousedown', 61, 98);
casper.page.sendEvent('mousemove', 311, 99);
casper.page.sendEvent('mouseup', 311, 99);
```

```javascript
this.mouse.move(61, 98);
casper.page.sendEvent('mousemove', 311, 99);
this.mouse.up(311, 99);
```

```javascript
this.mouse.move(61, 98);
this.mouse.move(311, 99);
this.mouse.up(311, 99);
```

I have no idea how to fix this...

**Comment by kensoh** [comment]
@picheli20 @ImaMiri it doesn't look like there is native support for this yet. Probably only implementable using mouse down/move/up now. I saw @ImaMiri other thread that it is not working. Not sure if this hack works now for her scenario?

**Comment by kensoh** [comment]
Closing the issue as there hasn't been replies for a long while. But do reopen if anything!
