### ISSUE TITLE
Link to appropriate directions for installing phantomjs < 2.0

### ISSUE THREAD

**Issue by brandondrew** [casperjs/casperjs#1248]
The installation page for CasperJS lists among dependencies

> PhantomJS 1.8.2 or greater, but less than 2.0. Installation instructions can be found [here](http://phantomjs.org/download.html)

but gives a link to directions for installing PhantomJS **_2.0.0**_.  It would be better to either give directions on casperjs.org (if there's no reliable & canonical set of appropriate directions on phantomjs.org) or to link to directions for the right version of PhantomJS.  The act of linking to the directions implies that they are the correct directions.  Many people will not immediately notice the version discrepancy.

**Comment by brandondrew** [comment]
I believe the installation would be as simple as 

```
brew install homebrew/versions/phantomjs198
```

**Comment by kensoh** [comment]
@brandondrew it's been a while, looks like the current download instructions are ok. I'm a CasperJS user looking through the old issues.

http://docs.casperjs.org/en/latest/installation.html

**Comment by kensoh** [comment]
Thanks @brandondrew ! Closing this issue for now as the current download instructions seem to be ok, but do ping if you see something wrong. Thank you again for flagging this out :)
