### ISSUE TITLE
xhr fails due to content-security-policy

### ISSUE THREAD

**Issue by Kevin-A** [casperjs/casperjs#1249]
My crawler sends data to a webserver using xhr. It sends the request through either Casper's clientutils module or a manual version. Both versions fail.

A domain on which this happens is Twitter.com. I don't actually want to crawl/scrape Twitter, but some redirects send me there. If I try to send a log entry while on that domain the crawler crashes with:

```
[error] Failed to open http://somewebsite.com/2015/03/01/yay/?share=twitter&nb=1
[error] [remote] SecurityError: DOM Exception 18: An attempt was made to break through the security policy of the user agent.
die message: Error: LogEntry is not properly created: null
```

Twitter's policy is: `content-security-policy → default-src https:; connect-src https:; font-src https: data:; frame-src https: twitter:; frame-ancestors 'self'; img-src https: blob: data:; media-src https: blob:; object-src https:; script-src 'unsafe-inline' 'nonce-gAC+s/MW2j6saqOAi/L8ww==' 'unsafe-eval' https:; style-src 'unsafe-inline' https:; report-uri https://twitter.com/i/csp_report?a=NVQWGYLXFVZXO2LGOQ%3D%3D%3D%3D%3D%3D&ro=false;`

I'm suspecting it's due to `connect-src https:;` as my webserver runs locally without SSL.

**Comment by Kevin-A** [comment]
Also the case on http://blog.getbootstrap.com/2012-12-08/bootstrap-2-2-2-released With a content-security-policy of: `Content-Security-Policy → default-src 'none'; style-src 'unsafe-inline'; img-src data:; connect-src 'self'`.

Seems to be an PhantomJS issue (https://github.com/ariya/phantomjs/issues/11337). Unfortunately I am already on 2.0.

It's also definitely causes by `connect-src`. Running in Chrome's console gives:

```
var req = new XMLHttpRequest(); req.open('req', 'http://www.google.com', false);
VM212:2 Refused to connect to 'http://www.google.com/' because it violates the following Content Security Policy directive: "connect-src 'self'".
```

**Comment by kensoh** [comment]
@Kevin-A this is an interesting issue.. Not sure if it is already fixed. Just following this thread to understand more.. I'm a CasperJS user now browsing through old issues.
