### ISSUE TITLE
Allow prompting user for input (such as password) during script execution

### ISSUE THREAD

**Issue by brandondrew** [casperjs/casperjs#1250]
I am writing a script to test an app I'm building.  Everything is going well so far except for one thing: it seems that the only way to make log-in information available to Casper is to either 
1. hard-code it in the script, OR
2. pass it on the command line when the script is initially run.

Option # 1 exposes my log-in info in the Git repo, so that's not good.  Option # 2 means I'm leaving the password in my shell history, which is not as bad but still not good.  

What I'd like to do is be able to ask the user for input _during_ the script execution.  For instance, with something like

```
var password = casper.ask("Password: ");
```

The closest thing I've been able to find in the docs (or by Googling generally) is [this](http://casperjs.readthedocs.org/en/latest/cli.html), which is about Option # 2.

**Comment by ngotchac** [comment]
After some investigation, this could be possible, but you won't be able to hide was the user writes in the console. Thus, I don't know if it's really usefull... At least it won't appear in your Bash history, or in your repo.

The reason is that PhantomJS uses QT.io, which reads and writes from/to stdin/stout as they were files, and cannot do this asynchronously. So you can only call `read(n)` where `n` is the number of bytes to read or `readLine()`, which both will return a string only when the user hits `<Enter>`.
Thus, you cannot read character by character, and cannot delete the entered character because you cannot write to stdout one line before...

I'm really not sure about that, but I'd be glad to be enlightened if I'm saying bullshits :p

**Comment by ngotchac** [comment]
You may try it here: https://github.com/ngotchac/casperjs/tree/allow-password-prompt

No test file has been written so I don't how this would work...

But here's a sample:
```javascript
var casper = require('casper').create();

casper.start().then(function() {
    var password = this.ask('Password: ');
    console.log('Input:', password);
});

casper.run();
```

**Comment by brandondrew** [comment]
If I understand you correctly, this is a huge improvement over the two previous options I mentioned.  With your approach, the only place the password is exposed (again, if I understand correctly) is in the terminal history.  As soon as I close (or clear) my terminal window, the password is not retrievable by normal means.  (Yes, perhaps some forensic voodoo might pull it from memory, but oh well.)

I think that's a big step forward.  I haven't tested it yet, but plan to do so soon...

**Comment by ngotchac** [comment]
Yep you understood correctly! However, clearing the Terminal will just output a few blank lines. But when you'll close it, no more traces of the password (except as you said from advanced Forensics :p)

**Comment by brandondrew** [comment]
If it turned out not to be possible *at all* to protect passwords with casperjs, the only other approach I could think of was writing a Ruby script to generate & run the casperjs script but never persist it to disk.  This would allow Ruby to do the initial interaction with the user in the terminal, and casperjs to do what it does best.

**Comment by brandondrew** [comment]
(I didn't mean issuing the `clear` command from the shell, but actually clearing the whole thing with the command that the terminal program itself offers.  For instance, on OS X both Terminal and iTerm have <kbd>Command</kbd> <kbd>K</kbd>, which clears the scrollback history.)

**Comment by ngotchac** [comment]
Oh yep, that's true. Could also be a NodeJS script, or whatever.

**Comment by brandondrew** [comment]
Having the ability to handle passwords in a relatively secure way is (IMHO) key for casperjs, since the big advantage that it has over a Ruby solution is that you can know ahead of time that you can log into any web site.  With Ruby you will run into situations where the site uses JavaScript to set cookies rather than HTTP headers, and since Ruby (at least all tools I've tried) is not actually running a headless browser, it's not executing the JavaScript and therefore not setting the necessary cookies and therefore not allowing you to log in.  That limitation has bitten me so many times with Ruby that I've just given up on it for all scraping/browser automation purposes.

That's a long way of saying: I hope this pull request gets accepted, since it adds a very important improvement to casperjs.

**Comment by rippo** [comment]
> Option # 1 exposes my log-in info in the Git repo

This is not entirely true as you can have a `password.js` file that you inject into phantom. This password.js file can then be excluded from GIT. 

You will get best of both worlds, scripts that can run with no user input and no sensitive info in your repo.

Just a thought

**Comment by brandondrew** [comment]
Yes, that's true, and a good point.  I'd still prefer not to have passwords saved on my hard drive, though, as it is also a security problem roughly equivalent to saving them in your shell history.

**Comment by Heart1010** [comment]
What is the actual state of this?

I also would find this very useful in my case where I first use casperjs to scrape a webpage and output all of the found select options in the terminal (because these option values change all the time). The user should then be able to write in the correct option value, press enter, and the next casperjs code should be run.

(or is this even possible right now in any way?!)

**Comment by jaamo** [comment]
This would actually be a great feature. Any plans to merge this into master? Or any other good practices to securely pass passwords to tests :)

**Comment by kensoh** [comment]
Hi @jaamo for me I create a separate password file from script file. I do it this way in my general purpose web automation tool base on CasperJS - https://github.com/tebelorg/TA.Gui. As the tool is designed to be run locally on user's local machine, the assumption is only he/she has access to the separate password file with credentials.

Hi @Heart1010 CasperJS does not support option selection (dropdown options) right out of the box, you have to write custom function to do that. See this CasperJS issue - https://github.com/casperjs/casperjs/issues/1390. I've also implemented this into the web automation tool above. What you described is possible I think. Get the options, print to screen, then get inputs using something like below. Then call your custom function to select the option.

```js
var input = ''; var sys = require('system');
input = sys.stdin.readLine();
```

Note that above code only works for running in PhantomJS mode. For SlimerJS mode using Firefox, use read() instead. However there is some issue going on now with read() so I've raised a feedback to SlimerJS - https://github.com/laurentj/slimerjs/issues/188.

**Comment by kensoh** [comment]
Closing this issue as it can already be done today when running in PhantomJS engine (above post is sample lines to do that). For SlimerJS, on top of the comment I added in issue 188, I raised a new issue to track that - https://github.com/laurentj/slimerjs/issues/639

But not sure the status of SlimerJS as the last reply to issue is 3 months ago.
