### ISSUE TITLE
casperjs 1.1beta 3  selftest failed

### ISSUE THREAD

**Issue by pats** [casperjs/casperjs#1251]
Hello,

Tests based on casperjs failed. I think this issue is related to phantomjs.

OS is Windows 7

```
O:\mobilegui>phantomjs -v
1.9.8
O:\mobilegui>casperjs
CasperJS version 1.1.0-beta3 at C:/Dev/casperjs-1.1, using phantomjs version 1.9.8
```

```
Details for the 2 failed tests:

In C:/Dev/casperjs-1.1/tests/suites/casper/encode.js:10
  base64encode() and download() tests
    assertEquals: Casper.base64encode() can retrieve base64 contents
In C:/Dev/casperjs-1.1/tests/suites/casper/logging.js:38
  logging tests
    assertEquals: Casper.log() logged messages
Unsafe JavaScript attempt to access frame with URL about:blank from frame with URL file:///C:/Dev/casperjs-1.1/bin/bootstrap.js. Domains, protocols and ports must match.
```

I think this is related to 
https://github.com/n1k0/casperjs/issues/1068
https://github.com/iamchrismiller/grunt-casper/issues/60

Regards,
patS

**Comment by istr** [comment]
Could you please try to install phantomjs 1.9.7 and check if you still encounter this issue?
Thanks.

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:**
Looks to be a stale help request. Assuming you've moved on to better and cooler things. Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
