### ISSUE TITLE
1.1-beta3 - cannot find module 'http'

### ISSUE THREAD

**Issue by tungtouch** [casperjs/casperjs#1254]
I was installed casperjs 1.1-beta3: npm install -g casperjs 
![screen shot 2015-06-19 at 8 24 31 pm](https://cloud.githubusercontent.com/assets/7944776/8254291/57b16c6c-16c1-11e5-9ca8-45a16b81e762.png)

test.js:
```javascript
//var require = patchRequire(require);
//phantom.casperPath = "/usr/local/bin/casperjs";
//phantom.injectJs(phantom.casperPath + "/bin/bootstrap.js");

var fs      = require('fs'),
    request = require('request');

var casper = require('casper').create({
    verbose: true,
    /*logLevel: "debug",*/
    pageSettings: {
        loadImages: false,        // The WebPage instance used by Casper will
        loadPlugins: false         // use these settings
    }
});
.....
```
Then, i run script: `casperjs test.js`
Log: 
![screen shot 2015-06-19 at 8 14 16 pm](https://cloud.githubusercontent.com/assets/7944776/8254282/49288a22-16c1-11e5-9155-09ba3f4b5673.png)

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:**
Looks to be a stale help request. Assuming you've moved on to better and cooler things. Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
