### ISSUE TITLE
sendAjax not working 

### ISSUE THREAD

**Issue by ivaaaan** [casperjs/casperjs#1257]
I have a script from example: 

``` javascript
var casper = require('casper').create();


var data, wsurl = 'http://api.github.com/users/mralexgray/repos';

casper.start('http://github.com/', function() {
    data = this.evaluate(function(wsurl) {
        return JSON.parse(__utils__.sendAJAX(wsurl, 'GET', null, false));
    }, {wsurl: wsurl});
});

casper.then(function() {
    require('utils').dump(data);
});

casper.run();
```

When i run: 

``` bash
$ casperjs api.js --web-security=no
null
```

So, why `null`?

**Comment by Kevin-A** [comment]
Look at the output in the console. The URL you provide has the following value for the `content-security-policy` header: `default-src 'none'`. This means you cannot do xhr on said page, which is what sendAJAX uses.

My issue explains this better: https://github.com/n1k0/casperjs/issues/1249
And on the PhantomJS repo: https://github.com/ariya/phantomjs/issues/13346

No solutions to either issue yet.

**Comment by kensoh** [comment]
@ivaaaan @Kevin-A it looks like the script is still giving output null. Even if I use below.

```
casper.options.pageSettings = {
loadImages: true,
loadPlugins: true,
webSecurityEnabled: false,
ignoreSslErrors: true,
localToRemoteUrlAccessEnabled: false
};
```

**Comment by kensoh** [comment]
Archiving issue using **ARCHIVE** label as CasperJS, like PhantomJS, is not actively maintained for now.
