### ISSUE TITLE
URL never changes

### ISSUE THREAD

**Issue by RenaudParis** [casperjs/casperjs#1258]
Hi,

I try to click on a (javascript) link that changes the URL twice, and wait for a given URL to arise using various methods, including wait(), waitForSelector(), waitForUrl(), and even a custom waitForUrlChange(), but nothing works.

In debug mode I get the "[debug] [phantom] Navigation requested" event displayed with the new URL that I was expecting, but when trying to bind the casper.on('load.finished') event, I still get the same old URL, not the new one (and it fails with each and every of the various attempts described above)

It seems like no content ever changes in CasperJS (it works just fine using vanilla PhantomJS, but I would rather not reinvent the wheel)

Anyone having the same issue?

PhantomJS 1.9.7 (installed using jakoch/phantomjs-installer)
CasperJS 1.1.0-beta3 (installed using npm install -g)

Windows 7 64 bits

```javascript
var casper = require('casper').create({
	                                      verbose: true,
	                                      logLevel: "debug"
                                      });

casper.on('load.finished', function(status)
{
	console.log('****** load finished, what is the new url?');
	console.log(this.getCurrentUrl());
	console.log(this.getTitle());
});

casper.start('https://www.labanquepostale.fr/particulier.html', function()
{
	console.log('starting url');
	this.echo(this.getTitle());
});

casper.thenClick('#nav-account a', function()
{
	console.log('page loaded after click link'); // It does not work, it seems that I have to manually wait for the new page to load because of the javascript code that loads the page
	console.log('clicked ok, new location is ' + this.getCurrentUrl());
});

//casper.waitForUrl(/^https:\/\/voscomptesenligne\.labanquepostale\.fr\/wsost\/OstBrokerWeb\/loginform/, function()
//{
//	this.echo('redirected to login.html!!');
//}, null, 8000);

//casper.wait(5000, function() {
//	this.echo("I've waited for 5 seconds.");
//	console.log('new location is ' + this.getCurrentUrl());
//});

casper.then(function()
{
	console.log('wait for selector...');
	this.waitForSelector('#imageclavier', function()
	{
		console.log('IMAGECLAVIER is present!');
		console.log('new location is ' + this.getCurrentUrl());
	}, null, 8000);
});

casper.run(function()
{
	casper.exit();
});
```

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:**
Looks to be a stale help request. Assuming you've moved on to better and cooler things. Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
