### ISSUE TITLE
could not use phantomjs engine

### ISSUE THREAD

**Issue by iam404** [casperjs/casperjs#1259]
hii
i found myself in a situation where after installing slimmerjs ,it is not being possible to run the test on phantomjs.
To note phantomjs was working fine before i installed slimmerjs.
my working env is Ubuntu 14.04
And using latest Casperjs version.
```
Fatal: you can't override the preconfigured casper instance in a test environment.
Docs: http://docs.casperjs.org/en/latest/testing.html#test-command-args-and-options
Unsafe JavaScript attempt to access frame with URL about:blank from frame with URL file:///usr/local/lib/node_modules/casperjs/bin/bootstrap.js. Domains, protocols and ports must match.
```

**Comment by ngotchac** [comment]
Have you changed your code after installing SlimerJS ?
Because it seems that you are doing a `var casper = require('casper').create();` that **is** neccessary in SlimerJS but forbidden in PhantomJS.

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:**
Looks to be a stale help request. Assuming you've moved on to better and cooler things. Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
