### ISSUE TITLE
casper.exit() does not block

### ISSUE THREAD

**Issue by timscott** [casperjs/casperjs#1263]
In 1.1.0-beta3, casper.exit() does not block execution. Subsequent code will continue to execute creating a race in which the results are unpredictable.

**Comment by VersatilityWerks** [comment]
Same issue here. Trying to find a fix asap. Need version 2.0 for a site that's acting up, but also need reliability.

**Comment by timscott** [comment]
Shane,

Yes, it’s painful. As a workaround, this seems to work okay. Change this:

capser.thenOpen url, ->
  if done
    @exit()
  keep_going()

To this:

capser.thenOpen url, ->
  if done
    @exit()
  else
    keep_going()

In other words, cut off all execution paths after exit() within the same callback. It’s possible that execution can race on to the next step, but I have not see that yet.

Of course the big problem is, I have a lot of code that exits in the middle of callbacks, and it’s only practical to apply the workaround as bugs manifest.

-- 
Tim Scott

On August 3, 2015 at 1:37:53 PM, Shane Stebner (notifications@github.com) wrote:

Same issue here. Trying to find a fix asap. Need version 2.0 for a site that's acting up, but also need reliability.

**Comment by VersatilityWerks** [comment]
My problem is that usually I do multiple error checks per step. On top of that, I already wrote like 40 different scripts and don't wanna have to change them all to be one check per step.

**Comment by VersatilityWerks** [comment]
Thanks for sharing your fix though. It's much appreciated!

**Comment by VersatilityWerks** [comment]
Def. of interest: https://github.com/ariya/phantomjs/issues/13450
Maybe it's not Casper's fault?

**Comment by VersatilityWerks** [comment]
Where is that located?

**Comment by kensoh** [comment]
@timscott @VersatilityWerks not sure if this is still happening? I'm a CasperJS user for couple of years. Browsing through open issues now to see if anything I can help with. Do you have a sample script and website which this can be replicated?

**Comment by VersatilityWerks** [comment]
From a year and a half ago? No lol.

**Comment by kensoh** [comment]
Lol.. I was talking to current main maintainer Jef that to help out maybe I only close issues which I can try the steps and are already working. Otherwise may miss valuable inputs to improve tool.

**Comment by kensoh** [comment]
@timscott @VersatilityWerks when I try with latest CasperJS v1.1.4 and PhantomJS v2.1.1, the immediate next few steps of simple echo still runs. However following that, the waitFor + remaining steps do not run. Strictly speaking, it looks like the behavior is still non-blocking and does not quit immediately.

**Comment by VersatilityWerks** [comment]
Wow, thanks for testing. That blows. Wish this was tackled by now.

**Comment by kensoh** [comment]
I guess a workaround is to make sure a .then type of step happens right after the .exit, before doing anything else. It is not ideal, but this is how I try to make sure no other bloopers appear when program is supposed to exit when a condition is reached.

**Comment by mheesters** [comment]
@kensoh Someone added a note to the exit function in the CasperJS manual referencing to this issue:
https://github.com/casperjs/casperjs/issues/193

**Comment by kensoh** [comment]
Thanks @mheesters yes #193 has more details on why this happens.

For folks having this issue, try something like below. What I found is doing a .wait(0) right after an .exit() somehow would make the exit terminate at the point where it is called. (at least for my use cases).

```js
casper.exit();
casper.wait(0);
```

I'll go update this at issue #193 as well.

**Comment by kensoh** [comment]
Archiving issue using **ARCHIVE** label as CasperJS, like PhantomJS, is not actively maintained for now.
