### ISSUE TITLE
casper.logs property undefined

### ISSUE THREAD

**Issue by naomik** [casperjs/casperjs#1269]
**casperjs version:** `1.1.0-beta3`
**phantomjs version:** `1.9.8`

``` js
var casper = require('casper').create();

casper.start("http://google.com", function() {
  this.log('loaded google!');
});

casper.then(function() {
  this.log('this is a debug message', 'debug');
  this.log('and an informative one', 'info');
  this.log('and a warning', 'warning');
  this.log('and an error', 'error');
});

casper.run(function() {
  require('utils').dump(this.logs);
  this.exit();
});
```

Run it

``` sh
$ casperjs myscript.js
undefined
```

As you can see, `this.logs` is `undefined`. According to the [logging docs](http://casperjs.readthedocs.org/en/latest/logging.html), the `logs` property should collect the log messages during script execution.

Paste from the docs:

> You can also dump a JSON log of your Casper suite just by rendering the contents of the Casper.logs property:

``` js
var casper = require('casper').create({
// ...
casper.run(function() {
    require('utils').dump(this.logs);
    this.exit();
});
```

**My end goal is to do something like**

``` js
casper.run(function() {
  fs.write('./report.log', JSON.stringify(this.logs, null, "\t"), 'w');
  // ...
});
```

I've also tried to initialize casper with various options

``` js
var casper = require('casper').create({logLevel: 'info'});
// ...
```

But no matter what I try, `this.logs` is undefined. Can someone please help?

**Comment by alexwybraniec** [comment]
Are you switching on verbose in your actual code?

var casper = require('casper').create({
    verbose: true
});

**Comment by kensoh** [comment]
@naomik @alexwybraniec yes this is a bug that is now fixed. The logging docs now show below which works for me. I'm a CasperJS user now looking through past issues.

```js
require('utils').dump(this.result.log);
```

**Comment by kensoh** [comment]
Thanks @alexwybraniec :) Hi @naomik closing this issue for now as the current logging docs statement works. Ping if you still have some issues. These days I'm on GitHub almost everyday, otherwise can email me ken@tebel.org
