### ISSUE TITLE
i can't load home page linkedin ? 

### ISSUE THREAD

**Issue by idir-ait** [casperjs/casperjs#1272]
Hey everyone;

I want to load the png of home page linkedin but i have empty file who i can do this ?

var casper = require("casper").create();
casper.start('https://www.linkedin.com/nhome/');

casper.then(function() {
  this.echo('Title : ' + this.getTitle());
  this.capture('image.png');
});

casper.run();

thx for your help :)

**Comment by ngotchac** [comment]
I don't know if that could be the issue, but LinkedIn is blocking some servers from accessing their content, for example the Heroku ones : see [here](http://stackoverflow.com/questions/23843482/accessing-linkedin-public-pages-using-python/23849628#23849628) or [here](http://stackoverflow.com/questions/27571419/how-to-avoid-http-1-1-999-request-denied-response-from-linkedin)

**Comment by idir-ait** [comment]
I don't think, because when i use URL without httpS it's not working but when is http it's work fine.

**Comment by ngotchac** [comment]
Oh, so maybe you could try playing with the `--ssl-protocol` and `--ignore-ssl-errors` CL options : http://phantomjs.org/api/command-line.html

**Comment by idir-ait** [comment]
I try  [sslv3|sslv2|tlsv1|any'] but it's the same, i think it's can work with -ssl-certificates-path=<val> but i don't have any idea how use it :/

**Comment by idir-ait** [comment]
up

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:**
Looks to be a stale help request. Assuming you've moved on to better and cooler things. Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
