### ISSUE TITLE
problems with casperjs script after osx update

### ISSUE THREAD

**Issue by CoralieV** [casperjs/casperjs#1273]
Since updating to OSX 10.10.3 (and 10.10.4) casperjs script is not working anymore. It is scraping empty screenshots instead of what it should see. 

When testing the same script on an apple computer with 10.10.2 installed it was working again and succesfully scraped full screenshots (same search query) Everything else installed is the same (version of Python, Phantomjs, Homebrew etc.). I tried different versions of phantomjs (not higher then 1.9.7 since that is not working with Casperjs either.. With version 1.8.2 I get the following error: WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead.

Stuck on what to do..

**Comment by amerikan** [comment]
I use casperjs 1.1-beta3  and phantomjs 1.9.8 and have not had any issues as you mentioned above.

**Comment by istr** [comment]
@CoralieV Please try with PhantomJS 2.0.0 and current CasperJS master from git. Thank you.

**Comment by soulteary** [comment]
It seems that there're many people have the problem with old release both casperjs and PhantomJS, why not release a  casperjs pre-release which contain the PhantomJS v2 bin.

**Comment by istr** [comment]
@soulteary You're right, and we would like to do this as fast as possible, but the man power for this project is on very thin ice currently, see https://github.com/n1k0/casperjs/issues/1350 and https://github.com/n1k0/casperjs/issues/1365.

If you would like to see an update check in CasperJS, feel free to implement it and create a PR.

**Comment by soulteary** [comment]
@istr i will.

**Comment by kensoh** [comment]
Bumping this interesting idea of update check :)

**Comment by kensoh** [comment]
Closing this as there hasn't been update for a long time. I'm also guessing most developers now have their channels of auto-updating packages. But do reopen if anything!
