### ISSUE TITLE
Problem with casperJS on Ubuntu

### ISSUE THREAD

**Issue by idir-ait** [casperjs/casperjs#1276]
Hey everyone;

I want to report you trouble on casperJS (I think it is a bug), when i try to execute my script (see below) I have message tell me "I'm `fs` modules",I do not understand what it means :/ ???

My code :
-----------
var casper = require("casper").create();
casper.start('https://www.linkedin.com/nhome/');
casper.then(function() 
{
  this.echo('Title : ' + this.getTitle());
  this.capture('image.png');
});
casper.run();

Result :
---------
$ casperjs monscript.js 
I'm `fs` modules

Informations :
----------------
$ casperjs --version 
1.1.0-beta3
$ which casperjs 
/usr/local/bin/casperjs
$ phantomjs --version
1.9.8
$ which phantomjs 
/usr/bin/phantomjs

$ cat /etc/issue
Ubuntu 14.10 \n \l

I also want to say that phantomjs work properly. If someone know how i can fix it ?

**Comment by shanvenleo** [comment]
I have the same problem in the windows10
I test 4 PCs ,have the same problem.
> >phantomjs --version
> 1.9.6
> >casperjs --version
> 1.1.1
> >casperjs sample.js
> I'm `fs` modules

**Comment by istr** [comment]
Broken with PhantomJS 1.9.*

Works for me using PhantomJS 2.1.1 and CasperJS 1.1.1 on Ubuntu 14.04 LTS.
