### ISSUE TITLE
Using sessionStorage with CasperJS

### ISSUE THREAD

**Issue by bl4de** [casperjs/casperjs#1282]
Hi there,

I'm testing an application with CasperJS and PhantomJS.

I've got a problem with test where some values from sessionStorage should be used. It looks like CasperJS does not use sessionStorage in any way (this particular feature which I'd like to test works fine in all browsers which support sessionStorage of course, so it's not a problem of application itself).

I've tried to call my tests with --local-storage-path=somefile, but it doesn't work either. Also, there's an information on http://phantomjs.org/api/command-line.html about localStorage:

> --local-storage-path=/some/path path to save LocalStorage content and WebSQL content.

but there's nothing about sessionStorage.

Did anyone experienced similar issue before?
Thanks

**Comment by stephanebachelier** [comment]
@bl4de you can use `sessionStorage` with casperjs.

See http://stackoverflow.com/questions/32554241/how-to-set-sessionstorage-in-phantomjs-and-casperjs.

In my case I've done something like this:

```js

casper.waitForUrl(/url/, function() {
  var value = this.evaluate(function(){
    return sessionStorage.getItem('foo');
  });
  console.log("session storage value: " + value);
}
```

**Comment by bl4de** [comment]
@stephanebachelier Thank you! I've missed this Stackoverflow post, it's from September.

I have to get back to this issue soon :)

**Comment by mickaelandrieu** [comment]
@stephanebachelier could be useful to complete the FAQ of official docs with this answer, what do you think @istr ?

**Comment by istr** [comment]
Maybe put a section how, when and why to use ```evaluate``` at a more prominent place, e.g. a sub-section of "quickstart".

From what I recall using CasperJS first and writing real stuff to test my apps this was the part least documented and hardest to get. Lots of help requests / questions seem to concern executing stuff in the page's context. So maybe best create an introductory section on that topic.

**Comment by kensoh** [comment]
Closing this issue for now, it seems that along the way the section is added. I find the evaluate section of API documentation useful, especially the flowchart diagram that really helps user in visualizing what the different contexts meant.

http://docs.casperjs.org/en/latest/modules/casper.html#evaluate
