### ISSUE TITLE
Casper infinitely loops when adding event handler for failure: Casper.test.on("fail" 

### ISSUE THREAD

**Issue by AwakenedClaymore** [casperjs/casperjs#1283]
I added this handler to help me take screenshots on fail.

casper.test.on("fail", function(failure) {
    timeOutHelper.screenshots("Failure_screenshot_" );
});

I noticed that if I try to reference a page like

var timeOutHelper = require(**dirname** + '/helpers/helper.js');

I will get "CasperError: Can't find module /path/of/file"

and I get an infinite loop of below:

FAIL CasperError: Can't find module /Users/tom/workspace/hello_trunk/hello-casper/pages/projec/project-page.js
CasperError: Casper is not started, can't execute `capture()`
  /Users/tom/casperjs/1.1-beta3-li1/node_modules/casperjs/modules/casper.js:430 in checkStarted
  /Users/tom/casperjs/1.1-beta3-li1/node_modules/casperjs/modules/casper.js:309 in capture
  /Users/tom/workspace/cap-frontend_trunk/cap-frontend-tests-casper/helpers/tools_helper.js:9 in screenshots
  /Users/tom/workspace/cap-frontend_trunk/cap-frontend-tests-casper/globals.js:30
  /Users/tom/casperjs/1.1-beta3-li1/node_modules/casperjs/modules/events.js:104 in emit
  /Users/tom/casperjs/1.1-beta3-li1/node_modules/casperjs/modules/tester.js:1412 in processAssertionResult
  /Users/tom/casperjs/1.1-beta3-li1/node_modules/casperjs/modules/tester.js:325 in assert
  /Users/tom/casperjs/1.1-beta3-li1/node_modules/casperjs/modules/tester.js:1253 in fail
  /Users/tom/casperjs/1.1-beta3-li1/node_modules/casperjs/modules/tester.js:1456 in processPhantomError
  /Users/tom/casperjs/1.1-beta3-li1/node_modules/casperjs/modules/tester.js:192 in onCasperError
  /Users/tom/casperjs/1.1-beta3-li1/node_modules/casperjs/modules/events.js:104 in emit
  /Users/tom/casperjs/1.1-beta3-li1/node_modules/casperjs/modules/casper.js:1228 in phantom_onError
  /Users/tom/workspace/cap-frontend_trunk/phantomjs:/bootstrap.js:58

Is there something I need to add in casper.test.on("fail", function(failure) to end casper?

**Comment by noma4i** [comment]
Same problem here.

**Comment by kensoh** [comment]
@AwakenedClaymore @noma4i it's been a while, not sure if this is still happening. I'm a CasperJS user for couple of years. Browsing through open issues now to see if anything I can help with. Do you have a sample script and website that this can be replicated on?

**Comment by noma4i** [comment]
This is not an issue as long as you will use fs to require files and share casper context with them. 
Like:
```
var fs = require('fs');
var _ = require(fs.absolute(fs.workingDirectory + '/includes/underscore.js')),
  helpers = require(fs.absolute(fs.workingDirectory + '/shared/helpers'))(casper, _),
```

So I believe that this should be closed with RTFM statement ;)

**Comment by noma4i** [comment]
Main point is: whenever you create casper instance you should share it with all helpers.

**Comment by kensoh** [comment]
Thanks @noma4i I haven't come across that in the docs, maybe I missed it :)

**Comment by kensoh** [comment]
@AwakenedClaymore closing this for now but do reopen if you still have an issue after using @noma4i 's suggestion. Thanks for raising the question :)
