### ISSUE TITLE
Unable to upload/import file from desktop

### ISSUE THREAD

**Issue by Prateek032** [casperjs/casperjs#1285]
The scenario is i need to import files from the directory to the web page but when i click on file upload, it gets stuck over there. I tried with all the possibilities but still the file upload is not working

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:**
Looks to be a stale help request. Assuming you've moved on to better and cooler things. Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
