### ISSUE TITLE
ReferenceError: Can't find variable: process

### ISSUE THREAD

**Issue by DeveloperUX** [casperjs/casperjs#1286]
I am having issues with CasperJS running on a mac. I'm trying to use SpookyJS (which relies on Casper). So I wasn't sure where to post this issue.  I am getting this error message whenever I try to run my application using CasperJS. I've been digging into it and looks like an issue with the different software versions.

Here's the error message:

```ReferenceError: Can't find variable: process```

I have tried different versions of CasperJS and PhantomJS and nothing seems to help.

These are the versions I am currently using:

```
PhantomJS: 1.9.8
CasperJS: 1.1-beta3
Mac version: 10.10 (Yosemite)
```

Any help would be appreciated.

**Comment by nathanboktae** [comment]
Sounds like you're trying to use a module or code that assumes it's running in a node.js environment rather than phantomjs.

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:**
Looks to be a stale help request. Assuming you've moved on to better and cooler things. Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
