### ISSUE TITLE
Casperjs launches PhantomJS which exits quietly, doing nothing

### ISSUE THREAD

**Issue by ysangkok** [casperjs/casperjs#1287]
I am having the issue that casperjs (master) simply launches, tries to start phantomjs, which just exits, and nothing happens. I inserted a `print(CASPER_COMMAND)` call just before the call to execvp in bin/casperjs and this is what I get:

    $ PHANTOMJS_EXECUTABLE=/home/janus/Downloads/phantomjs-1.9.8-linux-x86_64/bin/phantomjs ./casperjs/bin/casperjs testproxy.js 
    ['/home/janus/Downloads/phantomjs-1.9.8-linux-x86_64/bin/phantomjs', '/home/janus/browser-http-proxy/casperjs/bin/bootstrap.js', '--casper-path=/home/janus/browser-http-proxy/casperjs', '--cli', 'testproxy.js']
    $

The primary issue may not be with casperjs, but it would be useful if casperjs checked the exit code of phantomjs to see if something went wrong. When manually launching `/home/janus/Downloads/phantomjs-1.9.8-linux-x86_64/bin/phantomjs /home/janus/browser-http-proxy/casperjs/bin/bootstrap.js --casper-path=/home/janus/browser-http-proxy/casperjs --cli testproxy.js` and checking the exit code `$?`, I see that it is `1`, which signals an error.

**Comment by gmisura** [comment]
Are you missing a ; after PHANTOMJS_EXECUTABLE=/home/
janus/Downloads/phantomjs-1.9.8-linux-x86_64/bin/phantomjs

PHANTOMJS_EXECUTABLE=/home/janus/Downloads/phantomjs-1.9.8-linux-x86_64/bin/phantomjs;
./casperjs/bin/casperjs testproxy.js


On Sun, Aug 9, 2015 at 10:38 AM, Janus Troelsen <notifications@github.com>
wrote:

> I am having the issue that casperjs (master) simply launches, tries to
> start phantomjs, which just exits, and nothing happens. I inserted a
> print(CASPER_COMMAND) call just before the call to execvp in bin/casperjs
> and this is what I get:
>
> $ PHANTOMJS_EXECUTABLE=/home/janus/Downloads/phantomjs-1.9.8-linux-x86_64/bin/phantomjs ./casperjs/bin/casperjs testproxy.js
> ['/home/janus/Downloads/phantomjs-1.9.8-linux-x86_64/bin/phantomjs', '/home/janus/browser-http-proxy/casperjs/bin/bootstrap.js', '--casper-path=/home/janus/browser-http-proxy/casperjs', '--cli', 'testproxy.js']
> $
>
> The primary issue may not be with casperjs, but it would be useful if
> casperjs checked the exit code of phantomjs to see if something went wrong.
> When manually launching /home/janus/Downloads/phantomjs-1.9.8-linux-x86_64/bin/phantomjs
> /home/janus/browser-http-proxy/casperjs/bin/bootstrap.js
> --casper-path=/home/janus/browser-http-proxy/casperjs --cli testproxy.js
> and checking the exit code $?, I see that it is 1, which signals an error.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/n1k0/casperjs/issues/1287>.
>



-- 
Gabe Misura

**Comment by ysangkok** [comment]
@gmisura: No, I don't think so, I am executing this in the shell, and this is the syntax for setting environment variables for a single command. See point 7 "Assignment preceding command name" of the [Open Group Base Specifications Issue 7 Shell Grammar Rules](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_10_02).

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:**
Looks to be a stale help request. Assuming you've moved on to better and cooler things. Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
