### ISSUE TITLE
How can I get status flag with casper with "Open" method?

### ISSUE THREAD

**Issue by jefleponot** [casperjs/casperjs#1288]
with phantomjs :+1: 

<pre>
var webPage = require('webpage');
var page = webPage.create();

page.open('http://www.google.com/', function(status) {
  console.log('Status: ' + status);
  // Do other things here...
});
</pre>

How can we do the same thing with casperjs to get the status flag ?

**Comment by kensoh** [comment]
Hi Jef, closing this issue for now as there has not been replies for a long time :)
