### ISSUE TITLE
Another infinite loop report - multiple test cases provided

### ISSUE THREAD

**Issue by pleasantone** [casperjs/casperjs#1296]
This is outside test framework, in just native casperjs, with the caveat that I am running PhantomJS 2.x,
which is released, but still officially unsupported by CasperJS.

```
/*
 * Example of casperjs (current from github) and PhantomJS 2.0.1-development (unsupported by CapserJS)
 * problem with exception handling.
 */

// throw("before casper create");

/* produces the following output and (BUG!) the process hangs and does not exit

before casper create
  foo.js:6 in global code
    :0 in injectJs
      /usr/local/share/casperjs/bin/bootstrap.js:416
   BUG: process hangs, does not exit   
*/


var casper = require('casper').create({
    verbose: true,
    logLevel: 'debug',
});

// throw("before on.error");

/* produces no output at all (BUG!) and the process hangs and does not exit (BUG!) */

casper.on('error', function(msg, trace) {
    this.log('Error: ' + msg, 'error');
    this.exit(1);
});

// throw("after on.error");

/* produce repeated output -- (BUG!)
 *
 * [error] [phantom] Error: after on.error                                                                  
 * [error] [phantom] Error:   /home/pst/inteld:198                                                 
 * [error] [phantom] Error:   /home/pst/inteld:198
 * [error] [phantom] Error:   /home/pst/inteld:198                                                 
 * [error] [phantom] Error:   /home/pst/inteld:198                                                 
 * [error] [phantom] Error:   /home/pst/inteld:207
 * [error] [phantom] Error:   /home/pst/inteld:198
 * [error] [phantom] Error:   /home/pst/inteld:198                                                 
 * [error] [phantom] Error:   /home/pst/inteld:198                                                 
 * [error] [phantom] Error:   /home/pst/inteld:198
 * [error] [phantom] Error:   /home/pst/inteld:198                                                 
 * [error] [phantom] Error:   /home/pst/inteld:207     
 *
 * and the process hangs... (BUG!)
 */

casper.start('http://www.google.com');

casper.then(function test_throw() {

    throw("in casper step");

    /* produces repeated output -- (BUG!):
     *
     * [error] [phantom] Error:   /home/pst/inteld:198
     * [error] [phantom] Error: in casper step                                                                  
     * [error] [phantom] Error:   /home/pst/inteld:198                                                 
     * [error] [phantom] Error:   /home/pst/inteld:198
     * [error] [phantom] Error:   /home/pst/inteld:198                                                 
     * [error] [phantom] Error:   /home/pst/inteld:198                                                 
     * [error] [phantom] Error:   /home/pst/inteld:198
     * [error] [phantom] Error:   /home/pst/inteld:198                                                 
     * [error] [phantom] Error:   /home/pst/inteld:198                                                 
     * [error] [phantom] Error:   /home/pst/inteld:198                                                 
     * [error] [phantom] Error:   /home/pst/inteld:207
     *
     * and the process hangs... (BUG!)
     */
});

casper.run();
```

**Comment by pleasantone** [comment]
I also filed a similar bug with phantomjs, as the native phantomjs doesn't recover from an uncaught throw, but the looping seems to be our problem.

https://github.com/ariya/phantomjs/issues/13497

**Comment by istr** [comment]
Please re-check with the current master. I am very confident that the currently merged PRs to support phantomjs2 solved this issue.

**Comment by kensoh** [comment]
Thanks @pleasantone for raising this! Am looking through CasperJS open issues but not sure what to make of the output below.. Not getting the error output you shown but getting something else.

```
[info] [phantom] Starting...
[info] [phantom] Running suite: 3 steps
[debug] [phantom] opening url: http://www.google.com/, HTTP GET
[debug] [phantom] Navigation requested: url=http://www.google.com/, type=Other, willNavigate=true, isMainFrame=true
[debug] [phantom] Navigation requested: url=http://www.google.rs/?gws_rd=cr&ei=6uAkWbOuDaiF6ATO_Z6QBw, type=Other, willNavigate=true, isMainFrame=true
[debug] [phantom] url changed to "http://www.google.rs/?gws_rd=cr&ei=6uAkWbOuDaiF6ATO_Z6QBw"
[debug] [phantom] Successfully injected Casper client-side utilities
[debug] [phantom] start page is loaded
[info] [phantom] Step test_throw 3/3 http://www.google.rs/?gws_rd=cr&ei=6uAkWbOuDaiF6ATO_Z6QBw (HTTP 200)
in casper step                                                                  
  /private/tmp/phantomjs:/code/a.js:56 in test_throw
  /private/tmp/phantomjs:/platform/casper.js:1637 in runStep
  /private/tmp/phantomjs:/platform/casper.js:414 in checkStep
[error] [phantom] Error: in casper step
[debug] [phantom] Navigation requested: url=about:blank, type=Other, willNavigate=true, isMainFrame=true
[debug] [phantom] url changed to "about:blank"
```

**Comment by ovidiul** [comment]
I am having the same issue, we are trying to make a test against this site http://www.wheeler.ch/ , but no matter what i do, i get a loop with text

[debug] [phantom] Successfully injected Casper client-side utilities

which finishes after 5 seconds with FAIL "body" never appeared in 5000ms

If i change the address to another site, it works, so i am guessing something from this site javascript might be breaking casperjs or phantomjs, any ideas?

**Comment by kensoh** [comment]
@ovidiul do you have a minimal CasperJS script that can replicate the issue, and whether anyone here is familiar enough with PhantomJS to validate if a vanilla PhantomJS script will have the same problem?

The above linked issue looks closed saying infinite loop happens when phantom.exit() is not called.

**Comment by kiran-redhat** [comment]
I remember having same issue it probably because Casper not seeing your website opened. Have tried catching them with below?

Casper.on('error', function (){});

**Comment by ovidiul** [comment]
@kensoh, here is my test script, i use this command to run it from console

casperjs  --ssl-protocol=tlsv1 --cookies-file=cookies.txt --load-images=false --ignore-ssl-errors=true test --verbose 0900WheelerTest.js

**Comment by kensoh** [comment]
@ovidiul I saw that you already have the on error event mentioned by @kiran-redhat .

When I tried running, I see many lines of `[debug] [phantom] Successfully injected Casper client-side utilities` before throwing below timeout error. The timeout error looks to be expected, not sure why but when I load the website manually on Safari, page was blank and took 1 minute to appear.

```
[warning] [phantom] Casper.waitFor() timeout
FAIL "body" never appeared in 5000ms
#    type: uncaughtError
#    file: 0900WheelerTest.js
#    error: "body" never appeared in 5000ms

#    stack: not provided
PASS Untitled suite in 0900WheelerTest.js (NaN test)
```

Tracing that error message, it comes from injectClientUtils function in casper.js. That function is only called from onLoadFinished event when searching the repo on GitHub. I'm not sure why and how, it looks like that web page somehow keeps triggering the onLoadFinished event.

**Comment by kiran-redhat** [comment]
You mentioned, When tested manually it took about a minute which definitely means you have to put a wait (Casper.waitUntilVisible) let this to wait for Maximum of 2 mins while searching for element.

Note: I said 2 minutes just to make sure time delay is not a problem so we can figure out others. Ideally page shouldn't take more than 8 seconds (you probably have to get it fixed)

**Comment by kensoh** [comment]
Closing this issue for now as there is no replies from @pleasantone and @ovidiul .. But do reopen if anything!
