### ISSUE TITLE
trim() method in casperjs

### ISSUE THREAD

**Issue by ballesdbc** [casperjs/casperjs#1301]
would be possible to use trim() method in casperjs?
Thanks !

**Comment by paazmaya** [comment]
Do you mean `String.prototype.trim` ?

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:**
Looks to be a stale help request. Assuming you've moved on to better and cooler things. Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
