### ISSUE TITLE
Weird CasperJS error

### ISSUE THREAD

**Issue by sawteeth** [casperjs/casperjs#1308]
i am havnig lots of trouble debugging casper errors.  The URL loads fine in browser, the browser auth works fine, but i keep getting an error, ONLY from CasperJS (not browser)... i don't know why it says it is "downloading"... also it says, "Successfully injected Casper client-side utilities", so you'd think the page would have processed/loaded, but no....

any ideas??

>[debug] [phantom] Navigation requested: url=HTTPS://THE_URL.COM, type=LinkClicked, willNavigate=true, isMainFrame=true
[info] [phantom] Step anonymous 10/11: done in 9199ms.
Unable to load resource (#67URL:HTTPS://THE_URL.COM)
Error code: 299. Description: Error downloading HTTPS://THE_URL.COM - server replied: Internal Server Error
[debug] [phantom] url changed to "HTTPS://THE_URL.COM"
[debug] [phantom] Successfully injected Casper client-side utilities
[info] [phantom] Step anonymous 11/11 HTTPS://THE_URL.COM (HTTP 500)
<html><head><title>Error</title></head><body>The function requested is not supported
</body></html>

**Comment by crackjack** [comment]
how are you running the script, you could try running with --ssl-protocol switch like:

```$ casperjs --ssl-protocol=any yourscript.js```

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:**
Looks to be a stale help request. Assuming you've moved on to better and cooler things. Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
