### ISSUE TITLE
casperjs malfunction after page.setContent(content, url);

### ISSUE THREAD

**Issue by rosard1970** [casperjs/casperjs#1311]
Hi,

Following phantomjs docs, I do a page.setContent(content, url) call, and casperjs seems to catch it fine (detects url change call and if I put a capture image call inside a then function, shows that the page is rendered correctly). The problem is that the page has a form, and after setting the content, checking that is rendered correctly, if I fill the form and submit it, nothing happens. Anything is submitted, and the "then" function andther the submit is run almost inmediatly. Also, don't detects any url change or nothing.

Here my code:

casper.start();
casper.then(function() {
	try {
		var p = JSON.parse(fs.read("page.txt"));
		casper.page.setContent(p.content, p.url);
	} catch (e) {
	}
	casper.then(function() {
		continueCheck();
	});
});
function continueCheck() {
	casper.fill('form', { data: data }, true);
	casper.then(function() {
		saveLog("data sent: " + data, true); // this function saves an screenshot.
	});
}
casper.run();

I fix it by adding a wait after the form submit:

	casper.fill('form', { data: data }, true);
	casper.wait(1);
	casper.then(function() {
		saveLog("data sent: " + data, true); // this function saves an screenshot.
	});

So is like it skips something.

Also, just noticed, it resets user agent too, so something is wrong with this.

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:**
Looks to be a stale help request. Assuming you've moved on to better and cooler things. Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
