### ISSUE TITLE
clientutils module injection fails in Chrome

### ISSUE THREAD

**Issue by geekmuse** [casperjs/casperjs#1318]
Using the bookmarklet to inject CasperJS' clientutils module fails due to security issues with browser defaults.

![image](https://cloud.githubusercontent.com/assets/4575201/9944170/88464f86-5d53-11e5-9cea-eca912dd17d2.png)

**Comment by hexid** [comment]
@geekmuse This should have been fixed with 6c976a299caf2f9653851471ebdfdbfbedf6bc3c. Could you try updating your [bookmarklet](http://casperjs.readthedocs.org/en/latest/modules/clientutils.html#index-2)?

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:**
Looks to be a stale help request. Assuming you've moved on to better and cooler things. Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
