### ISSUE TITLE
Casperjs doesn't open some other websites ([DEBUG] Network - Resource request error: 3 ( "Host www.example.de not found" ) URL)

### ISSUE THREAD

**Issue by zeno2015** [casperjs/casperjs#1324]
I'm using Casperjs for downloading Websites. Until now every website I used with casperjs works fine. Now I want to add another website.

    
    casper.start('http://www.example.de', function() {
          var page = this.getHTML();
          this.echo(page);
    });

If I run this code with casperjs on my Desktop (Windows) it works. But If I run this same code on a server (centos) it shows me this:

    <html><head></head><body></body></html>

Why is it empty? I even tried to execute the js-file like this:

casperjs --ignore-ssl-errors=yes --ssl-protocol=any --web-security=no example.js

But it still shows me: `<html><head></head><body></body></html>`

There is only problem with the one Website-Url. It isn't even a https-Website. Simple http and html Website.

How can I fix this problem?

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:**
Looks to be a stale help request. Assuming you've moved on to better and cooler things. Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
