### ISSUE TITLE
wrong signature for onError callback

### ISSUE THREAD

**Issue by nfriedly** [casperjs/casperjs#1328]
(I found a few different problems with the onError callback, so I'm a few tickets to make things easier to track.)

http://docs.casperjs.org/en/latest/modules/casper.html#onerror indicates that the `onError` callback is fired with the signature `onError(String msg, Array backtrace)` but the signature actually appears to be `onError(Object casper, String msg, String engine)` or something along those lines.

``` js
var casper = require('casper').create({
    onError: function(message, backtrace, thirdArg) {
        this.echo("onError - numArgs: " + arguments.length);
        this.echo("message: " + typeof message);
        this.echo(message);
        this.echo("backtace: " + typeof backtrace);
        this.echo(backtrace);
        this.echo("thirdArg: " + typeof thirdArg);
        this.echo(thirdArg);
    },
    waitTimeout: 100
});

casper.start('http://casperjs.org/', function() {
    //...
});

casper.waitForSelector('#id-that-doesnt-exist', function() {
    //...
});

casper.run();
```

outputs:

```
onError - numArgs: 3
message: object
[object Casper], currently at http://casperjs.org/
backtace: string
Wait timeout of 100ms expired, exiting.
thirdArg: string
phantom
```

Also, calling `JSON.stringify()` on the first Object throws another error, but that's not necessarily wrong behavior, not all objects can be stringified.

I'm on CasperJS v1.1.0-beta3.

**Comment by zzanzare** [comment]
I believe this one can be closed as well now.
