### ISSUE TITLE
Some errors bypass the onError callback

### ISSUE THREAD

**Issue by nfriedly** [casperjs/casperjs#1329]
Some errors seem to completely bypass the `onError` callback. For example:

``` js
var casper = require('casper').create({
    onError: function(message, backtrace, thirdArg) {
        this.echo("onError called")
    }
});

casper.start('http://casperjs.org/', function() {
    this.click('#id-that-doesnt-exist');
});

casper.run();
```

Outputs:

```
CasperError: Cannot dispatch mousedown event on nonexistent selector: #id-that-doesnt-exist
  /usr/local/lib/node_modules/casperjs/modules/casper.js:1355 in mouseEvent
  /usr/local/lib/node_modules/casperjs/modules/casper.js:462 in click
  /Users/nfriedly/vzw-bot/test.js:8
  /usr/local/lib/node_modules/casperjs/modules/casper.js:1553 in runStep
  /usr/local/lib/node_modules/casperjs/modules/casper.js:399 in checkStep
```

I'm on CasperJS v1.1.0-beta3.

**Comment by kensoh** [comment]
Hi @nfriedly not sure if you are still having this. I tried replicating your code to click on an invalid element and it triggers the onError called message. It has probably been fixed since this was 1.5 years ago.

**Comment by kensoh** [comment]
@nfriedly was testing with a waitFor and the onError message appears. If executing a this.click directly using your script the same error still happens with v1.1.4.

**Comment by nfriedly** [comment]
hehe, I don't even remember what I was trying to do back then :)

**Comment by kensoh** [comment]
Haha.. Yes it is quite long ago. Hopefully I can figure out more on this, looks like an interesting catch-all for errors. Btw cool website and nice work that you are doing!

**Comment by kensoh** [comment]
@nfriedly I saw possible solution from this thread and looks to be working. Closing the issue for now and link to that thread for reference ;)

https://github.com/casperjs/casperjs/issues/1405
