### ISSUE TITLE
Synchronous XHR causing zero byte file downloads

### ISSUE THREAD

**Issue by laggingreflex** [casperjs/casperjs#1342]
Some downloads produce zero byte files. I debugged and found the root cause to be [synchronous XHR](https://github.com/n1k0/casperjs/blob/master/modules/casper.js#L243-L244). 
I wrote an async alternative and it works on the same file(s), proving indeed it's the sync xhr causing the issues. This is probably what's causing other such (zero byte files) download issues too. #73 #362 #1188

Here's a fix:

```
// this.download(downloadUrl, target); 
// ^ if this doesn't work. 
//   Try this:

this.thenEvaluate(function(url) {
    xhr = new XMLHttpRequest();
    xhr.addEventListener('load', function onTransferComplete() {
        // Set a flag when load completes, we'll keep checking it
        transferComplete = true;
    });
    xhr.open('GET', url, true); /* < ASYNC */
    xhr.responseType = 'arraybuffer';
    xhr.send(null);
}, downloadUrl);
this.waitFor(function check() {
    return this.evaluate(function() {
        return transferComplete;
    });
}, function then() {
    console.log('transferComplete!');
    var base64encoded = this.evaluate(function() {
        return btoa([].reduce.call(new Uint8Array(xhr.response), function(p, c) {
            return p + String.fromCharCode(c);
        }, ''));
    });
    /*clientutils = require('clientutils') */
    /*fs = require('fs') */
    var cu = clientutils.create(); 
    fs.write(target, cu.decode(base64encoded), 'wb');
});
```

**Comment by jefleponot** [comment]
thanks @laggingreflex , very good job. Does your code work with multiple parallel downloads ?

Hi #mickaelandrieu, @paazmaya 
Could we have a casperjs "download" method with parameters to force asynchronous mode ?

**Comment by istr** [comment]
When looking into the affected code, it seems that only ```clientutils.getBase64```, ```clientutils.getBinary``` ever use ```clientutils.sendAJAX``` which is causing the problem (using sync XHR).

To retain BC for 1.1 I would propose to:
- mark synchronous versions of ```clientutils.getBase64``` and ```clientutils.getBinary``` obsolete and issue a warning referencing this bug when called in sync mode
- rework ```clientutils.sendAJAX``` to support async requests / callback
- enhance ```clientutils.getBase64``` and ```clientutils.getBinary``` to be able to use a callback and work asynchronously in this case
- add casperjs.waitForAJAX to support waiting for the outcome of an asynchronous AJAX call
- add casperjs.waitForDownload that is based on casperjs.waitForAJAX and implements what @laggingreflex  outlined
- drop the problematic sync call versions of ```clientutils.getBase64``` and ```clientutils.getBinary``` and ```clientutils.getBase64``` as of 2.0

**Comment by jefleponot** [comment]
@istr and @laggingreflex , please could this compatibility code work for you ?

Thanks by advance
jef

**Comment by istr** [comment]
This is "hard to fix" because it cannot really be addressed without breaking BC for 1.1.

The question is if there is any point, whatsoever, to keep "BC" for a function that never actually worked reliably / as expected.

So maybe just clean up [jefleponot's PR](https://github.com/n1k0/casperjs/pull/1373) (I dislike [the boolean traps](http://ariya.ofilabs.com/2011/08/hall-of-api-shame-boolean-trap.html) introduced there as well as the kludgy "check-throw-error-on-wrong-flag-version-combination" in the code presented in that PR) and accept it as a bugfix thereafter?

@jefleponot @BIGjuevos @mickaelandrieu ?

**Comment by entrptaher** [comment]
I don't know if this is related or not.

Why ask casperjs to do everything? In future versions, will casperjs try to go to moon by itself?

If I want to download a file from github/sourceforge as a test, there are some random redirects and waiting, in that case cURL works just fine while casperjs doesn't. If casperjs could let curl handle the downloading issue. Corrupt file/ big file/ small file/ 0 byte file, there will be no more issue like this.

https://www.npmjs.com/package/multicurl

**Comment by istr** [comment]
@entrptaher good point -- of course DRY is good. This will definitely be a consideration for the 2.0 series.

But in this case we have to consider how to fix a problem within the current API set without breaking stuff for users out there "in the wild" probably using the non-broken parts in question.

**Comment by entrptaher** [comment]
They are using this.download(downloadUrl, target);
And I was talking about using curl inside that .download() function.
So whenever user triggers download(url,target) , it would use curl instead. So, their issue will be fixed and it'd be a great upgrade.

IDK, somehow all of my solutions are dangerous and risky.

**Comment by istr** [comment]
> And I was talking about using curl inside that .download() function.

Aha, ok... Sorry, missed that point. Thanks for clarification -- seems to be a viable idea. @mickaelandrieu, @BIGjuevos 

> IDK, somehow all of my solutions are dangerous and risky.

*g* All software is dangerous and risky, after all... ;-)

Let's see if we could land your proposal. A PR (for practical, in-depth discussion of the solution) would be highly welcome.

**Comment by mickaelandrieu** [comment]
> And I was talking about using curl inside that .download() function.

Hmm I don't want to depend on curl, I like the idea that casper is and stay a wrapper of phantom, with the pros (and cons) of phantom.
More, I'm not sure curl is installed by default on Windows, and for now we need a hand to find a active Windows contributor/user.

It's - of course - only my opinion, I wont be opposite to a good pull request, well tested and with working results :)

**Comment by istr** [comment]
> More, I'm not sure curl is installed by default on Windows

Good point. I like the idea of a "self-contained" package, too -- no (npm) hell of dependencies... ;-)

**Comment by entrptaher** [comment]
I too like self-contained packages.
But borrowing ideas from other npm packages won't hurt.
If Curl doesn't work, how about this?

https://www.npmjs.com/package/fetch

**Comment by istr** [comment]
> But borrowing ideas from other npm packages won't hurt.

Of course. A standalone PR based on https://github.com/andris9/fetch/blob/master/lib/fetch.js could just do the job. I am unsure, however, how easy it is to resolve the npm dependencies / ```requires``` there.

I think the point @mickaelandrieu made was that we currently have no ```dependencies``` at all in https://github.com/n1k0/casperjs/blob/master/package.json and he wants to stick with it.

**Comment by jefleponot** [comment]
Hi @entrptaher, @Istr, @mickaelandrieu 

That is a strange discussion. CasperJs is just an overlay to use a real web browser. It allows to do the same things as other web browsers like firefox, chrome, opera ...
So you can surf, download, watch movies ... etc ( except specific features : FTP, SSH ...)

Do you use your browser to download a data or Curl ?

I and @istr design a workaround that works in asynchronous mode, but we could search why synchronous don't work.

In my opinion, more the library simplifies life user , better it is.

**Comment by entrptaher** [comment]
Do we use or browser to download? Yes we do.
Do we use curl to download a file? Yes we do that too.

Anyway, this is the last thing I found, and It has no extra module dependencies. Worked for github downloads. https://github.com/SamDecrock/node-httpreq 
I hope the hard-to-fix problem will be fixed somehow :) .

**Comment by istr** [comment]
> That is a strange discussion. CasperJs is just an overlay to use a real web browser.

...a specialized headless browser.

Maybe we're trying to fix something here (in the wrapper), that could not reliably be fixed here, but in the underlying engine only. If you have a look at [the issues of PhantomJS](https://github.com/ariya/phantomjs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+xhr) you will find that there are (and have been) multiple problems with sync XHR all the time, e.g. https://github.com/ariya/phantomjs/issues/11284, https://github.com/ariya/phantomjs/issues/10498, https://github.com/ariya/phantomjs/issues/13891, https://github.com/ariya/phantomjs/issues/13908, https://github.com/ariya/phantomjs/issues/10157.

The oldest entry dates back to 2011 and still has an open 2.0 target.

So maybe we should decide just to "won't fix" the sync issue, mark that function problematic / dysfunctional and provide the async alternative @jefleponot proposed in his PR https://github.com/n1k0/casperjs/pull/1373.

Thoughts?

**Comment by istr** [comment]
Votes for "won't fix" / PhantomJS problem here please.

**Comment by istr** [comment]
Votes to rework PR #1373 to be async only and mark the current function broken here please.

**Comment by jefleponot** [comment]
I'm not a collaborator.. can I vote ?

@istr : I use CasperJS in chrome and recently in firefox extensions.. it works very well

**Comment by istr** [comment]
> I'm not a collaborator.. can I vote ?

Yes, of course. Just use the +1 reaction on the "voting" comment.

**Comment by BIGjuevos** [comment]
I'm on both sides of the fence.

1. It is not our responsibility to correct the problems and errors of our underlying engines.
 - This should drive people to improve phantom.  Might even be worthwhile for us to inform them of the pain we are seeing as well to get it moved up their priority list.
 - Supporting this use case could improve CasperJS adoption.
 - We provide support for alternative engines, why can't those be used.
2. It is in the best interest of the community and usage of the software to provide the functionality that people are requesting.
 - Lot's of precedents to do this.  Polyfills in browsers.  Phantom/Slimer are in the end another browser.
 - This is additional code for us that we have to maintain and deal with bugs.
 - Using a 3rd party lib introduces a dependency, that could turn out to be just as troublesome as casper.

When situations like this occur, I tend to err on the side of caution.  I'm voting won't fix (vote applied above) with the caveat of adding some notes to the documentation under known issues.

**Comment by jefleponot** [comment]
won't fix :+1: 
Propose a temporary alternative (asynchronous) :+1:

**Comment by jcarvajalp** [comment]
Hi, I tried to implement this code (just for a concept test) and appears me that "FAIL TypeError: null is not an object (evaluating 'str.length')" in the line fs.write, somebody happened  the same?

thanks

**Comment by enmanuelduran** [comment]
Is there a solution to this problem? I'm trying to download big files 20mb+ from casperjs ad it throws:

[error] [remote] getBinary(): Error while fetching http://usmoffers.com/affiliates/s.ashx?c=1977: [Exception... "Failure" nsresult: "0x80004005 (NS_ERROR_FAILURE)" location: "JS frame :: /usr/local/lib/node_modules/casperjs/modules/clientutils.js :: sendAJAX :: line 894" data: no]

just downloading an empty file, if there is not a solution can you recommend me something?

**Comment by mickaelandrieu** [comment]
@enmanuelduran give a try to slimerJS engine :)

**Comment by enmanuelduran** [comment]
@mickaelandrieu yes, in fact I started using slimerJs engine since the beginning but doesn't work, here's my case explained: http://stackoverflow.com/questions/40342285/unable-to-download-zip-file-from-url-with-casperjs

**Comment by kensoh** [comment]
Bumping this up and following this exciting thread :) CasperJS has made it much easier to download files, however downloading issues seem to still be a recurring topic.

**Comment by kensoh** [comment]
Want to tag the new PR https://github.com/casperjs/casperjs/pull/1835 that can be helpful in situations such as this issue. There are new events to detect download failure and could help troubleshooting / debugging.

**Comment by kensoh** [comment]
Just thinking of an alternative, since CasperJS can call shell, could we pass the URL to curl through waitForExec() and let it handle the download?

**Comment by kensoh** [comment]
Archiving issue using **ARCHIVE** label as CasperJS, like PhantomJS, is not actively maintained for now.
