### ISSUE TITLE
why casperjs timeout not working

### ISSUE THREAD

**Issue by Malenconiaprincep** [casperjs/casperjs#1343]
I will go and catch some page elements, but sometimes requested page no response, then I added a timeout, but not working

``` javascript
var fs = require('fs');
var settings = JSON.parse(fs.read('common.json'));
var casper = require('casper').create({
        clientScripts: [
                'include/jquery.js', // These two scripts will be injected in remote
        ],
        pageSettings: {
                loadImages: false, // The WebPage instance used by Casper will
                loadPlugins: false // use these settings
        },
        logLevel: "info", // Only "info" level messages will be logged
        verbose: true // log messages will be printed out to the console
});

casper.options.timeout = 5000;
// casper.options.stepTimeout = 5000;
casper.options.onTimeout =function(){
  this.echo('timeout','INFO');
}
// casper.options.onStepTimeout =function(){
// }


casper.userAgent('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.124 Safari/537.36');
var content = {};

casper.start(settings.url, function() {
  this.echo('open web','INFO');
});

casper.then(function(){
  var data = {};
  for(var key in settings.config){
    if (this.exists(settings.config[key])) {
      data[key] = this.getHTML(settings.config[key]);
    }else{
      data[key] = '';
    }
  }
  this.echo('/-----json-----' + JSON.stringify(data) + '-----json end-----/');
})

casper.run();

```

Hope someone help me to answer  ^_^

**Comment by amerikan** [comment]
Have you tried using `casper.options.waitTimeout = 5000;`

**Comment by desmond276** [comment]
In addition to the waitTimout above, would it be easier to handle page loads by checking http status of request?

**Comment by kensoh** [comment]
Thanks @Malenconiaprincep for raising this :) I'm a CasperJS user for couple of years. Browsing through open issues now to see if anything I can help with.

It looks like if you explicitly wait for some moments before starting to work on the webpage it should work. Or waiting to check for a selector that normally is the last to load. The issue may be the page has not been fully rendered for scraping / interaction. Nevertheless, a lot has changed since 2015, so maybe your script and data will work right off the shelf now.

**Comment by kensoh** [comment]
Thanks @amerikan and @desmond276 for sharing your inputs! @Malenconiaprincep closing this issue for now. But do reopen if you are still having the same experience with latest CasperJS v1.1.4 and PhantomJS v2.1.1. Thanks for raising it!
