### ISSUE TITLE
Cannot abort request in Mac OSX

### ISSUE THREAD

**Issue by ga0** [casperjs/casperjs#1345]
I wrote a simple test like this:

```
//test.js
var casper = require('casper').create({
    verbose: true,
    logLevel: 'debug',
    pageSettings: {
        loadImages: false
    }
});
casper.on('resource.requested', function(req, networkRequest) {
    this.echo("> " + req.url);
    networkRequest.abort();
});
casper.on('resource.received', function(resp) {
    this.echo("< " + JSON.stringify(resp));
});

var url = casper.cli.get('url');
casper.start(url);
casper.run();
```

and run it:

```
casperjs test.js --url=https://github.com --ssl-protocol=any
```

**The 'networkRequest.abort()' doesn't work in macosx, the request has been sent as normal.**

casper version: 1.1.0-beta3
phantomjs version: 1.9.7

This example runs perfectly in my windows pc and centos7 server.

**Comment by Acostan** [comment]
Same issue here: running phantomjs: 2.0.0 casper 1.1.0-beta3

**Comment by istr** [comment]
To address this we would need two things:
- migrate the tests that check ```request.abort``` from ```tests/suites/casper/request.coffee``` to plain JS to be future proof and work with PhantomJS 2.0.0 and later
- add OS/X tests to our builds https://docs.travis-ci.com/user/osx-ci-environment/

It would help a lot if you could do any of these in a branch and create a PR for that.

As a start, could you please check if the current test suite passes the coffee / abort tests locally with your setup (phantom up to 1.9.8 only)? (```make test``` in a checkout of current master)

**Comment by istr** [comment]
The test case you presented fails for me, too (and honestly I don't believe it could work correctly on the other platforms you mentioned). This is because you used the wrong event names to hook in.

If you have a look at https://github.com/n1k0/casperjs/blob/master/tests/suites/casper/request.js#L14 you will see that you need to hook into ```page.resource.requested``` instead of ```resource.requested```.

The following test works for  me (Linux / PhantomJS 1.9.7 and 2.0.0).

```js
//test.js
var casper = require('casper').create({
    verbose: true,
    logLevel: 'debug',
    pageSettings: {
        loadImages: false
    }
});
casper.on('page.resource.requested', function(req, networkRequest) {
    this.echo("> " + req.url);
    networkRequest.abort();
});
casper.on('page.resource.received', function(resp) {
    this.echo("< " + JSON.stringify(resp));
});

var url = casper.cli.get('url');
casper.start(url);
casper.run();
```

Please check if this works for you. Closing as invalid. Feel free to re-open if my corrected test fails for you (on OS/X), too.

**Comment by istr** [comment]
Followup: Your specific case is even [in the documentation as an example](http://docs.casperjs.org/en/latest/events-filters.html#events).

Note, however, that the ```resource.received``` is emitted differently and the handler takes on a different argument list.

**Comment by mepard** [comment]
This is strange. I've been using 'resource.requested' and aborting resource loads and it seems to work on both Mac OS X and Windows 10. It's used to blacklist some urls (ads, trackers and the like) and to work around a memory leak when load images is false.

Looking at https://github.com/n1k0/casperjs/blob/master/modules/casper.js#L2607, it appears both events are emitted for all resources, but 'page.resource.requested' is only emitted for the page url. I could be misunderstanding something, of course.

**Comment by istr** [comment]
@mepard Ok, seems that I was wrong with my assumption above -- strange, though, that the documented example works for me while the other version does not.

This needs closer investigation, re-opening.

**Comment by kensoh** [comment]
@ga0 it seems that along the way this seems to have been fixed (without the error message you mentioned). Running your script now gives the expected output. I'm running on v1.1.4 and v2.1.1 on macOS Sierra. Thanks for raising this! Closing the issue for now but do ping if anything :)

```
[info] [phantom] Starting...
[info] [phantom] Running suite: 2 steps
[debug] [phantom] opening url: https://github.com/, HTTP GET
[debug] [phantom] Navigation requested: url=https://github.com/, type=Other, willNavigate=true, isMainFrame=true
> https://github.com/
< {"contentType":null,"headers":[],"id":1,"redirectURL":null,"stage":"end","status":null,"statusText":null,"time":"2017-05-24T01:15:14.815Z","url":""}
[warning] [phantom] Loading resource failed with status=fail: https://github.com/
[debug] [phantom] Successfully injected Casper client-side utilities
[debug] [phantom] start page is loaded
[info] [phantom] Done 2 steps in 110ms
[debug] [phantom] Navigation requested: url=about:blank, type=Other, willNavigate=true, isMainFrame=true
[debug] [phantom] url changed to "about:blank"
```
