### ISSUE TITLE
suggestion: casper.getHTMLs(String selector [, Boolean outer])

### ISSUE THREAD

**Issue by rdpoor** [casperjs/casperjs#1347]
Along the lines of casper.getElementsAttribute(), it would be nice if there was a way to pick up multiple matches of HTML.  As described in http://stackoverflow.com/questions/33770798/extracting-table-elements-with-casperjs, imagine you have a table:

```
<html>
  <head></head>
  <body>
    <table>
      <tbody>
        <tr><td name="a">1</td><td>hop</td></tr>
        <tr><td name="b">2</td><td>skip</td></tr>
        <tr><td name="c">3</td><td>jump</td></tr>
      </tbody>
    </table>
  </body>
</html>
```

and you wanted to pick up ['hop', 'skip', 'jump'].  It would be useful if one could call:

```
casper.getHTMLs('table tr td:nth-child(2)')
```

to extract those.  Or if you wanted to get the text associated with all links on a page, you could do:

```
casper.getHTMLs('a[href]')
```

... rather than dropping down into eval() and such.  The implementation is straightforward.

Any interest?

**Comment by kensoh** [comment]
Archiving issue using **ARCHIVE** label as CasperJS, like PhantomJS, is not actively maintained for now.
