### ISSUE TITLE
Moving to CasperJS organisation, looking for new ownership

### ISSUE THREAD

**Issue by paazmaya** [casperjs/casperjs#1350]
I would like to bring up again (https://github.com/n1k0/casperjs/issues/1177#issuecomment-77518406) the possibility of moving the project under an organisation, which might help in this project not being unmaintained and abandoned.

This would require @n1k0 to press some buttons...

Once the change has been made, I would like to promote those people who have made pull requests that have had positive affect on the project, to have direct commit access.

**Comment by n1k0** [comment]
I agree, I have no time to properly maintain this project anymore, and moving it to an org with a new owner sounds good. Now the question is, who would be that new owner. We need someone actively using the project, knowing & understanding it deeply, and willing to dedicate the necessary amount of time to  maintain it properly.

I'm officially asking, who's interested?

**Comment by paazmaya** [comment]
The team mentioned in `README` has the following names:

    Nicolas Perriault (@n1k0)
    Nick Currier (@hexid)
    Laurent Jouanneau (@laurentj)
    Mickaël Andrieu (@mickaelandrieu)
    Matt DuVall (@mduvall)

Of which @hexid has recently made good work in the PhantomJS 2 related PRs.

Any other candidates to bring up?

**Comment by n1k0** [comment]
@paazmaya you should probably include yourself in the list, I'm realizing.

**Comment by istr** [comment]
@paazmaya I would really appreciate that. There seems to be quite a lot of people using phantomjs / casperjs stacks for testing their front-ends. Even though there are some alternatives, none of them are as battle proven and/or come as well-documented as casperjs. And lots of people urgently wait to see some progress on 2.0 (including me, that's why I [started to work on finishing the last steps needed](https://github.com/istr/casperjs/tree/feature/phantomjs2) @hexid left open).

**Comment by paazmaya** [comment]
I am afraid my biggest contribution to CasperJS is this https://www.instagram.com/p/yKZf-Fwf7R/
...and maybe taking ESLint in use, for which configuration is now out of date.

Anyhow I think that at the moment the focus should be getting PhantomJS 2 supported version out, even if it is without the support for SlimerJS. Let's call it `alpha` release, `2.0.0-alpha1` and have it available through the usual channels, like `npm`.
Once SlimerJS is not failing, then have finally the `2.0.0` out and start focusing on getting new features in and existing bugs fixed.
It seems that most of the issues, which create a lot of noise, are about the mismatching versions being installed and the lack of PhantomJS 2 support.

@n1k0 have you checked what is required for turning this repository into a organisation?
If I understand correctly, first https://help.github.com/articles/creating-a-new-organization-from-scratch/, then transfer this repository to the organisation and start putting people in to the organisation.

While at it, the website `casperjs.org` could also be moved (if not yet) to use GitHub Pages and have that repository also under the `casperjs` organisation.
Financing the web site domain name and DNS costs might be covered by collecting donations, etc..

**Comment by istr** [comment]
> Financing the web site domain name and DNS costs might be covered by collecting donations, etc..

I would willingly donate 5 to 10 yrs up-front domain name costs to an organisation.

**Comment by istr** [comment]
Maybe @jamescryer would be a good candidate if he has the time to do it. His organization [Huddle](https://github.com/Huddle/) has got a tool stack in production that heavily relies on phantomjs (the same tool stack I am using in some of my current projects).

**Comment by paazmaya** [comment]
Ok, include also @istr based on the recent very positive activity.

@n1k0 could we start moving repositories over to a CasperJS organisation?
The access rights and privileges should be able to keep at the same as currently, so the only change would initially be URL change.

**Comment by n1k0** [comment]
> Ok, include also @istr based on the recent very positive activity.

He's already been promoted as a repo collaborator ;)

> @n1k0 could we start moving repositories over to a CasperJS organisation?

I'd rather wait to have a 1.1 stable release ready before doing so, so people will upgrade everything at once. Also, there's already a casperjs repository in the casperjs org; I suspect once we move official development there, people will have to update their git url accordingly, as I can't see anything to automate the process. Thoughts?

We'll aslo have to start documenting the transition process, to ensure we don't miss anything (updating site, docs, package.json, etc). @paazmaya, @istr, @hexid anybody interested in starting this?

**Comment by istr** [comment]
> I'd rather wait to have a 1.1 stable release ready before doing so

I share that point of view. Let's try to get out a 1.1 stable within the current setup and prepare project transition / 2.0 planning in parallel. My primary focus now is 1.1 stable, so it would be great if someone else could cater for planning the transition process. @hexid, @paazmaya ? I will happily continue to browse through the open issues to classify, qualify, and reduce them in the meantime.

**Comment by brettjonesdev** [comment]
We use Casper pretty extensively at [Help Scout](http://helpscout.com) for testing our front-end, and like @istr would really hate to see it fall by the wayside.  I would love to see Phantom 2 support so we can test websockets, but I'm not familiar enough (or at all, honestly) with the underlying code to feel like I'd be much help developing it right now.

If you need extra eyes or assistance, I'd be willing to take a whack at items as needed, with the caveat that I have no background knowledge on the project at the moment.

**Comment by istr** [comment]
@brettjonesdev Within the current master Phantom 2 support is available for testing.
You could help trying out the current master branch and see if you can find any bugs.

We (at least me) strive to get out 1.1-beta4 (with Phantom 2 support) as soon as possible (hopefully this month), to foster broader testing.

**Comment by brettjonesdev** [comment]
Excellent I'll give that a shot, thanks!

**Comment by xuxingbgi** [comment]
We are a starup and using casperjs for our functional testing.  Look forward to having 1.1-beta4(with Phantom 2 support)!!!

**Comment by BIGjuevos** [comment]
@n1k0 We use CasperJS quite extensively at LinkedIn.  When you have a chance, let's find an opportunity to discuss .  Let me know what the best way to connect with you is.

**Comment by n1k0** [comment]
FWIW I'd like any discussion about new project ownership/reorg to be held in the open, so the team as a whole as well as the community knows about them. That means either filing an issue describing the plan/offer, or at least by starting a thread on the [casperjs mailing list](https://groups.google.com/forum/#!forum/casperjs).

Thanks for your understanding :)

**Comment by mickaelandrieu** [comment]
@n1k0 I'm against give the ownership to any company. But we accept with pleasure all the help anyone can offer /c @istr

**Comment by BIGjuevos** [comment]
@n1k0 @mickaelandrieu My goal was/is to take the temperature of the CasperJS Community.  I did not mean to make it seem like a back door deal (my apologies if it came across that way).  There are some discussions within the teams that are heading CasperJS initiatives within LinkedIn about taking a more active role with the open source side of casper.

So, I'd love to hear about how current collaborators and contributors feel about us taking a more active role in the guidance of the project (before we even consider putting forth a plan).  How does everyone feel about it?

**Comment by n1k0** [comment]
We have currently no governance model at all (I think?), which makes hard to figure out how to address this kind of request to begin with. While the repo is still hosted under my name, I'm not actively maintaining it as I don't have use cases for casper anymore since I moved to other fronts.

On the other hand, any help trying to find a new model to make this project moving forward is always greatly appreciated, and I'm happy you're offering to help here. While I'd be terribly uncomfortable to transfer full {owner,leader}ship to a single company (read: it's not gonna happen anyway), I'm all ears to alternative suggestions.

The very first area I can see critical needs to be addressed is issue triaging, so we could identify what's missing to finally tag a long awaited stable version. TBH I have no clue what the state of this is, so we should probably bring @istr @paazmaya @hexid to this discussion and ask them what kind of support they need the most atm.

**Comment by mickaelandrieu** [comment]
@n1k0 thank you to make the things clear :)
@BIGjuevos for now, our only objective is to release a stable 1.1 with some last issues and pull request to review. I'm not against new maintainers/reviewers/active contributors: I love contributors <3

If you want some guidance, I guess it's because you want CasperJS to evolve, providing some new features. I'd would like to know what kind of features/needs do you have, to get a good experience with ?

**Comment by BIGjuevos** [comment]
@mickaelandrieu I completely understand.  I saw the project was looking for new owners, we pride ourselves on being good shepards of open source project, and I figured at the minimum I'd bring up the topic.

Nonetheless, the biggest problems we are encountering deal with test stability when running on the newer versions of phantomjs.  Some projects have 1000s of tests executing.

What is the critical path to version 1.1, and where do you need the most help?

**Comment by jefleponot** [comment]
Hi @BIGjuevos , @n1k0 , @istr, @mickaelandrieu ,

On my side, we have also trouble of stability of phantomJS 2.1.1. 
Crashes occur on JavaScript injection (casper.evaluate method) (3%-5% of tests)

phantomJS 1.9.7 is more stable except for frames navigation (1% of tests).
(but we have many applications that will not work any more with this old version.)

@BIGjuevos , do you have solution to improve phantomJS 2.1.1 stability with casperJS ?

Jef, very interested

**Comment by mickaelandrieu** [comment]
@BIGjuevos we have a kind of roadmap to finalize 1.1 https://github.com/n1k0/casperjs/milestones/1.1
From my side I do care about stability of testing, if we can improve CasperJS to be more stable, let's do it!

As @n1k0 says, the best help we can have for now is review of pull requests, tagging issues and close all irrelevant (@istr have done a great job).

If you have some patchs that you want to suggest to improve CasperJS, it can be discussed too: I think this is a (very) open project, @jefleponot can tell ^^

Mickaël

**Comment by BIGjuevos** [comment]
@mickaelandrieu @istr OK, I like the goal of getting 1.1 out first.  I'll pitch in as much as I can.  Then I feel like the next biggest problem facing casper would be stability on top of phantomjs (now that it is semi-alive again) @n1k0 @istr .

Any objections to me reading through the issue list (for both 1.1 and non 1.1) and pinging @mickaelandrieu (or related) to get some action on the issues (close, add label, etc..)?  It looks like some PRs died off and some other people never completed changes.  I'll try to pick up what I can.  Probably re-submit as my own PR.

**Comment by n1k0** [comment]
@BIGjuevos Sounds good, and thank you. Feel free to ping @istr as well as he did a great job at triaging lately and is probably the team member who has the most accurate knowledge of the current state of things.

**Comment by istr** [comment]
@BIGjuevos 
> It looks like some PRs died off and some other people never completed changes. I'll try to pick up what I can. Probably re-submit as my own PR.

That would be a great achievement. It could probably be a good idea to address those marked "bug" first. A cleanup / re-base / re-submission of stale PRs would be really nice. :+1:

**Comment by n1k0** [comment]
@BIGjuevos you're now part of the team with push access, cheers and thanks for your work on the project :)

**Comment by BIGjuevos** [comment]
@n1k0 Thanks!  I really appreciate you doing so.  I'll try my best to live up to the wonderful example that @istr and @mickaelandrieu have set.

Now, let's get that version 1.1 released!

**Comment by mlalpho** [comment]
CasperJS for-the-win! Keep up the great work gents :beers: 

I'm no where near contributing-strength on the core code, but I'm becoming an avid user. Loving 1.1.1 -- Great docs!

**Comment by istr** [comment]
@mlalpho Thanks for the compliments. Still struggling with the staffing level, so any contribution is welcome (including those that do not touch any line of code).
