### ISSUE TITLE
SlimerJS CLI tests

### ISSUE THREAD

**Issue by hexid** [casperjs/casperjs#1364]
Currently, the SlimerJS cli tests are being skipped due to a few issues
- [ ] laurentj/slimerjs#379
- [ ] laurentj/slimerjs#403

This issue is here to document progress so that we can reenable these tests at some point.

**Comment by istr** [comment]
Yes. I propose we address this as part of 1.1.

**Comment by istr** [comment]
@mickaelandrieu @BIGjuevos @hexid any objection to postpone this to 2.0?

**Comment by mickaelandrieu** [comment]
Hmm, why not. I'm pretty sure someone will fix theses issues into SlimerJS project and we just have to enable again the related tests... it's a non blocking issue to our stable release :)

**Comment by kensoh** [comment]
Closing this issue for now, as the issues are still open at SlimerJS for almost 2 years.. And there hasn't been replies to issues for past 3 months, not sure the status of SlimerJS project.
