### ISSUE TITLE
Step never completes (it gets stuck)

### ISSUE THREAD

**Issue by amerikan** [casperjs/casperjs#1374]
I have had a casperjs test for a while and then all of a sudden it **stopped working**, the tests never complete. It was working on both my local machine Mac OSX and also on my VPS (Ubuntu), but same bad behavior happens on both.

After some debugging, it seems there's a `<script>` tag which I load from a cdn that is causing a step to hang and never complete.

``` html
<script src="https://js.pusher.com/3.0/pusher.min.js"></script>
 <script type="text/javascript">
    var pusher = new Pusher('my_real_key_is_here', { encrypted: true}); // This line causes entire casperjs to hang
</script>
```

When I remove the above portion of the code, the tests work as usual. When it's present a step gets stuck and never completes, which doesn't make much sense right now. **What in the above code can possibly be hanging a step in casperjs?**

I added `casper.options.stepTimeout = 10000;`, which does prevent it from hanging, but the script will not pass my tests.

Is there something that causes a **step** to never complete?

**Comment by amerikan** [comment]
Seems like pusherjs does some xhr streaming and xhr polling which seem to be causing the problem. Do any of you guys know what exactly cause it for it to get stuck and never to complete or timeout?

**Comment by kensoh** [comment]
Hi @amerikan is this still happening for you? I'm a CasperJS user for 2 years, and understand that this probably is the underlying browser behavior from PhantomJS, and might be already fixed over time.

**Comment by kensoh** [comment]
Hi @amerikan closing this issue for now, but do reopen if you are still having the same experience with latest CasperJS v1.1.4 and PhantomJS v2.1.1. Thanks for raising it!
