### ISSUE TITLE
create casper#fetchTexts(selector) and clientutils#fetchTexts(selector)

### ISSUE THREAD

**Issue by rdpoor** [casperjs/casperjs#1375]
I'd like to see a casper#fetchTexts(selector) method, which behaves like casper#fetchText(selector), but returns an array of matched texts rather than catenated.  I've created a fork in preparation for a pull request, but (as per https://github.com/n1k0/casperjs/blob/master/CONTRIBUTING.md), I'm floating the idea here first for comment and discussion.
## motivation

Given a bit of html as follows:

```
<table>
  <tbody>
    <tr><td><a href="x">red</a></td></tr>
    <tr><td><a href="y">green</a></td></tr>
    <tr><td><a href="z">blue</a></td></tr>
  </tbody>
</table>
```

with casper, it's easy to extract matching element attributes as an array like this:

```
casper.getElementsAttributes('table tbody tr td a', 'href');
=>
['x', 'y', 'z']
```

but there's no corresponding method to extract innerHTML text that matches a selector.  I am proposing:

```
casper.getTexts('table tbody td td a');
=>
['red', 'green', 'blue']
```
## design questions
- Is `getTexts()` the right name?  I chose it to parallel `getText()` in the way `getElementAttribute()` parallels `getElementsAttribute()`.  It's not a perfect parallel because `getElementAttribute()` returns the _first_ matching attribute, `getText()` returns _all_ matching text concatenated together.  Despite that, it feels like the right name.
- Should getTexts() support an optional `Boolean outer` argument in the style of getHTML()?  I'd argue for no, simply because the existing getText() doesn't support it.  (Although one could argue that maybe it should.)
- Is there any reason NOT to implement the corresponding `getTexts()` method in the `clientutils` module?
- If `getTexts()` passes muster, it would seem sensible to re-implement `getText()` as `getTexts().join('')`.  Are there any arguments against doing so?
## proposed test suite

To make it concrete, here's an untested sketch of casperjs/tests/suites/casper/fetchtexts.js:

```
/*eslint strict:0*/
casper.test.begin('fetchTexts() basic tests', 1, function(test) {
    casper.start('tests/site/index.html', function() {
        test.assertEquals(this.fetchTexts('ul li'), ['one', 'two', 'three'],
            'Casper.fetchTexts() can retrieve text contents');
    }).run(function() {
        test.done();
    });
});

casper.test.begin('fetchTexts() basic tests', 1, function(test) {
    casper.start('tests/site/index.html', function() {
        test.assertEquals(this.fetchTexts('input[name="dummy_name"]'), ['dummy_value'],
            'Casper.fetchTexts() can retrieve text contents from input elements');
    }).run(function() {
        test.done();
    });
});

casper.test.begin('fetchTexts() handles HTML entities', 1, function(test) {
    casper.start().then(function() {
        this.setContent('<html><body>Voil&agrave;</body></html>');
        test.assertEquals(this.fetchTexts('body'), ['Voilà'],
            'Casper.fetchTexts() fetches decoded text');
    });
    casper.run(function() {
        test.done();
    });
});

casper.test.begin('fetchTexts() handles empty elements', 1, function(test) {
    casper.start().then(function() {
        this.setContent('<html><body></body></html>');
        test.assertEquals(this.fetchTexts('body'), [''],
            'Casper.fetchTexts() fetches empty string');
    });
    casper.run(function() {
        test.done();
    });
});

casper.test.begin('fetchTexts() handles non-matching elements', 1, function(test) {
    casper.start().then(function() {
        this.setContent('<html><body></body></html>');
        test.assertEquals(this.fetchTexts('table'), [],
            'Casper.fetchTexts() returns empty array');
    });
    casper.run(function() {
        test.done();
    });
});
```

**Comment by kensoh** [comment]
Bumping up in case it's still relevant for you. Normally for situations where I expect multiple matches I check explicitly if something exists then read it.

**Comment by kensoh** [comment]
Bumping up and copying @jefleponot thanks @rdpoor your suggestion looks neat!

**Comment by kensoh** [comment]
Archiving issue using **ARCHIVE** label as CasperJS, like PhantomJS, is not actively maintained for now.
