### ISSUE TITLE
Bug : bootstrap patchedRequire with phantomjs-2.0.0-X

### ISSUE THREAD

**Issue by jefleponot** [casperjs/casperjs#1378]
Hi everybody,

look at this strange bug with phantomJS last version : 

**jef@jef-HP-Elite-7000-Microtower-PC:**~/dev/casperjs/samples$ cat require.js
    /*eslint strict:0*/
    /*global CasperError, console, phantom, require*/

```
require("each.js");
```

**jef@jef-HP-Elite-7000-Microtower-PC:**~/dev/casperjs/samples$ ../bin/casperjs require.js 
    Error: Cannot find module 'casper'

```
phantomjs://bootstrap.js:289
phantomjs://bootstrap.js:254 in require
/home/jef/dev/casperjs/samples/each.js:4
/home/jef/dev/casperjs/samples/each.js:21
```

^C
**jef@jef-HP-Elite-7000-Microtower-PC:**~/dev/casperjs/samples$ ../bin/casperjs each.js 
     Google - http://google.com/
     Google - http://yahoo.com/
     Bing - http://bing.com/
### The surcharging require method doesn't work recursively any more.

Please, Is someone could do this test  ?

**Comment by kensoh** [comment]
Closing the issue for now as that was an older PhantomJS version, and there hasn't been new replies to this issue for quite long.
