### ISSUE TITLE
When is then() reliable?

### ISSUE THREAD

**Issue by bitwombat** [casperjs/casperjs#1383]
This section in the docs has me puzzled:

```
Warning

Step functions added to then() are processed in two different cases:

    when the previous step function has been executed,
    when the previous main HTTP request has been executed and the page loaded;

Note that there’s no single definition of page loaded; is it when the DOMReady event
has been triggered? Is it “all requests being finished”? Is it *all application logic being
performed”? Or “all elements being rendered”? The answer always depends on the
context. Hence why you’re encouraged to always use the waitFor() family methods to
keep explicit control on what you actually expect.
```

Doesn't this mean that I can _never_ rely on the DOM being in a certain state when my then() is executed?  And doesn't this mean then() is useless?

I see code like this in the examples:

```
    this.start("http://yahoo.com/", function() {
        this.echo("Page title: " + (this.getTitle()));
    });
    this.then(function() {
        this.echo((this.evaluate(countLinks)) + " links");
    });
```

According to the docs, though, that then() function, counting the links, may run before the DOM is complete and all the links are available.  Right?

If I'm right, that means using Casper to "drive" a website for testing isn't about setting up sequential steps, but rather event-driven using the waitFor() family.

**Comment by bitwombat** [comment]
More musings on this issue.

Many examples use .then as if you can write sequential web-page manipulating CasperJS scripts.  ".then()" is used in the [FAQ](http://docs.casperjs.org/en/latest/faq.html) and even the [docs for .click()](http://docs.casperjs.org/en/latest/modules/casper.html#click).  WaitFor doesn't show up in the either of those, nor in the [quickstart](http://docs.casperjs.org/en/latest/quickstart.html).  

Even other [authors of examples](http://jsebfranck.blogspot.fr/2014/03/page-object-pattern-with-casperjs.html) fall into this trap.

As the warning for .then() states, this won't really work.  Many mailing list questions are from people being tripped up by this same thing - Calling .click() in a .then(), and having it fail silently because the DOM isn't ready.

Is there a technical fix?  Maybe .then() waiting for one of the three conditions listed in the warning (DOM ready, all requests fulfilled, or all elements rendered)?  What are the trade-offs?  Execution time?  Side-effects?

Maybe this situation can be helped by something blunt in the FAQ like: "Manipulate pages with event-driven code using the WaitFor() family, rather than sequential code using .then()".  This is basically what the warning says, but it apparently needs to be more prominent.

**Comment by andreportela** [comment]
Hi @bitwombat!

I agree with you because I've fallen in the same trap you mentioned 😱

My suggestion is to list all things that need to be updated in docs right here as a check list in this issue and gradually fix one by one with maybe several pull requests mentioning this issue.

I got what you said about `then()` family, but I disagree on changing its behavior. Many developers already use this family to make several simple things, let's keep them happy 😃 

I suggest we create a bunch of new methods merging `then()` method with `wait()` family so instead of writing something like:

casper.start('http://www.somepage.com', function() {
    this.fill('#login', {
        'user':    "awesomeUser",
        'password':    "swordfish"
    }, true);
}).then(function(){
    this.waitForText("Title of the second page", function() {
        this.clickLabel('Link to the third page');
    });
}).then(function(){
    this.waitForText("Title of the third page", function() {
        this.echo(this.getHTML()); // you should get third page html
    });
});
casper.run();

**We could write something like:**

casper.start('http://www.somepage.com', function() {
    this.fill('#login', {
        'user':    "awesomeUser",
        'password':    "swordfish"
    }, true);
}).thenWaitForText("Title of the second page",function(){
        this.clickLabel('Link to the third page');
}).thenWaitForText("Title of the third page", function() {
        this.echo(this.getHTML()); // you should get third page html
});
casper.run();

Which I think its more clear and less verbose. 
What do you guys think?

**Comment by istr** [comment]
Ping @BIGjuevos @mickaelandrieu @jefleponot @paazmaya  for discussion.

**Comment by kensoh** [comment]
Hi @bitwombat is this issue still happening for you? I normally explicitly check for an element before interacting with it. In a project I'm working on now base on CasperJS, I make each step explicitly check for an element to be there before interacting with it immediately after it has appeared.

Saw your cross-reference above on Twitter, I've just made a reply to a similar question on Twitter automation - https://github.com/casperjs/casperjs/issues/1824

**Comment by bitwombat** [comment]
@kensoh I think explicitly checking for an element before interacting with it is the same as I'm saying above (from a year ago) that I need to do.  But that means you don't have a nicely reading, clean chain of .then() statements.

**Comment by kensoh** [comment]
@bitwombat oh yeah that is surely a side-effect. I'm an test automation engineer. But I kinda hate writing a lot of code to do automation, and reading/maintaining a lot of code. So I started a project to make a wrapper around CasperJS, such that simple 'natural-language' looking steps can be converted automatically into working CasperJS code to run it.

For example below block of steps will be converted into lines of sequential and auto-wait steps. It also supports JS code directly so developers won't lose their coding flexibility. In the process of making the project I have to write a lot of code. But it makes prototyping and developing automation much easier for me. Also added a live mode recently to make iteration even faster.

https://github.com/tebelorg/TagUI#how-it-works

```
https://www.typeform.com
click login
type username as user@gmail.com
type password as 12345678
click btnlogin
hover Test Event
click action results tooltip
click section_results
download https://admin.typeform.com/form/2592751/analyze/csv to report.csv
```

**Comment by kensoh** [comment]
Closing this issue for now but do reopen if anything. Thanks @bitwombat !
