### ISSUE TITLE
Native support for selecting an option from a drop-down

### ISSUE THREAD

**Issue by tim-montague** [casperjs/casperjs#1390]
CasperJS should support the ability to select options from a drop-down, even if it's not apart of a form (http://docs.casperjs.org/en/latest/modules/index.html). Selenium offers the `select` and `addSelection` commands.

Users on StackOverflow suggest this code, but it doesn't work correctly when used with commands like `waitFor()`.
https://stackoverflow.com/questions/16332312/how-to-click-a-select-option-and-then-evaluate-loaded-content-with-casperjs/34553086#34553086

```
casper.evaluate(function() {
    $('#select_element_selector').val('value').change();
});
```

This solution (also on StackOverflow) works with `waitFor()`.
https://stackoverflow.com/questions/28515292/how-to-fill-a-select-element-which-is-not-embedded-in-a-form-with-casperjs/28515450#28515450

```
casper.selectOptionByValue = function(selector, valueToMatch){
    this.evaluate(function(selector, valueToMatch){
        var select = document.querySelector(selector),
            found = false;
        Array.prototype.forEach.call(select.children, function(opt, i){
            if (!found && opt.value.indexOf(valueToMatch) !== -1) {
                select.selectedIndex = i;
                found = true;
            }
        });
        // dispatch change event in case there is some kind of validation
        var evt = document.createEvent("UIEvents"); // or "HTMLEvents"
        evt.initUIEvent("change", true, true);
        select.dispatchEvent(evt);
    }, selector, valueToMatch);
};
```

I also discussed this on StackOverflow -
https://stackoverflow.com/questions/16332312/how-to-click-a-select-option-and-then-evaluate-loaded-content-with-casperjs/34553086#34553086

**Comment by vallettea** [comment]
+1

**Comment by piersb** [comment]
+1

**Comment by sanstream** [comment]
+1

**Comment by mickaelandrieu** [comment]
> Selenium offers the select and addSelection commands.

As a note, CasperJS is intended to be a wrapper of PhantomJs. We don't try to make a Selenium challenger, or even respect their API. What you are looking for is a complete framework like Mocha/Chai with something like webdriver.io probably..

**Comment by istr** [comment]
@vallettea @piersb @sanstream Please use the "add reaction" feature instead of void "+1" comments. Thank you. (see http://i.imgur.com/2ihNOmh.png)

**Comment by kevin-bruton** [comment]
I agree that this function should form a part of core CasperJS, as it is easy enough to find dropdowns outside of forms, to update web pages with new data via ajax or whatever.
Please hear us, core maintainers!
The function provided here by tfmontague has worked well for me!

**Comment by istr** [comment]
@kevin-bruton The staffing level of CasperJS is still very deplorable. Any PR that helps implementing this is highly welcome.

**Comment by kensoh** [comment]
Thanks @tim-montague for posting the solution here. I've implemented this custom function for an issue for my web automation project base on CasperJS/PhantomJS - https://github.com/tebelorg/TA.Gui/issues/11

If someone can point me in the right direction and if this is something technically possible for me to do, I can try taking a look at it. I'm a test automation engineer, with a little JS experience gained from using CasperJS.

**Comment by kensoh** [comment]
Someone posted the same question to CasperJS mailing list, so I thought update my implementation here as well. It is a modification of above solution in order to support both XPath and CSS selectors.

```js
casper.selectOptionByValue = function(selector, valueToMatch) { // solution posted in casperjs issue #1390
this.evaluate(function(selector, valueToMatch) {var found = false; // modified to allow xpath / css locators
if ((selector.indexOf('/') == 0) || (selector.indexOf('(') == 0)) var select = __utils__.getElementByXPath(selector);
else var select = document.querySelector(selector); // auto-select xpath or query css method to get element
Array.prototype.forEach.call(select.children, function(opt, i) { // loop through list to select option
if (!found && opt.value.indexOf(valueToMatch) !== -1) {select.selectedIndex = i; found = true;}});
var evt = document.createEvent("UIEvents"); // dispatch change event in case there is validation
evt.initUIEvent("change", true, true); select.dispatchEvent(evt);}, selector, valueToMatch);};
```

**Comment by kensoh** [comment]
Archiving issue using **ARCHIVE** label as CasperJS, like PhantomJS, is not actively maintained for now.
