### ISSUE TITLE
proposal features

### ISSUE THREAD

**Issue by jefleponot** [casperjs/casperjs#1408]
Hi @n1k0, @istr, @mickaelandrieu ...

Here is a list of proposals to increase casper capacities and portability, 
I have already coded some of these features and i would like to know 
if you could integrate them into casper project.

If you agree with some, I would take the time to propose them as pull requests. 
So here is the list : 
1. Render improvements
   With phantomJs or SlimerJs environment, there is no mouse cursor on screen-shots. 
   It's really difficult to follow any browsing and have a visual check of all 
   mouse actions. This proposal add a cursor before any render calls. 
   Also it's fun to clip a rectangle area but it could be better to have multiple clips for large scrolling zone.
   We could add comments into image or write image metadata (date, title, numbering ...)
   Renders could be triggered automatically before events with pre-format filenames.
2. Web Browsing.
   Casper is not designed to be used with html site build with <maps> tags or complex <canvas>. 
   You couldn’t click on a specific tag area. "I drive few virtual machines with noVNC with slimerjs 
   (to test heavy client appliances) and casperjs lacks some parameters to be really usable".
   When you use a real browser (chrome, FF...), you could open a new page by clicking on a link with mouse wheel or force open a link in the same page (and in addition it saves the browser memory usage).
3. Text Selector and partial text selector
   Any test utility use "link text" as selector. Casper has only a "clickLabel" slot to access with a text selector. "clickLabel" doesn't work with text transformed by css (text-transform: uppercase) or html tags (sample : &lt;a&gt;Casper&lt;b&gt;JS&lt;/b&gt;&lt;/a&gt;).
   Xpath selector could substitute to text selector but it quickly becomes a gas-works to maintain.
   for example : "//td/a[normalize-space(translate(string(),'\u00A0',' '))='%s'] | //a[normalize-space(translate(@title,'\u00A0',' '))='%s'])[last()]" .
   Text link (and partial text link) is very useful to generalize as selector object.
4. scheduling tasks
   Casperjs can shedule asynchronous tasks easily. To be a perfect player, we could add several commands : rewind, stop (clean shutdown with cleaning timers and ending tasks), replay, breakpoint ... bypass tasks with emittion for logs. Evaluate method may match asynchronous returns that could simplify data transmissions and Casperjs may be usable in other browsers (like in a chrome extensions - chrome.tabs.executeScript(integer tabId, object details, function callback))
5. Advanced features
   -Image analysis and comparison (for visual regression testing,  defacing ...)
   -Browsing by image recognition (test responsive formatting)
   ...
   it could be nice to interface some javascript libaries like
   ResembleJS
   PhantomCSS (my choice)
   Huxley 
   Wraith 
   Hardy 
   SiteEffect.io 
   to add advances features in native mode.

Regards, jef

**Comment by istr** [comment]
Lots of stuff. I fear we currently don't have enough manpower to integrate most of them... Any working and complete PR for any issue and/or extension on the core topics is highly welcome.
Preferably you work on [fixing the open bugs](https://github.com/n1k0/casperjs/issues?q=is%3Aopen+is%3Aissue+label%3ABug) first, though.

For some of the "advanced" topics, however, there are working third-party packages. For visual regression testing, for example, I am using a [patched version of PhantomFlow with PhantomJS 2.0.0 support](https://github.com/istr/PhantomFlow/tree/feature/phantomjs2) that stacks on PhantomCSS. This works well in gitlab CI automated testing, too.

I think it would be best to concentrate on the core features (that is: test-driving browser engines) in CasperJS and leave "advanced" stuff to external packages that build on it.

**Comment by jefleponot** [comment]
Hi Istr,

thanks for PhantomFlow link. (i didn't know this project)

To fix the open bugs, you could replicate tests and environments so it not obviously. Is there any test branch with open bugs ?

I agree with you to be best concentrate on the core but to me it is not enough flexible so I had to patch (extend) many lines (or surcharge methods). The core limit is really difficult to define on open projects.

My overlay of casperJS is quite big too it holds in many plugins (depend on execution type) :
- Loader Json scenarios (selenium + seBuilder) with shared authentication bricks.
- Interactive execution mode
- Error prioritization management (rules)
- Internet Explorer Library Compatibility Site
- Check generated pdf file content (with pdftohtml export)
- Check generated OpenOffice file content (with unoconv export)
- planning execution (scenario enable/disable moment, exception date)
- messageBox renders (with downloaded box)
- exports system : resume, transfert render file, transfert logs, data base integration
- favicon searcher (for the wall appliances)
- defacing test (with a phantomCSS fork)
- highlighter area for videos
- SLA modules based on "performance"
- technology list updater based on "wappalyser"
- supervision (check html headers consistency)
- Binding IP (BindProcessToIPonLinux instead of a phantomjs fork)
...
And Server Module for scenario management (creation, maintenance, deletion) and remote renders.

So that's why I proposed to improve ordinary features (selector, events, scheduling and renders).

Regards
Jef

**Comment by roneyrao** [comment]
Snapshots comparison is implemented in this extension, [casperjs-assert-match-snapshot](https://www.npmjs.com/package/casperjs-assert-match-snapshot).

**Comment by kensoh** [comment]
Archiving issue using **ARCHIVE** label as CasperJS, like PhantomJS, is not actively maintained for now.
