### ISSUE TITLE
casper.eachThen doesn't allow falsy values.

### ISSUE THREAD

**Issue by kellyjosephprice** [casperjs/casperjs#1418]
When using `eachThen`, if any of the array values are falsy, they get passed in as undefined:

```
casper.eachThen([0], function (response) {
    // response.data == undefined
});
```

**Comment by paazmaya** [comment]
Would you like to create a Pull Request which adds a test case for this?

**Comment by kellyjosephprice** [comment]
Oops, looks like I had a typo in the PR: #1419

**Comment by kensoh** [comment]
Thanks @kellyjosephprice ! I'm a CasperJS user for couple of years. Browsing through open issues now to see if anything I can help with. Saw that your PR has been merged. Closing this issue :)
