### ISSUE TITLE
how do you use CasperJS ?

### ISSUE THREAD

**Issue by jefleponot** [casperjs/casperjs#1424]
I will explain my way to use casperJS.

I have at least 3 running loop of casperJs launch in sequential mode: 
- the first one executes steps for test
- the second one executes specifics steps to insert test results into database (using a web service)
- the third one executes specifics steps to transfer logs and screen-shots to a web servers (using another web service)

Issue : What is the best solution ?
- Running 3 objects of Casper in sequential
- Running only 1 object of Casper, reusing it 3 times

Another issue : How do you stop running mode without killing (exiting) process ?
it is necessary on global timeout, errors ... events.

Here is a proposal #1422

Your sincerely , jef

**Comment by istr** [comment]
@jefleponot Why did you close it?

**Comment by jefleponot** [comment]
Because it was just for you and you read it! (to add my PR)
as you mention that was just a "documentation usage" (I can't access to forum)

Is there a little chance that one of my PRs will be insert into the projet ?

**Comment by istr** [comment]
Yes, of course. :-) We'll cater for that and integrate as much of your stuff as possible in the 1.1 release. I am following the rule that I merge a PR
- if a second maintainer is happy with it, too
- I had the chance to review and test it on my own

Thanks for patience.

**Comment by jefleponot** [comment]
Thanks for your answer.

I would like to become one of maintainer even if I lack of rigor when I code.
I was formatted to "piss code" for firms and it is very difficult to change.
Your's and Michael's advices are a great inspiration for me :+1: 

CU

**Comment by istr** [comment]
@jefleponot I would leave this decision up to @n1k0 who is still in charge of this repo and has his good reputation associated with it.

**Comment by n1k0** [comment]
I'm leaving this decision to the current team of active maintainers. As I've told a few times already, I'm now too far from code & usage to be even relevant.

I suggest the team keeps on challenging any code changes as much as required to ensure they won't have to maintain things they don't need, understand or believe they're wrong.

What I'm seeing in #1422 doesn't make much sense *to me*, and I wouldn't feel confident landing these features and maintain them over time; but I'm possibly alone here, which is totally fair as one more time, I'm not really part of this project anymore :)

If I had to give you a single advice, that would be to first start discussions on the mailing list whenever you wonder how things could be achieved using the current API, and *then* only send a PR if you *really* feel something's missing or broken. Having group discussions & gathering opinions from the users community is the highest value you can get in such situations.

**Comment by jefleponot** [comment]
Hi @n1k0 , @istr 

I just come back from vacation.
Nicolas: your opinion is really important even if you are now detach from any liability.

CasperJs is a great hight quality project for web tests (and supervision). We use it on phantomJS and slimerJS for tests. Ours scenarists use it also in a chrome extension (and soon in firefox 45  with webExtensions) to generate scenarios. CasperJs is fully functional to run basic scenario.
But with a patchwork of web applications, we have to hack casperJS to get a hight level of features such as these provided by selenium, ghost Inspector, ...

For some time, I suggest some improvements, because the project seems to enter phase of maintenance and does not add other features that could allow to run complex tests.

With #1422 , I propose another alternative to properly ended tests without using a die or an exit function when, for example, a time-out event occurs ( and eventually relaunch another test (like a suite)). As I said before, complex scenarios require that kind of features.

Regards

**Comment by mickaelandrieu** [comment]
@jefleponot I think a lot of needs you can be done creating CasperJS modules (http://docs.casperjs.org/en/latest/writing_modules.html) and/or only by extending the native API without any hack.

It's true that the project is in kind of maintenance, but we still accept and review pull requests... the main issue is to keep CasperJS "not to big to be maintained by 1 or 2 people".

From my point of view, we should document more how to create his own modules and probably list (or accepts in an organization ?) a list of modules.

For instance, I'd like to see tester/exporter module(s) to not be tied to phantomjs API.

My 2 cents :)

**Comment by kensoh** [comment]
Wow.. It has been really a while. Bumping up the issue as the PR has not yet been merged.

**Comment by kensoh** [comment]
Archiving issue using **ARCHIVE** label as CasperJS, like PhantomJS, is not actively maintained for now.
