### ISSUE TITLE
Eslint issue

### ISSUE THREAD

**Issue by jefleponot** [casperjs/casperjs#1430]
Has everybody got 801 problems when you launch eslint on modules directory ?

```
✖ 801 problems (0 errors, 801 warnings)
```

Is it useful to solve warnings or eslint is just used to show criticals ?

**Comment by istr** [comment]
This is ok for the moment.

I propose to tackle linting in separate PRs that have no changes but linting changes (no functional modification whatsoever).

It would be best to address one file per PR to keep things clean.

**Comment by paazmaya** [comment]
Could try to run ESLint with `--fix` parameter, to see which warnings get fixed automatically, as they often are just syntax related.

http://eslint.org/docs/user-guide/command-line-interface#fix

**Comment by mickaelandrieu** [comment]
@paazmaya :+1:

**Comment by kensoh** [comment]
Closing the issue for now as it seems to be resolved
