### ISSUE TITLE
Link with target="<frame-name>" makes the test hang with slimerjs.

### ISSUE THREAD

**Issue by autra** [casperjs/casperjs#1431]
When clicking a `<a href=".." target="aFrameName">...</a>`, casperjs hangs with used with slimerjs.

**Step to reproduce**
- checkout https://github.com/autra/casperjs/tree/link-target-slimerjs
- run `bin/casperjs selftest tests/suites/casper/click.js`
- then run `bin/casperjs selftest tests/suites/casper/click.js --engine=slimerjs`
- observe the results

**expected**
both tests complete.

**actual**
When executed with `--engine=slimerjs`, the test does not proceed to the next step after the click on the link with a target="aFrameName".

TBH, I'm not 100% sure it is casperjs bug. I may be a slimerjs bug, but I couldn't reproduce with slimerjs alone, without casperjs. I supposed that the problem was on this side for this reason.

**Comment by istr** [comment]
Which SlimerJS version is affected? NOTE that SlimerJS 0.9.6 still breaks things and is not covered by our test suite yet. https://github.com/n1k0/casperjs/blob/master/.travis.yml#L133

**Comment by autra** [comment]
0.9.5 and 0.9.6 are affected. I didn't test any other version, but if you want me to test a specific version, I can try.

**Comment by autra** [comment]
Just to be sure, to switch engine, I just need to set the `ENGINE_EXECUTABLE` environment variable right?

**Comment by istr** [comment]
> Just to be sure, to switch engine, I just need to set the ENGINE_EXECUTABLE environment variable right?

Exactly.

**Comment by kensoh** [comment]
Thanks @autra wanted to update that with CasperJS v1.1.4 and SlimerJS v0.10.3 I get an error for your example. Without SlimerJS no error.

```
# element focus on click 
FAIL [Exception... "Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsIURILoader.openURI]"  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: resource://slimerjs/webpageUtils.jsm :: setWindowContent :: line 320"  data: no] 
#    type: uncaughtError 
#    file: tests/suites/casper/click.js 
#    error: {} 
#    stack: not provided 
```

**Comment by kensoh** [comment]
Closing the issue for now, as it might be a SlimerJS issue. Not sure the current status because the last response to issue was 3 months ago. But do reopen if anything!
