### ISSUE TITLE
Missing ssl-ciphers phantomjs native arguments

### ISSUE THREAD

**Issue by ggeligible** [casperjs/casperjs#1433]
Hello,

I have noticed that --ssl-ciphers is missing from [phantomjs native arguments](https://github.com/n1k0/casperjs/blob/e84ca6507d738b63c3b97c4f21dac11181d0cead/bin/casperjs#L15-L44). Does it mean that --ssl-ciphers parameter is ignored while calling phantomjs? Is it possible to get is added?

Thanks,
Gaurav

**Comment by kensoh** [comment]
Thanks @ggeligible for raising! It looks like your suggestion is now into master. Closing for now but do ping if you find an issue :)

https://github.com/casperjs/casperjs/blob/master/bin/casperjs

```
            'ssl-protocol',
            'ssl-ciphers',
            'ssl-certificates-path',
```
