### ISSUE TITLE
Firing blur, focus events when field is filled (setField method in clientutils.js file)

### ISSUE THREAD

**Issue by ketchoop** [casperjs/casperjs#1438]
I think it would be great if you add this thing, because blur() and focus() method doesn't fire same events.

**Comment by kensoh** [comment]
Thanks @ketchoop have you tried using evaluate to directly manipulate the field to focus and blur as needed? I think sendKeys supports the focus part but not the blur part. Closing this issue for now, but do reopen if anything!
