### ISSUE TITLE
Make form optional in fillSelectors() or make method like "fillInput()"

### ISSUE THREAD

**Issue by Macek007** [casperjs/casperjs#1439]
Hi, 

Don't you want to make form optional in fillSelectors() or make method like "fillInput()" or setInputValue()

I found in many discussions request how to fill inputs without form, I have same issue.

I suggest to make encapsulation to method setField in casperutils.js which should do this without a lot work.

Do you want pull request?

Refactor tip: Maybe should be better to make special function for each input type (radio, select etc.) in setField method.

Thanks

P.S. CasperJS is really great!

**Comment by istr** [comment]
> Do you want pull request?

Yes, every complete and useful PR that adheres to the [contributing guidelines](https://github.com/n1k0/casperjs/blob/master/CONTRIBUTING.md) is highly welcome.

**Comment by Macek007** [comment]
Hi!

1000x sorry about silly question but I am newbie with GitHub pull request :(
I am ready with this feature, but I am no able to make pull request... I followed https://github.com/n1k0/casperjs/blob/master/CONTRIBUTING.md and made local copy, made branch but I am not able push it back with this error:

remote: Permission to n1k0/casperjs.git denied to Macek007.
fatal: unable to access 'https://github.com/n1k0/casperjs.git/': The requested URL returned error: 403

Did I do it in bad way? Should I made my own fork first? Thanks a lot.

**Comment by mickaelandrieu** [comment]
@Macek007 it make sense because you don't have admin rights on @n1k0's repository.

You need to fork the `casperjs` repository first, using the "Fork" button on top right of Github interface when you are on the casperjs repository page.

Then you will be able to push everything, because the new created repository is yours.

When you will push new commits, Github will notify you and suggest you to make a "pull request".

Let me know if you need help :)

**Comment by yoannmoinet** [comment]
@Macek007 you can follow these to understand how [PR works](https://help.github.com/articles/using-pull-requests/) and what [forking means](https://help.github.com/articles/fork-a-repo/).

**Comment by kensoh** [comment]
@Macek007 I'm CasperJS user for couple of years.. Was looking through open issues and saw that you have committed code to your repo. Not sure if a pull request is sent. Bumping this up.

**Comment by kensoh** [comment]
Oh looks like it has been shipped but pending committing of your PR for doc - https://github.com/casperjs/casperjs/pull/1461 :)

**Comment by kensoh** [comment]
Bumping up this thread and copying maintainer @jefleponot 

Thanks @Macek007 .. not sure if you enable maintainers to edit to remove the tabs directly.

**Comment by kensoh** [comment]
Archiving issue using **ARCHIVE** label as CasperJS, like PhantomJS, is not actively maintained for now.
