### ISSUE TITLE
Why this simple code does not work?

### ISSUE THREAD

**Issue by dastiw1** [casperjs/casperjs#1441]
var casper = require("casper").create({
    verbose: true
});

// The base links array
var links = [], productLinks = [];
var catLink = "http://3dnews.ru";

// Just opens the page and prints the title
function start(link) {  
    this.start(link, function() {
        this.echo('Page title: ' + this.getTitle());
    });
}

function check() {
    start.call(this, catLink);
}

casper.start().then(function() {
    this.echo("Starting");
});

casper.run(check);

**Comment by paazmaya** [comment]
`catLink` ?

Please format the code properly in order to make it more readable, possibly with code blocks

**Comment by jefleponot** [comment]
Hi @dastiw1,

You have just forgotten one line :smile: 

```
var casper = require("casper").create({
    verbose: true
});

// The base links array
var links = [], productLinks = [];
var catLink = "http://3dnews.ru";

// Just opens the page and prints the title
function start(link) {
    this.start(link, function() {
        this.echo('Page title: ' + this.getTitle());
    });
}

function check() {
    start.call(this, catLink);
    this.run(function(){this.exit(0);});  // <=== HERE
}

casper.start().then(function() {
    this.echo("Starting");
});

casper.run(check);
```

Best regards

**Comment by kensoh** [comment]
@dastiw1 closing this issue, tried running Jef's code and it works with below output :)

```
Starting
Page title: Все самое интересное из мира IT-индустрии
```
