### ISSUE TITLE
Bug: loadInProgress

### ISSUE THREAD

**Issue by jefleponot** [casperjs/casperjs#1442]
Sometime a resource is extremely slow and phantomJS (and SlimerJs) takes few minutes to call the "onLoadFinished" event and sometime the event never happened.

CasperJs use a variable "loadInProgress" to wait the end of the loading page.
bug : when resource is slow , "loadInProgress" is never set to "true" and steps can't continue. 
PhantomJs and SlimerJs manage the event "onResourceTimeout" to resolve this loading state.

http://phantomjs.org/api/webpage/handler/on-resource-timeout.html
http://docs.slimerjs.org/current/api/webpage.html#webpage-onresourcetimeout

CasperJS would have to use this event "onResourceTimeout" .
Could CasperJs have a timer to do stop waiting so long time and go to next step ? 
Could CasperJs use another event like "readystatechange" or "DOMContentLoaded" to begin actions instead of the "load" event ?

In your opinion, what is the best solution to solve the problem  @istr , @mickaelandrieu , @paazmaya ... ?

Thank you in advance for your ideas
Jef

**Comment by jefleponot** [comment]
has anybody got an idea about the "Bug: loadInProgres" issue ?

**Comment by kensoh** [comment]
Hi Jef, I'm closing this issue for now as there hasn't been replies on this for a while..
