### ISSUE TITLE
Test cases isolation

### ISSUE THREAD

**Issue by riston** [casperjs/casperjs#1455]
Currently, I am using multiple files with different test cases like A, B, C etc. When the tests are executed the I assume to get back into "clean state". When in a test A user sign-in's user it's now signed in for other tests also, the cookies and requests loading continues for the next tests also B and C. The hack solution is to do the clean up manually, logout or clear cookies. How to you guys approach this test isolation problem? This issue gets really annoying when there are many tests.

**Comment by m3martin** [comment]
I've experienced a similar problem. I've added `casper.page.clearMemoryCache();` (via  http://stackoverflow.com/a/28314662) after my tests & that seems to help. If there's a better way, I'd love to know it.

**Comment by javsalgar** [comment]
I have suffered from this kind of issue as well. In very specific cases, `casper.page.clearMemoryCache()` didn't seem to be sufficient. I think that, in this kind of situations, it might be worth thinking in having separate CasperJS calls per test file (kind of annoying, though). I would also like to know which is the 'correct' way of dealing with session data and multiple tests in CasperJS.

**Comment by kensoh** [comment]
For a project that I'm working on, I handle iterations through [shell script](https://github.com/tebelorg/TagUI/blob/master/src/tagui) or batch file and calling CasperJS. I thought this would destroy and create new CasperJS+PhantomJS instances and would be more reliable for batch automation.

Not sure if for testing this is a good way. My use case is more for automating web interactions, not collecting results in a single test run. Though I compile the results of all the runs into the same file.

**Comment by kensoh** [comment]
Closing this issue for now as there hasn't been new feedback or issues raised. But do reopen if anything!
