### ISSUE TITLE
Issue templates now available, should we use?

### ISSUE THREAD

**Issue by paazmaya** [casperjs/casperjs#1456]
Since https://github.com/blog/2111-issue-and-pull-request-templates happened, how about starting to use that feature?

**Comment by kensoh** [comment]
As a user, I don't like filling issues templates hehe. Though it helps support if there is a recurring common set of parameters which are vital for troubleshooting an app. Only if there is, will at least help reduce one round-trip to clarify and get response. Sometimes users raise an issue and disappear 4eva.

**Comment by kensoh** [comment]
Closing this issue for now as there's no more updates around this topic..
