### ISSUE TITLE
waitForPopup() not working in repeat() ?

### ISSUE THREAD

**Issue by LuckyLillia** [casperjs/casperjs#1460]
I have written code for the following:
1) Opens a web page
2) Clicks on a Link
3) Popup opens
4) Click a button and do something
5) Popup closes

This is a sample code below. This works for a test page.
If I give actual website url it loads popup for 1st time button click.
The second time, it clicks button but waits for popup before timing out. It halts just before the waitForPopup().
The link to open popup is visible and it is also being clicked. But it waits for the popup before timing out.

Any idea why the waitForPopup() is timing out in repeat() the second time?

In the waitForPopup() what is the regex for any url? I am giving /http/ is that right?

[test.js.txt](https://github.com/n1k0/casperjs/files/154252/test.js.txt)
[test.html.txt](https://github.com/n1k0/casperjs/files/154253/test.html.txt)

Thanks

PS: Actually, this is similar to what I am facing - http://stackoverflow.com/questions/29714614/waitforpopup-in-casperjs-always-gets-wait-timeout
and this one - https://groups.google.com/forum/#!topic/casperjs/CVARjJ8dR2s
For me, it works for the first time but timing out the second time

**Comment by JiaxiangZheng** [comment]
+1

From the source code `modules/casper.js`, it seems the `page.onPageCreated` event is only binded when for the first time page creating, so for code bellow will not work.

```javascript
casper.test.begin('test name', function(test) {
  casper
    .start(url1, function () {
      test.assertHttpStatus(200);
    })
    .waitForSelector(selector1, function () {
      this.click(selector1);
    })
    .waitForPopup(popupPattern, function () {
      test.assertEquals(this.popups.length, 1);
    })
    .withPopup(popupPattern, function() {
        this.click(selector2);
        this.waitForPopup(popupPattern2, function () {
          test.assertEquals(this.popups.length, 2);
        })
        .withPopup(popupPattern2, function() {
          test.assertExists(someselector);
        });
    });

   casper.run(function() {
       test.done();
   });
});
```

**Comment by jefleponot** [comment]
just have a look to #1711

**Comment by kensoh** [comment]
@LuckyLillia @JiaxiangZheng happy to confirm that running the test.js on test.html now works after Jef's commit. I'm running CasperJS v1.1.4 on PhantomJS v2.1.1. Closing this for now, but do ping here if anything :)

```
Step 1 - Page Loaded
Step 2 - button clicked 1 Time
Step 3 - Popup loading 1 Time
Step 4 - Inside Popup 1 Time
Step 4 - Closing Popup 1 Time
Step 5 - Reload
Step 2 - button clicked 2 Time
Step 3 - Popup loading 2 Time
Step 4 - Inside Popup 2 Time
Step 4 - Closing Popup 2 Time
Step 5 - Reload
Step 2 - button clicked 3 Time
Step 3 - Popup loading 3 Time
Step 4 - Inside Popup 3 Time
Step 4 - Closing Popup 3 Time
Step 5 - Reload
```
