### ISSUE TITLE
captureSelector with clipRect

### ISSUE THREAD

**Issue by brucejcw** [casperjs/casperjs#1463]
I may want to capture a selector, but the captured image was not big enough, so I can't capture the whole image but get partial

**Comment by desmond276** [comment]
Have you set your viewport?

**Comment by Awakening-j** [comment]
@desmond276 I've set viewport

**Comment by Awakening-j** [comment]
@desmond276 what is the right order to call casper api  `viewport` and `start`

**Comment by desmond276** [comment]
@Awakening-j hmm... I don't think its the viewport since you said you set it.  I usually set it when I create the casper object.

**Comment by kensoh** [comment]
Hi @brucejcw do you still have this issue? I haven't encountered this situation before. Capturing selectors or the whole webpage works for me. Maybe it has been fixed..

**Comment by kensoh** [comment]
Hi @brucejcw not sure if this issue is resolved for you with latest CasperJS v1.1.4 and PhantomJS v2.1.1? Closing this for now but please reopen if it is still happening. Thanks for raising this! Thanks also to @desmond276 for sharing your inputs!
