### ISSUE TITLE
How to clean Popups?

### ISSUE THREAD

**Issue by LuckyLillia** [casperjs/casperjs#1472]
I have some code which clicks a link, which opens a popup.
When I close the popup window, and I run this command,
this.echo("popup list entries - " + this.popups.list());

It gives the < deleted > message instead of "-"

If I include this code inside casper.repeat function, it breaks the second time.

But if I do not close the popup window, it repeats successfully.

Any ideas how I can clean the this.popups.list() or how to call popups.clean() ?
So that the this.popups.list() becomes "-" ?

**Comment by BIGjuevos** [comment]
@LuckyLillia I refactored the `popups.clean` method in #1490 about 2 weeks ago.  It now automatically cleans any outstanding popups instead of just the one (that might or might not exist).

Can you please retry with the latest master and let us know if it solves your problem?

**Comment by BIGjuevos** [comment]
Closing this issue.  @LuckyLillia I encourage you to try version 1.1.0 that has the new cleaning popup logic.

Please feel free to re-open this issue if the problem persists.
