### ISSUE TITLE
resourceExists() returns true in some cases when resource is not here

### ISSUE THREAD

**Issue by silicium14** [casperjs/casperjs#1480]
The function `resourceExists()` checks for the resource status code being different than 404 when the wanted resource is provided as a `string` or `regex` argument (see [modules/casper.js](https://github.com/n1k0/casperjs/blob/500b5b4751f29e7d9bb4523d28f99d7a4dc97dc2/modules/casper.js)).

In the following cases, with `string` or `regex` argument, the function will return `true` (`resource.status` will be `null` and thus satisfying the `!== 404` condition):
- network is not available
- the server at resource URL does not send a response
- the resource is at an invalid URL

I those cases, `resourceExists()` sould return `false`, in my opinion. The function should check that the resource status code is 200. Maybe some other HTTP codes (redirect?) also mean that the resource is available to the browser, but I'm not sure here. 

For now, it is possible to use a `function` argument to `resourceExists()` for custom resource mathing to obtain the behaviour I describe.

**Comment by jefleponot** [comment]
just have a look at this PR #1446 , you can complete it if you want

**Comment by kensoh** [comment]
Thanks @silicium14 for raising this! Closing the issue for now as the PR has been merged. But do reopen if anything!
