### ISSUE TITLE
URL hash not redirect

### ISSUE THREAD

**Issue by brucejcw** [casperjs/casperjs#1482]
I have a list of url,  
[xxx/url#hash, xxx/url#hash2/, xxx/url#hash3],  
seems page not redirect when only hash changed.  
I've tried self.back(), still not working

```
casper.start().each views, (self, view) ->
    self.thenOpen view.url, ->
```

**Comment by Awakening-j** [comment]
@istr  Any idea for this?

**Comment by istr** [comment]
Not yet, sorry... I need to create a short test case for that.

**Comment by Awakening-j** [comment]
@istr i'm waiting for your testing result

**Comment by Awakening-j** [comment]
+1
any one also have this issue ?

**Comment by kensoh** [comment]
Hi @brucejcw bumping up this issue and seeing if you still encounter this issue.

**Comment by kensoh** [comment]
Closing this issue for now, it seems to be fixed along the way. But do reopen if anything! I tried running a series of navigation steps using thenOpen and the getCurrentUrl returns the correct updated URL.
