### ISSUE TITLE
Lack of error trace

### ISSUE THREAD

**Issue by brucejcw** [casperjs/casperjs#1486]
I've set `verbose : true` and wrapped with `try catch`, still missing some unexpected crush in casper, as a case of `casper.start().each(urls, func)`, sometimes it only execute once, but no any error log?? How can I debug this  
![2016-03-18 16 02 12](https://cloud.githubusercontent.com/assets/8085088/13872170/490a23dc-ed23-11e5-9481-0ae67a399508.png)

**Comment by kensoh** [comment]
Hi @brucejcw maybe you have already found a solution. For a tool I'm working on, I handle iterations from the (shell script)[https://github.com/tebelorg/TagUI/blob/master/src/tagui] or batch file. This way, new instances of CasperJS/PhantomJS will be created and destroyed. For my use I find this is good and should be more stable in running batch automation.

**Comment by kensoh** [comment]
Hi @brucejcw maybe you have already found a solution. For a tool I'm working on, I handle iterations from the [shell script](https://github.com/tebelorg/TagUI/blob/master/src/tagui) or batch file. This way, new instances of CasperJS/PhantomJS will be created and destroyed. For my use I find this is good and should be more stable in running batch automation.

**Comment by kensoh** [comment]
Closing this for now but do reopen if it is still an issue. Thanks for raising this!
