### ISSUE TITLE
Warning about mutating the Prototype instead of using Object.create

### ISSUE THREAD

**Issue by wskorodecki** [casperjs/casperjs#1487]
I've found interesting warning about performance:

`JavaScript warning: file:///home/user/Repositories/casper/node_modules/casperjs/modules/http.js, line 70: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create`

It is being displayed when I choose SlimerJS as an engine.

**Comment by istr** [comment]
@wskorodecki Good finding. I am sure that there is a better shim available that does not need to mess about with Object's Prototype.

**Comment by kensoh** [comment]
@wskorodecki may I check if you are still experiencing this? I was running CasperJS and SlimerJS for a while but didn't see this before. Not sure if it has been fixed.

**Comment by wskorodecki** [comment]
@kensoh It is not related to SlimerJS but to Firefox. This message may not be always displayed because it is highly related to specific web pages and specific Firefox versions. I've spotted this many times when I have been surfing on Facebook via SlimerJS. That's what I remember - currently I cannot check if this is still happening when SlimerJS is working under recent versions of Firefox.

**Comment by kensoh** [comment]
Thanks @wskorodecki very much for your reply. I see.. This isn't exactly replicable but still a valid suggestion for CasperJS maintainers to review. Copying current main maintainer @jefleponot too.

**Comment by kensoh** [comment]
Adding on I'm not sure the status for SlimerJS because the last reply on issues was 3 months ago.
