### ISSUE TITLE
0 as a timeout value in wait() method

### ISSUE THREAD

**Issue by wskorodecki** [casperjs/casperjs#1488]
`CasperError: wait() only accepts a positive integer > 0 as a timeout value`

I think it is better to allow 0 as a value, because sometimes it is very useful to disable all application delays in configuration by changing some variable to 0 instead of adding if-statements for this purpose or adding 1 as a value which is ugly.

In other words - if the timeout value is omitted or 0 the method should interpret this as "call the function immediately". Just like the setTimeout() function works in JavaScript:

`setTimeout(function() {console.log('It works!');}, 0);`

**Comment by istr** [comment]
A PR to resolve this issue is highly welcome.

**Comment by kensoh** [comment]
Hi @wskorodecki this seems to be possible now, I can do a wait with 0 as parameter.

**Comment by kensoh** [comment]
Thanks @wskorodecki! Looks like your pull request is already merged, closing this issue for now. Probably no change in documentation needed (existing doc looks ok) but copying @jefleponot for his call.
