### ISSUE TITLE
How could you capture dialogueBox ?

### ISSUE THREAD

**Issue by jefleponot** [casperjs/casperjs#1492]
Hi @istr , @mickaelandrieu , @paazmaya , @n1k0 ...

Do you think, it's possible to capture (render) an entire web browsing ?

casperJS allows to filter page.confirm or page.prompt or remote.alert... but when you run casper.capture any dialogue Box are captured because these dialogues depends on the operating system.

```
var casper = require("casper").create({viewportSize :{width: 1024, height: 768}});

casper.setFilter("page.prompt", function(msg, value) {
    if (msg === "Do you like CasperJS?") {
        return "yes I do";
    }
});

casper.on("page.prompt", function(msg, value){
     this.capture('screencap.png');
});

casper.start("http://casperjs.org", function() {
    this.evaluate(function(){
        window.prompt('Do you like casperJS ?','yes I do');
    });
});
casper.run();
```

That will be nice to have that kind of screen-shot :

![screenshot01 copie](https://cloud.githubusercontent.com/assets/5547697/13920062/46b011b4-ef71-11e5-82e7-1dc0e3185bdb.png)

another kind of screen-shot : 

![screenshot02](https://cloud.githubusercontent.com/assets/5547697/13920798/170be092-ef75-11e5-8022-c943926f867c.png)

Does anyone need this feature ?

**Comment by mickaelandrieu** [comment]
Hmm this make me think to http://mindthecode.com/recording-a-website-with-phantomjs-and-ffmpeg/ ^^

I don't have this kind of need, though. Also, I think what you want is a real browser, but CasperJS is an headless tool. You can follow what is done during testing with tools like selenium and mocha/chai.js, this is realy out of scope of what CasperJS is supposed to do.

I remember that @n1k0 wanted to remove - or at least extract - Tester Api to focus CasperJS native APIs on his wrapper missions :)

PS: I don't understand why you need setFilter() function here.

**Comment by jefleponot** [comment]
Hi @mickaelandrieu ,

thank you for mindthecode link :smile: 

I personally coded this feature 2 years ago, so I just ask if someone need it.
"Confirm" functions are really use-full to validate disconnection from portals. Other methods like "alert" or "prompt" are now out-of-date. 

With this feature, I coded "cursor positioning" to follow mouse movement and show area that had been clicked or imputed. 
![index](https://cloud.githubusercontent.com/assets/5547697/13921978/bc61cd2c-ef7a-11e5-8c69-786d5cee0b80.png)

It works both on phantomJS and SlimerJS.

very nice to follow developments websites with tests

**Comment by mickaelandrieu** [comment]
@jefleponot how about a [CasperJS extension](http://docs.casperjs.org/en/latest/writing_modules.html) then ? :) I mean, if you want to release it as open source code, it's totaly up to you ^^

**Comment by jefleponot** [comment]
:cry: it needs to hook few casper modules

**Comment by mickaelandrieu** [comment]
no problem, @n1k0 is so great => http://docs.casperjs.org/en/latest/extending.html

**Comment by istr** [comment]
@jefleponot Do you have a real use case for that? Nowadays most browser push users to qualify ```alert``` and ```prompt``` calls being spam. Many users fall in to the trap of blocking these calls: 

![shot-block-alerts](https://cloud.githubusercontent.com/assets/4235579/13948450/5d10f8e2-f020-11e5-9b57-141ae6a518a3.png)

Lately I had to replace all ```alert``` and ```prompt``` calls with custom modals just because of that. I guess that apart from debugging these two are goners now...

**Comment by jefleponot** [comment]
Hi @istr,

All our web applications were developed with IE6 and IE8 compatibility. 
"alert" and "prompt" are now out-of-date but we have many "confirm" for portals disconnection
and also many download-Boxs for generated files (libreOffice or PDF)

I coded two files "render.js" and "clientrender.js". it creates an iframe to simulate dialogue Box on triggers. it makes also appears a cursor and displays a comment on renders pictures (page title, date, section, number of screen-shot).

**Comment by jefleponot** [comment]
Hi @mickaelandrieu , @istr , @paazmaya 

Do you know why "event.js" file is not format like other source code files ?

no comment , no description ... is it a copy paster from another project ?

This PR add structure to event.js file : #1496

**Comment by kensoh** [comment]
Bumping up this thread :)

**Comment by metmajer** [comment]
@jefleponot: +10 on making the mouse cursor visible! Got some code to share?

**Comment by kensoh** [comment]
Archiving issue using **ARCHIVE** label as CasperJS, like PhantomJS, is not actively maintained for now.
