### ISSUE TITLE
How can I get the code coverage of my project when running casper ui automation tests

### ISSUE THREAD

**Issue by flyHe** [casperjs/casperjs#1502]
Is there any tool to get the code coverage when running casper tests,so I can know if the casper cases is enough for project

**Comment by BIGjuevos** [comment]
@flyHe would something like: https://github.com/yannickcr/mystery-inc be of assistance?

**Comment by flyHe** [comment]
@BIGjuevos  yes,it looks good,but I got some confusion on this,it can make Istanbul code coverage reporter,but how can I use it with my casper test?Should I make it as a module of my test?Thanks

**Comment by BIGjuevos** [comment]
@flyHe Not sure how to actually implement it (as it depends on your setup), but you could inject [instanbul](https://github.com/gotwarlost/istanbul) into the page you want coverage on, start it, and control the results through a ``casper.evaluate``.

**Comment by flyHe** [comment]
@BIGjuevos Thanks.Though instanbul can not work in production env.It can work in dev env now.

**Comment by BIGjuevos** [comment]
@flyHe What scenario do you have that involves getting code coverage in production?

**Comment by flyHe** [comment]
@BIGjuevos When the app is in build step to be production on remote,it will do the ui test,and I want to get the code coverage of the test.But [istanbul-middleware]
(https://github.com/gotwarlost/istanbul-middleware) must ensure this is not production.The middleware will intercept all GET requests to Javascript file.It will influence the whole app if in production.So I can only get the coverage in my local environment

**Comment by BIGjuevos** [comment]
Can you use http://docs.casperjs.org/en/latest/modules/casper.html?highlight=inject#index-1 to inject istanbul and then use casper.evaluate to get the results?

**Comment by flyHe** [comment]
@BIGjuevos I haven't found the method to inject the istanbul into page on browser.The istanbul need start with the app

**Comment by kensoh** [comment]
Bumping this up, don't know of any dominant code coverage tool to pair with CasperJS.

**Comment by kensoh** [comment]
Closing the duplicate issue https://github.com/casperjs/casperjs/issues/825 and inherit its Enhancement label.

**Comment by kensoh** [comment]
Closing this ticket in favor of the newer ticket (https://github.com/casperjs/casperjs/issues/1872), as this issue hasn't moved for over a year.
