### ISSUE TITLE
Problem with new function newPage()

### ISSUE THREAD

**Issue by NghiemDuongHung** [casperjs/casperjs#1511]
When I try to use function newPage(), task manager show there are too many TCP Connection and the application got hanged. I know open multiple url will create many TCP Connection but when I used this function, the number of connections increase a lots more, here is the code I used.

`casper.start();

var json = require('list.json');
casper.then(function() {
    var current = 0
    var end = json.length;
    for (;current < end;) {
        (function(cur) {
            casper.thenOpen(json[cur], function() {
                console.log(json[cur]);
                var data = this.evaluate(function() {
                    return $("title").text();
                });
            }).then(function() {
                casper.page.close();
                casper.newPage();
            });
        })(current);
        current++;
    }
});

casper.run();`

**Comment by entrptaher** [comment]
> That sounds normal.
> 
> PhantomJS supports HTTP keep-alive (persistent HTTP connections), and has it enabled by default. It is probably just opening 2 (or less) connections per server (as it is supposed to according to the spec), and that is what you are seeing.

Copied from: http://stackoverflow.com/questions/20658305/phantomjs-uses-several-tcp-connections-when-loading-one-page

**Comment by istr** [comment]
I think the problem here is, that many PhantomJS instances are spawned in the loop that do *not* share their persistent connections, thus the congestion. Probably the connections of PhantomJS are not closed when `casper.page.close()` is called (NOTE: this is just a wild guess without further inspecting your test case, so I might be utterly wrong with this suspicion).

**Comment by entrptaher** [comment]
@istr I tried his code, and the tcp connects were doing all great. All were exiting and entering perfectly.

**Comment by istr** [comment]
@entrptaher Ok, nice... :smile: Thanks for checking this.
I am closing this, because it seems to be explained. @NghiemDuongHung feel free to re-open if you have more specific information about the situation where the congestion occurs.

**Comment by NghiemDuongHung** [comment]
The problem is, when I dont use 
.then(function() {
casper.page.close();
casper.newPage();
})
I can scrap thounsand of pages, but when I use it, my app hang after around 20-30 pages, definitely not normal to me

**Comment by entrptaher** [comment]
Ah, tbh, I saw the delay too.
Its a serious problem then.

**Comment by kensoh** [comment]
@NghiemDuongHung bumping this up to check if running v1.1.4 + v2.1.1 still have the issue for you? I'm a CasperJS user for couple of years now browsing through open issues.

**Comment by NghiemDuongHung** [comment]
@kensoh I don't have any more work relate to scrap since then, but you can test with the code I post above

**Comment by NghiemDuongHung** [comment]
@kensoh @istr  I just tested with v1.1.4 (500 pages, same computer), it seems like the problem has been solved

**Comment by kensoh** [comment]
Thanks @NghiemDuongHung for your quick reply and good news 😄
