### ISSUE TITLE
Partial screenshots

### ISSUE THREAD

**Issue by zeepi222** [casperjs/casperjs#1512]
Hi,

I am having an issue where casperjs is not capturing complete screenshots (see attached image). I have tried introducing a delay before doing the capture, however it has not made any difference.

CasperJS version 1.1.0-beta3
phantomjs version 2.0.1

Capersjs code is as follows:

```
  onWaitTimeout: function() {
      this.wait(15000,function() {
          this.capture('wait-timeout.png', {
              top: 0,
              left: 0,
              width: 1024,
              height: 768
              });
    });
},
```

The debug looks as follows;

```
[warning] [phantom] Casper.waitFor() timeout
[info] [phantom] Step _step 18/22: done in 68368ms.
[info] [phantom] wait() finished waiting for 15000ms.
[debug] [phantom] Capturing page to /vagrant/scripts/logs/wait-timeout.png with clipRect {"top":0,"left":0,"width":1024,"height":768}
[info] [phantom] Capture saved to /vagrant/scripts/logs/wait-timeout.png
```

![wait-timeout](https://cloud.githubusercontent.com/assets/17309633/14269921/8fb23a4c-fb2c-11e5-94b6-bf2bef7b7418.png)

Any ideas how I can fix this?

Thanks

**Comment by zeepi222** [comment]
I am seeing this issue with both ...
CasperJS version 1.1.0-beta3 / phantomjs version 2.0.1
and
CasperJS version 1.1.0-beta5 / phantomjs version 2.1.1

**Comment by BIGjuevos** [comment]
@zeepi222 what happens when you try a non 2.0+ version of phantom?  Something like 1.9.18

**Comment by istr** [comment]
I had the issue too in some of my test cases. Waiting for a pre-defined duration is not the right approach. Try to wait for the selector / the set of selectors you want to capture to be in place using ```casper.waitForSelector()```.

**Comment by jefleponot** [comment]
Hi @istr , @zeepi222 , @BIGjuevos 

Something page finishes to load but css styles aren't applied. 

How could be sure that all css styles are applied ? before rendering :-)

**Comment by BIGjuevos** [comment]
Are they dynamically loaded, are you getting some sort of security exception?

**Comment by istr** [comment]
> How could be sure that all css styles are applied ?

That can be tricky, especially if they're loaded dynamically. If you know (at least a part of) the resource URLs you could ```waitForResource()```. If you know some (fixed part) of the CSS content, you could ```waitForText()```. I am doing the latter for web fonts in a special situation:

The page loads the web fonts using a variant of http://bdadam.com/blog/loading-webfonts-with-high-performance.html. The test suite then waits for some known part of content to occur:

```casper.waitForText('@font-face {font-family:"myfont";font-weight:400;font-style:normal;src:url(data:application/x-font-woff;charset=utf-8;base64,d09GRgABAAAAANJ4ABQAAAACmPgAAQ')```

**Comment by jefleponot** [comment]
Hi @BIGjuevos , @istr 
Thank you for reply.

I do as you @Istr, I wait for a specific style attribute apply on a selector. But if the css file changes, my scenario becomes out of date.

here is a copy of my generic function : 
````js
  //"assertElementStyle": ["locator", "propertyName", "value"],
  //"verifyElementStyle": ["locator", "propertyName", "value"],
  //"waitForElementStyle":["locator", "propertyName", "value"],
  //"storeElementStyle":  ["locator", "propertyName", "variable"],
  "ElementStyle": function ElementStyle(elm){
    "use strict";
    elm.selector = seBuilder.BuildSelector ( elm.locator );
    if (this.exists( elm.selector )){
      return this.evaluate(function(selector, property, value) {
        var elm = __utils__.findOne( selector );
        var style = window.getComputedStyle(elm,"").getPropertyValue(property);
        return (value == style);
      }, elm.selector, elm.propertyName, elm.value);
    }
    return false;
  },
````

**Comment by BIGjuevos** [comment]
@jefleponot waitForResourceExists looks to support a regex as well as a callback function for checking resource existence.  Can you write your own function to block until the resource is loaded?

See extract from casper.js

```javascript
Casper.prototype.resourceExists = function resourceExists(test) {
    "use strict";
    this.checkStarted();
    var testFn;
    switch (utils.betterTypeOf(test)) {
        case "string":
            testFn = function _testResourceExists_String(res) {
                return res.url.indexOf(test) !== -1 && res.status !== 404;
            };
            break;
        case "regexp":
            testFn = function _testResourceExists_Regexp(res) {
                return test.test(res.url) && res.status !== 404;
            };
            break;
        case "function":
            testFn = test;
            break;
        default:
            throw new CasperError("Invalid type");
    }
    return this.resources.some(testFn);
};
```

**Comment by jefleponot** [comment]
@BIGjuevos thank for reply but it is not that I need. 
I will test different events 

DOMContentLoaded
readystatechange
load
beforeunload
unload
window.performance.timing.loadEventEnd
window.performance.timing.domInteractive
...

my scenarios must be the least sensitive as possible. Resources are to much variable and changeable.

**Comment by kensoh** [comment]
Closing this issue for now as a solution is proposed for original issue. But do reopen if anything!
