### ISSUE TITLE
Control step execution when CasperJs tests are running

### ISSUE THREAD

**Issue by BIGjuevos** [casperjs/casperjs#1513]
## Request

I would like to execute the steps that casperjs has stored in any order I'd like with my own timing mechanism.

As such, I propose that a new API be added to allows me to determine when casper moves on to the next stop.
## Proposed API:

**casperOptions.autostart**: If set to false, upon calling run(), casper does not go straight to the first thing in the queue.
**casper.stepForward()**: Causes casper to execute the next thing in the queue (just the next thing).  If the end, if the last thing, it acts if it hits end of queue now.
**casper.resumeExecution()**: Causes casper to continue to execute the rest of the queue as if the **autostart** parameter had not been passed in.
**casper.thenBreak()**: A step in the queue that causes the queue to exit pre-maturely and give execution back to the caller to do things.
## Benefits:

this, we aren't adding in additional things to make the series of .then harder to read, and I think that this is easier to follow, things stay sequential, we just control the time at which they are being executed. Plus, I'm pretty sure we stay completely backwards compatible with a few changes to the internals of the runner.

This scales up realistically by bringing in a larger number of casper instances, and allows implementers to contrive rather convoluted use cases utilizing multiple instances of CasperJS to accomplish multi-page scenarios.

This would further allow for crazy bootstrapping in-between steps of tests and other things that pausing execution of the test queue would bring.

Blatantly stolen from conversation at #1500

**Comment by entrptaher** [comment]
Hi, so did you try to create the API?
Even in any forks/gists?

**Comment by BIGjuevos** [comment]
@entrptaher That is my goal this weekend.  I plan on having an early draft PR up.

**Comment by entrptaher** [comment]
No update?
Though the commit seems useful.

**Comment by kensoh** [comment]
This thread has been a while, but bumping this up as a lot of invested discussion has gone into this topic :)

**Comment by kensoh** [comment]
Bumping up this thread and copying @jefleponot
