### ISSUE TITLE
Curiously dubious results that don't make sense 1.1.0-beta5

### ISSUE THREAD

**Issue by robogeek** [casperjs/casperjs#1517]
I'm just learning CasperJS, and have written a test against a sample NodeJS/Express application I've written.  The test script has 23 assertions.  At the end it says the results are dubious because it planned 5 tests but saw 23 tests.  I have no idea how it determined there would be 5 tests - this makes no sense.

This was written for a book, and I'd like cleaner results before publishing it.  Suggestions?

Results:

```
Test file: uitest.js                                                            
# Can login to Notes application
PASS Can login to Notes application (5 tests)
PASS Page title is: "Notes"
PASS Login button is found
PASS HTTP status code is: 200
PASS should be on /users/login
PASS HTTP status code is: 200
PASS Page title is: "Notes"
PASS logout button is found
PASS Add Note button is found
PASS HTTP status code is: 200
PASS Page title is: "Add a Note"
PASS "docreate" input field has the value "create"
PASS HTTP status code is: 200
PASS Page title is: "Test Note Title"
PASS Find "Test Note Body with various textual delights" within the selector "p#notebody"
PASS HTTP status code is: 200
PASS Page title is: "Test Note Title"
PASS "notekey" input field has the value "testkey"
PASS HTTP status code is: 200
PASS Page title is: "Notes"
PASS logout button is found
PASS HTTP status code is: 200
PASS Page title is: "Notes"
PASS Login button is found
⚠  Can login to Notes application: 5 tests planned, 23 tests executed
FAIL 23 tests executed in 86.22s, 23 passed, 0 failed, 1 dubious, 0 skipped.    

Details for the 1 failed test:

In uitest.js
  Can login to Notes application
    dubious: Can login to Notes application: 5 tests planned, 23 tests executed
```

And the test

```

var notes = 'http://localhost:3000';

casper.test.begin('Can login to Notes application', 5, function suite(test) {
    casper.start(notes, function() {
        test.assertTitle("Notes");
        test.assertExists('a#btnloginlocal', "Login button is found");
        this.click("a#btnloginlocal");
    });
    
    casper.then(function() {
        test.assertHttpStatus(200);
        test.assertUrlMatch(/users\/login/, 'should be on /users/login');
        this.fill('form', {
            username: "me",
            password: "w0rd"
        });
        this.click('button[type="submit"]');
    });
    
    casper.waitForSelector('#btnlogout', function() {
        // this.echo('Logged in?');
        test.assertHttpStatus(200);
        test.assertTitle("Notes");
        test.assertExists('a#btnlogout', "logout button is found");
        test.assertExists('a#btnaddnote', "Add Note button is found");
        this.click("#btnaddnote");
    });
    
    casper.waitForUrl(/notes\/add/, function() {
        test.assertHttpStatus(200);
        test.assertTitle("Add a Note");
        test.assertField("docreate", "create");
        this.fill('form', {
            notekey: 'testkey',
            title: 'Test Note Title',
            body: 'Test Note Body with various textual delights'
        });
        this.click('button[type="submit"]');
    });
    
    casper.waitForUrl(/notes\/view/, function() {
        test.assertHttpStatus(200);
        test.assertTitle("Test Note Title");
        test.assertSelectorHasText("p#notebody", 'Test Note Body with various textual delights');
        this.click('#btndestroynote');
    });
    
    casper.waitForUrl(/notes\/destroy/, function() {
        test.assertHttpStatus(200);
        test.assertTitle("Test Note Title");
        test.assertField("notekey", "testkey");
        this.click('input[type="submit"]');
    });
    
    casper.waitForUrl(notes, function() {
        test.assertHttpStatus(200);
        test.assertTitle("Notes");
        test.assertExists('a#btnlogout', "logout button is found");
        this.click("#btnlogout");
    });
    
    casper.waitForUrl(notes, function() {
        test.assertHttpStatus(200);
        test.assertTitle("Notes");
        test.assertExists('a#btnloginlocal', "Login button is found");
    });

    casper.run(function() {
        test.done();
    });
});
```

**Comment by mickaelandrieu** [comment]
@robogeek it's "you" who say to CasperJS that you expect to run 5 tests.

```js
casper.test.begin('Can login to Notes application', 5, function suite(test) {
```
The second parameter is the number of expected tests to be run by CasperJS.

Can you tell us about this book ? If you need some review for the CasperJS code produced, you can contact me by email.

Mickaël

**Comment by robogeek** [comment]
Oh my...  I suppose I would have found that eventually ;-)

BTW, the above IS the code I produced for the book.  Does it look reasonable other than missing that one parameter.

The book is called Node.js Web Development - and I'm finishing up the 3rd edition right now.  As the title implies, it's all about Node.js programming.  CasperJS is featured in the last half of the chapter on testing.

**Comment by mickaelandrieu** [comment]
@robogeek well, thanks a lot to talk about CasperJS, even if we are not realy compatible with node ^^

**Comment by BIGjuevos** [comment]
Do you have some sample markup as well that you are testing?  The code looks to only be testing a single happy path through the application.

**Comment by robogeek** [comment]
Yeah - I have about 15 pages of space to discuss CasperJS which simply doesn't give room to do more than discuss this "happy path" (as you call it).  The reader does see some negative test cases in another portion of the chapter, but there's simply not enough room to give a full treatment of testing strategies.

The application front-end is written with Bootstrap.  One thing shown in the chapter is to add id's to particular elements that we can then use in the test to determine things.  For example, this application has a different set of Button's depending on whether the user is logged-in or logged-out.  Hence, #btnlogout is a Bootstrap Button, as are the other #btnxyzzy elements.  Checking those Buttons lets the application easily determine this state.

This line:

```
test.assertField("docreate", "create");
```

Checks against a hidden input that is a flag indicating whether that form is being used to Edit or Create a Note.  

On the /notes/view page there's a row of buttons at the bottom for various purposes.  In the test we just click on the Destroy button.  I suppose I could add another couple of stanzas to test Editing a note.  In the interest of space I didn't do so.

Finally, I did change the test to leave off the "5" parameter and now the test works perfectly.

**Comment by BIGjuevos** [comment]
I understand.  You've only got so much space in a book.

The tests you've got look like the cover a good base and convey the concept well.  There is lot's more to test as well, such as on page interaction and things of the like.  But, y'know, space.

Glad to see you've got it working, and best of luck with the rest of the book.  Thanks for including us!

Feel free to re-open, or open another issue if you want some more assistance.
