### ISSUE TITLE
Migration to casperjs organization

### ISSUE THREAD

**Issue by BIGjuevos** [casperjs/casperjs#1526]
I'm volunteering myself to deal with the fallout from a migration to the casperjs organization.

@n1k0 @mickaelandrieu @istr, what does that process look like?  Do we have any options aside from n1k0 clicking a button and us dealing with the fallout?

**Comment by istr** [comment]
Probably it is much easier than expected. It should be sufficient to create organisations at
- github.com
- npmjs.com
- (maybe readthedocs)

in the first step, set them up and populate in a second step and then transfer the ownership of the repo / npm name in a third step. I guess that this would be the best way to keep the history and should provide a smooth transition.

If in doubt, I would try to execute the process with a (useless) dummy github/npm project beforehand.

**Comment by BIGjuevos** [comment]
Alrighty I'll do some experimentation.  Any objections to doing this before we snapshot another release?

**Comment by istr** [comment]
> Any objections to doing this before we snapshot another release?

No, this was the initial plan, as far as I remember: issue 1.1.0 and then move on with an organisation.

**Comment by n1k0** [comment]
@istr @BIGjuevos @mickaelandrieu I've just added you guys as contributors of the casper org. Please tell me if you have access to whatever you need for setting up everything.

**Comment by BIGjuevos** [comment]
Thanks @n1k0 

GitHub has some pretty decent docs on this over at: https://help.github.com/articles/transferring-a-repository/

Looks like we need to remove the fork from the org, transfer and things just magically work out.

**Comment by jefleponot** [comment]
Hi @BIGjuevos 
Could you please explain me what does "Migration to casperjs organization" mean ?

Thanks by advance -> I'm still a newbie

**Comment by BIGjuevos** [comment]
> Could you please explain me what does "Migration to casperjs organization" mean ?

Presently all code is graciously hosted by our great overlord @n1k0 on his personal account.  The goal is to move Casper into a self sustain organization over at https://github.com/casperjs.

The org let's us be more flexible with how things are done across multiple repos.  GitHub, as always, has an awesome article on the difference: https://help.github.com/articles/what-s-the-difference-between-user-and-organization-accounts/

Hope this clears things up.

**Comment by n1k0** [comment]
Yeah, also this project is yours guys; there's no point to keep it under my name, especially since I don't have the time to contribute. Moving it to its own org will reflect that this is an entirely community driven project.

**Comment by mickaelandrieu** [comment]
@n1k0 any chance to see you again on this project?  :(  what did you expect for 2.0?

**Comment by n1k0** [comment]
> what did you expect for 2.0?

Two important things:

- Get rid of the testing framework; there are many better out there;
- Drive casper from nodejs directly; every single person I met in person asked me for it.

The first one is rather trivial if you accept you explode BC.

The second one is super complicated, as phantom and node won't ever share the same event loop, so message passing and serialization everywhere to communicate between them. My early attempts were not very encouraging, but I'm pretty sure there should be an efficient way...

**Comment by BIGjuevos** [comment]
> Get rid of the testing framework; there are many better out there

- Would it be to our advantage to write our own mocha/chai/etc... drivers?  It seems like your giving the community a high bar to have to jump if we just drop it.  Right now you get testing for free.  I feel that that is something worth keeping.  Even if we decide to do an optional driver system (kind of what yeoman does with generators).
- Luckily when going between major versions, you are allowed to break BC.

> Drive casper from nodejs directly; every single person I met in person asked me for it.

- Newer versions of node seem to be a bit more viable for doing something like this.  I'd imagine that your going to encounter async callback hell by trying to do synchronous things in an async environment.  That would probably be the largest share of bugs.  "Help, I can't get asyncXYZ() from node when using casper.syncThing()"

**Comment by n1k0** [comment]
These are just ideas and feedback I had back in the days when casper was not as "popular" as today. 

And just to be clear I'm not saying that's what the path to 2.0 should look like in any way :)

**Comment by BIGjuevos** [comment]
> I've just added you guys as contributors to the casper org. Please tell me if you have access to whatever you need for setting up everything.

@n1k0 It seems the best route forward would be to move the repository to the casperjs organization.  GitHub will automatically forward everything, as long as you don't create a repo named casperjs under your account again (That'll remove the redirect).  But from what I can tell, it moves all issues, stories, wiki, and forwards everything.

Moving it this way would give us the time to be able to change all of the links to point to the org based repo, TravisCI, ReadTheDocs, etc...

Once we've got everything pointing to the new location, you can fork again and not risk blowing things up!

It seems to be just a few clicks of the mouse for you.
1. Delete casperjs/casperjs (or rename to like casperjs/casperjs-defunct)
2. Move n1k0/casperjs to casperjs/casperjs

**Comment by n1k0** [comment]
> Moving repository to casperjs/casperjs. This may take a few minutes.

It worked. Now, celebrate :)

**Comment by mickaelandrieu** [comment]
@n1k0 any chance to get more rights on the organization ? I cant create repositories for instance, or ban trolls (ie flamers), I want to be sure we will be able to maintain this project even if one of us stay alone.

Also, I'd like to post some tweets using @CasperJs official account (only for release or relevants new features), any chance to share this account ? :)

**Comment by BIGjuevos** [comment]
We're in the new org.  Closing this.  The 2.0 stuff should go into #1524

**Comment by n1k0** [comment]
> Any chance to get more rights on the organization ?

@mickaelandrieu I've just tweaked the default permissions for members, is it okay now?

> Also, I'd like to post some tweets using @CasperJs

Sure, I'll send you access details by email.

**Comment by mickaelandrieu** [comment]
@n1k0 yes, thank you and thank you :)

**Comment by BIGjuevos** [comment]
Looking to clean things up, make everything a bit easier to manage and have a clear vision of what we need to do to hit 1.2 and track towards 2.0.

I would like to do the following things:
1. Close any issue from 2014 or before.
2. Close any obviously stale PR.
3. Close any PR that will be obsoleted by plans that will be covered by v2.

Thumbs up/down on this will be enough of a signal for me.

**Comment by BIGjuevos** [comment]
Side note, thanks @n1k0 for facilitating all of this!

**Comment by n1k0** [comment]
@BIGjuevos thank *you* for shaking the tree lately ;)

**Comment by paazmaya** [comment]
Great to see @casperjs/casperjs!

**Comment by istr** [comment]
@n1k0 @BIGjuevos Thanks for making the transition possible.

@n1k0 It would be great if you could add at least https://www.npmjs.com/~mickaelandrieu to the list of npm maintainers, so we have a little bit more backing there, too. Lots of people seem to prefer the installation via npm and it would be good to have a handful of people being able to perform a full release cycle. Thank you!

**Comment by istr** [comment]
@BIGjuevos 

> Close any issue from 2014 or before.

Maybe let us be a bit picky and retain at least the feature requests that we still deem valuable and the obvious / qualified bug reports.

**Comment by n1k0** [comment]
@istr I'm confused as @mickaelandrieu is already listed as a package maintainer atm.

**Comment by istr** [comment]
> I'm confused as @mickaelandrieu is already listed as a package maintainer atm.

@n1k0 Oh, sorry for confusion -- this is a quirk in the npmjs UI. I tried to add him, but nothing changed and there was no means of confirmation, so I assumed that the operation failed because I was not allowed to add him. Sorry for the noise...

**Comment by BIGjuevos** [comment]
@n1k0 I've setup a slack for the community to utilize and I want to get us a nice pretty domain setup for us at http://slack.casperjs.org that should point to http://ryannull.com:3000 (which is a slackin app that allows anyone to self invite).

Should we pull some DNS trickery by using a masquerade? Or would you have another preference to do?  Also, feel free to come and join us on the slack.

**Comment by BIGjuevos** [comment]
General update on the cleanup.  I took a lot of time today and closed almost 100 issues that were from before a year ago.  I only closed things I had high confidence on.  Our total open issue count is now under 200.  At a future point, I'll go through this past year as well and clear out any stragglers.
