### ISSUE TITLE
Bug Loading page with phantomJS and SlimerJS

### ISSUE THREAD

**Issue by jefleponot** [casperjs/casperjs#1531]
Laurent Jouanneau @laurentj has added Support of webpage.onResourceTimeout

FOR PR #1446

(Commits on Mar 31, 2016) for SLIMERJS 0.9.7. And it works :-)
So I will redo PR when CasperJS will add in Travis Test the next SlimerJS stable version.

Maybe it's better to fix the bug from browser versions that address the event requestTimeout.
any idea @istr , @BIGjuevos, @mickaelandrieu ?

**Comment by istr** [comment]
> So I will redo PR when CasperJS will add in Travis Test the next SlimerJS stable version.

Ok. The only show stopper for 0.9.7 as far as I remember is breaking of coffescript.

We should consider to drop mentioning coffescript for the 2.0 series.

**Comment by jefleponot** [comment]
There are many tools to convert Javascript in Coffescript and the opposite. 
I agree with @entrptaher here when he says that CasperJS don't have to do all and anything which is not support natively in a web browser.

But we can always write a documentation to migrate
or/and propose an alternative solution using "extras/coffee-script.js" library.

I never use Ruby or CoffeScript but it seams not to be difficult to do it :baby:

**Comment by jefleponot** [comment]
@istr, one PR for you #1536

**Comment by kensoh** [comment]
Closing this as the PR is closed due to CS being out-of-scope.
