### ISSUE TITLE
 first study casperjs,run my demo,but  xunit xml has no testcase,why?

### ISSUE THREAD

**Issue by firmlybelieve** [casperjs/casperjs#1535]
```js
casper.test.begin('Study', 1, function suite(test) {
    casper.start("https://github.com/n1k0/casperjs", function() {
        test.assertTitle("GitHub - n1k0/casperjs: Navigation scripting & testing utility for PhantomJS and SlimerJS", "verify title");
	});
    casper.run(function() {
        test.done();
    });
});
```

runcommond: casperjs test demo.js --xunit=log.xml
Test file: demo.js
# Study
PASS Study (1 test)
PASS verify title
PASS 1 test executed in 9.038s, 1 passed, 0 failed, 0 dubious, 0 skipped.

but log.xml content is:
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE casperjs PUBLIC "-//CasperJS//XUnit Test Results" "testsuites"><testsuites/>

I used phantomjs 1.9.8
Trouble to help me, I was a rookie.

**Comment by BIGjuevos** [comment]
What version on CasperJS are you using?

**Comment by eddiesholl** [comment]
The recent commit at https://github.com/casperjs/casperjs/commit/3742e14637363fa86eacc0c514d20834decd0dab seems to have broken the xunit output. No one calls getXML() anymore :(

**Comment by firmlybelieve** [comment]
@eddiesholl ,Thank you very much.
Back to the old version,It works normally.

**Comment by mickaelandrieu** [comment]
@

**Comment by BIGjuevos** [comment]
Probably my fault.  I'll take a look.

**Comment by BIGjuevos** [comment]
I've got a PR open to fix this.  Sorry about the inconvenience.

**Comment by istr** [comment]
> I've got a PR open to fix this. Sorry about the inconvenience.

We should add some test for the ```--xunit``` flag there.
