### ISSUE TITLE
Feature request: Using clickLabel for non-first occurrence of label

### ISSUE THREAD

**Issue by CharlesBelov** [casperjs/casperjs#1540]
I'm execuiting casperjs throuugh phantomjs form wraith. My code

```
module.exports = function (casper, ready) {
    // test interaction on the page
    casper.wait(2000, function() {
        casper.clickLabel('Reports','a');
        casper.wait(500);
        ready();
    });
}
```

selects the first link occurence of "Reports" on the page. Unfortunately, I need the second link occurrence. 

It would be nice if CasperJS provided a way to use clickLabel() for a non-first-occurence in the page. Possibilities might include replacing
`clickLabel(String label[, String tag])`
wtih one of the following:

```
/* use selector in place of tag */
clickLabel(String label[, String selector])

/* optional parameter to choose 2nd, etc., matching label, skip 0 or more */
clickLabel(String label[, String tag[, Integer skipCount]])

/* optional parameter to choose 2nd, etc., matching label, choose nth */
clickLabel(String label[, String tag[, Integer sequenceCount]])

/* optional parameter to choose first matching string of type tag within selector */
clickLabel(String label[, String tag[, String selector]])
```

For a page with the following occurrences of Reports within the test page:
1. `<li class="nav-title"><a href="/about-sfmta/reports">Reports</a></li>`
2. `<ul class="nav nav-tabs"> ... <li><a href="#reports" data-toggle="tab" onClick="ga('send', 'event', { eventCategory: 'Unit', eventAction: 'Click', eventLabel: 'Reports'});">Reports</a></li>`
3. `<div class="tab-pane" id="reports">
   <h4>Reports</h4>`

where my intended target is item 2, this would play out as:

```
/* use selector in place of tag */
casper.clickLabel("Reports", ".nav-tabs a")

/* optional parameter to choose 2nd, etc., matching label, skip 0 or more */
casper.clickLabel("Reports", "a", 1)

/* optional parameter to choose 2nd, etc., matching label, choose nth */
casper.clickLabel("Reports", "a", 2)

/* optional parameter to choose first matching string of type tag within selector */
casper.clickLabel("Reports", "a", ".nav-tabs")
```

**Comment by BIGjuevos** [comment]
If I understand the feature request properly. Could you just:

    casper.click('label.class:nth-type-of(2)')

This should be possible with CSS selectors. 

Can you let me know if this solves your problem as well?

**Comment by CharlesBelov** [comment]
Thank you. I'm actually shooting for the label "Reports" on an anchor tag inside the third list item within an unordered list of class nav-tabs, so my code was

```
module.exports = function (casper, ready) {
    // test interaction on the page
    casper.wait(2000, function() {
        casper.click('ul.nav-tabs li:nth-type-of(4) a');
        casper.wait(500);
        ready();
    });
}```

Casper appears to have not returned "ready" as wraith did not create a snapshot.

I also tried, to see if I could get casperjs to tell me what the error was, to no avail:

```
module.exports = function (casper, ready) {
  casper.on("page.error", function(msg, trace) {
    casper.echo("Error:    " + msg, "ERROR");
    casper.echo("file:     " + trace[0].file, "WARNING");
    casper.echo("line:     " + trace[0].line, "WARNING");
    casper.echo("function: " + trace[0]["function"], "WARNING");
    errors.push(msg);
  });


  // test interaction on the page
  casper.wait(2000, function() {
      casper.click('ul.nav-tabs li:nth-type-of(4) a');
      casper.wait(500);
      ready();
  });
}
```

The following code, involving a non-repeating label, works just fine, so I know it's not just my setup or environment.

```
module.exports = function (casper, ready) {
    // test interaction on the page
    casper.wait(2000, function() {
        casper.clickLabel('Members','a');
        casper.wait(500);
        ready();
    });
}
```

**Comment by BIGjuevos** [comment]
Do you have some sample html that is a minimal use case so I can try out your problem?  I want to understand your use case better.  See if it is possible with our current API. 

Also,  feel free to put up a PR that we can discuss. We love co tributes a from users.

**Comment by CharlesBelov** [comment]
The following also provides no output of any kind:

```
module.exports = function (casper, ready) {
    // test interaction on the page
    casper.wait(2000, function() {
        casper.click('ul.nav-tabs li:nth-type-of(2) a') or die("That did not work well.", 1);
        casper.wait(500);
        ready();
    });
}
```

**Comment by CharlesBelov** [comment]
Oops, posts cross. I'll try to come up with some minimal HTML and will post it. It probably won't be today.

**Comment by BIGjuevos** [comment]
Whenever you get a chance. Just try to isolate this down to the smallest use case. 

I look forward to your response.

**Comment by kensoh** [comment]
@CharlesBelov bumping this up. I'm a CasperJS user for couple of years.

**Comment by kensoh** [comment]
Closing this as there's no response for a long while. But do reopen if anything!
