### ISSUE TITLE
this.page.uploadFile does not verify whether file exists

### ISSUE THREAD

**Issue by stefanv** [casperjs/casperjs#1544]
The call succeeds, but this can cause very strange errors in the backend.  E.g., we saw this as 400 errors with recv() interrupted.

**Comment by kensoh** [comment]
Thanks @stefanv for raising this! This looks like an inherent method from PhantomJS. Not sure if this is already fixed now or if additional checks should be made from CasperJS. Bumping this up.

**Comment by kensoh** [comment]
Copying maintainer @jefleponot and closing this for now as this directly inherits from PhantomJS I believe. And with the 2k open issues not sure if it can be addressed for now. Thanks @stefanv for raising this and do reopen if anything!
