### ISSUE TITLE
waitForResource how to set multi resource url

### ISSUE THREAD

**Issue by Awakening-j** [casperjs/casperjs#1547]
waitForResource how to set multi resource url, I need to waiting for 2 resource requested  
BTW, what is the unit of ` waitForResource(String|Function|RegExp testFx[, Function then, Function onTimeout, Number timeout])`, is it 'ms'?

**Comment by istr** [comment]
Just make two subsequent calls to wait for the resources. The function will call the success function immediately if the resource exists (it does not trigger a load, however). So in most cases the second call will return immediately / very fast if the two resources are fetched in parallel and/or already finished loading.

Timeout is in milliseconds, see  https://github.com/casperjs/casperjs/blob/master/modules/casper.js#L2208
