### ISSUE TITLE
Best way to re-capture when failed in any error

### ISSUE THREAD

**Issue by brucejcw** [casperjs/casperjs#1549]
```
casper.on 'error', (msg, backtrace)->
    casper.echo("error: #{msg}");
    how to do doCapture here? missing arguments
```

```
doCapture = (self, url, view)->
    self.thenOpen url, ()->
        this.waitForResource text/regex/func, onReceived, onTimeout, timeout number
    onTimeout = ()->
         doCapture(self, url, view)
```

```
casper.start().each views, (self, view) ->
   .......
   doCapture self, url, view
```

I'm using [waitForResource](http://docs.casperjs.org/en/latest/modules/casper.html#waitforresource) function to capture.
Thanks for the [onTimeout](http://docs.casperjs.org/en/latest/modules/casper.html#waitforresource) function, timeout and romote js error will be caught by [onTimeout](http://docs.casperjs.org/en/latest/modules/casper.html#waitforresource), so I can redo capture, but one situation is not `CasperError: No element matching selector found: .chart`, and it will be caught by `casper.on 'error'`, but in this situation, I lost all the params from `doCapture`, so How can I redo capture? and what is the best way to do re-capture?  

Another question is this error will stop program, so capser will exit, how can I catch this exception

**Comment by Awakening-j** [comment]
One more question:  
when I manage `onTimeout` function, I can't get any info about the error  
```
this.waitForResource (resource)->
	return resource.url.indexOf...
, ()->
	...
, (a, b, c, d)->
	console.log a
	console.log JSON.stringify(b)
	console.log c
	console.log d
```  
<img width="505" alt="2016-04-21 21 23 44" src="https://cloud.githubusercontent.com/assets/8085088/14710295/64a33210-0807-11e6-8690-05724b48a0f1.png">  
How to get the error info like in the `casper.on 'page.error'`

**Comment by Awakening-j** [comment]
@istr Any idea about this ?

**Comment by Awakening-j** [comment]
+1

**Comment by Awakening-j** [comment]
anyone could help?

**Comment by kensoh** [comment]
Hi @brucejcw it looks like you want to keep checking for the resource. Would it work if you change the waitTimeout option directly to a very large number? So that script will keep waiting until that resource appears. I'm a CasperJS user just browsing through the issues here.

**Comment by kensoh** [comment]
Hi @brucejcw closing this issue for now but do reopen if it is still an issue to you and there is something we can assist on! I'm on GitHub most days but reachable on ken@tebel.org if anything.
