### ISSUE TITLE
Maintenance and evolution of the Maven plugin : casperjs-runner-maven-plugin

### ISSUE THREAD

**Issue by bguerin** [casperjs/casperjs#1551]
Hello CasperJS !

I would like to offer my help to maintain the maven plugin of this great tool.
The organisation repository is here :
https://github.com/casperjs/casperjs-runner-maven-plugin

It is based on this one, on which I worked a lot :
https://github.com/linsolas/casperjs-runner-maven-plugin

And I have an even more up to date clone (testing and documentation generation with travis-ci) :
https://github.com/netceler/casperjs-runner-maven-plugin

I am wondering how I could report all the changes on my clone into the reference one, aka the one in the organization.
I am ready to help over the time, not just a one shot thing and goodbye.

Thanks for answers !

**Comment by istr** [comment]
Hi @bguerin. Thanks a lot for the offer to help, this is highly welcome.

As an organisation repo already exists and you seem to have a more recent/active version it could be best to get the "official" casperjs version in sync with yours with a single, large PR.

After that we could start to continue improving on that using regular PRs from your repo (currently all CasperJS maintainers have private clones where they prepare their respective PRs).

@BIGjuevos @mickaelandrieu thoughts, comments?

**Comment by mickaelandrieu** [comment]
Totaly agree ! Welcome @bguerin :-) we can probably give access only to this repository, right ?

**Comment by BIGjuevos** [comment]
Any help is always welcome!  Open Source wouldn't work otherwise.

If would be good to get the repos in sync.  It looks like the one from linsolas is abandoned (last commit 2 years ago).  It would be great for the people using it to keep ours up to date.

Let's make it happen.

**Comment by BIGjuevos** [comment]
Looks like I don't have permissions to make the change to get him added.  Looks like @n1k0 may need to tweak some things: https://help.github.com/articles/repository-permission-levels-for-an-organization/

**Comment by n1k0** [comment]
@BIGjuevos all org members now have admin privileges. Be careful ;)

**Comment by BIGjuevos** [comment]
@n1k0 I've setup a new team (https://github.com/orgs/casperjs/teams/maven-supporter), looks like he just needs to be added to the organization on the new team I setup.  Looks like another thing I don't have access to.

**Comment by bguerin** [comment]
Hi,

Great ! many thanks !
Ok to sync the organization repo from mine with one large PR
Of course, I only need access to this repo.
And after, I will have to look how to deploy new version of the plugin in Maven central ...

**Comment by BIGjuevos** [comment]
Turns out, I can add you directly.  @bguerin, welcome to the family, you are now a collaborator over at: https://github.com/casperjs/casperjs-runner-maven-plugin

We can't wait to see what you do.

PS - I'd still like to have him added via the team.  It'll make managing permissions easier.

**Comment by n1k0** [comment]
@BIGjuevos just added @bguerin to that team. The only way for you to be able to manage people within teams is to become an org owner it seems, which I'm finding slightly overkill.

If we keep struggling with ACLs and stuff that's probably what will happen eventually though.

**Comment by bguerin** [comment]
I am preparing the PR to sync casperjs/casperjs-runner-maven-plugin with my fork.
I will fix path and identifier to match casperjs infrastructure, instead of linsolas one.

Juste one question : for issues on this plugin, where do you prefer them to be opened, on a new issues tracker on the plugin repository, or here, on the main _casperjs_ repository ?

**Comment by BIGjuevos** [comment]
@bguerin I've activated the Issue Tracker for that repository.  Please maintain the issues for the maven plugin in that directory.

**Comment by bguerin** [comment]
Thanks @BIGjuevos , will do it !

**Comment by bguerin** [comment]
PR submitted, I assume I will accept it myself ?
With it, continuous integration through travis-ci is coming (already configured)
And travis-ci build maven site, which will be available via GitHub pages : http://casperjs.github.io/casperjs-runner-maven-plugin/

ok for you ?
