### ISSUE TITLE
Casper doesn't pass firefox cli args to Slimer

### ISSUE THREAD

**Issue by NeonPaul** [casperjs/casperjs#1559]
Slimerjs allows certain [firefox-specific args](https://docs.slimerjs.org/current/configuration.html#command-line-options) to be passed on the command line. Namely these are:

> `-P name` - Use the indicated profile
> `-CreateProfile name` - Create a new profile
> `-profile path` - Use the given directory as a profile

Casper tries to pass these on but because the arg name and value are separated by a _space_ (I'm launching using NodeJS's `child_process.spawn`) rather than an _equals_ character (see [bin/casperjs line 116](https://github.com/casperjs/casperjs/blob/master/bin/casperjs#L116)), it fails.

The workaround solution I have found for the `-P` argument is only to use a profile named `test`, passing `-P` and `test` as two separate arguments (with an additional `test` argument to activate the testing library).

(NB: something to watch out for is that slimer expects the arg name and value to actually be separate arguments - e.g. `"slimerjs" "-P" "myProfile" "myScript.js"` - [issue filed here](https://github.com/laurentj/slimerjs/issues/463))

**Comment by BIGjuevos** [comment]
So, there was a pull request #1507 that supposedly solved this issue.

What versions of SlimerJS and CasperJS are you using.  This is in version 1.1.0 and above.  Can you try that version and let us know how it goes?

**Comment by NeonPaul** [comment]
@BIGjuevos We are using `casperjs@1.1.0` and `slimerjs@0.9.6`

**Comment by hugsbrugs** [comment]
Yes it's really anoying not being able to launch slimerjs from casperjs with this Profile option : 
```
casperjs --debug=true --engine=slimerjs -P MyProfile my-script.js
```
launches the browser to let me choose my profile and then quit : 
```
(process:7337): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
JavaScript warning: resource://slimerjs/slUtils.jsm, line 155: JavaScript 1.7's let blocks are deprecated
JavaScript error: jar:file:///usr/local/lib/node_modules/slimerjs/lib/slimer/xulrunner/omni.ja!/components/XULStore.js, line 66: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIProperties.get]

(process:7337): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
JavaScript strict warning: resource://gre/modules/GMPUtils.jsm, line 92: ReferenceError: reference to undefined property this.KEY_LOG_BASE
JavaScript warning: resource://slimerjs/slUtils.jsm, line 155: JavaScript 1.7's let blocks are deprecated
unknown option --casper-path=/usr/local/lib/node_modules/casperjs
2016-06-10T10:48:15.180Z [DEBUG] Gecko version: 38.0.5
2016-06-10T10:48:15.180Z [DEBUG] script args: --casper-path=/usr/local/lib/node_modules/casperjs --cli MyProfile my-script.js
2016-06-10T10:48:15.180Z [DEBUG] Configuration: debug=true
2016-06-10T10:48:15.180Z [DEBUG] Configuration: Script=unknown??
```

**Comment by clochix** [comment]
I was able to start SlimerJS with a custom profile using the following syntax:
```
slimerjs -P <profile> $CASPER_PATH/bin/bootstrap.js --casper-path=$CASPER_PATH --cli test script.js
```
(replace `$CASPER_PATH` with the path where Casper is installed.

**Comment by kensoh** [comment]
Joining this thread, I had issue using the profile option to invoke SlimerJS (to basically run with cookie / saved session). Have noted @clochix's method to try next time facing the scenario.

**Comment by kensoh** [comment]
Closing this for now as the PR has been merged for a few months. Though Windows portion not yet done I think.. Do reopen if anything!

**Comment by kensoh** [comment]
Also copying @jefleponot
