### ISSUE TITLE
Please make __utils__.sendAJAX support custom headers

### ISSUE THREAD

**Issue by Sayalic0** [casperjs/casperjs#1560]
That's very useful, and every time I need it, I will just modify the source code of `__utils__.sendAJAX` to support custom headers. 

There is a [StackOverflow post](http://stackoverflow.com/questions/24268647/sending-http-headers-in-form-submission-casperjs) which is about the custom header feature, and one can see it takes dozens lines of code to implement such a feature.

Why I don't just post a pull request? Because I'm a beginner for JavaScript. I think my implementation is dirty, so I post a issue here.

**Comment by paazmaya** [comment]
Would you mind sharing your implementation, even if you feel it is "dirty" ?

**Comment by Sayalic0** [comment]
You may see Pull Request #1562

**Comment by Sayalic0** [comment]
Travis-CI build failed for just 1 test case, but I think my code has nothing to do with `Casper.base64encode()`. I read the test code, it's just retrieve a local image file and encode it to base64 string. But in my code, it returns a zero length string instead of 6410 as expected. I have no idea to fix that, so could you please give me some advices?

Failed test logs:
```
FAIL Casper.base64encode() can retrieve base64 contents
#    type: assertEquals
#    file: /home/travis/build/casperjs/casperjs/tests/suites/casper/encode.js:9
#    code: test.assertEquals(image.length, 6160, 'Casper.base64encode() can retrieve base64 contents');
#    subject: 0
#    expected: 6160
```

**Comment by kensoh** [comment]
Hi @Sayalic0 bumping this up :)

**Comment by kensoh** [comment]
Hi @Sayalic0 I saw that the reference implementation was made, but was it by another user improving on your original implementation? Hmmm...

Want to thank you for your contribution!! Also copying current maintainer Jef @jefleponot for info. Closing this issue for now as there are no outstanding actions I think. But do give a shout if anything!
