### ISSUE TITLE
Bug/Usability Casper Test unrecognized syntax: for(.. of ..)

### ISSUE THREAD

**Issue by riyadshauk** [casperjs/casperjs#1565]
When iterating over maps, we should be able to use "of" in a for-loop in JavaScript, as seen in [these MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map#Iterating_Maps_with_for..of).

`for (var [key, value] of myMap.entries()) { poof; }` doesn't work when running `test test/testIncludingMyFile.js --includes=myFile.js`.

Error message preventing my Casper test from running:
```
FAIL SyntaxError: Expected token 'in'
#    type: error
#    subject: false
#    error: "SyntaxError: Expected token 'in'"
#    stack: in injectJs() in phantomjs://code/myFile.js:70
in _forEachInclude() in phantomjs://platform/tester.js:1594
in forEach() in :0
in runSuites() in phantomjs://platform/tester.js:1593
Test file: test/testIncludingMyFile.js    
```

Line 70 of myFile.js:
        `for(var key of myMap.keys()) {`

(variables and filenames obviously generalized here lol)

**Comment by riyadshauk** [comment]
UPDATE to Issue (probably supersedes the original issue in priority):

Upon taking out the for(.. of..) loop and using a forEach instead, just to get Casper to work with my code (kind of bad for usability, right?), I realized the following:

It appears [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) isn't recognized in CasperJS. Why is that? Should it not be recognized?

Error message:
FAIL ReferenceError: Can't find variable: Map
```
#    type: uncaughtError
#    file: test/testBackgroundScript.js:20
#    error: Can't find variable: Map
#           phantomjs://code/testMyFile.js:20:30
#           runStep@phantomjs://platform/casper.js:1577:31
#           checkStep@phantomjs://platform/casper.js:404:28
#    stack: not provided
```

Line 20 of testMyFile.js:
      `var myMap = new Map();`

**Comment by riyadshauk** [comment]
I just realized that the versions might be useful to know:
```
$ casperjs --version
1.1.0-beta5
$ phantomjs --version
2.1.1
```

**Comment by mickaelandrieu** [comment]
Hi,

``Map`` is not supported natively by phantomjs (https://kangax.github.io/compat-table/es6/#phantom), you may need to transpile your code using babel.

Mickaël

**Comment by BIGjuevos** [comment]
Closing this issue as it looks to be a compatibility issue with PhantomJS and ES6.  Please feel free to re-open if new information comes to light.

Null
