### ISSUE TITLE
'click' documentation issue

### ISSUE THREAD

**Issue by ianchanning** [casperjs/casperjs#1566]
I'm using casper js v1.1.1 with phantom js v2.1.1 on Linux mint.

**Edit: I've found the documentation now and submitted pull request https://github.com/casperjs/casperjs/issues/1567 for this now. I would still suggest that the casperjs-docs repo be removed or changed to point at the correct docs.**

There is a problem with the ['click' sphinx documentation](http://docs.casperjs.org/en/latest/modules/casper.html#click). I'm adding it here as there doesn't appear to be issues that I can add to https://github.com/casperjs/casperjs-docs.

This is connected to #1532 as it is one of the main examples given on the home page which should be a self contained script that you can copy and paste which works.

Currently the click documentation has the following example:

``` js
casper.start('http://google.fr/');

casper.thenEvaluate(function(term) {
    document.querySelector('input[name="q"]').setAttribute('value', term);
    document.querySelector('form[name="f"]').submit();
}, 'CasperJS');

casper.then(function() {
    // Click on 1st result link
    this.click('h3.r a');
});

casper.then(function() {
    // Click on 1st result link
    this.click('h3.r a',10,10);
});

casper.then(function() {
    // Click on 1st result link
    this.click('h3.r a',"50%","50%");
});


casper.then(function() {
    console.log('clicked ok, new location is ' + this.getCurrentUrl());
});

casper.run();
```

The problem with that is that you can't copy and paste it in to a file and run it straight off.

First you need `var casper = require('casper').create();`, which is easy enough if you've read other examples.

However then it just produces no output and no errors and it's not clear why. 

I tracked it down to the fact that the first `this.click('h3.r a');` is successful but then the later clicks aren't on the assumed google page and so crash, preventing any further output - so the last `console.log` never gets run.

Bizarrely the 'latest' docs for ['click' in github](https://github.com/casperjs/casperjs-docs/blob/master/modules/casper.rst#click), would actually work, it just looks like someone has added two extra examples of how to use click that break the code.

``` js
casper.start('http://google.fr/');

casper.thenEvaluate(function(term) {
    document.querySelector('input[name="q"]').setAttribute('value', term);
    document.querySelector('form[name="f"]').submit();
}, { term: 'CasperJS' });

casper.then(function() {
    // Click on 1st result link
    this.click('h3.r a');
});

casper.then(function() {
    console.log('clicked ok, new location is ' + this.getCurrentUrl());
});

casper.run();
```
1. Ideally we should be able to submit issues directly to the docs
2. Why is the github docs repo out of sync with the live docs?
3. Please could we fix the example so that it is directly runnable and ideally all examples linked from the home page should be made so that they are self contained scripts that are directly runnable - it should only require the first `require` / `create` statement to be added.
4. Please could you fix the example so that it doesn't crash, either by only having the one click example or else my suggestion would be to include `back` calls, but then the example becomes quite long:

``` js
var casper = require('casper').create();

var logClick = function() {
    console.log('clicked ok, new location is ' + this.getCurrentUrl());
};

var logBack = function() {
    console.log('clicked back, location is ' + this.getCurrentUrl());
};

casper.start('http://google.fr/');

casper.thenEvaluate(function(term) {
    document.querySelector('input[name="q"]').setAttribute('value', term);
    document.querySelector('form[name="f"]').submit();
}, 'CasperJS');

casper.then(function() {
    // Click on 1st result link
    this.click('h3.r a');
});

casper.then(logClick);

casper.back();

casper.then(logBack);

casper.then(function() {
    // Click on 1st result link
    this.click('h3.r a',10,10);
});

casper.then(logClick);

casper.back();

casper.then(logBack);

casper.then(function() {
    // Click on 1st result link
    this.click('h3.r a',"50%","50%");
});

casper.then(logClick);

casper.run();
```

**Comment by ianchanning** [comment]
Ok, I figured out why the documentation is different now. I should have been looking at the [master branch][1]. I had read the contribution document, but it's not obvious that by default you're not on the master branch.

It's also further confusing that you have a separate repo for casper docs. Could I suggest deleting that repo, or removing everything from there and pointing people to the master branch.

  [1]: https://github.com/casperjs/casperjs/blob/gh-pages/README.md#casperjs-documentation

**Comment by istr** [comment]
@ianchanning Thank you for the very detailed description of what is going wrong with documentation on an abstract level. As we generally seem to be in a clean-up and consolidation phase in this project right now, I invite @BIGjuevos and @mickaelandrieu to discuss if it could make sense to drop the separate repo. Probably this is only a legacy that should get cleaned.

**Comment by BIGjuevos** [comment]
I'm on board with killing that repo.  It is confusing unless you are familiar with how our docs are generated.

**Comment by kensoh** [comment]
Bumping up this thread and copying @jefleponot

**Comment by kensoh** [comment]
Archiving issue using **ARCHIVE** label as CasperJS, like PhantomJS, is not actively maintained for now.
