### ISSUE TITLE
Wait for multiple alternative selectors with CasperJS

### ISSUE THREAD

**Issue by slavafomin** [casperjs/casperjs#1570]
Hello!

Thank you for this great library!

However, is it possible to wait for multiple alternative selectors with it?

From [my question](http://stackoverflow.com/questions/36989132/wait-for-multiple-alternative-selectors-with-casperjs) on SO:

> I have an application, that can react differently to the actions of my CasperJS script, so I need to wait for different selectors simultaneously and act according to the first matched selector. However, it looks like CasperJS can only wait for one selector at a time.
>
> How do I wait for different reactions and divert execution of the script to the different branches?

Thanks!

**Comment by istr** [comment]
You might want to try to wait for the combined selectors (CSS comma-separated list act as a logical `or`) and then check for each selector if it exists in the page and branch, along the lines of this (untested) pseudo-code:

```js
var selectors = [
  '.my.first .fancy .selector',
  '.boring'
];
casper.waitForSelector(selectors.join(', '), function(){
  var idx;
  for (idx = 0; idx < selectors.length; ++idx) {
    if (casper.exists(selectors[idx])) {
      doSomething();
    }
  }
});

**Comment by slavafomin** [comment]
Thanks @istr for the suggestion, it's a clever workaround! )

Maybe CasperJS should provide an API function for this also?

**Comment by istr** [comment]
> Maybe CasperJS should provide an API function for this also?

Maybe, if someone is willing to create a full-fledged PR for this feature. @BIGjuevos @paazmaya @mickaelandrieu 

Anybody who wants to implement this or thinks it is a good feature to have, feel free to re-open.

**Comment by mepard** [comment]
That technique would only work with all CSS selectors, without any XPath selectors in the mix.

**Comment by istr** [comment]
> That technique would only work with all CSS selectors, without any XPath selectors in the mix.

Right, but XPath has a logical `or`, too. If you can tell if it is XPath or CSS you're using that could be catered for using a different separator in the `join()` call (`|` afaik). Mixed XPath/CSS selectors in a single call would not work (at least I do not have an idea how to make that work with the simple technique mentioned).
