### ISSUE TITLE
Casperjs Sticky session - working behind loadbalancer/proxy

### ISSUE THREAD

**Issue by alebeta90** [casperjs/casperjs#1571]
i have a proxy loadbalancer which send the request to 3 proxy servers and then I can reach the web application in the other end. The thing is that depending on the proxy server i use to i have a different answer for the application and i want make casper use for each session one proxy server. I already configure sticky session on the load balancer, but i think the sticky session is not enabled in casper, them if i make 3 request, this requests use different proxys, and i want use one per session, but i need sticky session enable in casperjs.

**Comment by BIGjuevos** [comment]
Does the problem also appear if you write a script directly for PhantomJS?

**Comment by alebeta90** [comment]
Hello @BIGjuevos i already check and the loadbalancer was tacking the session from one of my cookies but the problem relay in the loadbalancer because the expire time of the cookie. My problem was solved in the server side.

Thanks for the quick answer.

have a nice day.

**Comment by istr** [comment]
Closing as @alebeta90 marked it resolved.
