### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by jonataswalker** [casperjs/casperjs#1572]
Hi guys,

I'm trying to add Travis CI to [this project](https://github.com/jonataswalker/ol3-geocoder) and everything goes fine except tests that require a webserver &mdash; `require('webserver').create()`.

[Travis report.](https://travis-ci.org/jonataswalker/ol3-geocoder/builds/128209869#L365)

My `.travis.yml` is pretty like the one used here in casperjs.
```
script:
  - xvfb-run -a make ci
```
I'm aware this is more likely a phantomjs question but I'd like to setup Travis CI like you did.

**Comment by BIGjuevos** [comment]
I'd try to create a simple use case in straight phantomjs and see what it does.

Also, we do have a sample of a server that I know works with phantom > 2.0 and casper >= 1.1 in the [cookbook](http://docs.casperjs.org/en/latest/cookbook.html#creating-a-web-service).

The cookbook may help.  If not, let's discuss further.  Also, someone else may know more than me.

**Comment by jonataswalker** [comment]
Well well, got it working (https://travis-ci.org/jonataswalker/ol3-geocoder). Apparently it was missing Phantom 2.1.1 installation:
```
#.travis.yml
before_install:
  wget https://github.com/BIGjuevos/phantomjs-builds/archive/v2.1.1.tar.gz -O $PWD/travis-phantomjs/v2.1.1.tar.gz
  tar -xf $PWD/travis-phantomjs/v2.1.1.tar.gz -C $PWD/travis-phantomjs
  sudo ln -sf $PWD/travis-phantomjs/phantomjs-builds-2.1.1/bin/phantomjs $(which phantomjs)
```
Thanks @BIGjuevos

**Comment by BIGjuevos** [comment]
No problem.  Thanks for using my phantomjs builds repo as well!
