### ISSUE TITLE
Build bin/casperjs before contributing

### ISSUE THREAD

**Issue by jonataswalker** [casperjs/casperjs#1575]
I didn't find in [Contribution Guide](https://github.com/casperjs/casperjs/blob/master/CONTRIBUTING.md) how to build `bin/casperjs` so I can use it in a script before sending a PR.

**Comment by istr** [comment]
I am not sure what you would like to see there...

`bin/casperjs` is a python script that is shipped in the package, as well as a pre-compiled `mono`-based `bin/casperjs.exe` for windows users. So there is no need to build `bin/casperjs`. If you need to recompile the windows binary (you rarely need to, only for really windows-specific contributions) there is a `compile-dotNET:` target in the `Makefile`.

Please elaborate (best with a PR against the Contribution guide) what you would like to have here as additional information. Thank you.

**Comment by jonataswalker** [comment]
Well, so `bin/casperjs` is not the file I'm looking for. What I'd like to do is: Make some changes, test them (this should be against some built file right?) and then contribute with a PR.

**Comment by istr** [comment]
> (this should be against some built file right?)

No. CasperJS is plain JavaScript, basically. So no "building" involved here.

Basic workflow:
  1. discuss in an issue if the community wants/needs your PR to protect yourself from wasting your time
  2. clone CasperJS repo to your own
  3. create a feature branch
  4. add documentation preferably including a reference to the issue created in 1.
  5. add tests for the bug you are resolving or the feature you are implementing (most often change *.js files in `tests/`, for major added functionality: add new *.js file there)  
   (your new tests should fail at this point!) 
  6. change the CasperJS *.js files (bug-fix or new feature)
  7. run selftest and cli test (`make test`)
  8. if tests pass: push your stuff to github and create PR that refers to the issue in 1.
  9. wait for travis CI to pass the tests on all engines on your PR
  10. if travis CI tests fail, inspect failures and iterate 5. to 9. until travis CI passes
  11. wait for approval or comments from CasperJS team and/or community
  12. react to feedback
    1. changes to PR requested: iterate through 4. to 11., 5. to 11., or 6. to 11. as appropriate
    2. PR approved and merged - done
    3. PR rejected after discussion and consensus - done

Maybe we should add this workflow to the docs. @BIGjuevos @mickaelandrieu

**Comment by jonataswalker** [comment]
@istr A really detailed answer. Many thanks.

This is (for me) done.
