### ISSUE TITLE
Suite test results display before tests are run

### ISSUE THREAD

**Issue by entendu** [casperjs/casperjs#1576]
Using the sample code [here](http://docs.casperjs.org/en/latest/testing.html#browser-tests), incorrect results of the test suite are displayed before the tests are run:

```
$ casperjs test casperjs/google.js 
Test file: casperjs/google.js                                                   
# Google search retrieves 10 or more results
PASS Google search retrieves 10 or more results (5 tests)
PASS google homepage title is the one expected
PASS main form is found
FAIL google title is ok
#    type: assertTitle
#    file: casperjs/google.js:12
#    code: test.assertTitle("casperjs - Recherche Google", "google title is ok");
#    subject: "Google"
#    expected: "casperjs - Recherche Google"
FAIL 3 tests executed in 0.502s, 2 passed, 1 failed, 0 dubious, 0 skipped.      

Details for the 1 failed test:

In casperjs/google.js:12
  Google search retrieves 10 or more results
    assertTitle: google title is ok

```

Notice that `PASS Google search retrieves 10 or more results (5 tests)` is printed before the tests are actually run.

When I update the sample code to use english & pass the tests, the same thing happens:

```
$ casperjs test casperjs/google.js 
Test file: casperjs/google.js                                                   
# Google search retrieves 10 or more results
PASS Google search retrieves 10 or more results (5 tests)
PASS google homepage title is the one expected
PASS main form is found
PASS google title is ok
PASS search term has been submitted
PASS google search for "casperjs" retrieves 10 or more results
PASS 5 tests executed in 1.093s, 5 passed, 0 failed, 0 dubious, 0 skipped.      
```

I noticed this happening on my own test suites and used this sample to verify.

This does NOT happen using the "[cow can moo](http://docs.casperjs.org/en/latest/testing.html#unit-testing)" example:
```
$ casperjs casperjs/cow-test.js
Test file: casperjs/cow-test.js                                                     
# Cow can moo
PASS Subject equals the expected value
PASS Subject is strictly true
PASS Cow can moo (2 tests)
PASS 2 tests executed in 0.026s, 2 passed, 0 failed, 0 dubious, 0 skipped.   
```

Platform: OSX 10.11.4
```
$ phantomjs --version
1.9.8

$ casperjs --version
1.1.0-beta4
```

**Comment by morozgrafix** [comment]
Noticed that as well with `phantomjs 2.1.1` and `casperjs 1.1.1` on `OSX 10.11.4 (15E65`

**Comment by mickaelandrieu** [comment]
@morozgrafix nope the test is not executed before, the first line is the result of your testsuite.
If you don't believe me, just remove the related test or execute the ``casperjs selftest`` command.

But I h

**Comment by morozgrafix** [comment]
Thanks I will dig through my test and see what's going on.

**Comment by morozgrafix** [comment]
@mickaelandrieu i looked into it a little more.
when i run `casperjs selftest` I see the following output (partial snippet below):
```
# waitForText() tests
PASS waitForText() tests (3 tests)
PASS Casper.waitForText() can wait for text
PASS Casper.waitForText() can wait for regexp
PASS Casper.waitForText() can wait for decoded HTML text
```

line `PASS waitForText() tests (3 tests)` shows up before following 3 tests are executed and I think this is the same issue that @entendu has experienced.

same thing happens when I run following example from README:
```
casper.test.begin('a twitter bootstrap dropdown can be opened', 2, function(test) {
    casper.start('http://getbootstrap.com/2.3.2/javascript.html#dropdowns', function() {
        test.assertExists('#navbar-example');
        this.click('#dropdowns .nav-pills .dropdown:last-of-type a.dropdown-toggle');
        this.waitUntilVisible('#dropdowns .nav-pills .open', function() {
            test.pass('Dropdown is open');
        });
    }).run(function() {
        test.done();
    });
});
```

result of running `casperjs test simple_example.js`:
```
Test file: simple_example.js
# a twitter bootstrap dropdown can be opened
PASS a twitter bootstrap dropdown can be opened (2 tests)
PASS Find an element matching: #navbar-example
PASS Dropdown is open
PASS 2 tests executed in 1.476s, 2 passed, 0 failed, 0 dubious, 0 skipped.
```

line `PASS a twitter bootstrap dropdown can be opened (2 tests)` shows up right away before actual tests are executed.

**Comment by morozgrafix** [comment]
Had some more time to dig through this and looks like output has changed between `1.1.0-beta3`and `1.1.0-beta4`. 

Here is what I see when running twitter bootstrap example from my previous comment:
```
$ node_modules/casperjs/bin/casperjs --version
1.1.0-beta3
$ node_modules/casperjs/bin/casperjs test simple_example.js
Test file: simple_example.js
# a twitter bootstrap dropdown can be opened
PASS Find an element matching: #navbar-example
PASS Dropdown is open
PASS 2 tests executed in 1.007s, 2 passed, 0 failed, 0 dubious, 0 skipped.
```
and
```
$ node_modules/casperjs/bin/casperjs --version
1.1.0-beta4
$ node_modules/casperjs/bin/casperjs test simple_example.js
Test file: simple_example.js
# a twitter bootstrap dropdown can be opened
PASS a twitter bootstrap dropdown can be opened (2 tests)
PASS Find an element matching: #navbar-example
PASS Dropdown is open
PASS 2 tests executed in 1.166s, 2 passed, 0 failed, 0 dubious, 0 skipped.
```

both times executed with `phantomjs@1.9.20`

**Comment by mickaelandrieu** [comment]
Ok  it's definitely an issue :)  thanks for your impressive report! 

Now I just need time to figure out what is going on :( if you can fix it it will be very appreciated though 👍

**Comment by morozgrafix** [comment]
sadly I'm very unfamiliar with casperjs code, but I think this line has something to do with it https://github.com/casperjs/casperjs/compare/1.1-beta3...1.1-beta4#diff-1a7fdf5fb5e85e08050e105aa0544c9eR1112 where `if (this.options.concise) {` was changed to `if (!this.options.concise) {`

**Comment by mlalpho** [comment]
I believe this is an order of execution issue (async). Even with `--fail-fast` or calling `casper.exit` from a previous test suite, the execution of `casper.test.begin(...` produces this output when `--concise` is not in use even though the tests within the suite itself do no run. I noticed this as well and reverting the change avoids the excess printout but doesn't solve the real problem. like @morozgrafix, I don't think I'm familiar enough to submit a proper PR to fix this.. at least not yet ;)

**Comment by childen** [comment]
We are experiencing the same problem as @entendu. Afaik the early PASS message is generated as soon as the test.begin callback function returns (next method in begin). Instead it shoud be generated when the test.done() function is called (next method in done).

The bug does not appear in the examples as they call casper.run in the begin functions callback method.

**Comment by mickaelandrieu** [comment]
Merged, thank you !
