### ISSUE TITLE
RPM for CasperJS 1.1.1.

### ISSUE THREAD

**Issue by daniel-lucio** [casperjs/casperjs#1577]
http://inside-out.xyz/technology/rpm-for-casperjs-1-1-1.html

If anyone wants to use it :+1:

**Comment by mickaelandrieu** [comment]
Hi,

I've just contacted the author, let's see what happens.

Thanks for the hint Daniel.

**Comment by mickaelandrieu** [comment]
Reopened as you are the author :D  I'm interested if you want to join the team as RPM maintainer, what do you think ? 

ping @casperjs/contributors

**Comment by BIGjuevos** [comment]
No objections.  It'd be good to have someone responsible for it.  Is this something e can break off into it's own repo?

**Comment by daniel-lucio** [comment]
Please contact me to see what this implies.

**Comment by kensoh** [comment]
Closing this thread and merging to #1669 as the updated RPM package for CentOS there is v1.1.3.
