### ISSUE TITLE
Compatibilities : backward, downward, upward, forward ...

### ISSUE THREAD

**Issue by jefleponot** [casperjs/casperjs#1580]
Hi everybody,

I have a philosophical issue.

Casperjs' new developments allow compatibility with current version of phantomJS and slimerJS and also compatibility with older versions (this is BC) . -- Except orientations like coffee-script  -- : 
That is OK.

But what do you do when SlimerJS or PhantomJS provide in a feature in a current version ? 
1. Must we provide a workaround for older versions so that the functionality can work too when it is possible ?

For instance, multiple file for <input type=file> with webpage.uploadFile and webpage.onFilePicker 
works only since slimerJS 0.10.0 so in travis CI test for slimerJS 0.95

``` yaml
FAIL Evaluated function returns true
#    type: assertEval
#    file: /home/travis/build/jefleponot/casperjs/tests/suites/casper/formfill.js
#    subject: false
#    fn: undefined
#    params: undefined
```

https://travis-ci.org/jefleponot/casperjs/jobs/128851308
1. Must we generate an exception to warn users ?
2. Must we inform in documentation that older versions can't access to method ?

I have this issue for #1446  with webpage.onResourceTimeout

But there are also for
webpage.onLongRunningScript
webpage.stopJavascript
webpage.onRepaintRequested 
...

Big Project like jQuery works with 2 versions : 
- a version for all browsers (with plug-in)
- a version for current browsers

How do you think about that @istr @BIGjuevos @mickaelandrieu ?

Regards 
Jef

**Comment by mickaelandrieu** [comment]
Hi @jefleponot, for me we should provide a support *only* for PhantomJS api (1 & 2).

For instance, slimerjs 0.9.5 have some issues to support `uploadFile`, this is why we can't support it atm.

Mickaël

**Comment by jefleponot** [comment]
Hi @mickaelandrieu,

Here is a more concrete example, I still use 1.9.7 PhantomJS because it is very stable and above all it is very representative of previous web browsers before 2012.

But he has a big problem, it is unable to properly handle the slow queries.

SlimerJS 0.10.0 (firefox > 38) and PhantomJS 2.1.1 makes it perfectly but there are too recent.

Do CasperJS must solve this kind of problem: harmonizing functionality between different versions?

**example** : 

````js
if (phantom.casperEngine === 'slimerjs' && utils.ltVersion(phantom.version, '0.10.0'))) {
        this.checkRequestTimeout = (function (data) {
            var self = data;
            return function(){
                if ((!!this.page.settings.resourceTimeout) && (!isNaN(this.page.settings.resourceTimeout))) {
                    var now = new Date().getTime();
                    for (var i = self.resourcesTime.length-1 ; i >= 0 ; i--) {
                        if (now > self.resourcesTime[i].time + self.page.settings.resourceTimeout) {
                            var request = self.resourcesTime[i];
                           self.resourcesTime.splice(i, 1);
                            request.errorCode = 408;
                            request.errorString = "Request Timeout";
                            request.abort();
                            self.page.onResourceTimeout(request);
                        }
                    }
                }
            };
}
````

jef

**Comment by mickaelandrieu** [comment]
I ... don't know, I'm more for a [CasperJS extension](http://docs.casperjs.org/en/latest/writing_modules.html#writing-casperjs-modules) like this:

```js
// modules/polyfill.js
var casper = require('casper');
casper.prototype.methodToBeHarmonized = function() {
    if (phantom.casperEngine === 'slimerjs' && utils.ltVersion(phantom.version, '0.10.0'))) { /.../ }
};

return casper;
```
```js
var casper = require('./modules/polyfill').create({
    verbose: true,
    logLevel: "debug"
});
```

Sounds crap, but this is the idea: move polyfill code outside of main api. What do you think @jefleponot  ?

**Comment by jefleponot** [comment]
OK.. for a CasperJS extension for Forward Compatibility.
It could be nice to insert this extension into CasperJS main project.
a proposed filename ? which repertory ? ..

**Comment by mickaelandrieu** [comment]
@jefleponot I like `polyfill` but I agree also with something like `forward-compatibility`

the important thing here is to be able to enable this extension when we need it :)

**Comment by paazmaya** [comment]
Perhaps the feature support for different drivers like phantomjs or slimerjs should be done in a progressive enhancement style.
Such as including files from casperjs as per the current driver allows to support.
Then features would be distributed across different files and possibly namespaces, while the support capabilities would be listed in an entry file that includes feature files when needed and possible.

**Comment by kensoh** [comment]
Bumping up this thread for review / discussion..
