### ISSUE TITLE
PhantomJS memory leak issue

### ISSUE THREAD

**Issue by entrptaher** [casperjs/casperjs#1581]
For past two days, I'm having a serious problem. Its probably related to phantomjs, but more debugging shows that the page crashes right after **clientutils** have been loaded. I think someone might find it helpful in near future if it gets fixed.

I got several different crash reports. But I'm certain it's related to memory overload.
## Crash Report 1:

![Noticing the Problem](http://i.imgur.com/T2vh2Nq.png)
## Crash Report 2:

Windows exception 0xc0000005
This is the issue, but on a ubuntu server. https://github.com/ariya/phantomjs/issues/14020
## Possible reasons:
- Memory problem due to setting loadimages to false. https://github.com/ariya/phantomjs/issues/12903
## Tested operating Systems:
- Windows 8.1 x64, Phantomjs 2.1.1, casperjs 1.1.1 : Runs OK!
- Ubuntu 14.04 x64, Phantomjs 2.0.0, casperjs 1.1.1 : Crashes after loading clientutils. (Thought version might cause the problem)
- Ubuntu 14.04 x64, Phantomjs 2.1.1, casperjs 1.1.1 : Crashes after loading clientutils, has no problem after setting loadimages: true.
## Untested but want to test, might have to rewrite casper code:
- Phantomjs builds older than 2.0

**Comment by istr** [comment]
> Untested but want to test

You could just grab any of the supported PhantomJS binaries along the lines of `.travis.yml` https://github.com/casperjs/casperjs/blob/master/.travis.yml (versions 1.9.1 through 1.9.8) and try again if you see a crash. Would be nice if we have an information if this is related to 2.* only. Thank you.

**Comment by entrptaher** [comment]
I tested a sample login with 1.9.7, 1.9.8, 2.1.1
And heres some update regarding the analysis of this issue.

- The script causes problem on Ajax based lazy loaded pages only.
- Script causes problem that has many redirects and trackers (live chat, googletags etc.)

- On v1.9.7, it stops right at when this.fill() tries to find the login field. (Casperjs doesn't have backward compatibility in that case.)
- On v1.9.8, it hangs up right after submitting the form. Then it tries to close the process, but can't do because there is ongoing process. And when it exists, it says **timeout**, as well as the output of this issue https://github.com/ariya/phantomjs/issues/12697
- On v2.1.1, it stops when waiting for selector, giving the output  `Killed`
- Changing the viewport and useragent ofc may change how the page will be rendered. 

All of the codes below was started like this,
```js
// casperscript.js
phantom.casperPath = '/usr/lib/node_modules/casperjs';
phantom.injectJs(phantom.casperPath + '/bin/bootstrap.js');

var casper = require('casper').create({
    pageSettings: {
        loadImages: false,//The script is much faster when this field is set to false
        loadPlugins: true,
        userAgent: 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36'
    },
      verbose: true,
      logLevel: "debug"
});
casper.options.viewportSize = {width: 1600, height: 950};//Set bigger screen
//then set variables like theURL, thePassword etc
```

Here are some sample commands that failed on Ajax based websites.
```js
casper.start('https://twitter.com/#!/n1k0');

casper.waitForSelector('.tweet-row', function() {
    this.captureSelector('twitter.png', 'html');
    this.echo("Done!");
});

casper.run();
```
The above code produces the error, 
`[phantom] Casper.waitFor() timeout`

Another code,
```js
//First step is to open Website
casper.start().thenOpen(theURL, function() {
    console.log("Open Website...");
});

//Now we have to populate username and password, and submit the form
casper.then(function(){
    console.log("Login using username and password");
    this.fill('form.loginForm', {
        'email':theEmail,
        'password': thePassword,
    }, true);
});

//Make a screenshot of the page
casper.waitForSelector(theFinalSelector, function() {
    console.log("Make a screenshot....");
    this.capture('Home.png');
}, null ,1000000);

casper.run();
```
Its not like they don't work, they do, but sometimes they do, sometimes they don't. 

Now, the final thing I notice is this thing, **a lot** of this thing in **ajax** based pages.
 - This line >> `[debug] [phantom] Navigation requested: url=about:blank, type=Other, willNavigate=true, **isMainFrame=false**`

- Clientutils loads while the page is still loading, this info might have something to do with the whole thing.

In casperjs, is there a way to block other specific url from loading?

**Comment by jefleponot** [comment]
hi @entrptaher 

Perhaps , you are talking of : 
````js
casper.on('resource.request', function(requestData, networkRequest){
    // your filter url or ... then
    networkRequest.abort();
});
````

**Comment by entrptaher** [comment]
I found out that this issue has a relation to https://github.com/casperjs/casperjs/issues/178
I'll try to find why this happens, is it my codes thats messed up or is it the program. I'll let you know if all of them are just some silly mistakes or not.

**Comment by entrptaher** [comment]
This is getting a headache, sometimes it does this, sometimes it works just as fine.
Will try to find what is really going on.
Until then, I'm closing this issue (will reopen later, or if the 0x00005 gets fixed, I think I won't even have to.. :) ).

**Comment by entrptaher** [comment]
I found out why the script crashes after client utils load on AJAX based sites.
Phantomjs uses upto 500mb+ ram for a single moment when those scripts loads. Now, if the server has 512mb ram, the script closes from **memory exhaustion**. 
I'll try to find out if I can solve this problem by using some sort of workaround.

**Comment by entrptaher** [comment]
@jef, that function is probably be,
```js
casper.on('page.resource.requested', function(requestData, request) {
    if (requestData.url.indexOf('http://adserver.com') === 0) {
        request.abort();
    }
});
```

**Comment by istr** [comment]
@entrptaher oh, wow... I had some OOM issues on smaller host with PhantomJS, too. It would be great if we could somehow detect / catch / warn if they occur.

**Comment by entrptaher** [comment]
We all saw how phantomJS did not fix the memory leaks even after 1 year. 

Some random related issues:
- https://github.com/casperjs/casperjs/issues/1581
- https://github.com/casperjs/casperjs/issues/1686
- https://github.com/casperjs/casperjs/issues/1673
- https://github.com/casperjs/casperjs/issues/1684
- https://github.com/casperjs/casperjs/issues/1747

There are many more in the this and any other PhantomJS dependent repo. Rather than writing this in PhantomJS repo where all related issues are piling up with no resolve and solving PhantomJS error will take another 10 years if this goes in this pace and people will eventually move into nightmareJS or other alternatives.

I suggest the following, 
- Since CasperJS is mostly dependent on phantomJS, we can either leave it to phantomJS crew or find the **cure** to this problem ourselves.
- Meanwhile, We strongly warn the users about memory loop with versions and ajax. 
- We test everything with slimerJS and figure out if the problems persists there too.

**Comment by kensoh** [comment]
Thanks @entrptaher for tracking and compiling this useful info! Not sure what is the status for PhantomJS after maintainer stepping down, but hope someone takes up the baton! There are a lot of vested interests in PhantomJS ecosystem and I sincerely hope someone from community or a company continues to maintain it. Also adding on to this thread - https://github.com/casperjs/casperjs/issues/1825

**Comment by entrptaher** [comment]
It seems to me that, Right now the only way casperjs can continue is to move on to something like electron or headless chrome which has activity. Maybe we can close this issue right now.

**Comment by kensoh** [comment]
@entrptaher that's true. I heard there are already efforts made by Vitaly for successor but there wasn't positive response. Hope there will be some corporate white knight with vested interests to continue supporting and developing PhantomJS.

Linking to the CasperJS thread having this discussion about the new headless browsers - https://github.com/casperjs/casperjs/issues/1825

There are a group of issues related to PhantomJS, bumping this up for CasperJS maintainers to discuss and make a call whether to close PhantomJS issues (which have bugs pending on PhantomJS) as a group if it is not going to be updated anymore.

**Comment by lyweiwei** [comment]
I also ran into this issue, after some investigation, I found one source of the leak come from `Event#initCustomEvent`. `CustomEvent` is not supported in PhantomJS, so most of the libraries polyfill it with the old fashion `initCustomEvent`. In case you pass a detail object to this function, that object is leaked.

This is the minimal page I created to reproduce the leak.
```html
<html>
  <body>
    <div class='container'></div>
    <script>
      var event = document.createEvent("CustomEvent");
      event.initCustomEvent("testingtheevent", false, false, {});
      window.dispatchEvent(event);
    </script>
  </body>
</html>
```
Fortunately, the leak is only for the last parameter of `initCustomEvent`, the following code looks fine
```js
<html>
  <body>
    <div class='container'></div>
    <script>
      var event = document.createEvent("CustomEvent");
      event.initCustomEvent("testingtheevent", false, false);
      event.detail = {};
      window.dispatchEvent(event);
    </script>
  </body>
</html>
```

I'm not familiar with PhantomJS code base, and cannot locate the implementation of `initCustomEvent`. It would be great if the maintainer can help get this leak fixed.

A work around is to inject a polyfill in advance.
```js
function CustomEvent(type, params) {
  var e = document.createEvent('CustomEvent');
  var bubbles = Boolean(params && params.bubbles);
  var cancelable = Boolean(params && params.cancelable);

  e.initCustomEvent(type, bubbles, cancelable);
  if (params && params.detail) {
    e.detail = params.detail;
  }
}
```

**Comment by kensoh** [comment]
Thanks @entrptaher for consolidating the memory-related issues!

Closing this issue for now, seconding your view. Puppeteer just released, it looks to be a potential candidate to consider adopting to support Chrome.

**Comment by entrptaher** [comment]
For those who will visit this page later,
https://github.com/graphcool/chromeless and https://github.com/GoogleChrome/puppeteer are two chromeless potential alternatives right now. There will be more in future.
