### ISSUE TITLE
Warn if the server response does not contain a Content-Type header.

### ISSUE THREAD

**Issue by istr** [casperjs/casperjs#1584]
CasperJS has an implicit `Content-Type` of `text/html` if an explicit `Content-Type` header is missing in the server response. This has implications on the behavior of `getPageContent()`.

Proposal: we should _generally_ emit a warning if a response comes without `Content-Type` so users will be aware that their shabby "web server" misbehaves and may produce unexpected/undefined behavior in several browsers (including, but not limited to PhantomJS).

Ping @mickaelandrieu @BIGjuevos

**Comment by kensoh** [comment]
Bumping up the thread and also copying @jefleponot

**Comment by kensoh** [comment]
Archiving issue using **ARCHIVE** label as CasperJS, like PhantomJS, is not actively maintained for now.
