### ISSUE TITLE
What is the difference between module.exports and exports?

### ISSUE THREAD

**Issue by Sayalic0** [casperjs/casperjs#1591]
I implemented a custom module:

**FileUtil.js**:

```
var require = patchRequire(require);
module.exports = function(pre) {
    var module = {}

    module.writeStringToFile = function writeStringToFile() {
        casper.echo(pre + " succ");
    };

    return module
}
```

**Main.js**:

```
var casper = require('casper').create();
var FileUtil = require('FileUtil')('xxx')
FileUtil.writeStringToFile() // xxx succ
```

That works well, but if I change `module.exports = function(pre)` to `exports = function(pre)`, it broke down. 

Indeed, I always use `exports` before, since all of official modules use exports and I never see any module use `module.exports`. I get stuck here and I post it to [StackOverflow](http://stackoverflow.com/questions/37313580/how-to-make-a-custom-casperjs-module-with-custom-parameter), then I know `module.exports`.

So, what is difference between `module.exports` and `exports`?

**Comment by kensoh** [comment]
@Sayalic0 wanted to ask if you have found the answer since then? I'm a CasperJS user for couple of years, now looking through open issues. I saw this and couple of other posts - https://medium.com/@lazlojuly/node-js-module-exports-vs-exports-ec7e254d63ac

**Comment by kensoh** [comment]
@Sayalic0 closing this for now, it looks more of a JavaScript question but not sure if you have found a better answer for this since then. If you do, please share. Thanks for raising this question!
