### ISSUE TITLE
Wrong calc element bounds after call scrollTo method

### ISSUE THREAD

**Issue by imdmitrykravchenko** [casperjs/casperjs#1592]
Function clientutils.getElementBounds returns values obtained with getBoundingClientRect, but it wrong when window.scrollX or window.scrollY not equal to zero (call scrollTo, for example)

**Comment by kensoh** [comment]
Thanks @imdmitrykravchenko, bumping up, it looks like the PR is pending test case. I'm a CasperJS user for couple of years, browsing through open issues to see if any general issues I can help.

**Comment by kensoh** [comment]
Bumping up the thread, it looks like the PR is blocked pending test case.

**Comment by kensoh** [comment]
Archiving issue using ARCHIVE label as CasperJS, like PhantomJS, is not actively maintained for now.
