### ISSUE TITLE
TypeError: 'caller', 'callee', and 'arguments' properties...

### ISSUE THREAD

**Issue by eh1160** [casperjs/casperjs#1594]
I get the following error when I try to run a casperjs test through slimerjs, and the script includes a class with inheritance:
`FAIL TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them`

Here is how I run script (files are listed below):
`casperjs --engine=slimerjs test tests/test.js`

And here are the full results: 

```
Test file: tests/test.js                                                         
# Test Class Inheritance 
PASS Test Class Inheritance (NaN test) 
PASS Subject is strictly true 
FAIL TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them 
#    type: uncaughtError 
#    file: tests/test.js 
#    error: {} 
#    stack: not provided 
FAIL 2 tests executed in 0.941s, 1 passed, 1 failed, 0 dubious, 0 skipped.       

Details for the 1 failed test:

In tests/test.js 
  Test Class Inheritance 
    uncaughtError: TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them 
```

`test.js`

```
var TestClass = require("classes/TestClass").TestClass;
var testClass = new TestClass();

casper.test.begin('Test Class Inheritance', function suite(test) {
    casper.start("http://www.google.com", function() {
        test.assertTrue(true);
        testClass.create({});
    });

    casper.run(function() {
        test.done();
    });
});
```

`TestClass.js`

```
var casper = require('casper').create();

var TestClass = function() {};


TestClass.prototype.create = function() {
    casper.thenOpen("http://www.google.com").then(function() {});
};

TestClass.prototype.constructor = TestClass;

exports.TestClass = TestClass;
```

**Comment by istr** [comment]
This is certainly due to the usage of strict mode (`'use strict';`), see
https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Strict_mode

Anybody out there who knows a fix for that?

**Comment by eh1160** [comment]
I wondered if there was a `'unuse strict'` that I could place in my script, but I couldn't find one.  I definitely don't want to branch casperjs or slimer.

**Comment by istr** [comment]
No, probably the problem lies in the module wrapping / patch require code that clashes with gecko. We need to investigate this.

**Comment by pjhl** [comment]
I have the same problem. Trace:
```bash
Script Error: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them
       Stack:
         -> file:///C:/node/casperchild/node_modules/casperjs/modules/casper.js: 436
         -> file:///C:/node/casperchild/node_modules/casperjs/modules/casper.js: 436 (in function checkStarted)
         -> file:///C:/node/casperchild/node_modules/casperjs/modules/casper.js: 1560 (in function run)
         -> file:///D:/node/casperchild/test/casper-scripts/simple.js: 5
```

In my case, problem in function:
```javascript
Casper.prototype.checkStarted = function checkStarted() {
    "use strict";
    if (!this.started) {
        throw new CasperError(f("Casper is not started, can't execute `%s()`",
                                checkStarted.caller.name));
    }
};
```

I tried to reproduce this error in a test file, but I did not succeed. Script:
```javascript
console.log(typeof checkStarted.caller);
```

Casper script simple.js to reproduce error:
```javascript
var Casper = require('casper').Casper;
new Casper().run();
```

I execute it ```casperks.cmd --verbose --log-level=debug --engine=slimerjs simple.js```.

Environment: windows10, node v6.9.2, casperjs v1.1.3, slimerjs v0.10.2.

PS. I temporary fixed it for me by overwriting the function *checkStarted*.

**Comment by kensoh** [comment]
Bumping up the thread and copying maintainer @jefleponot

**Comment by kensoh** [comment]
Archiving issue using ARCHIVE label as CasperJS, like PhantomJS, is not actively maintained for now.
