### ISSUE TITLE
How to open popup without a url and just a title

### ISSUE THREAD

**Issue by miguelmota** [casperjs/casperjs#1595]
How to open popup without a url and just a title? The popup's content is dynamically added so it's not an actual file.

This doesn't work

``` javascript
casper.withPopup(/.*/gi, () => {});
```

**Comment by mickaelandrieu** [comment]
@miguelmota CasperJS (PhantomJs) does'nt supports ES6 for now => https://kangax.github.io/compat-table/es6/#phantom

**Comment by miguelmota** [comment]
It has nothing todo with ES6 and I'm not using PhantomJS. I'm just wondering how to select a "popup" window when there is no url.

```javascript
window.open('');
```

`withPopup` requires a regex for a url.

**Comment by kensoh** [comment]
@miguelmota this looks to be addressed? I think current document allows referencing popup using the page title - http://docs.casperjs.org/en/latest/modules/casper.html#withpopup
