### ISSUE TITLE
CasperJS freeze

### ISSUE THREAD

**Issue by JohnnyEvo** [casperjs/casperjs#1597]
CasperJS version : 1.1.1
PhantomJS : Prebuilt/ 2.1.7

I have no problem on local.

With CI server (codeship, circleci), my tests freeze randomly. And this freeze works timed out.

I have many test files, this is one : 

```
/**
 * Test de l'interface utilisateur de la connexion
 *
 * Usage :
 *  $ casperjs test src/*/**Bundle/Tests/Casperjs/loginDesktopTest.js
 */

// Configuration
casper.options.viewportSize = {width: 1920, height: 1080};
casper.options.pageSettings.loadImages = false;
casper.options.pageSettings.loadPlugins = false;
casper.options.pageSettings.localToRemoteUrlAccessEnabled = true;

// Global vars
var baseUrl = "http://127.0.0.1:8000/app.php",
    login = {username: "paul.bismuth@test.fr", password: "test"},
    screenshotsDirectory = "casperjs/actuel/";

// Test
casper.test.begin('Test interface de la connexion', 6, function (test) {
    // Connexion via le formulaire
    casper.start(baseUrl + '/fr_FR/login', function () {
        casper.test.comment("## Page de connexion");

        test.assertTitle('Mon site', 'Titre de la page correct');
        test.assertExists('form#connexion', 'Formulaire de connexion présent');

        // this.echo('Screenshot : 00');
        // this.capture(screenshotsDirectory + '00.png');

        casper.test.comment("## On remplit & valide le formulaire");
        this.fill('form#connexion', {
            "_username": login.username,
            "_password": login.password
        }, true);

        this.wait(1); // To follow two redirections
    });

    // On regarde si la redirection est bonne
    casper.then(function () {
        casper.test.comment("## Vérification de la redirection");
        test.assertTitle('Mon site (connecté)', 'Titre de la page correct');

        test.assertExists('.liste', 'Liste présentet');
        test.assertTextExists('Titre 1', 'Le Titre 1 est présent');
        test.assertTextExists('Titre 2', 'Le Titre 2 est présent');

        // this.echo('Screenshot : 01');
        // this.capture(screenshotsDirectory + '01.png');
    });

    casper.run(function () {
        test.done();
    });
});
```

My command to launch tests : 

```
casperjs test src/Bg/**Bundle/Tests/Casperjs/*DesktopTest.js --pre=src/Bg/UserBundle/Tests/Base/LoginDesktopTest.js
```

I active the log and this is result : 

```
Test file: src/*/**Bundle/Tests/Casperjs/TestFileDesktopTest.js  
# Test interface du module
[info] [phantom] Starting...
[info] [phantom] Running suite: 19 steps
PASS Test interface du module (34 tests)
[debug] [phantom] opening url: http://127.0.0.1:8000/app.php/fr_FR/dashboard/test, HTTP GET
[debug] [phantom] Navigation requested: url=http://127.0.0.1:8000/app.php/fr_FR/dashboard/test type=Other, willNavigate=true, isMainFrame=true
[debug] [phantom] Navigation requested: url=http://127.0.0.1:8000/app.php/fr_FR/login, type=Other, willNavigate=true, isMainFrame=true
*** freeze here ***
```

I contacted CI's supports but they haven't solutions. I think to memories' limit but I'm not sure. How confirmed my problem ? Another have a similar problem ?

Nota : With Travis-CI, no problem.

**Comment by istr** [comment]
Probably memory related /  OOM. PhantomJS needs lots of memory in some situations, there is another open issue pointing in that direction.

**Comment by JohnnyEvo** [comment]
Thank you for your response. I'll look on the PhantomJS's repo.

I tested with SlimerJs and exactly same problem so i d'ontk now if the problem is Casperjs, my test files, ...

**Comment by mlalpho** [comment]
What does passing phantomjs arg `--debug=true` get you? In addition to casperjs arts, `--log-level=debug` and `--verbose=true`

**Comment by JohnnyEvo** [comment]
I try with this args but there are no more informations. PhantomJS and/or CasperJS suddenly freeze.

**Comment by m-matveev** [comment]
Got a same issue. --debug=true and --log-level=debug provide me a more information. 
My output was: " updateLoadingProgress: 90" 
I try to run in with option --engine=slimerjs and see that casperjs hangs on google-analytics.com requests. This script help me disable ga requests:

/**
 * Add a listener for the phantomjs resource request.
 *
 * This allows us to abort requests for external resources that we don't need
 * like Google adwords tracking.
 */
casper.options.onResourceRequested = function(casper, requestData, request) {
    // If any of these strings are found in the requested resource's URL, skip
    // this request. These are not required for running tests.
    var skip = [
        'googleads.g.doubleclick.net',
        'cm.g.doubleclick.net',
        'www.googleadservices.com',
        'mc.yandex.ru'
    ];


    skip.forEach(function(needle) {
        if (requestData.url.indexOf(needle) > 0) {
            request.abort();
        }
    })
};

**Comment by BIGjuevos** [comment]
Instead of disabling this code on the testing level.  It is probably best for the codebase to support a testing mode that just doesn't include these resources on page load.

That would circumvent most of the issues you are having.

In the event you are unable to do this because it is code neither you nor your company have control over, ignore this suggestion.

**Comment by kensoh** [comment]
Hi @JohnnyEvo does this still happens for you with latest CasperJS/PhantomJS? Or with higher CI machine specs do it still happen?

**Comment by kensoh** [comment]
Hi @JohnnyEvo not sure if this issue is resolved for you with latest CasperJS v1.1.4 and PhantomJS v2.1.1? Closing this for now but please reopen if it is still happening. Thanks for raising this!

**Comment by JohnnyEvo** [comment]
Sorry, I didn't have time to work with CasperJs. I just know that I have no problem with SlimerJs. I'll try with PantomJs in the coming days and I'll keep you up to date.

Thank you for your attention

**Comment by kensoh** [comment]
No probs @JohnnyEvo thanks for having a look. Looking forward to see if there are any clues where the issue can be investigated. I would also like to link to this comment by @statico on CircleCI - https://github.com/casperjs/casperjs/pull/264#issuecomment-22575514 (that is the only other occurrence of circleci/codeship in CasperJS issues search for both close and open issues)
