### ISSUE TITLE
Communication channel between Casper and Node?

### ISSUE THREAD

**Issue by slavafomin** [casperjs/casperjs#1598]
Hello!

Thank you for this great library!

However, is there a way to setup a communication channel between Casper.js and Node.js application?

I'm starting Casper using `child_process.spawn` and I can read it's output in Node, but is it possible to receive messages from Node's parent process in Casper?

I've tried to implement inter-process communication using `stdin`/`stdout` pipes, but it's not working as expected, is there an example of some sorts?

Thanks!

---

I know about SpookyJS, but it's not working with latest versions of Node/Casper/Phantom and is not maintained anymore.

---

Maybe you can give me a simple example of how I can properly read `stdin` in Casper?

**Comment by istr** [comment]
See https://github.com/casperjs/casperjs/issues/1524. You can find some options in the discussion.

Closing as "duplicate".
