### ISSUE TITLE
Our community is on StackOverflow ...

### ISSUE THREAD

**Issue by mickaelandrieu** [casperjs/casperjs#1599]
Hi everyone,

let's take a look at http://stackoverflow.com/questions/tagged/casperjs , there are almost 2000 questions tagged !

I think we should remove the mailing list and redirect people to stackoverflow, also we should try to take time to answer some questions and improve the docs this way.

What do you think ?

**Comment by istr** [comment]
@mickaelandrieu Let us do this. PR welcome. I am currently overloaded, sorry for that. Situation will improve mid of June.

**Comment by mickaelandrieu** [comment]
Same here : after PrestaShop day and end of my teaching activity I'll come back ^^

**Comment by mickaelandrieu** [comment]
@jcrben as we are not active enough to be on our own google mailing list, I'm in favor of the "less bad" option.

Also, even for the PrestaShop (where we are a lot of active developpers), we are not so active on Gitter.

I'm not against better ideas than mine :)

**Comment by mlalpho** [comment]
I generally lean towards IRC for informal discussion/direct code help. Google mail lists and stackoverflow are usually the first stopping point for issues, but, when all else fails..IRC is much more direct.What about a freenode channel or someone hosting a Mattermost? Get enough ppl on there and index the logs and you have yourself a great medium for communication :+1:

**Comment by BIGjuevos** [comment]
We already have a freenode channel #casperjs.  Feel free to come join us.  I have a BNC so I am technically always there, but I tend to pay attention to it at least a few days a week.

I've also attempted to get a slack going (it even has travisci and github integrations).  Presently, you can request self registration through http://ryannull.com:3000 Although I am trying to get slack.casperjs.org setup to host the same thing.

The thing about supporting the community, is that we should do as much of it on their terms as possible.  If this means going through slack, irc, and something else, I'm OK with it.  As long as we have a responsible party for each medium to help help the community alive in that medium

**Comment by mlalpho** [comment]
Ryan, that's great to hear. I'll come hang out :)
