### ISSUE TITLE
window.location.href redirect not handled

### ISSUE THREAD

**Issue by quetz** [casperjs/casperjs#1600]
casperjs version 1.1.1

Say I have two pages `a.html` and `b.html`.
`a.html` contains code like that:

``` html
<html>
<body>
<script language="JavaScript">
window.location.href="http://my.server/b.html"
</script>
</body>
</html>
```

casperjs script is like:

``` javascript
// we start from other page
casper.start('http://my.server/z.html', function() {})
casper.thenOpen('http://my.server/a.html', function() {
// B
})
casper.run(function() {
// C
})
```

`page` object at points B and C have `url=/a.html`, not `/b.html`, while if I hook `page.resource.received` event I see that `/b.html` is requested (although it seems impossible to get `b.html` body at that point)

This behaviour seems to me like a bug. If it is not, what's correct way to get to `/b.html` body?

Inserting any amount of waits at random points do not help, so it must not be a timing issue. All requests are done before point B is hit.

**Comment by mlalpho** [comment]
As a workaround, what if you used regex on the page source to get the url? And then pass that down to `casper.evaluate (function (url){window.location.href=url;}, url);` ?

**Comment by kensoh** [comment]
@quetz do you still encounter this with v1.1.4? I'm a CasperJS user and looking at some issues.

**Comment by kensoh** [comment]
@quetz wanted to update that this seems to be fixed along the way. I tried to replicate your files on my server and it works with below files + output. I'm using CasperJS v1.1.4 + PhantomJS v2.1.1. Closing this issue for now but do reopen if you still have an issue!

a.html
```html
<html>
<body>
<script language="JavaScript">
window.location.href="http://tebel.org/b.html"
</script>
</body>
</html>
```

b.html
```html
<html>
<body>
<h1>file b</h1>
</body>
</html>
```

script
```js
...

casper.start('http://tebel.org', function() {
this.echo(this.getCurrentUrl());})

casper.thenOpen('http://tebel.org/a.html', function() {
this.echo(this.getCurrentUrl());})

casper.run()
```

output
```
http://tebel.org/
http://tebel.org/b.html
```
