### ISSUE TITLE
casper testing doc seems to be broken

### ISSUE THREAD

**Issue by andreportela** [casperjs/casperjs#1603]
Hi guys!

First things first. Congrats for the great project, your attitude is awesome!

I've read CONTRIBUTE.md to figure it out how to. While I was reading I've noticed that in the section https://github.com/casperjs/casperjs/blob/master/CONTRIBUTING.md#write-tests the link that should explain more is broken. Where that info is supposed to be?

**Comment by istr** [comment]
Here: http://docs.casperjs.org/en/latest/testing.html

A PR to fix this broken link is welcome.

**Comment by andreportela** [comment]
Thanks @istr! It has helped me a lot to figure it out a few things!
