### ISSUE TITLE
Are fs.basename(), fs.dirname(), fs.pathJoin() safe to use in my project?

### ISSUE THREAD

**Issue by beatak** [casperjs/casperjs#1604]
I read code and see see the extension to PhantomJS's `fs` module. They all look very useful methods to  me but since they are not documented, I'm a little hesitant to use it in my project. Do you guys think they are here to stay for a long run? or is it a hack, maybe better things to come soon?

Thanks!

**Comment by istr** [comment]
If you'd ask me: consider the code in `bin/bootstrap.js` "internal" only. The extensions are mainly there to work around platform specific quirks. But maybe it could be a good idea to make them "public" -- this would need documentation and test cases as well as moving this from `bootstrap.js` to `modules/utils.js` or `modules/clientutils.js`

**Comment by kensoh** [comment]
Hi @beatak do you mean fs as in below? I actually used this since I started using CasperJS/PhantomJS in 2015. I still continue using this and don't know (and haven't explore) other ways. So far ok for me.

```js
var fs = require('fs');
fs.write(...
```

**Comment by kensoh** [comment]
Adding on @beatak, with recent development in PhantomJS it is unlikely to have big changes for now. However CasperJS may have to add support for new headless browsers such as Chrome, or headless Firefox (through SlimerJS). Closing this issue for now as there isn't new developments but kindly ping if you have questions or at ken@tebel.org !
