### ISSUE TITLE
CasperJS SSL 

### ISSUE THREAD

**Issue by HabiMobinzada** [casperjs/casperjs#1609]
Hi
I have a Https: site which I can only enter with a certificate. In PhantomJS it is working fine, but if I want to do something in CasperJS it does not work. I think CasperJS does not have the parameter I need to pass the SSL authentication.
The parameters I used in PhantomJS are:

--ssl-client-certificate-file=D:\ssl\clientcert.cer 
--ssl-client-key-file=D:\ssl\clientcert.key 
--ssl-client-key-passphrase=123456
--ignore-ssl-errors=true 
--ssl-protocol=any

Does someone have an idea or had a similar problem?

**Comment by MeixnerTobias** [comment]
same issue here, would be great if someone had a solution or was able to have it run.
thank you.

**Comment by BIGjuevos** [comment]
I'll take a look at this.

**Comment by v-pravin** [comment]
These arguments haven't been pushed to Casper's Python script. A workaround is to create a PhantomJS config file with all those arguments in it and pass its path through '--config'. This worked for me.

**Comment by mickaelandrieu** [comment]
Or..  add theses options,  right?

**Comment by BIGjuevos** [comment]
yeah, we should support these options.

**Comment by mlalpho** [comment]
Any progress on this?

**Comment by jefleponot** [comment]
@mlalpho, Thank you point this evolution.
That is quite a challenge to create test code for this feature :smile: 
I will try to do it
