### ISSUE TITLE
Phantom page.captureContent is not supported

### ISSUE THREAD

**Issue by aymen-mouelhi** [casperjs/casperjs#1611]
I tried setting captureContent to a list of urls I am interested in getting their body object, but it seems that casperjs doesn't interpret this option.
I am using phantom v 2.1.1, and I set captureContent after casper.start()

**Comment by mlalpho** [comment]
Maybe look at this and see if it helps: http://stackoverflow.com/questions/12009881/using-phantomjs-to-read-the-response-body

**Comment by mlalpho** [comment]
Were you able to figure this out? Does casperjs source need modification to support this phantomjs property?

**Comment by kensoh** [comment]
@aymen-mouelhi and @mlalpho can you kindly share with me more what is a use case for this? (for learning purpose) I would think that using this.getHTML() will be able to get the contents.

**Comment by mlalpho** [comment]
@kensoh  I believe the idea is to capture specific parts of the page (css, js, etc) to avoid downloading all the assets. This thread may be key to pointing out that it may no longer be supported in phantomjs, but is supported in slimerjs http://stackoverflow.com/questions/22058321/status-of-phantomjs-onresourcereceived-response-body-work

**Comment by kensoh** [comment]
Thanks @mlalpho for sharing! I understand now, this is an interesting use case 😃

**Comment by jefleponot** [comment]
@mlalpho  @kensoh 

I'm also interested in  page.captureContent features but it works only with slimerJS.
A PR has been made for phantomJS but it was unstable ... so never merged ..

**Comment by kensoh** [comment]
Closing the issue for now.. As it involves dependency upstream from PhantomJS. I saw some commits from Vitaly in early July, but not sure of the status now for PhantomJS. But do reopen if anything!
