### ISSUE TITLE
Memory leak 

### ISSUE THREAD

**Issue by Suhar777777** [casperjs/casperjs#1612]
Please help! I have 2 scripts doing the same things. One script run with only phantomjs, and other script run with casperjs on phantomjs. So, after 24 hours running the scripts, first script used not more 300 mb  RAM, but the second scripts used more then 1800 mb RAM, and continue increase!!! Please help, why so happened. Why phantomjs using casperjs increase to 1800 mb RAM, and without casperjs it is all ok and normal?????
 In my searching, I have some things:
1. Every second increase array casper.resources. I put in my second script this code casper.echo('resources -- ' + casper.resources.length) and I saw after 24 hours length of array increase from 1 to 80000 elements!!!!!!
2. Every 30 minutes increase array casper.history. I put in my second script this code casper.echo('history -- ' + casper.history.length) and I saw after 24 hours length of array increase from 1 to 48 elements!!!!!
However I searching another arrays (steps, waiters) but they not changed.
Then I decided delete some elements from casper.resource and casper.history,  I put in my second script this code casper.resources.length = 10 and casper.history.length = 1.
After this I run script. But different between second script1 and second script2 was only 100mb not how I want 1500mb(((((
Please help searching another array which increase length and so that increase RAM????

**Comment by Suhar777777** [comment]
Yes!!!! I did it!!! I forgot that I have 11 pages, and I deleted elements of array casper.resources and casper.history only on a first page. Now I deleted elements of array casper.resources and casper.history from all 11 pages!!! After this RAM on a first script === RAM on a second script!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by istr** [comment]
Thanks for the update.
