### ISSUE TITLE
Console doesn't exit on windows, when running 'casperjs test'

### ISSUE THREAD

**Issue by ambrt** [casperjs/casperjs#1613]
I tried all ways to make script exit after execution but none works, console is hanging on `finished` echo.

```
  casper.run(function() {
        this.echo('finished');
        this.test.done(3);
        casper.exit(999);
        casper.bypass(999);
        casper.bypass(999);
        phantom.exit();

      });
```

Windows 10, phantomjs - 2.1.1 casperjs 1.1.1

**Comment by mlalpho** [comment]
If it's a one-off cmd.exe execution, then it should exit..but if you opened the console and manually ran the command, casper or phantom exit calls are not going to close the window.

Try wrapping your script execution is a .bat file and refer to batch file documentation for syntax

**Comment by BIGjuevos** [comment]
Have you tired including a `casper.done()` instead of a `this.test.done()`?

**Comment by paulroho** [comment]
@BIGjuevos There is no `done()` on `casper`.

**Comment by kensoh** [comment]
Hi @ambrt, seconding what @mlalpho said. On Windows I have a batch file wrapping around CasperJS execution which may be helpful for you - https://github.com/tebelorg/TagUI/blob/master/src/tagui.cmd

**Comment by kensoh** [comment]
@ambrt besides the sample batch file in previous post, would like to add below link. I guess a way is to return by using exit without the /b option, to force exiting of console if that's your intention. Closing this issue for now, or ping here if you have any questions! or email at ken@tebel.org

https://stackoverflow.com/questions/10534911/how-can-i-exit-a-batch-file-from-within-a-function
