### ISSUE TITLE
waitForPopup does not work with invalid certificate

### ISSUE THREAD

**Issue by cvillemure** [casperjs/casperjs#1615]
I don't know if it's a PhantomJS bug or a CasperJS bug, but if I click on link that trigger a window.open on a website running with an invalid certificate (my dev computer) the popup never opens (or Casper never knows it was opened)

I started CasperJS with the following flag

--ignore-ssl-errors=true --proxy-type=none --ssl-protocol=any

**Comment by istr** [comment]
Please include CasperJS and PhantomJS version you are using in any issue you open. Thank you.

**Comment by cvillemure** [comment]
CasperJS 1.1.1
PhantomJS 2.1.1

**Comment by kensoh** [comment]
Hi @cvillemure do you still have the same problem with CasperJS v1.1.4? What if you also include options such as below? These are the options with lowest security protection that I know of.

casper.options.pageSettings = {
loadImages: true,
loadPlugins: true,
ignoreSslErrors: true,
**webSecurityEnabled: false,**
**localToRemoteUrlAccessEnabled: true**
};
