### ISSUE TITLE
can't run casperjs use phantomjs 2.1.1

### ISSUE THREAD

**Issue by happyqq** [casperjs/casperjs#1616]
when I run this scrpt in centos 7.0 x64 and  phantomjs 2.1.1 (/usr/local/sbin/phantomjs)

I can't see anything is output。why?

`

var casper = require('casper').create();

casper.start('http://casperjs.org/', function() {
    this.echo(this.getTitle());
});

casper.thenOpen('http://phantomjs.org', function() {
    this.echo(this.getTitle());
});

casper.run();

`

**Comment by mlalpho** [comment]
Hmm, tried on OL6 and works:
```
casperjs ./phantom-test.js
CasperJS, a navigation scripting and testing utility for PhantomJS and SlimerJS
PhantomJS | PhantomJS
[mlalpho]$ phantomjs --version
2.1.1
```

Are you using casperjs/master ?

Did you add phantomjs to PATH? `export PATH=$PATH:/usr/local/sbin/`

**Comment by mlalpho** [comment]
@happyqq Were you able to get this example script working?

**Comment by happyqq** [comment]
@mlalpho 
I forget this problem for a long time,but in this time,It runs work fine
In this days,
I only run "yum update"  in my centos and have installed a new software "httpie"
I don't know why it is ok now?

sorry
