### ISSUE TITLE
Get casper engine

### ISSUE THREAD

**Issue by hugsbrugs** [casperjs/casperjs#1617]
Hi everybody,

I wonder how can I get current casperjs engine (slimer or phantom) ? something like casper.engine would be great but not found something like that in docs.

I've tried with CLI arguments with no luck (think it's only for my casper script arguments) : 
```javascript
if(casper.cli.has("--engine"))
	current_engine = casper.cli.get("--engine");
```
Thanks for your suggestions !

**Comment by mlalpho** [comment]
`phantom.casperEngine` #1414 👍

**Comment by hugsbrugs** [comment]
Thanks for ```phantom.casperEngine``` tip !

Can't retrieve info with ```casper.cli.get( 'engine' )``` neither ...
