### ISSUE TITLE
how i can fill data in select2-selection 

### ISSUE THREAD

**Issue by saraabed** [casperjs/casperjs#1619]
i use   `casper.fillSelectors('form[id="form"]', { }` to fill data in (radio button - input - drop-down ) 
but i have filed use ( select2-selection ) , how can i fill data in it ??

**Comment by mlalpho** [comment]
Not very familiar with select2, but, instead of using .fill, try using .sendKeys and .click on the facade elements that select2 listens to to make changes to what I assume are hidden elements.

**Comment by mlalpho** [comment]
Any luck? I've had to do similar things with bootstrap typeahead as this doc describes: http://docs.casperjs.org/en/latest/modules/casper.html?#sendkeys

**Comment by saraabed** [comment]
i can't understand what you are mean ?! @mlalpho

**Comment by mickaelandrieu** [comment]
Please, use the mailing list or stackoverflow if you need help about your application.

If you are **sure** that you have a bug about casperjs or to suggest a improvement, don't hesitate to fill a new issue.

Mickaël
