### ISSUE TITLE
sendAJAX return data as undefined  ?!

### ISSUE THREAD

**Issue by saraabed** [casperjs/casperjs#1621]
i have API that contain data like that `{ main [ {"id":"1",,"name":"A"} , {"id":"2",,"name":"b"} , {"id":"3",,"name":"c"} ]}` so i want to get **name** value 

i write this code but each time return name as undefined !!!!

`casper.then(function () {
    var wsurl = "apiUrl";
    jsonObject_fields = casper.evaluate(function (wsurl) {
        try {
            return JSON.parse(__utils__.sendAJAX(wsurl, 'GET', null, false));
        } catch (e) {
            console.log("Error in fetching json object");
        }
    }, wsurl);
    
    Array.push(JSON.stringify(jsonObject_fields.main));
    console.log("array" + Array);

    for (var i in Array) {
        console.log("name" + i.name);
    }
});`

**Comment by mlalpho** [comment]
@saraabed: there are a few things going terribly wrong with your code.

1. That data you have isn't valid JSON `{ main [ {"id":"1",,"name":"A"} , {"id":"2",,"name":"b"}, {"id":"3",,"name":"c"} ]}` If you remove the extra comma `,` it would be.
2. I don't see any place where you're called casper.start() or casper.run() -- if you are that's okay if this is just a partial snippet.
3. You are using the special keyword `Array` as a variable name
4. You are not using `var` to instantiate jsonObject_fields
5. inside your evaluate() you are using the word, `utils` when it should be `__utils__` not sure if the markdown styling just messed up your snippet or not.. You should use three backticks \`\`\` to begin and end a large code block.
6. If you are not calling start() or your previous navigation step is on a different domain than your ajax call, then your sendAJAX will fail. Try returning `e` to see the exception message

Give this a try:
```
var casper = require('casper').create();
var utils = require('utils');
casper.start( 'url' );
casper.then( function () {
    var wsurl = "url";
    var jsonObject_fields = this.evaluate( function(wsurl) {
        try {
            return JSON.parse(__utils__.sendAJAX(wsurl, 'GET', null, false));
        } catch (e) {
            return e;
        }
    }, wsurl );

    var arr = [];
    utils.dump( jsonObject_fields );
    for (var key in jsonObject_fields.main) {
      arr.push( jsonObject_fields.main[key].name );
    }
    utils.dump( arr );

});

casper.run();
```
With JSON: `{ "main": [ {"id":"1","name":"A"}, {"id":"2","name":"b"}, {"id":"3","name":"c"} ] }`
I get:
```
[debug] [remote] sendAJAX(): Using HTTP method: 'GET'
{
    "main": [
        {
            "id": "1",
            "name": "A"
        },
        {
            "id": "2",
            "name": "b"
        },
        {
            "id": "3",
            "name": "c"
        }
    ]
}
[
    "A",
    "b",
    "c"
]
```

**Comment by saraabed** [comment]
@mlalpho 

thanks thanks thanks this is helpful and it work with me grate :)

**Comment by mlalpho** [comment]
Glad I could help :+1: Want to close the issue? :)

**Comment by saraabed** [comment]
yes :+1: @mlalpho
