### ISSUE TITLE
how i can scraping data form website page and set it in same array ?! 

### ISSUE THREAD

**Issue by saraabed** [casperjs/casperjs#1622]
i have page that contents **30** div like that 

` <div>
            <div class="product-title">
                <h2 class="title"><a href="#"> Iphon 6 </a></h2>
            </div>
            <div class="price-box ">
                <span id="prod-price">89.00 $ </span> 
            </div>
</div>`

i want to use casperJs to scraping data (title - price ) for each div 

i write this code , but i save **title** in array and save it in csv file  and **price** in another array and save it in csv file 

but i want to put each title with it price in one array to be like that 

`{product [ {"title":"x" , "price":"999"} ,  {"title":"y , "price":"555"} ,  {"title":"z" , "price":"333"}  ]}`

then save it in csv file :) 

here declarer variable ::

`var casper = require('casper').create();
var fs = require('fs');
var title;
var price;
var priceArr = [];
var titleArr = [];
`
and her function i use :: 

`function getTitle() {
    var title = document.querySelectorAll('h2.title a');
    return Array.prototype.map.call(title, function (e) {
        return e.innerText
    });
}
function getPrice() {
    var price = document.querySelectorAll('#prod-price');
    return Array.prototype.map.call(price, function (e) {
        return e.innerText
    });
}`

and here start , then and run 

`casper.start().thenOpen("siteUrl", function () {
});
casper.then(function () {
    title = this.evaluate(getTitle);
});
casper.then(function () {
    price = this.evaluate(getPrice);
});
casper.then(function () {
    for (var i in title) {
        console.log(title[i]);
        titleArr.push(links[i]);
    }
});
casper.then(function () {
    for (var i in price) {
        console.log(price[i]);
        priceArr.push(price[i]);
    }
});
casper.then(function () {
    fs.write('title.csv', titleArr, 'w');
    fs.write('pric.csv', priceArr, 'w');
});
casper.run();`

**Comment by mlalpho** [comment]
@saraabed github issues are not meant to be used as a support forum, questions like these are better asked on the google mailing list, https://groups.google.com/forum/#!forum/casperjs, or in the freenode irc,  chat.freenode.net, channel: `#casperjs`

If there are actual issues that casperjs is having, then open an issue. Please read the "Support" section in the Readme.md https://github.com/casperjs/casperjs
