### ISSUE TITLE
Casperjs log during the CI build

### ISSUE THREAD

**Issue by skananitos** [casperjs/casperjs#1625]
All the tests for my web app are written on Casperjs. I use Gulp as my building tool. I've created a new task to run the tests:

```
gulp.task("test", function () {
    gulp.src("tests/maintest.js")
    .pipe(casperJs())
    .pipe(exit());
});
```
Locally I start the server first and in a separate terminal I run the tests. In this case, I can see Casperjs' logs as usual.

My problem is when I'm trying to run the tests during the CI build on the server. The tests probably succeed (otherwise, the CI build will fail), but I can't see the Casperjs' logs. So, how can I "import" Casperjs logs on server's logs?

**Comment by mlalpho** [comment]
Would it help if you piped the casperjs output to a file or used `--xunit`? Being unfamiliar with your gulp setup and the lack of supporting information on how you're executing casperjs in this cas does not leave much to aid with diagnosing your particular issue.

**Comment by skananitos** [comment]
The solution that I found is the following:

```
gulp.task("test", function() {
    connect.server({
    port: 8080,
    root: "build"
  });
  var phantomJs = require("phantomjs-prebuilt");
  process.env.PHANTOMJS_EXECUTABLE = phantomJs.path;
  gulp.src("tests/maintest.js")
  .pipe(casperJs())
   .on("end", function() {
     connect.serverClose();
  });
});
```

So, I start separately the server just for the test task in order to get the Casperjs' logs. The problem here is that the server closes before the tests finish.

**Comment by BIGjuevos** [comment]
Gulp likely has some timeout somewhere.  Have you checked the gulp docs?

**Comment by skananitos** [comment]
Ok, so the solution was to add an extra pipe line before the "end" event:

```
gulp.task("test", function() {
    connect.server({
    port: 8080,
    root: "build"
  });
  var phantomJs = require("phantomjs-prebuilt");
  process.env.PHANTOMJS_EXECUTABLE = phantomJs.path;
  gulp.src("tests/maintest.js")
  .pipe(casperJs())
   **.pipe(gulp.dest("./")**
   .on("end", function() {
     connect.serverClose();
  });
});
```

**Comment by istr** [comment]
@skananitos nice that you found a solution for your problem. Would you mind creating a PR that adds your sample to a good place in our documentation?

**Comment by BIGjuevos** [comment]
This is resolved, closing. 

@skananitos, please feel free to open a PR adding info to ours or phantomjs' documentation.
