### ISSUE TITLE
get all table content please ?!

### ISSUE THREAD

**Issue by anaCode5** [casperjs/casperjs#1626]
i have table with specific class name , so i want to get all table data --> how i can do that using casperJs ?!

**Comment by mlalpho** [comment]
@anaCode5 github issues are not meant to be used as a support forum, questions like these are better asked on the google mailing list, https://groups.google.com/forum/#!forum/casperjs, or in the freenode irc, chat.freenode.net, channel: #casperjs

If there are actual issues that casperjs is having, then open an issue. Please read the "Support" section in the Readme.md https://github.com/casperjs/casperjs

**Comment by anaCode5** [comment]
Ok thanks :)
