### ISSUE TITLE
Casperjs not work with react.js

### ISSUE THREAD

**Issue by ccjar** [casperjs/casperjs#1629]
I have an issue, when in the page html exits a div with react.js  Casperjs not found this div.

My  part of the code : 

 casper.waitForSelector(".add-anchor.add_button.btn.btn-primary.btn-xs",
       function success() {
           test.assertExists(".add-anchor.add_button.btn.btn-primary.btn-xs");
           this.click(".add-anchor.add_button.btn.btn-primary.btn-xs");
       },
       function fail() {
           test.assertExists(".add-anchor.add_button.btn.btn-primary.btn-xs");
   });

   casper.then(function(){
	   
	   this.echo(" URL" + this.getCurrentUrl());
	   this.capture("diag2.png");  // the picture created is blank! not load react.js
	   
   });
  
 
   casper.waitForSelector(x("//*[@id='crudForm']"),
       function success() {
           test.assertExists(x("//*[@id='crudForm']"));
          // this.click("#headingPromotions span");
       },
       function fail() {
           test.assertExists(x("//*[@id='crudForm']"));
   });

HTML : 

<div id="crm">
<div data-reactid=".0">
**<div data-reactid=".0.$nodeFactory">
<form id="crudForm" class="form-horizontal" data-reactid=".0.$crmForm" accept-charset="utf-8"** enctype="multipart/form-data" method="post" action="http://admiral.hub.trafficgenerationltd.com/crm/index/insert" role="form">
<div id="myModal" data-reactid=".0.$modal"></div>
</div>
</div>

Result : 

PASS Find an element matching: .add-anchor.add_button.btn.btn-primary.btn-xs
PASS Find an element matching: xpath selector: //*[@id='crm']/div
PASS Find an element matching: xpath selector: //*[@id='page-wrapper']/script[1]
FAIL Find an element matching: xpath selector: //*[@id='crudForm']
  type: assertExists
 file: admin2.js
  subject: false
  selector: {"type":"xpath","path":"//*[@id='crudForm']"}
FAIL 10 tests executed in 18.503s, 9 passed, 1 failed, 1 dubious, 0 skipped.    

Details for the 2 failed tests:

**Comment by ccjar** [comment]
HTML :   
div id="crm">
<div data-reactid=".0">
<div data-reactid=".0.$nodeFactory">
<form id="crudForm" class="form-horizontal" data-reactid=".0.$crmForm" accept-charset="utf-8" enctype="multipart/form-data" method="post" action="http://admiral.hub.trafficgenerationltd.com/crm/index/insert" role="form">
<div id="myModal" data-reactid=".0.$modal"></div>
</div>

**Comment by ccjar** [comment]
![selection_010](https://cloud.githubusercontent.com/assets/20111324/16306971/e683452a-395f-11e6-9548-f788c45e80d2.png)

**Comment by BIGjuevos** [comment]
@ccjar 

You're not the first to report issues with react and casperjs.  Most of these issues are in the underlying layer of phantomjs and it using an older webkit and not supporting cool things that react uses.

Look at something like: https://gist.github.com/jarednorman/c3d5af727ca09f6230a1 as an example.

It doesn't look like your issues can be concretely linked to a bug in CasperJS.

I encourage you to look at the debugging toolkits provided to you by CasperJS, PhantomJS/SlimerJS.

CasperJS: http://docs.casperjs.org/en/latest/debugging.html
PhantomJS: http://phantomjs.org/troubleshooting.html
SlimerJS: https://docs.slimerjs.org/current/configuration.html#about-debug

In the event you can convert this into a reproducible bug that traces it's way back to CasperJS, I encourage you to re-open this issue with details on how to reproduce the bug.  We'd be happy to look into it.
