### ISSUE TITLE
Can't change PATH in CI system causes 'python is not recognised as an internal or external command'

### ISSUE THREAD

**Issue by andycodecomplove** [casperjs/casperjs#1631]
My team uses Visual Studio Team Services (VSTS) for build and deployment. We use a hosted build agent (ie we don't control what is installed on the machine or how its configured) which has Python 2.7 installed but C:\Python27 has not been added to the PATH environment variable (raised a separate [issue](https://github.com/Microsoft/vsts-tasks/issues/1939) with the VSTS project).

I can create a batch file which SETs PATH before I immediately call .bin/casperjs.cmd, but I'd rather not plus we are a cross-platform team, so we'd rather just call 'npm run test' (we are pulling in casperjs via npm). However, I get 'python is not recognised as an internal or external command' in VSTS.

I can change package.json from:

```
{
  "scripts": {
    "test": "casperjs test tests --xunit=reports/test_results.xml"
  }
}
```

To:

```
{
  "scripts": {
    "test": "SET PATH=%PATH%;C:/Python27/;C:/Python27/Scripts; && casperjs test tests --xunit=reports/test_results.xml"
  }
}
```

But that breaks the build for my developers working in non-Windows environments. (Although it works in VSTS :smile: )

I'd much rather specify the full path to python.exe via an environment variable which gives me, and others, much greater control in hosted build environments.

I suggest to change .bin/casperjs.cmd from:

```
@IF EXIST "%~dp0\python.exe" (
  "%~dp0\python.exe"  "%~dp0\..\casperjs\bin\casperjs" %*
) ELSE (
  @SETLOCAL
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  python  "%~dp0\..\casperjs\bin\casperjs" %*
)
```

To:

```
@SETLOCAL ENABLEDELAYEDEXPANSION

@IF EXIST "%~dp0\python.exe" (
  "%~dp0\python.exe"  "%~dp0\..\casperjs\bin\casperjs" %*
) ELSE (
  SET PATHEXT=%PATHEXT:;.JS;=;%
  IF NOT DEFINED PYTHON SET PYTHON=python
  !PYTHON! "%~dp0\..\casperjs\bin\casperjs" %*
)
```

Where PYTHON is a Windows environment variable pointing to C:\Python27\python.exe. If PYTHON does not exist, it would fallback to the previous behaviour, ie: 'python', which assumes PATH contains the Python installation directory. I have tested this locally and it works when PATH contains the Python installation directory or when PYTHON is set.

I'd happily make the change and raise a pull-request, but I can't find .bin/capserjs.cmd and I'm not an experienced npm/Node/JS developer (am I missing something?).

Is this a change you'd like to make?

Cheers,
Andy

**Comment by istr** [comment]
Yes... Generally the dependency on a full-fledged python installation should be removed imho.

**Comment by andycodecomplove** [comment]
@istr any update? I can make the change if you can point me in the right direction.

**Comment by istr** [comment]
Simply try to create a PR for that. Alas, the CasperJS members are not so very Windows-centered, so expect the PR to take some time to pass review. Thank you.

**Comment by kensoh** [comment]
Hi @andycodecomplove are you still facing this issue with CasperJS v1.1.4? Looking at casperjs.exe history, it looks like the source code for the Windows executable comes from `src/casperjs.cs`

However I don't know anything more that may be helpful. I'm a CasperJS user and I know Jef (current maintainer) has a lot on his hands. So just browsing through issues. A tool I make is base on CasperJS, so I hope CasperJS to continue supporting new browsers such as Chrome headless. Especially when PhantomJS maintainer just stepped down.
