### ISSUE TITLE
No such file or directory; did you install phantomjs in aws lambda

### ISSUE THREAD

**Issue by deepakgd** [casperjs/casperjs#1636]
**I request you please don't make this duplicate or close this issue without reading fully. i am facing this in AWS lambda not in local system** 

I am using node-lambda. In local my casperjs code working fine.But when i am trying casperjs code in AWS lambda i am getting ` [Errno 2] No such file or directory; did you install phantomjs` in aws lambda error. How to fix this issue?. How can i set path to phantomJS?.

**Comment by mickaelandrieu** [comment]
Hi @deepakgd 

> did you install phantomjs ?

Regards

**Comment by deepakgd** [comment]
Yes in my node_modules there is phantomjs and also I include phantomjs
inside my project root folder

**Comment by deepakgd** [comment]
My code working fine in local but it was not working in AWS lambda

**Comment by mickaelandrieu** [comment]
Humm, would you mind to check if phantomjs is available in the PATH ?

**Comment by BIGjuevos** [comment]
Notably, you can also set the path to phantomjs and casperjs will respect it. I have this configured for each executable environment I have for my setup.

`env PHANTOMJS_EXECUTABLE="node_modules/path/to/executable/phantomjs"`

If neither of our solutions solve your problem.  Please re-open this issue and we can dig deeper into your issues.

@mickaelandrieu This is a common enough question.  Is this worth adding to the FAQ in the docs?
