### ISSUE TITLE
Selftest fails

### ISSUE THREAD

**Issue by BHouwens** [casperjs/casperjs#1638]
I'm getting a complete selftest failure and inability to run even simple scripts. Using CasperJS v1.1.1 and PhantomJS 2.1.1

**Comment by istr** [comment]
Which platform?

**Comment by BHouwens** [comment]
I'm on OSX El Capitan v10.11.4

**Comment by istr** [comment]
Ok, will try to reproduce. Could you tell us how you installed both of them (brew / npm / other?) and what is the output of the self-test?

**Comment by BHouwens** [comment]
I installed both through npm. Just running it now, the tests pass.... I will test on a custom simple script and if I don't run into anything feel free to close this ticket, although setup and installation-wise I haven't changed anything.

**Comment by mickaelandrieu** [comment]
@BHouwens if you can reproduce this issue, please report it again with:
- Operating system
- versions of both casper and phantom
- the installation method: npm, git ?

I close for now, thank you for report :)

**Comment by BHouwens** [comment]
I think this had something to do with a local installation via npm. Version usage for both Casper and Phantom exactly the same, but destroying the `node_modules` and reinstalling now works. Thanks guys

**Comment by mickaelandrieu** [comment]
> I think this had something to do with a local installation via npm. Version usage for both Casper and Phantom exactly the same, but destroying the node_modules and reinstalling now works. Thanks guys

Remember an old issue cause npm had a `fs` module: did you have an error message related to ``fs`` module ?
