### ISSUE TITLE
Release 1.1.2

### ISSUE THREAD

**Issue by mickaelandrieu** [casperjs/casperjs#1639]
Hi,

@istr @BIGjuevos we should release as often as possible. Maybe can we document the process to let any core member do it when available (and when everyone is OK, of course) =)

Mickaël

**Comment by BIGjuevos** [comment]
Sounds good to me.  I know @istr has the most experience.

Further, do we need to grant any more access to npmjs.org, or do we already have sufficient permissions?

**Comment by mickaelandrieu** [comment]
@BIGjuevos I think I have all required permissions but I've never release casperjs.

If @istr can document the process, it would be awesome :+1:

**Comment by istr** [comment]
Ok, nothing very special about it. I will create a doc next weekend.

**Comment by BIGjuevos** [comment]
OK, I've prepped the release and have tagged 1.1.2.  Unfortunately, I don't have npm permissions to be able to actually publish the new version.

Only thing left to do is:
1. publish drafted release in GitHub ([thank you compare feature](https://github.com/casperjs/casperjs/compare/1.1.1...1.1.2))
2. `npm publish ./`

**Comment by istr** [comment]
Added you as a collaborator @ npmjs and published the npm. Thanks a lot for preparing the new release. @BIGjuevos I will do you the honor of publishing the release @ github.

**Comment by istr** [comment]
Installed 1.1.2 by means of npm and ran the self-test successfully.

**Comment by mickaelandrieu** [comment]
Still,  I'm interested on step by step instructions :) 

Thank you both of you for this release!

**Comment by istr** [comment]
@mickaelandrieu Yes, of course... Still unsure where to put this, though.

**Comment by mickaelandrieu** [comment]
@istr by the way, is the casper.exe recompiled for 1.1.2 ?

**Comment by istr** [comment]
@mickaelandrieu good question -- I did not check this. :-(
@BIGjuevos ?

**Comment by BIGjuevos** [comment]
I'll do a recompile and retag just to be sure.

**Comment by RikRakRok** [comment]
Hi ! 
I don't really know if this is the place to post this but ...
One issue I found in the Casperjs 1.1.2 is to click on hiding button ! 
Like for example if I need to put my mouse on a square to display a button, I can click it with casperjs 1.1.2 ! And when I go back to 1.1.1 it's working !! 
Hope it's useful !

**Comment by mickaelandrieu** [comment]
ping @jefleponot for click on hiding button issue :p

**Comment by jefleponot** [comment]
Hi @RikRakRok 

we commit a PR , have a look at #1246

JEF

**Comment by mickaelandrieu** [comment]
@jefleponot if I've well understood:
* since 1.1.2 we can now click on hidden button
* @RikRakRok reports that it is not working on 1.1.2 but works well on 1.1.1

Or do I misunderstand something ? My english is bad (I'm french :p )

**Comment by RikRakRok** [comment]
(Non ! On pouvais déjà le faire en 1. 1.1 puis suite au 1.1.2 on ne pouvait plus du à une erreur je pense. Maintenant cette erreur à été corrigé et on peut cliquer sur un bouton cacher avec le 1.1.1 et 1.1.2)

**Comment by mickaelandrieu** [comment]
:+1: great !

**Comment by jefleponot** [comment]
No

There were a bug in previous version (1.1.1)

You could send an event click on something not visible : that makes no sense
Now to click on an hidden tag, you have to make it visible first and after you can send click event : it saves a lot of inconsistency.

Sorry, this correction requires us to correct some test.

@mickaelandrieu , @istr : do you agree i add an exception when code try to click on hidden tag (in a new PR)?

**Comment by RikRakRok** [comment]
Oh ok I didn't understand.. So I stay with 1.1.1 because its important for me to click on unvisible button.. Because to appear you need to put your mouse i' a specific area and I can't with casperjs

**Comment by jefleponot** [comment]
I had many time this kind of navigation, menu appears not "hover" css .
Just use "casper.mouse.move" to make menu visible.
I could send you code, if you need

**Comment by RikRakRok** [comment]
Non need, I will look at it thanks :)

**Comment by jefleponot** [comment]
you're welcome

**Comment by istr** [comment]
My 2 cents: @jefleponot s bug-fix makes absolutely sense to me. No need to roll that back and/or modify from my point of view.

**Comment by bguerin** [comment]
Hello all,

Great to have this 1.1.2 release.
Maybe we could update the link behind the download button on the site ? ;)

**Comment by BIGjuevos** [comment]
1.1.3 has been released and published with a recompiled binary.  Sorry for the delay people, this is the first opening I had.
