### ISSUE TITLE
Close input tags in site/*.html

### ISSUE THREAD

**Issue by showell** [casperjs/casperjs#1641]
This is a low priority request, but are there any plans to close input tags with `/>` in site/*.html?

I work on a project with old vendored version of casper, and we pass the files through our linter.  We are about to apply the following patch to our vendored files:

https://github.com/zulip/zulip/pull/1198/commits/5392596c01d54a3d7b594ff4c20d8891f7a96bb6

We thought it wouldn't hurt to ask if these could be upstreamed.  Thanks!

**Comment by istr** [comment]
Note that `<input>` is valid HTML / HTML5 and we are using `<!DOCTYPE html>` in our test files, indicating that this is, in fact, HTML5. You only get in trouble if your interpretation / linting presumes XHTML. There are other small problems that render the test cases invalid (e.g. `<input>` as a direct child of `<body>`). We will happily pull this upstream, if you create a PR for that. Some of the illegal code, however, is there in place on purpose, e.g. `<input type="whatever" name="strange" id="strange">`.

**Comment by showell** [comment]
Sorry, I should have clarified that our linter is using XHTML.  Thanks for the context on the strange/strange case--that's good to know for the future.  I'm closing this for now.
