### ISSUE TITLE
1.1.2 release does not work with coffeescripts

### ISSUE THREAD

**Issue by bguerin** [casperjs/casperjs#1644]
I read #1536 and ok, 2.0 will drop support for Coffee ...

But at this time, we are on 1.1, and #1246 included in 1.1.2 breaks support for Coffee scripts ...
This has been fixed with #1642, but this is not in 1.1.2 ...
Please consider releasing a 1.1.3, or at least clearly mention that 1.1.2 will NOT support Coffee scripts

and ok, I will plan to rewrite my 30 test files from Coffee to ... I don't know ...

**Comment by bguerin** [comment]
You are right, I am still on phantomjs 1.9.7

The scenario is different with PhantomJS 2 ? Coffee works with Phantom 2 ?

**Comment by mickaelandrieu** [comment]
@bguerin phantomjs > 2 is not compatible anymore with coffee so you'll need to compile your coffee scripts by yourself before launch your tests. So, you should plan to rewrite your tests, or at least to not use coffee for the next ones :)

@BIGjuevos ok for tomorrow, thank you for your time Ryan !

Mickaël

**Comment by bguerin** [comment]
Thanks guys !

@mickaelandrieu thanks for clarification, ok, this is what I had in mind

**Comment by BIGjuevos** [comment]
1.1.3 has been released.

Cheers everyone.

**Comment by bguerin** [comment]
Yes ! Thanks !

**Comment by bguerin** [comment]
@BIGjuevos 1.1.3 works great, however, `casperjs --version` show 1.1.2 ...
