### ISSUE TITLE
Socket hang up error when trying to use casper.js web service with node.js

### ISSUE THREAD

**Issue by Akhoy** [casperjs/casperjs#1649]
I've created a web service in casper.js and I'm trying to invoke that in node.js. The casper.js script is as below: 

```javascript
var casper = require('casper').create();
var server = require('webserver').create();
var ipAndPort = '127.0.0.1:8585';
var url = "testUrl";
server.listen(ipAndPort, function (request, response) {
casper.start(url, function(){
//bunch of this.then's
});
casper.run(function () {
        response.statusCode = 200;
        response.write("All Done");
        response.close();
    });
});
```

This web service starts properly when invoked from node using a standard `http.get` request but it ends with a **socket hang up** error. Is there something that I'm doing wrong here? Is this issue related to phantom.js or casper.js?

Phantom.js version - 2.1.1
Casper.js version - 1.1.2

**Comment by BIGjuevos** [comment]
That looks pretty straightforward to me.

Darn close to our [example](http://docs.casperjs.org/en/latest/cookbook.html#creating-a-web-service) as well.

`webserver` is a construct of phantomjs.  I encourage you to pull out all of the casperjs stuff and try just a script with phantomjs and see if your problem persists.

In the event the problem goes away, it may be a bug with casperjs.  Please re-open this issue if this is what you experience.

For issues like this, I would also like to refer you to our [mailing list](https://groups.google.com/forum/#!forum/casperjs).  GitHub is not a support forum.
