### ISSUE TITLE
CasperJS 1.1.2 remote debugging bug with expanding «Watch Expressions» vars

### ISSUE THREAD

**Issue by keeprock** [casperjs/casperjs#1650]
I ran a remote debugger panel using:

`casperjs --ssl-protocol=any --ignore-ssl-errors=true --remote-debugger-port=9000 compiled.js`

which is, basically, a pretty standard one.

After I got into an actual debugger, I found out that there is no way I can expand «Watch Expression» variables. You may click on an arrow or try to double click a name - no luck. Clicking on an arrow gives you nothing, double click - opens a rename input.

Grouping attributes like «Scope Variables», «Breakpoints», «DOM breakpoints» are working fine and expand on a click.

Also, I notice that on an «Event Listener Breakpoints» we got a similar structure. I've been able to expand them by multiple clicking rampage. Which is got me to the point that something wrong with it. It would be ok to have that kind of behaviour on the «Watch Expressions» if they were not renaming all the time as I double click on them.

I've searched for any Chrome Debugger option that can help me to set a «one-click» expand, but with no luck.

If this is a PhantomJS issue, I'll be glad to hear it from you and gladly transmit this issue on their Github.

p.s. I got a Dark Reader on my Chrome (reason for dark theme).

Thanks!
![screen shot 2016-07-19 at 08 35 29](https://cloud.githubusercontent.com/assets/5209820/16939813/a5566798-4d8d-11e6-9059-8e86f394001e.png)
![screen shot 2016-07-19 at 08 35 21](https://cloud.githubusercontent.com/assets/5209820/16939812/a556136a-4d8d-11e6-9123-3659e9773c9f.png)

**Comment by kensoh** [comment]
Hi @keeprock yes this sounds like PhantomJS. The remote debugging feature is built into PhantomJS and I assume CasperJS being a wrapper the behavior you experienced is likely the design built into PhantomJS - http://phantomjs.org/troubleshooting.html

**Comment by kensoh** [comment]
However, not sure the state because PhantomJS maintainer recently stepped down. There hopefully will be a passing on of baton! There are also some new changes of headless Chrome and Firefox.

**Comment by kensoh** [comment]
@keeprock closing this issue as it is under PhantomJS domain, but do ping if you have any questions, or email ken@tebel.org. I'm a CasperJS user for couple of years, now browsing through open issues to see if anything I can help out.
