### ISSUE TITLE
Doc Cookbook - script 404 broken (because end of google code)

### ISSUE THREAD

**Issue by pieplu** [casperjs/casperjs#1651]
Hi!

This script [404-and-500-errors](http://docs.casperjs.org/en/latest/cookbook.html#script-to-automatically-check-a-page-for-404-and-500-errors) is broken. The URI.js code is no longer accessible.

I correct the script, but it's with 2 files...

The URI lib: https://gist.github.com/pieplu/6be55d1d8f27ea9b8dcf4de6b1933547
And the script corrected: https://gist.github.com/pieplu/a19d925c31a1d1d41b7226f8186af48b

I don't know what is the best way for correct that.

**Comment by jefleponot** [comment]
Hi @pieplu,

Could you propose a PR ?

**Comment by pieplu** [comment]
Why not, but I don't think that the URI.js lib is not intersting on the doc, but needed. Can we store that on the repo? Or on any other place?

**Comment by kensoh** [comment]
Hi @pieplu or maybe store directly at your gist? Then PR can be made on `docs/cookbook.rst`

https://gist.githubusercontent.com/pieplu/6be55d1d8f27ea9b8dcf4de6b1933547/raw/54f4434c1d77a3b090089032d1e5f8f18be800fd/URI.js

**Comment by pieplu** [comment]
Thanks @kensoh, I forget it! #1828

**Comment by kensoh** [comment]
@pieplu Jef had merged your PR into master. Closing the issue, and thanks again!
