### ISSUE TITLE
Is it possible to catch errors from injected scripts after the DOM is loaded?

### ISSUE THREAD

**Issue by GaryKing** [casperjs/casperjs#1654]
I've got the following code, in two files, casper.js (the main file), and inject.js (which is injected).

In inject.js, if there's a JavaScript error, and the code is run after the DOM is loaded (such as within jQuery's .ready() block), then no error will appear in Casper. This isn't a problem if the code is run immediately.

Is it possible to get an error even if the injected code runs after the DOM? Check the comments for more details.

**casper.js**

```javascript
// Include Casper's "utils" so we can dump variables.
var require = patchRequire(require);
var utils = require('utils');

// Open a URL and inject our JS.
var casper = require('casper').create();
casper.start('http://example.com/', function() {
  casper.page.injectJs('inject.js');
});

// Wait a moment to give everything time to load, then check that the function
// exists and returns something.
casper.wait(1000, function() {
  var testValue = casper.evaluate(function() {
    return test();
  });

  casper.echo(testValue);
});

// If there are any errors along the way, then print them.
casper.on('page.error', function(msg, trace) {
  casper.echo(msg);
  casper.echo(utils.dump(trace));
});

// Actually run everything.
casper.run();
```

**inject.js**

```javascript
// Be strict on this page so that errors occur.
'use strict';

function run() {
  window.test = function() {
    // An error will occur here because the variable was never declared.
    testing = 'test';
    return testing;
  }
}

// If the below line is used, then "ReferenceError: Strict mode forbids implicit
// creation of global property 'string'" appears as expected.
// run();

// If the below line is used instead of the one above, then the same error does
// not appear.
document.addEventListener('DOMContentLoaded', run);
```

**Comment by jefleponot** [comment]
an "if" is required

```js
// Be strict on this page so that errors occur.
"use strict";

function run() {
  window.test = function() {
    // An error will occur here because the variable was never declared.
    var testing = 'test';
    return testing;
  }
}

// If the below line is used instead of the one above, then the same error does
// not appear.
if (document.readyState === "complete"){
// If the below line is used, then "ReferenceError: Strict mode forbids implicit
// creation of global property 'string'" appears as expected.
    run();
} else {
// If the below line is used instead of the one above, then the same error does
// not appear.
    document.addEventListener('DOMContentLoaded', run);
}

```

**Comment by GaryKing** [comment]
Is it possible to also make this work with jQuery's $(document).ready(), which uses DOMContentLoaded?

**Comment by jefleponot** [comment]
casper.on('page.initialized',function(){
   casper.page.injectJs('inject.js');
});

**Comment by GaryKing** [comment]
I've tried all of these but they don't return an error if the injected script runs after the DOM is loaded.

Sorry if I wasn't clear, but my situation is that inject.js uses jQuery's $(document).ready() to run code. Because this code only runs after the DOM is finished loading, Casper doesn't catch any errors that occurs in this code, when checking the "page.error" event.

Is there a way for Casper to catch errors that occur even in injected code that runs after the DOM is done loading (which uses jQuery's $(document).ready())?

**Comment by BIGjuevos** [comment]
You should be listening for a `remote.message` or a `remote.error` of the page has already loaded.

**Comment by GaryKing** [comment]
Excellent thanks, I managed to figure things out. page.error ultimately did the trick, but remote.message was also helpful in debugging my injected script with console.log().
