### ISSUE TITLE
"Invalid regexp" if pattern begins with a capitalized character.

### ISSUE THREAD

**Issue by GaryKing** [casperjs/casperjs#1655]
I've got a weird bug, where if I use test.assertMatch() and the pattern begins with a capital, or contains a single letter, then I get "error: Invalid regexp.". I checked the Casper source and I'm not sure why this would happen.

**Errors:**

`test.assertMatch(newLinks.text, /F/);`
`test.assertMatch(newLinks.text, /f/);`
`test.assertMatch(newLinks.text, /Fin/);`

**No errors:**

`test.assertMatch(newLinks.text, /fi/);`

I even tested:

`typeof /F/`

Which equals `object`. But I know that Casper does this instead:

`Object.prototype.toString.call(/F/).match(/^\[object\s(.*)\]$/)[1].toLowerCase()`

And I end up with `regexp` as I should.

**Comment by BIGjuevos** [comment]
what happens if you try to create it with a `new RegExp` instead?

**Comment by GaryKing** [comment]
I get the same error.

**Comment by GaryKing** [comment]
Turns out that the error was referring to another line in my file rather than the one I kept changing, although the information I stated in my original post is still true; as in, changing a seemingly unrelated regex match would suppress the error message.
