### ISSUE TITLE
Accept @jefleponot as a new core team member

### ISSUE THREAD

**Issue by mickaelandrieu** [casperjs/casperjs#1658]
Hi @casperjs/contributors,

@jefleponot already proposed his help to maintain casperjs. I no longer use CasperJS (PrestaShop tests are based on mocha/chai/webdriver.io) so It's difficult to me to follow the news and decide as I'm not realy concerned anymore.

Jef works a lot with CasperJs, he's good and we need fresh blood you know.

This is why, except if someone is _realy_ opposed to new members, I'd like to add him as part of team.

ping @casperjs/contributors 

Mickaël

**Comment by jefleponot** [comment]
@mickaelandrieu, Thank you for your proposition

**Comment by BIGjuevos** [comment]
@casperjs/contributors I have no objections and no opposition.

I think we should get @istr on board with a proposition like this.

**Comment by mickaelandrieu** [comment]
As no one seems against a new team member and because we still need fresh blood, I will invite him to be part of core team :)

**Comment by jefleponot** [comment]
I accepted your invitation.
I try to contact @istr but no response.

**Comment by mickaelandrieu** [comment]
Welcome :)

We have 2 rules:
* never merge his own pull requests
* wait for 2 reviews (sounds hard theses times as most of the team is unactive :/)

Mickaël

**Comment by jefleponot** [comment]
it seems logical.
Thank you for everything.

Jef 

how should we deal with the issues (label, close, ...) ?

**Comment by jefleponot** [comment]
another thing, could you please tell me who we can rerun travis tests ?

**Comment by mickaelandrieu** [comment]
Of course you can use labels or create new ones if needed, you can close every old or irrelevant anymore issue.

You should be able to re run travis tests, I will do it else :)

I'm sorry to not be that active, I have so much work with PrestaShop.
