### ISSUE TITLE
utils dump output difficult to read, not like docs

### ISSUE THREAD

**Issue by bitwombat** [casperjs/casperjs#1660]
When I do this in 1.1.0-beta3:

```
require('utils').dump(casper.steps.map(function(step) {
    return step.toString();
}));
```
Verbatim, from [the docs][(http://docs.casperjs.org/en/latest/modules/utils.html)

I don't get this:

```
[
    "function step1() { this.echo('this is step one'); }",
    "function step2() { this.echo('this is step two'); }",
    "function _step() { this.open(location, settings); }",
    "function step3() { this.echo('this is step 3 (google.com is loaded)'); }"
]
```

I get something like this:
```
    "function _step() {\n        this.open(location, settings);\n    }",
    "function () {\n    this.log(\"YEP\", \"info\");\n    this.log(this.getTitle(), \"info\");\n}",
    "function _step() {\n        this.waitStart();\n        var start = new Date().getTime();\n        var 
condition = false;\n        var interval = setInterval(function _check(self) {\n            /*jshint 
maxstatements:20*/\n            if ((new Date().getTime() - start < timeout) && !condition) {\n                
condition = testFx.call(self, self);\n                return;\n            }\n            self.waitDone();\n            if 
(!condition) {\n                self.log(\"Casper.waitFor() timeout\", \"warning\");\n                var 
onWaitTimeout = onTimeout ? onTimeout : self.options.onWaitTimeout;\n                
self.emit('waitFor.timeout', timeout, details);\n                clearInterval(interval); // refs 
#383\n                if (!utils.isFunction(onWaitTimeout)) {\n                    throw new CasperError('Invalid 
timeout function');\n                }\n                try {\n                    return onWaitTimeout.call(self, 
timeout, details);\n                } catch (error) {\n                    self.emit('waitFor.timeout.error', 
error);\n   

```

But longer.

I get that that's the actual code being executed at every step, but is that look what's intended?  I'm having trouble correlating the steps shown in the dump with my source code.

**Comment by BIGjuevos** [comment]
The output looks string encoded.  That is easy enough to handle with some regex.

As far as the functions go, you should try naming your lambdas to something more descriptive.  That should help in your backtracking.

**Comment by bitwombat** [comment]
> As far as the functions go, you should try naming your lambdas to something more descriptive. That 
> should help in your backtracking.

Yes, sorry, I do (I read the Debugging section of the docs after original post).

Sure I could replace the \n's with real line feeds, but I'm still going to be seeing a lot of internal code for every waitFor (turns out that's what's causing the large output).

I'm asking whether the team considers this a bug/feature request or not.

**Comment by BIGjuevos** [comment]
My understanding of the dumps is that it gives you an idea of what casper is going to do, and thus I would expect it to show off the internals of what it is actually doing.  The presumption behind this is that if you are dumping all of the steps, you are probably debugging casper anyways.

If you are after what you have already given casper, then you already have that in your source code.

If you are looking for something else that is not in either of the two cases, can you provide an example of what your code would look like and what the output should look like?

I do concur that the output should look better and not be encoded like that.

The project ultimately reflects the needs of the users, so I'd like to know what you expect.

**Comment by bitwombat** [comment]
Yes, I'm trying to debug things, but 95% of the output is casper internal code.

How about something like this (with the total number of steps incrementing as they do so they line up with the other debug output)?

```
    step _step 1/5: {
        this.open(location, settings);
    }

    step step1 2/6: {
        this.log("Yep, got here", "info");
        this.log(this.getTitle(), "info");
    }

    step _step 3/6:  <internal waitFor>
```

**Comment by BIGjuevos** [comment]
I like the idea.  Would you be willing to put a PR up so we can discuss it?

**Comment by bitwombat** [comment]
Sure, will do.  Will put (my attempt at) the code change on "The List" :)
