### ISSUE TITLE
Custom user-agent not work in popups

### ISSUE THREAD

**Issue by Twi1ight** [casperjs/casperjs#1662]
Use capser.userAgent set custom useragent string, but this not working in popup requests

I'm using Windows 10 and CasperJS version 1.1.2 and Phantomjs 2.1.1

testing code:
`var casper = require('casper').create({
    logLevel: "debug",
    verbose: true
});
var utils = require('utils');

casper.userAgent('Casperjs Test UserAgent');
casper.on('page.resource.requested', function (requestData, request) {
    utils.dump(requestData);
});

// window.open
casper.on('popup.created', function (newpage) {
    newpage.onResourceRequested = function (requestData, request) {
        utils.dump(requestData);
    };
});

casper.start('http://httpbin.org');

casper.then(function () {
    this.evaluate(function () {
        window.open('http://yahoo.com');
    })
});

casper.run();`

outputs:

> casperjs popup.js
> [info] [phantom] Starting...
> [info] [phantom] Running suite: 3 steps
> [debug] [phantom] opening url: http://httpbin.org/, HTTP GET
> [debug] [phantom] Navigation requested: url=http://httpbin.org/, type=Other, willNavigate=true, isMainFrame=true
> {
>     "headers": [
>         {
>             "name": "Accept",
>             "value": "text/html,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8"
>         },
>         {
>             "name": "User-Agent",
>             "value": "Casperjs Test UserAgent"
>         }
>     ],
>     "id": 1,
>     "method": "GET",
>     "time": "2016-07-31T11:13:34.662Z",
>     "url": "http://httpbin.org/"
> }
> [debug] [phantom] url changed to "http://httpbin.org/"
> [debug] [phantom] Successfully injected Casper client-side utilities
> [debug] [phantom] start page is loaded
> [info] [phantom] Step anonymous 3/3 http://httpbin.org/ (HTTP 200)
> {
>     "headers": [
>         {
>             "name": "Accept",
>             "value": "text/html,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8"
>         },
>         {
>             "name": "Referer",
>             "value": "http://httpbin.org/"
>         },
>         {
>             "name": "User-Agent",
>             "value": "Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/538.1 (KHTML, like Gecko) PhantomJS/2.1.1 Safari/538.1"
>         }
>     ],
>     "id": 1,
>     "method": "GET",
>     "time": "2016-07-31T11:13:40.269Z",
>     "url": "http://yahoo.com/"
> }
> [info] [phantom] Step anonymous 3/3: done in 5637ms.
> [info] [phantom] Done 3 steps in 5653ms
> [debug] [phantom] Navigation requested: url=about:blank, type=Other, willNavigate=true, isMainFrame=true
> [debug] [phantom] url changed to "about:blank"

**Comment by jefleponot** [comment]
Hi @Twi1ight,

When a popup occurs, casperJS doesn't copy main page property or method. This is why you have to redo an initialization of userAgent.

```js
 casper.on("popup.created", function create(popup) {
        popup.settings.userAgent ='Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1)';
});
```

@BIGjuevos , @Istr, @mickaelandrieu , what do you think about this kind of operation ?
Regards

**Comment by BIGjuevos** [comment]
Is keeping these settings regardless of the page us making assumptions about the user's environment that is best kept in their bootstrapping and configuration?

**Comment by jefleponot** [comment]
Hi @BIGjuevos ,

The trouble with casper.userAgent method is that ist name suggests the userAgent of the browser (not only the current page) will be changed.

2 solutions : 
- renamed the method casper.userAgentPage
- apply userAgent to the wholly browser configuration.

I was even surprised the first time I used it as @Twi1ight .

**Comment by mickaelandrieu** [comment]
> renamed the method casper.userAgentPage

the first step could be to precise this state in docs :)

**Comment by tmallery** [comment]
This is a bug phantomjs, https://github.com/ariya/phantomjs/issues/11884.
I found that the code below doesn't work. I saw in the proxy log that created the page was requested with the same default phantomjs user-agent no matter what I set. 
```javascript
casper.on("popup.created", function create(popup) {
        popup.settings.userAgent ='Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1)';
});
```

**Comment by jefleponot** [comment]
HI @tmallery,
I push a PR #1118 that solves this trouble for PhantomJS > 2 and SlimerJS > 0.9.0

**Comment by kensoh** [comment]
Wanted to confirm that this is now working. Using same script from @Twi1ight the output is -

```
[info] [phantom] Starting...
[info] [phantom] Running suite: 3 steps
[debug] [phantom] opening url: http://httpbin.org/, HTTP GET
[debug] [phantom] Navigation requested: url=http://httpbin.org/, type=Other, willNavigate=true, isMainFrame=true
{
    "headers": [
        {
            "name": "Accept",
            "value": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
        },
        {
            "name": "User-Agent",
            "value": "Casperjs Test UserAgent"
        }
    ],
    "id": 1,
    "method": "GET",
    "time": "2017-05-23T15:47:17.456Z",
    "url": "http://httpbin.org/"
}
[debug] [phantom] url changed to "http://httpbin.org/"
[debug] [phantom] Successfully injected Casper client-side utilities
[debug] [phantom] start page is loaded
[info] [phantom] Step anonymous 3/3 http://httpbin.org/ (HTTP 200)
[debug] [phantom] Navigation requested: url=http://yahoo.com/, type=Other, willNavigate=true, isMainFrame=true
{
    "headers": [
        {
            "name": "Accept",
            "value": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
        },
        {
            "name": "Referer",
            "value": "http://httpbin.org/"
        },
        {
            "name": "User-Agent",
            "value": "Casperjs Test UserAgent"
        }
    ],
    "id": 1,
    "method": "GET",
    "time": "2017-05-23T15:47:23.109Z",
    "url": "http://yahoo.com/"
}
[info] [phantom] Step anonymous 3/3: done in 5702ms.
[debug] [phantom] Navigation requested: url=https://www.yahoo.com/, type=Other, willNavigate=true, isMainFrame=true
{
    "headers": [
        {
            "name": "Accept",
            "value": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
        },
        {
            "name": "Referer",
            "value": "http://httpbin.org/"
        },
        {
            "name": "User-Agent",
            "value": "Casperjs Test UserAgent"
        }
    ],
    "id": 2,
    "method": "GET",
    "time": "2017-05-23T15:47:23.434Z",
    "url": "https://www.yahoo.com/"
}
[debug] [phantom] url changed to "https://www.yahoo.com/"
{
    "headers": [
        {
            "name": "Accept",
            "value": "text/css,*/*;q=0.1"
        },
        {
            "name": "Referer",
            "value": "https://www.yahoo.com/"
        },
        {
            "name": "User-Agent",
            "value": "Casperjs Test UserAgent"
        }
    ],
    "id": 3,
    "method": "GET",
    "time": "2017-05-23T15:47:23.837Z",
    "url": "https://s.yimg.com/os/fp/atomic-css.7822879f.css"
}
{
    "headers": [
        {
            "name": "Accept",
            "value": "text/css,*/*;q=0.1"
        },
        {
            "name": "Referer",
            "value": "https://www.yahoo.com/"
        },
        {
            "name": "User-Agent",
            "value": "Casperjs Test UserAgent"
        }
    ],
    "id": 4,
    "method": "GET",
    "time": "2017-05-23T15:47:23.838Z",
    "url": "https://s.yimg.com/zz/combo?/os/stencil/3.1.0/styles-ltr.css&/os/yc/css/bundle.c60a6d54.css"
}
```

**Comment by kensoh** [comment]
@Twi1ight closing this for now as it works with v1.1.4. Do ping here again if you run into issue with the same code for v1.1.4. Thanks for raising this!
