### ISSUE TITLE
Promises in CasperJs?

### ISSUE THREAD

**Issue by RichardJECooke** [casperjs/casperjs#1663]
Hi, this is a documentation feature request. The docs don't explain how Casper uses promises.

There is a .then() function, but it isn't on all classes? It's not explained how it works.

Most other functions look like that awful old-fashioned nested callback style.

**Comment by BIGjuevos** [comment]
`.then` is more of a concept of steps than promises. 

How do you think we could make this more clear in the documentation?

**Comment by RichardJECooke** [comment]
Oh, thats sad. Our code base tries to use `await` everywhere to avoid dozens of nested chains and callback functions.

It would great if somewhere on the home page of your docs you could state that you don't support ES6 and promises, or at least in the `then()` documentation - cos that name is confusing.

**Comment by jefleponot** [comment]
Hi @RichardJECooke,

support of ES6 not depends on CasperJS but your headless browser.
PhantomJS version is not yet compatible to ES6
But it works with SlimerJS 0.10.0 :-)

**Comment by jefleponot** [comment]
CasperJS goals is to harmonize headless browser execution so the main loop for BC couldn't use promise methods

**Comment by BIGjuevos** [comment]
Theoretically, casperjs is ES version agnostic. The ultimate dependency is the headless browser you choose to use as jef pointed out.

**Comment by mlalpho** [comment]
Can someone submit a PR for the documentation to clarify the support for promises?

Perhaps require ES6+ for 2.0 so that CasperJS can use promises at its core?

**Comment by jefleponot** [comment]
@RichardJECooke @BIGjuevos 
Next phantomJS version (2.5) allows to use Promises as SLimerJS does.
It could be a real improvement for CasperJS to integrate "Promises". For BC we could inject 
extern library like https://github.com/stefanpenner/es6-promise.

Do you agree to add this feature in casperJS 2.0 ?

**Comment by kensoh** [comment]
Adding on, the recent news with Vitaly stepping down as PhantomJS maintainer may mean that BC planning could only be with reference to the current PhantomJS v2.1.1.

**Comment by kensoh** [comment]
Also tagging on for reference the status of PhantomJS - https://github.com/ariya/phantomjs/issues/14946#issuecomment-303985078

**Comment by kensoh** [comment]
Bumping up the thread for review. I've seen some PhantomJS related commits from Vitaly in early July. But there's also a wave of new Chrome-based tools. Most recently the Puppeteer project from Chrome team. Not sure if considering that project for CasperJS migration is viable, to support Chrome browser.
