### ISSUE TITLE
Can someone use withPopup successfully？

### ISSUE THREAD

**Issue by zhangjh** [casperjs/casperjs#1665]
My casperjs version is 1.1.3 and phantomjs version is 2.1.1 .

My question is why I can not use withPopup to switch to another popup window? I can do this in version 1.1.1-beta & 1.9.8.

My code is like this:

```
casper.click(btn);
casper.waitForPupup(/pattern/,function(){
    casper.withPopup(/pattern/,function(){
         ......
    });
});
```

When I run this case, it always return "`error: /pattern/ did not pop up in 5000ms`"

**Comment by kensoh** [comment]
@zhangjh I'm able to use waitForPopup and withPopup. But I am running v1.1.4. Does it still happen for you with v1.1.4?

**Comment by kensoh** [comment]
@zhangjh wanted to confirm that the 2 work on v1.1.4. Closing the issue for now but do ping if you still have issue with the same code running on v1.1.4. Thanks for raising this!
