### ISSUE TITLE
 Whether the cookie or proxy will interfere with each other in multiple processes

### ISSUE THREAD

**Issue by mingshi** [casperjs/casperjs#1667]
i am not sure whether the cookie or proxy will interfere with each other when i run multiple casper processes with python mutiple processes module.

for example:
i start two processes at the same time like : 
`casperjs --cookies-file=test.txt --proxy=1.1.1.1 a.js`
`casperjs --cookies-file=test1.txt --proxy=2.2.2.2 a.ja`

i wanner know whether the cookies info or proxy info will interfere between the two processes ?

anyone know ?

**Comment by kensoh** [comment]
Hi @mingshi if I understand correctly, CasperJS/PhantomJS is not meant to run in parallel. Using separate installations isolated from each other might help. But for the Python multiple processes module even with isolated instances it still needs testing to see if something breaks. Have you tried running some tests?

**Comment by mingshi** [comment]
yes, i have runed some tests which provd that there will be no impact between processes.

**Comment by mingshi** [comment]
@kensoh 
yes, i have runed some tests which provd that there will be no impact between processes.

**Comment by kensoh** [comment]
@mingshi thanks for tip! I'm picking up Python now to integrate SikuliX with a project I'm working on. Another bottleneck for me on my VPS with 2GB is I think reasonably it can only handle 2 CasperJS/PhantomJS processes. Base on stats from top command.

**Comment by mingshi** [comment]
@kensoh i think it's depending on your server cpu cores and memery size.
CasperJS developed based on PhantomJS, we runed it on headless mode, so we can start several hundred processes concurrently。However，the headless mode does not have some of the inherent features of the browsers，finally we chosed selenium + python

**Comment by kensoh** [comment]
@mingshi thanks for sharing! I see.. I should try to load test my VPS to see how many sessions I can run concurrently. Right now I just use a shell script cronjob to manage a queue so only 1 process can run at any 1 time.

In my previous job, we once used Selenium Firefox farm to load test an app. I think it was 10 laptops each with 10 Firefox tabs. As you know that is not good way to load test, so we go back to LoadRunner.

**Comment by kensoh** [comment]
Forgot to close, since the answer is not interfere. Good reference for next person to ask this. Mingshi's implementation is using Python multiple processes module.
