### ISSUE TITLE
webpage html body loaded by javascript evaluate still fails

### ISSUE THREAD

**Issue by andreinoel** [casperjs/casperjs#1671]
hello I want to scrape a website but the content of the website is loaded through a script so the view source is just some html and javascript but on the developer console elements It's a full website with all the divs. I tried using evaluate just to echo out one word from the webpage but it returns null

`var fs = require('fs');
var casper = require('casper').create({
    loadImages: true,
    loadPlugins: true,
    verbose: true,
    logLevel: "debug",
   pageSettings: {
        javascriptEnabled: true,
        userAgent: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/536.5 (KHTML, like Gecko) Chrome/19.0.1084.9 Safari/536.5',
    },
});
var x;
casper.start("http://example.com");
casper.wait(5000,function (){
	this.echo("I waited");
   
});

casper.then( function(){
	x = this.evaluate(function(){
		return document.getElementById('footer_login_link').textContent;
       });
});

casper.run(function(){
    this.exit();
});`

so the document.getElementById('footer_login_link').textContent is returning null but when I type it on the developer console it returns the "login" word

**Comment by BIGjuevos** [comment]
Seems like whatever engine you are using is encountering some issues.

I encourage you to look at the debugging toolkits provided to you by CasperJS and PhantomJS.

CasperJS: http://docs.casperjs.org/en/latest/debugging.html
PhantomJS: http://phantomjs.org/troubleshooting.html

In the event you can convert this into a reproducible bug that traces it's way back to CasperJS, I encourage you to re-open this issue with details on how to reproduce the bug.
