### ISSUE TITLE
clientScripts inject bug

### ISSUE THREAD

**Issue by brian6peng** [casperjs/casperjs#1672]
Hello,  I want to inject some client scripts, but I find that it is not always injected correct. However,  `ClientUtils` is always injected correct. Maybe the function `injectClientScripts` should be called in the function `evaluate` just like  function `injectClientUtils` be called.  Anything advise?

**Comment by BIGjuevos** [comment]
Do you have a way to minimally reproduce this?

**Comment by kensoh** [comment]
@brian6peng does this still happen for you with v1.1.4? I'm a CasperJS user just looking through the issues. Have not encountered this use case myself.

**Comment by kensoh** [comment]
Hi @brian6peng not sure if this issue is resolved for you with latest CasperJS v1.1.4 and PhantomJS v2.1.1? Closing this for now but please reopen if it is still happening. Thanks for raising this!
