### ISSUE TITLE
: No such file or directory - After linux install

### ISSUE THREAD

**Issue by csimpi** [casperjs/casperjs#1680]
Hi!
I installed casperjs (phantomJS installed before, i can use it and run it from everywhere etc)
$ cd ~
$ git clone git://github.com/casperjs/casperjs.git
$ cd casperjs
$ ln -sf `pwd`/bin/casperjs /usr/local/bin/casperjs

I get this message after run casperjs xy.js:
: No such file or directory

Phantomjs works, and phantom binary linked to /usr/local/bin like casperJS

**Comment by jefleponot** [comment]
you need the environment variable PHANTOMSJS_EXECUTABLE

$ export PHANTOMSJS_EXECUTABLE=/usr/local/bin/phantomjs
$ casperjs xy.js

Regards
