### ISSUE TITLE
Regression on viewportsize

### ISSUE THREAD

**Issue by rippo** [casperjs/casperjs#1681]
Not sure whether this is a regression in phantom or casper. But I have a simple responsive site in bootstrap that has a collapsable menu . Nothing has changed on that site.  

I upgraded from 1.0.5-beta to 1.1.3

This USED to work FINE on all beta versions, that is even on the default view port size  (400px)

```
casper.test.begin('Navigation test', 2, function (test) {

    casper.start("http://localhost:43504", function () {
        test.assertTitle("Home - CasperJS Mvc");
    });

    casper.thenClick("ul > li:nth-child(2) > a", function () {
        test.assertUrlMatch("/home/about", "URL ends with: /home/about");
    });

    casper.run(function () {
        test.done();
    });
});
```

Basically it cannot find the second a[href]

However if I add a default viewportSize eg.

```
casper.options.viewportSize = { width:768, height:600 }
```

everything passes as the menu is shown, is this now the default behavoiur? Do I always need now to specify a viewportSize?

If the menu is collapsed (767px or smaller) e.g.

```
casper.options.viewportSize = { width:767, height:600 }
```

then it fails.

**Comment by kensoh** [comment]
@rippo interesting scenario.. I haven't encountered something like this because I always define the size. Not sure if it happens for you in v1.1.4. If it is a regression it probably will still happen.

**Comment by kensoh** [comment]
I searched the code, can't find where this could happen. Although there is a bug fix commit a year+ ago which has references to the viewportsize of the page object.

https://github.com/casperjs/casperjs/commit/0f622e7ea225054b59b80c27c305194661c9c822

Also, documentation says PhantomJS default viewport is 400 x 300 and CasperJS doesn't overwrite it by default. Sounds like either some change in CasperJS logic or PhantomJS reduction in default viewport size could contribute to this. But it worked for you at 400 previously. So maybe something related to above commit, but am not sure.

http://docs.casperjs.org/en/latest/modules/casper.html#viewportsize

**Comment by rippo** [comment]
Strange. Most likely a Phantom regression or "feature" Thanks for looking. We can close if you like

**Comment by kensoh** [comment]
Ok @rippo, thanks for adding on your inputs. At the moment there isn't any other open issue on this behaviour. But I'll keep a lookout for new issues for this scenario, then reopen or tag to this issue as needed.
