### ISSUE TITLE
Switch to iframe based on selector

### ISSUE THREAD

**Issue by csimpi** [casperjs/casperjs#1682]
Hi!
There is an iframe without name.
How can i fill a form inside an iframe based on its id?
switchToChildFrame(0) isn't works.

Thank you!
Peter

**Comment by csimpi** [comment]
My solution is:
**You have to use --web-security=no parameter**

```
casper.thenEvaluate(function(){    
    var ifr = document.getElementById( 'iframeID' );
    var ifrDoc = ifr.contentDocument || ifr.contentWindow.document;
    var pwdi = ifrDoc.getElementById( 'my-input-id' ).value='John Doe';
 })
```

**Comment by jefleponot** [comment]
you have to use the "withFrame" method.

```js
casper.withFrame(  ==>  number of frame or iframe <==, function() {
    this.test.assertTitle('FRAME TITLE');
    this.fill('form#contact-form', {
        'subject':    'I am watching you',
        'content':    'So be careful.',
        'civility':   'Mr',
        'name':       'Chuck Norris',
        'email':      'chuck@norris.com',
        'cc':         true,
        'attachment': '/Users/chuck/roundhousekick.doc'
    }, true);
});
```

Regards

**Comment by csimpi** [comment]
Hi! As i said,my iframe has no name attribute, and some resason withFrame method works only name or number of iframe, and i can't use selector :(
I tried use number of frame but it isn't worked.
But i posed my solution before.

**Comment by jefleponot** [comment]
IFRAMES has position so just pass your iframe position in withFrame method :-)

**Comment by jefleponot** [comment]
withFrame(String|**Number** frameInfo, Function then)

**Comment by csimpi** [comment]
**I tried use number of frame but it isn't worked.**

**Comment by jefleponot** [comment]
it begin to 0

**Comment by csimpi** [comment]
Yes, i know, i coding from when i was 7 years old, so yes, i know :))) Ty

**Comment by jefleponot** [comment]
ah ok,ty
