### ISSUE TITLE
Logger module: Misleading doc

### ISSUE THREAD

**Issue by 1dal** [casperjs/casperjs#1683]
Hi, 
in docs: 

_You can also dump a JSON log of your Casper suite just by rendering the contents of the Casper.logs property:_
`
var casper = require('casper').create({
// ...
casper.run(function() {
    require('utils').dump(this.logs);
    this.exit();
});
`

This is not working. Dump line can be replaced with `utils.dump(this.result.log);`. 
Sorry for bad english.

**Comment by mickaelandrieu** [comment]
Hi @onedal88 would you mind to do a pull request to update the example in docs ?

Thank you

Mickaël

**Comment by onedal88** [comment]
Hi @mickaelandrieu,  #1691 

Thank you.

**Comment by kensoh** [comment]
@1dal your update looks to be in the latest documentation - http://docs.casperjs.org/en/latest/logging.html

**Comment by kensoh** [comment]
@1dal your push is now in latest documentation - http://docs.casperjs.org/en/latest/logging.html

**Comment by kensoh** [comment]
Thanks @1dal ! Closing this for now, not sure why your commit wasn't reflected as merged. But your changes are now in the latest doc.

**Comment by 1dal** [comment]
Hi, thank you! :)
