### ISSUE TITLE
CasperJS randomly stops

### ISSUE THREAD

**Issue by csimpi** [casperjs/casperjs#1684]
Hi!

Is there any variable limits in casperJS?
I have a huge URL list (300 url). I use eachthen and thenopen to open all url and evaluate some datas. 
When i use my script with 1-10 url it is run well, but when i use 50+ url casperjs randomly stops (sometimes it can get through all url). 
I can think to overflow or something similar error. 
Anybody with similar problem?

Peter

**Comment by csimpi** [comment]
I keep digging, and i can't find solution.
I have a script what step through a link all pages, and put all pages all links to a variable. 
I'ts a huge list with ~15000 url.
The script crashes without debug error message after ~100 pages (4800 url)

```
[info] [phantom] Step anonymous 536/5212: done in 358072ms.
[info] [phantom] Step anonymous 537/5213 http://www.aliexpress.com/item/BOSCK-8321J-men-s-fashion-watches-luxury-watch-brand-business-double-calendar-quartz-watch-waterproof-casual/32734494322.html?ws_ab_test=searchweb201556_0,searchweb201602_2_10057_10056_10065_10068_10055_10054_10069_301_10059_10058_10032_10073_10017_10070_10060_10061_10052_10062_10053_10050_10051,searchweb201603_2&btsid=982a6c9a-96cf-494a-9c71-2f21ac674b78 (HTTP 200)
[info] [phantom] Step anonymous 537/5213: done in 358106ms.
[info] [phantom] Step anonymous 538/5213 http://www.aliexpress.com/item/BOSCK-8321J-men-s-fashion-watches-luxury-watch-brand-business-double-calendar-quartz-watch-waterproof-casual/32734494322.html?ws_ab_test=searchweb201556_0,searchweb201602_2_10057_10056_10065_10068_10055_10054_10069_301_10059_10058_10032_10073_10017_10070_10060_10061_10052_10062_10053_10050_10051,searchweb201603_2&btsid=982a6c9a-96cf-494a-9c71-2f21ac674b78 (HTTP 200)
[info] [phantom] Step anonymous 538/5213: done in 358139ms.
PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.
Segmentation fault (core dumped)
```

**Comment by mickaelandrieu** [comment]
The error is self described. You should report the issue to phantomJS core team.

Give a try to SlimerJs also, you can use it with CasperJS.
