### ISSUE TITLE
thenOpen inside eachThen opens wrong url

### ISSUE THREAD

**Issue by csimpi** [casperjs/casperjs#1685]
```
    casper.eachThen(itemlinks, function(response) {
        var url = response.data;
        this.echo('URL:'+url);
        //this.captureSelector('itemDetailsasdasd.png', 'html');
        casper.thenOpen(url, function() {
```

**Result**

```
URL:http://www.full-serie.com/seriestv/594-high-maintenance-saison-1-episode-1.html
Series VOSTFR » Page 2 - Série TV en Streaming ( YouWatch - VOSTFR - VF - vk streaming - Full Serie ) -
 http://www.full-serie.com/series-vostfr/page/2/
```

WTF?
You can see url variable contents new url (http://www.full-serie.com/seriestv/594-high-maintenance-saison-1-episode-1.html), thenOpen open it, but after open the title, url and screenshot is the old url. thenOpen don't open URL in url variable. 
currentURL != url
Why?

**Comment by krazyjakee** [comment]
WOW nearly 3 months!

Their documentation for [eachThen](http://docs.casperjs.org/en/latest/modules/casper.html#eachthen) uses this exact example and it's failing. Probably worth writing a test for this.

**Comment by mlalpho** [comment]
@jefleponot @istr @mickaelandrieu @BIGjuevos  can we get this labeled? Needs testing? Bug? Confirmed?

**Comment by krazyjakee** [comment]
It looks like if there are any failures in `thenOpen` then it echoes the title of the last working instance. OP, like me, may have not been running or had failures running his local test server. The issue is that the example should be updated to check that the `thenOpen` was actually successful before echoing the title.

**Comment by mlalpho** [comment]
@krazyjakee would you be willing to submit a PR for the documentation example and note the expectations?

**Comment by kensoh** [comment]
I haven't experienced issues with using thenOpen multiple times in my script. I do some steps at URL1 then call thenOpen to URL2, and some steps, etc. Maybe it is specific case when used with eachThen. Adding on, the 2 places where this example happen is `docs/modules/casper.rst` and `docs/writing_modules.rst`
