### ISSUE TITLE
CasperError: Can't find module ./lib/extended {with phantom 2.1.1 and casper version 1.1.3}

### ISSUE THREAD

**Issue by mragansh** [casperjs/casperjs#1687]
unable to upgrade my casper version and phantom version for my project as lib path are not able to get the functionality .
var casper = require('./lib/casper-extended').create({
    verbose: true
    , colorizerType: "Dummy"
    , logLevel: "debug"
});
Need help to resolve this.

**Comment by mickaelandrieu** [comment]
> require('./lib/casper-extended')

hi @mragansh,
sounds like you are using your own fork of casperjs, try to find help on stackoverflow or to hire someone to help you, GitHub issues are only about CasperJS bugs.

Thank you
