### ISSUE TITLE
[error] [phantom] Maximum step execution timeout exceeded for step

### ISSUE THREAD

**Issue by xwartz** [casperjs/casperjs#1689]
I have a page that fails with this error sometimes，I have no idea how to handle the error.

Any one help?

**Comment by kensoh** [comment]
Hi @xwartz can you share your script and some comments on where the error happens?

**Comment by xwartz** [comment]
@kensoh  

Thx，I have solved this issue.

**Comment by Kameals** [comment]
How could you solve this ? I have faced same issue..
