### ISSUE TITLE
The unpredictable behavior with the pre-1.0 way to pass args

### ISSUE THREAD

**Issue by jamb0ss** [casperjs/casperjs#1692]
With the pre-1.0 way to pass args to `casper.evaluate` function we have an unpredictable behavior, that cause a very hard to find bugs.

For instance, if the number of keys in the `data` object is equal to the number of expected args of the  `casper.evaluate` function, then this object is "unpacked" according to the pre-1.0 way:

```
var casper = require('casper').create();

var data = {
    x: 1,
};

casper.start('about:blank', function() {
    this.echo(casper.evaluate(function(data) {
        return JSON.stringify(data);
    }, data));
});

casper.run();
```

Expected output:

```
{"x": 1}
```

Output:

```
1
```

and if we change the `data` object:

```
var data = {
    x: 1,
    y: 2,
};
```

then the output:

```
{"x":1,"y":2}
```

I suggest to drop this functionality at all. Otherwise we have the logic, that changes based on the input data without any explicit control from our side.

**Comment by kensoh** [comment]
@jamb0ss bumping this up, and not sure if this issue is still valid for v1.1.4? I'm a CasperJS user and just looking through the various issues here.

**Comment by kensoh** [comment]
@jamb0ss I've just ran your code and 2 examples. It is still happening this way for v1.1.4. Get what you mean, inconsistency in terms of data representation depending on the dimension.
