### ISSUE TITLE
No stack trace for test fials

### ISSUE THREAD

**Issue by abnerlee** [casperjs/casperjs#1696]
On casperjs 1.1-beta3/phantomjs 1.9.7/macOs 11.11, casperjs can print stack trace when test fails (like #1230) 

But after I upgrade to casperjs 1.1.2/phantomjs 2.1.1/macOS 11.12, the test fail message is too simple and without any detailed info, for example:

``` log
[info] [phantom] Step anonymous 6/33 http://localhost:3333/ (HTTP 200)
FAIL Find an element matching: [md-inline='strong']
#    type: assertExists
#    subject: false
#    selector: "[md-inline='strong']"
[debug] [phantom] Successfully injected Casper client-side utilities
[debug] [phantom] Navigation requested: url=about:blank, type=Other, willNavigate=true, isMainFrame=true
[debug] [phantom] url changed to "about:blank"
[debug] [phantom] Successfully injected Casper client-side utilities
```

It should also print out the test `.js` file and some line number

PS: I already set `logLevel: "debug", verbose: true`, and use command like `casperjs test test/test.js --includes=test/pre.js`

**Comment by kensoh** [comment]
Hi @abnerlee does this happens for you using CasperJS v1.1.4 and PhantomJS v2.1.1?

I'm a CasperJS user and it seems that script failures are still outputting with detail information similar to your #1230 issue.

**Comment by kensoh** [comment]
@abnerlee closing this for now as detailed trace appears when I use v1.1.4 + v2.1.1. But do ping or email at ken@tebel.org if anything!
