### ISSUE TITLE
Windows release package 1.1.3 still shows version 1.1.2

### ISSUE THREAD

**Issue by stackflows** [casperjs/casperjs#1698]
`casperjs.exe --version` yields 1.1.2 instead of 1.1.3 when using the [1.1.3 release zip archive](https://github.com/casperjs/casperjs/files/513615/casperjs-1.1.3.zip). 

E.g. in package.json:

``` json
{
  "name": "casperjs",
  "description": "A navigation scripting & testing utility for PhantomJS and SlimerJS",
  "version": "1.1.2",
```

Maybe the ZIP archive was built from an outdated source tree?

**Comment by kensoh** [comment]
Hi @stackflows does the same issue happen for you for the current build CasperJS v1.1.4?

I haven't encountered this but I install from brew, or download directly from casperjs.org homepage.

**Comment by kensoh** [comment]
@stackflows closing this issue for now as the latest CasperJS is v1.1.4, but do ping if you encounter this for v1.1.4. Thanks @stackflows!

**Comment by stackflows** [comment]
As PhantomJS went out of business, I had to move to another test runner and did not check again. Sorry for that.

**Comment by kensoh** [comment]
No probs @stackflows hope you found a good one for your needs.

I think PhantomJS just recently came back alive - https://github.com/ariya/phantomjs/commits/master
