### ISSUE TITLE
empty POST when submitting form with large data

### ISSUE THREAD

**Issue by prasanthsd** [casperjs/casperjs#1707]
I have a form that is loaded and I just simply submit the form. In the form there is input type=hidden field that has some long string stored in it. This works fine on a regular browser and does not work with casper. On analyzing this with, apache itself is getting empty POST data from casper. If I reduce the data on the hidden input it works fine. Is there a size limit or something defined in casper?

Below is the code:

```
var casper = require('casper').create();

casper.start('http://localhost/loadForm', function() {
   // Wait for the page to be loaded
   this.waitForSelector('form[action="/saveConfig"]');
});

casper.then(function() {
    this.evaluate(function() {
        $('#form').submit();
    });
});

casper.run();
```

**Comment by mickaelandrieu** [comment]
When asking for help, please ask your question [on the mailing list ](http://groups.google.com/group/casperjs) first.

If you feel that you need to report an issue against CasperJS (and you are sure that it is not a problem specific to your installation), please include at least:
- the platform you are running on (like here: CentOS)
- the CasperJS version you are using
- the engine type and version you are using
- a minimal example script and/or description of the specific situation that helps to *reproduce* your problem

Thank you.

(Feel free to re-open this issue if you come back with more specific information and asking on the mailing list did not lead to a solution)
