### ISSUE TITLE
is possible to not output content to stdout?

### ISSUE THREAD

**Issue by xurwxj** [casperjs/casperjs#1709]
it's default output to stdout when we grab content of a url, is possible change to a variable?

```
app.use('*', function ( req, res, next ){ 
  var url = t_url + req.originalUrl; 
  var delay = process.env.delay_second || 1800;
  console.log(req.get('User-Agent'));
  var a = exec(`casperjs ./reptile.js --remote=${url} --delay=${delay}`);
  res.send( a.stdout );
});     

casper.wait( delay, function (){
    casper.echo( this.getHTML() );
    this.exist();
}); 
casper.run();
```

content of a.stdout will also be displayed in stdout.log that we dont want to when code as above.

**Comment by jefleponot** [comment]
system.stdout.write('Hello, system.stdout.write!');
system.stdout.writeLine('Hello, system.stdout.write!');
