### ISSUE TITLE
Cannot extract knockoutjs data-bind created content on ubuntu os. Works on windows.

### ISSUE THREAD

**Issue by ikertrump** [casperjs/casperjs#1710]
I am writing a casperjs script. It extracts the text of a span tag, which content is created by knockoutjs data-bind. My code works perfectly on windows, but it doesn´t work on linux (either on debian or on ubuntu). If I write the this.getHTML() in a txt file, all data-bind elements are not loaded in DOM.  They only appear as an array in a script tag.
The version of my phantomjs is 2.1.1. I have tried with Casperjs 1.1.0-beta3 and the master branch, with no success. Can someone help me? Is there any bug on casperjs due to it works on windows but not on linux? I need to use debian os. Below is my code. Thanks.
HTML Tag
    <span class="product-name" data-bind="visible: nameLabelVisible(), 
    text: selectedNameLabel(), css: { disabled: isDisabled }">Dog</span>
Casperjs Script
    var url='http://exampleurl.com';
    var selector='span.product-name';
    var casper = require('casper').create({
	    pageSettings: {
      	    webSecurityEnabled:false,
		    loadImages:  true,       
            loadPlugins: true,  
		    javascriptEnabled: true
        },
    });
    casper.start(url);
    casper.wait(5000);
    casper.then(function(){
	    var texto = this.evaluate(function(selector){
            var s = document.querySelector(selector).innerHTML;
            return s;
         }, selector);
        this.echo("result: " + texto);	
    });
    casper.run(function() {
	    this.exit();
    }); 
Result:
    result: null

**Comment by jefleponot** [comment]
Hi @ikertrump,


You code can't work for many reasons. 

"casper.wait(5000);" is an asynchronous method so you have to use it like that : 

```js
casper.start('http://exampleurl.com');

casper.wait(5000, function() {
    var texto = this.evaluate(function(selector){
        var s = document.querySelector(selector).innerHTML;
        return s;
   }, selector);
   this.echo("result: " + texto);
});

casper.run();
```

it's not recommended to use a "wait" method because duration aren't constants, It is better to use a "waitFor" method on up-datable texts.

Regards.
jef

**Comment by ikertrump** [comment]
Thank you for your response Jef. You are right  that I have to retrive the data inside the casper.wait. However, that doesn`t resolve my problem. The code that you sent me works perfectly on windows but not on debian os. The problem is related to the data-bind generated element. The html tag is this :
`` <span class="product-name" data-bind="visible: nameLabelVisible(), text: selectedNameLabel(), css: { disabled: isDisabled ```}">Dog</span>`
I don´t know if I am doing something wrong, or the problem comes from phantomjs for linux. If I print the html code, the data-bind elements are not loaded. On windows works perfectly but, it does not work either on Ubuntu or Debian. I hope somebody could help me.

**Comment by jefleponot** [comment]
Hi @ikertrump,

really strange bug,

Could you create a branch with your code to test ? it's quite difficult to identify bug without reproduce it.
Regards

**Comment by ikertrump** [comment]
Hi @jefleponot 
Thank you so much for your help. This problem is driving me crazy. You have an example down below. I decided to wait 10 seconds, i think it is enough time to load the page while testing. The problem is with data-bind elements. I have attached the html code retrieved from the casperjs. As you can see, in html_windows.txt the `<span class="current-who capital" data-bind="text: currentWhoIsLooking() &amp;&amp; currentWhoIsLooking().capitalizedName ? currentWhoIsLooking().capitalizedName : 'No matter'">Someone</span>` is loaded, whereas in the html_debian.txt not.  In windows, I am using casperjs 1.1.0 beta3 and phantomjs 2.1.1. In debian 8.6 jessie x64, I am using casperjs 1.1.2 and phantomjs 2.1.1. I have tried downgrading both versions but no results. Also tried on Ubuntu.  This problem ocurrs in every website with  data-bind="text: ..." May be there is a problem with phantomjs, because I also tried selenium webdriver + phantomjs and the same happened. Selenium + chrome worked perfect on debian. However, I need to use casperjs for my project. Thanks for your support.

`var url="http://www.mamba.ru/";
var selector='span.current-who';
var fs=require('fs');
var casper = require('casper').create({
	pageSettings: {
      	webSecurityEnabled:false,
		loadImages:  true,       
        loadPlugins: true,  
		javascriptEnabled: true
    },
});

casper.userAgent('Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/538.1 (KHTML, like Gecko) Safari/538.1');
casper.start(url);
casper.wait(10000,function(){
	var texto = this.evaluate(function(selector){
        var s = document.querySelector(selector).innerHTML;
        return s;
    }, selector);
	//var texto=casper.getElementInfo(selector).text;
    this.echo("result: " + texto);
     fs.write('html.txt',this.getHTML(),'w');
});

casper.run(function() {
	this.exit();
}); ` 


[html_debian.txt](https://github.com/casperjs/casperjs/files/573774/html_debian.txt)
[html_windows.txt](https://github.com/casperjs/casperjs/files/573775/html_windows.txt)

**Comment by jefleponot** [comment]
Hi @ikertrump 

"Deine IP 176.9.107.215 wurde blockiert"

You never go to the good site with debian.
- With Window you go on an english web site : Mamba — Free online chat, networking and social dating
- With Linux, you go on a german web site: Anmelden Mamba.ru kostenfreies soziales Netzwerk und chatte mit neuen Freunden in der ganzen Welt!

change your environment variable or just the http headers : 

```js
this.open('http://www.mamba.ru/', {
        method: 'get',
        headers: {
            'Accept-Language': 'en-US,en;q=0.5'
        }
    });
```
And look at any redirection
```js
casper.on('resource.received', function(resource) {
    casper.echo(resource.url);
});
```

Regards
