### ISSUE TITLE
Casper hangs indefinitely on click

### ISSUE THREAD

**Issue by shanewignall** [casperjs/casperjs#1713]
On the site I'm testing, in the browser, I click on a button (image with onClick method), and it opens a modal dialog.

In casper, when I click, the script hangs indefinitely with no console output.

Any code written after the click will not execute. Below I have pasted the portion of the code I am talking about, with the two methods of clicking I have tried commented out.

    this.then(function() {
      this.capture('before_click.png');
    });

    /*this.thenEvaluate(function() {
      document.getElementById('ctl00_ContentPlaceHolder1_ibChangeManagers').click();
    });*/

    /*this.then(function() {
      this.click('#ctl00_ContentPlaceHolder1_ibChangeManagers');
    });*/

    this.then(function() {
      this.capture('after_click.png');
    });

'after_click.png' is not generated with either of the commented-out approaches. Really stumped on this one.

**Comment by jefleponot** [comment]
hi @shanewignall 

with modal dialog, use a filter event


page.confirm

Arguments: message

Return type: Boolean

New in version 1.0.

Allows to react on a javascript confirm() call:
```js
casper.setFilter("page.confirm", function(msg) {
    return msg === "Do you like vbscript?" ? false : true;
});
```
page.prompt

Arguments: message, value

Return type: String

New in version 1.0.

Allows to react on a javascript prompt() call:
```js
casper.setFilter("page.prompt", function(msg, value) {
    if (msg === "What's your name?") {
        return "Chuck";
    }
});
```

**Comment by shanewignall** [comment]
Setting a 'page.prompt' filter with 'setFilter' (before clicking the button to open the window) still doesn't trigger after clicking the button. Still an indefinite hang.. no code from within the 'setFilter' was executed..

**Comment by shanewignall** [comment]
Tried casper.mouse.click('#myselector'), and it did _not_ make the script hang, but it also did not make the modal window appear, even after a manual wait of 10 seconds.

**Comment by jefleponot** [comment]
Modal window never appears with phantomjs or slimerjs because it is create by windows manager (windowOS or macos or ...) 
Something window popup can freeze main page.

Try to trace all requests

**Comment by shanewignall** [comment]
@jefleponot  Ahh, that makes sense! Thanks for the info, I'm glad I know that now. If that's true, then this issue is definitely not a fault with casper, so I will close this in a bit.. but first.. how do you 'trace' requests?

Also, to get around this issue, I'm going to test out using the code from http://stackoverflow.com/questions/25663053/how-can-i-make-window-showmodaldialog-work-in-chrome-37 to make the popup appear.

**Comment by shanewignall** [comment]
@jefleponot Injecting that code didn't help.. there's got to be a way to get around this.. some code to inject to replace the window.showModalDialog function.. The code in the link above replaces the modal dialog with a normal window.. maybe I'm not switching to the new window or something like that?

**Comment by shanewignall** [comment]
I have an 'on.('popup.loaded') event, and that is triggered, but if I take a screenshot from within that event, I just get half of the screen, maybe the half that the popup isn't covering? Maybe the code I inject will allow me to switch to the window before taking a screenshot? Then again.. not sure how casper handles normal windows..

**Comment by jefleponot** [comment]
Could you give us the url site to understand that happen ?

**Comment by shanewignall** [comment]
The website is behind a corporate firewall, but if it helps, this is the code executed when the button is clicked, with the parameters of (ADSearch, 6). Let me know if you want me to inspect any other code on the page.

```
function openWindow(dialogWindow, type) {
	//show modal dialog box and collect its return value
	var retval;
	var domain = '';	
        var cacheId = '';	
        var txtGroupType = '';
        
        if (document.getElementById("ctl00_ContentPlaceHolder1_txtGroupType")!=null)
            groupType = document.getElementById("ctl00_ContentPlaceHolder1_txtGroupType").value;
            
        if (document.getElementById("ctl00_ContentPlaceHolder1_ddDomain")!=null)
            domain = document.getElementById("ctl00_ContentPlaceHolder1_ddDomain").value;

        if (document.getElementById("ctl00_ContentPlaceHolder1_txtCacheId")!=null)
            cacheId = document.getElementById("ctl00_ContentPlaceHolder1_txtCacheId").value;
        
        if (domain == '')    
            if (document.getElementById("ctl00_ContentPlaceHolder1_lblDomain")!=null)
                domain = document.getElementById("ctl00_ContentPlaceHolder1_lblDomain").innerHTML;
        

        //check to see if a domain was found
        if (domain == '')
            if (dialogWindow == 'ADSearch')
                alert('You must first select a domain for the group prior to adding managers and members.');
            else
                alert('You must first select a domain for the group prior to importing managers or members.');
        else
        {
            //open the appropriate window
            if (dialogWindow == 'ADSearch')
    		    retval=window.showModalDialog('../ADSearch.aspx?Type=' + type + '&domain=' + domain + '&grpType=' + groupType + '&cacheId=' + cacheId,'ADUserLookup','dialogHeight: 880px; dialogWidth: 842px; edge: Raised; center: Yes; help: No; resizable: Yes; status: No; status:no; dialogHide:false; help:no; scroll:yes');
	        else
	            retval=window.showModalDialog('GroupMemberImport.aspx?Type=' + type + '&domain=' + domain + '&grpType=' + groupType + '&cacheId=' + cacheId,'GroupMemberImport','dialogHeight: 400px; dialogWidth: 842px; edge: Raised; center: Yes; help: No; resizable: Yes; status: No; status:no; dialogHide:true; help:no; scroll:yes');
	        
		    if(retval!=null)
		    {
		        //rebuild member lists
		        __doPostBack('changeMembers','');
		    }
		}
	}
}
```
