### ISSUE TITLE
Cannot find module 'casper' after npm install --save

### ISSUE THREAD

**Issue by heldrida** [casperjs/casperjs#1714]
After npm install --save casperjs

I get the error Cannot find module 'casper'

Looking into node_modules directory, I find the casperjs directory, so

require('casperjs') also returns

I get the error Cannot find module 'casperjs'
```

Message:
    Cannot find module 'casperjs'
Details:
    code: MODULE_NOT_FOUND
Stack:
Error: Cannot find module 'casperjs'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
```

**Comment by heldrida** [comment]
Ok forget it
`
While CasperJS is installable via npm, it is not a NodeJS module and will not work with NodeJS out of the box. You cannot load casper by using require(‘casperjs’) in node. Note that CasperJS is not capable of using a vast majority of NodeJS modules out there. Experiment and use your best judgement.`

**Comment by frontr-uk** [comment]
so what is it capable with?

**Comment by hackerunet** [comment]
Apparently nothing, is capable of raise some good feelings in devs community all around the world to then take your feelings and crush them against an iron spine bed and then take your heart out while is still beating and pumpin some blood...

**Comment by sorin-postelnicu** [comment]
So how can I run this example code from Casper's homepage?
http://casperjs.org/

var casper = require('casper').create();

**Comment by riddler2kone** [comment]
Like they show it on their homepage ;-)

`casperjs sample.js`
