### ISSUE TITLE
Local setUp/tearDown functions cannot be async

### ISSUE THREAD

**Issue by dritter** [casperjs/casperjs#1715]
If I specify a configuration object with async `setUp` and/or `tearDown` functions these never get called.

Example:
```JavaScript
casper.test.begin('setUp() tests', 1, {
  setUp: function(callback) {
      setTimeout(function() {
          setUp = true;
          callback();
      }, 50);
  },
  test: function(test) {
    test.assertTrue(setUp, 'Tester.setUp() executed the async setup function');
    test.done();
  }
});
```

In the [docs](http://docs.casperjs.org/en/latest/modules/tester.html#setup) there is no word about async setUp/tearDown working _only_ in the casperjs-global context.

**Comment by kensoh** [comment]
Bumping up this interesting use case. @dritter I'm a CasperJS user and test automation engineer. Can you share more on your use case why async is needed for setup and teardown? I'll assume normally we want setup to be synchronously done before all the other testing happens.

**Comment by kensoh** [comment]
Am thinking to close this, but other tools are also looking for have async setup/teardown. Looks like there are unique use cases for such and you've already committed much code. For example this https://github.com/nunit/nunit/issues/60. Also tagging current main maintainer @jefleponot.
