### ISSUE TITLE
upload file  doesnt work

### ISSUE THREAD

**Issue by bashizer** [casperjs/casperjs#1716]
I want to upload file but doesn't work i don't know why ??

web site 
`... 
<input onchange='uploadImages()' type="file" id="photo" accept="image/*" multiple>
...`
casperjs
`...
this.page.uploadFile("input#photo", 'logo.jpg');
...`

**Comment by gitredvike** [comment]
I have the same issue. I'm using the example from the documentation, but it doesn't work for me - http://docs.casperjs.org/en/latest/modules/casper.html#fill.

**Comment by turakvlad** [comment]
I have the same issue. I'm using the example from the documentation, but it doesn't work for me - http://docs.casperjs.org/en/latest/modules/casper.html#fill.

**Comment by kensoh** [comment]
@bashizer @turakvlad this is interesting, following this issue to see how it develops. I don't have an existing scenario or script to try this though.

**Comment by kensoh** [comment]
Adding on, the call to this.page.uploadFile is using PhantomJS method to upload. It takes in only CSS selector. If something is not working, may have to file at PhantomJS repo, but you know how it goes.. 2k open issues. As CasperJS is only a wrapper around PhantomJS, especially for this part, closing the issue for now. But do reopen if there's anything to follow-up!
