### ISSUE TITLE
Should declare dependency on PhantomJS

### ISSUE THREAD

**Issue by zaz** [casperjs/casperjs#1719]
The [`phantomjs-prebuilt`](https://www.npmjs.com/package/phantomjs-prebuilt) package should be added as a dependency, as CasperJS doesn't seem to work at all without it.

If there's some practical reason for not doing this, it should at least be added as an optional dependency.

**Comment by jefleponot** [comment]
Please Proposes a PR

**Comment by zaz** [comment]
@jefleponot: Okay. PR #1743

**Comment by jefleponot** [comment]
@mickaelandrieu , do you agree to add this feature ?

**Comment by alexs20** [comment]
It is still has problem with phantomjs-prebuilt. I have phantomjs-prebuilt installed but not phantomjs as my karma-jasmine using only latest version.
After installing CasperJS and running "casperjs selftest" i got he flowing message:
"Fatal: The system cannot find the file specified; did you install phantomjs?"

**Comment by jefleponot** [comment]
Hi @alexs20 

Try with environment variable : PHANTOMJS_EXECUTABLE=../phantomjs-prebuild/bin/phantomjs

But I'm not sure that "casperjs selftest" will success because phantomjs-2.5.0 isn't stable

**Comment by kensoh** [comment]
Closing this for now as the dependency has already been merged and no other issues feedback, but do reopen if anything!
