### ISSUE TITLE
new functionnality : waitForRender

### ISSUE THREAD

**Issue by jefleponot** [casperjs/casperjs#1722]
Hi everybody,

With CasperJs, you can take whole or partial screen-shots (with "casper.captureX" methods), but ...

Issues : 
- how to be sure that rendering is what you expect (Image / Canvas / Flash / Video / SVG / Complex CSS) ?
- how to wait for the end of a css3 or JavaScript animation ?
- how to click on a screen zone without any locator (canvas / Image Area ) or dynamic selector ?

I would like to propose a new method that could compare an image with the browser's screen and wait until it matches : waitForRender

does someone agree to add this feature ? @BIGjuevos , @mickaelandrieu @mehdishojaei
or image recognition couldn't be use by casperjs  ?

prototype:

```js
/**
 * Waits for a render page having its content matching the provided image pattern
 *
 * @param  String          fileOrData     The filename or base64Data image pattern
 * @param  Function      then             The next step function (optional)
 * @param  Function      onTimeout   Function to call on operation timeout (optional)
 * @param  Number       timeout       Timeout in milliseconds (optional)
 * @param  Object          options        A property bag of information about the condition of render
 * @return Casper
 */
Casper.prototype.waitForRender = function waitForRender(fileOrData, then, onTimeout, timeout, details) {
```

Another thing, when matching occurs, coordinates will be send to the next function "then". 

**With this feature, everybody could test all applications :  web or not web. Casperjs could drive tests on virtual machines thought "novnc" and "spiceHtml5"**  :computer: :eye:

**Comment by mickaelandrieu** [comment]
Why not ? As soon as we can test it, I agree :)

Thank you @jefleponot !

**Comment by mehdishojaei** [comment]
@jefleponot,  Good Idea.

**Comment by mehdishojaei** [comment]
I think the main problem is that always we have a delay between screen captures, so for example in animations the desired frame can be lost.

**Comment by kensoh** [comment]
Bumping this thread :)

**Comment by kensoh** [comment]
Archiving issue using ARCHIVE label as CasperJS, like PhantomJS, is not actively maintained for now.
