### ISSUE TITLE
wait() is not working as expected 

### ISSUE THREAD

**Issue by NaikPrateek** [casperjs/casperjs#1725]
I have created some functions, that i will use in some of the scripts. below is the just one sample function which does page validation part.

    //verify page is opened properly
    exports.validation = function (casper) {
         return casper
             .wait(5000, function () {
                 this.wait(8000);
                 this.waitUntilVisible('.icon-share', function () {
                     this.test.assertExists('.icon-share', 'the element Shareable Link exists');
            });
            this.wait(8000);
            this.waitForSelector('div.btn > input:nth-child(1)', function () {
                this.test.assertVisible("#rcloud-navbar-menu > li:nth-child(7) > a:nth-child(1)", 'Cell delete check box exists');
            });
        });
    };

In my test script i simply use

    functions.validation(casper);

But in console it displays like below

> `FAIL ".icon-share" still did not exist in 5000ms`

even after providing so much wait() still it gets fail. 
The most strange part is the above validation fails only in headless mode.

**Comment by jefleponot** [comment]
casper.wait() have to got a callback function, example : 

```js
this.wait(8000, function(){
   this.waitForSelector('div.btn > input:nth-child(1)', function () {
            this.test.assertVisible("#rcloud-navbar-menu > li:nth-child(7) > a:nth-child(1)", 'Cell delete check  box exists');
        });
});
```
