### ISSUE TITLE
popup windows are wiped out between Tester instances

### ISSUE THREAD

**Issue by tmallery** [casperjs/casperjs#1727]
The problem is that if you have multiple Tester test cases, the main page is preserved between them, but all popups are not.

Test case below, but it looks like a simple fix to casper.start(). It stomps over the existing "this.popups" object with a new pagestack instance.

I've included a test, note that you have to rename the file extensions:
childWindowTest -> '.js'
otherWindow -> '.html'
spawnsChildWindow -> '.html'

github doens't like 7zip and it doens't like the zip archive 7zip creates so I renamed the files.

[childWindowTest.txt](https://github.com/casperjs/casperjs/files/627221/childWindowTest.txt)
[otherWindow.txt](https://github.com/casperjs/casperjs/files/627220/otherWindow.txt)
[spawnsChildWindow.txt](https://github.com/casperjs/casperjs/files/627222/spawnsChildWindow.txt)

**Comment by jefleponot** [comment]
@tmallery I had propose a PR , what do you think about #1118 ?

**Comment by tmallery** [comment]
@jefleponot , that change does many good things but I don't think it fixes this issue. I didn't see a change to Casper.start to prevent it from creating new pagestack instance when it should reuse the existing instance.

**Comment by jefleponot** [comment]
@tmallery 

I had integrated your test files, could you please check if it's better for the trouble you have pointed ?

**Comment by kensoh** [comment]
Archiving issue using ARCHIVE label as CasperJS, like PhantomJS, is not actively maintained for now.
