### ISSUE TITLE
Annoying failing visibility check issue with hidden ancestor

### ISSUE THREAD

**Issue by amberv0** [casperjs/casperjs#1736]
Referencing #1222
I'm wondering why it has been there for ages and nobody fixed that.
So in `clientutils.js` in the `this.elementVisible` part of the check is:
```
            var visibles = ["inline", "inline-block", "flex", "inline-flex"];
            if (visibles.indexOf(style.display) !== -1) {
                return true;
            }
```

I really have no clue why it is done this way (but I suppose there should be a good reason) - but this obviously causes problems with hidden ancestors. E.g., imagine I have a button (inline-block) in a hidden div (my real case). This test will return automatically true, which is wrong. I checked computed styles in Chrome dev tools, it's indeed the case, my button has the `inline-block` display style.

So I tried to comment out this part. My own tests started running properly (which is good), but for some very strange reason quite a few selftests on casperjs failed. With the most widespread FAIL reason:
`CasperError: evaluate() requires javascript to be enabled`. Which is very surprising - why on earth would the visibility check cause it?

Also I'm surprised by the last paragraph of this answer - http://stackoverflow.com/a/28011576/6018048 - it's definitely not my case. Maybe something has changed in the Chrome's engine?

**Comment by mlalpho** [comment]
@amberv0 would you be willing to submit a PR for a fix and update tests? It looks like @Rykus0 was working on one but I haven't seen a PR. This issue has surely fallen through the cracks.

If can use jquery and `casper.evaluate` `$( 'element' ).is( ':visible' )` that could work in the mean time..

**Comment by amberv0** [comment]
@mlalpho, I traced the origins of the current implementation of visibility check to commit 97abe4b58af2fafd6ef36a3efa69e48607a9eb3e which is meant to fix the issue https://github.com/casperjs/casperjs/issues/715
Notably, no test for svg was added. But later @n1k0 mentioned the problem it caused. Interestingly, changes were not reverted. In my opinion, the hidden container use case is much more widespread than the svg problem. I'll try to find a better solution that fixes my problem and maintains the svg case functionality

**Comment by amberv0** [comment]
Ok, I spent some time searching for checks of visibility in the svg case and thinking about #715. So the fix in #715 was not really a fix, it was a very fast patch by @n1k0. It was not solving the described problem at all (but was definitely causing many problems).
The original issue appeared because it turns out that for the svg elements (e.g. `circle`) `offsetWidth` and `offsetHeight` are undefined. That's why it was impossible to check if the element is visible.
The solution I can think of is to check for `offsetWidth/Height` being `undefined`. If so, and `display` or `visibility` are not set to hide the element, then assume that the element is visible.
We can also use `.getBoundingClientRect()` in this case to check for non-zero `width` and `height` (see https://developer.mozilla.org/en-US/docs/Web/API/CSS_Object_Model/Determining_the_dimensions_of_elements for reference)

What do you think about it?

**Comment by mlalpho** [comment]
Cheers! nice sleuthing. that sounds like a reasonable solution to me.

**Comment by jefleponot** [comment]
Good analysis @amberv0, can you propose a PR ?

**Comment by amberv0** [comment]
@jefleponot , yes, going to do it. For some strange reason selftests used to fail with the new version (that's why I couldn't submit a PR right away), but it's not the case anymore - everything passes
The version that works perfectly for my urgent needs is below. Could you check that with this selftest works equally well on your system?
If everything is ok on your system, then I'll add a couple of tests (for the hidden ancestor case, as well as for the svg situation). And will see if I should use `.getElementBound` (http://docs.casperjs.org/en/latest/modules/casper.html?highlight=bounds#getelementbounds). For the non-svg case I think there is no need, but I need to check what happens when the svg ancestor is hidden.

```
this.elementVisible = function elementVisible(elem){
            var style;
            try{
                style = window.getComputedStyle(elem, null);
            }catch(e){
                return false;
            }
            var hidden = style.visibility === 'hidden' || style.display === 'none';
            if(hidden){
                return false;
            }
            if(style.visibility === 'hidden' || style.display === 'none')return false;
            if(elem.offsetHeight === 'undefined') return true
            return elem.offsetHeight > 0 && elem.offsetWidth > 0;
        };
```

**Comment by jefleponot** [comment]
@amberv0 , I test you code : it doesn't work.
so with some correction, what do you think about that : 

```js
this.elementVisible = function elementVisible(elem) {
    var style;
    try {
        style = window.getComputedStyle(elem, null);
    } catch (e) {
        return false;
    }
    if (style.visibility === 'hidden' || style.display === 'none') {
        return false;
    }
    return typeof elem.offsetHeight === 'undefined' || elem.offsetHeight > 0 && elem.offsetWidth > 0;
};
```

I'm waiting for svg test and "getElementBound" call :smiley:

**Comment by amberv0** [comment]
@jefleponot , yep, of course you are right, for the svg case it wouldn't work. Thanks for noticing the missing `typeof`!

**Comment by amberv0** [comment]
Ok, got back to the subject. Now everything seems to be working and covered by tests (parent with `display:none` and the svg case, and also fixed one of the existing tests), except the case of parent having `visibility: hidden`. I'm not really sure how you could easily check that, without recursion (a nice full-featured visitility check example can be found here https://github.com/UseAllFive/true-visibility/blob/master/visibility.js).
Also I can't get slimerjs to work, so cannot run tests there.

By the way, the function that seems to cover all the cases (except hidden parents) can be quite simple, it turns out:

```
this.elementVisible = function elementVisible(elem) {
            if(elem.style.visibility === 'hidden' || elem.style.display === 'none') return false;//is there possibly a need to use window.getComputedStyle() ?
            var cr = elem.getBoundingClientRect();
            return cr.width > 0 && cr.height > 0;
```

Doing a PR

**Comment by amberv0** [comment]
@jefleponot , just noticed that there is one problem reportet by travis-ci:

>   172:98  error    Expected space or tab after "//" in comment          spaced-comment

I don't think it's serious, but should I fix this and resubmit the PR? On my machine eslint was failing miserably to produce proper results (having too many errors reported), so I just skipped this part.

**Comment by jefleponot** [comment]
Hi @amberv0,

I'm very interested in your PR, do you think you could finished it soon ?

Regards

**Comment by amberv0** [comment]
@jefleponot , I think it's ok now. I took your remarks into account and now all tests do pass (so the only problem was indeed with comments formatting, I guess).

**Comment by Rykus0** [comment]
Sorry for dropping the ball on this one.  I did have a fix, but lost my work before I could clean it up and submit a PR, and I haven't been able to work on any side projects (even small ones) for a while.  It looks like @amberv0 's solution is better than mine anyway!  Glad to see this!

**Comment by jefleponot** [comment]
@amberv0 , @Rykus0 , @mlalpho

Thanks for PR and Review

**Comment by booleanbetrayal** [comment]
I'm actually seeing some use cases where #1740 is breaking because `elem.getBoundingClientRect()` is returning `0` width and height for custom element directives in an Angular application. I think this may be an underlying PhantomJS issue as these elements display as expected despite reporting these 0 bounds.

**Comment by kensoh** [comment]
Archiving issue using ARCHIVE label as CasperJS, like PhantomJS, is not actively maintained for now.
