### ISSUE TITLE
step timeout checking problems

### ISSUE THREAD

**Issue by bughit** [casperjs/casperjs#1741]
```js
var stepTimeoutCheckInterval = setInterval(function _check(self, start, stepNum) {
    if (new Date().getTime() - start > self.options.stepTimeout) {
        if (getCurrentSuiteId(self) === stepNum) {
            self.emit('step.timeout', stepNum, self.options.onStepTimeout);
            if (utils.isFunction(self.options.onStepTimeout)) {
                self.options.onStepTimeout.call(self, self.options.stepTimeout, stepNum);
            }
        }
        clearInterval(stepTimeoutCheckInterval);
    }
}, this.options.stepTimeout, this, new Date().getTime(), getCurrentSuiteId(this));
```
If you're going to use setInterval for this, the delay must be short (retryTimeout) otherwise the following nasty things can happen:

* You are likely to end up waiting double the stepTimeout because on the first _check, (new Date().getTime() - start > self.options.stepTimeout) may not be true
* Casper supports ["multirun"](https://github.com/casperjs/casperjs/blob/master/samples/multirun.js) mode.  By the time the long delay _check runs, you could easily be in another suite and all of the sudden (getCurrentSuiteId(self) === stepNum) could be true for completely unrelated steps.  With a short delay, there's an opportunity to clear the interval earlier, when you're on a different step but before stepTimemout.

There are several possible (combinations) of solution to consider:

* using setTimeout
* using setInterval with a short delay
* clearing intervals/timeouts more aggressively.  all run related intervals/timeout should be cleared when a run finishes, all step related intervals/timeouts should be cleared when the step advances

**Comment by bughit** [comment]
here's a possible fix
```js
var stepTimeoutCheckInterval = setInterval(function _check(self, start, stepNum) {

    if (getCurrentSuiteId(self) !== stepNuml) {
        // as soon as we detect moving on to the next step, stop checking for step timeout
        clearInterval(stepTimeoutCheckInterval);
    } else if (new Date().getTime() - start > self.options.stepTimeout) {
        // if we are still on the same step and timed out, stop checking and emit
        clearInterval(stepTimeoutCheckInterval);
        self.emit('step.timeout', stepNum, self.options.onStepTimeout);
        if (utils.isFunction(self.options.onStepTimeout)) {
            self.options.onStepTimeout.call(self, self.options.stepTimeout, stepNum);
        }
    }   

}, this.options.retryTimeout, this, new Date().getTime(), getCurrentSuiteId(this));
```

possibly a better but more involved alternative would be to use setTimeout, store the timeoutId in the instance, turn the step property into a getter/setter and whenever step value changes, clear the timeout if tiemoutId if present (the timeout callback would null it).

**Comment by jefleponot** [comment]
@bughit, 
that looks good..
Does errors occur to identify bug and proposal a Fix ?

it could be nice if you propose a PR.

**Comment by jefleponot** [comment]
@bughit 
Please, propose a PR...

**Comment by kensoh** [comment]
Closing the issue for now but do reopen if there's anything!

**Comment by kensoh** [comment]
This is a great discussion, but doesn't look like moving with a PR, and probably CasperJS core team can't implement this for now.. Closing for now.
