### ISSUE TITLE
casper.create is not a function

### ISSUE THREAD

**Issue by elimence** [casperjs/casperjs#1744]
I just installed `"casper": "^0.1.1"` and followed the basic example, but the following line:
```
casper.start('https://mlabs-fire-html-reports.herokuapp.com/demo/?template=ios')
```
throws the error: `TypeError: casper.start is not a function`

I'm I missing something? Saw another issue about this but it was closed without any resolution.
Thanks

**Comment by BIGjuevos** [comment]
How are you including casper?
