### ISSUE TITLE
URL fragments are lost when setting window.location

### ISSUE THREAD

**Issue by jonttu-** [casperjs/casperjs#1746]
Please see attached test case. Is this intended behaviour?

The test and output are also listed below.

```
// test.js
var casper = require('casper').create();

casper.start('http://google.com/', function() {
    this.evaluate(function() {
        window.location = 'http://yahoo.com/#param=test';
    });
});

casper.then(function() {
    this.echo(this.getCurrentUrl());
});

casper.run();
```

```
 jkuusela$ casperjs test.js
https://www.yahoo.com/
```

[test.js.zip](https://github.com/casperjs/casperjs/files/701012/test.js.zip)

**Comment by jefleponot** [comment]
@jonttu- 
Please precise your version of casperjs and browser Engine.

I test with casper 1.1.3 , here is my results: 
PhantomJS 2.1.1 - http://www.google.fr/?gfe_rd=cr&ei=EaV4WJOgKert8weD1YLQCA
PhantomJS 1.9.7 - http://www.google.fr/?gfe_rd=cr&ei=OqV4WOjlK4fBXqeLsLAO
SlimerJS 0.8.4 - https://fr.yahoo.com/?p=us#param=test
SlimerJS 0.10.2 - https://fr.yahoo.com/?p=us#param=test

**Comment by jefleponot** [comment]
Else it better to use casper.open method :-)
