### ISSUE TITLE
PhantomJS has crashed. Error

### ISSUE THREAD

**Issue by noinlijin** [casperjs/casperjs#1747]
```
var casper = require('casper').create({
    pageSettings: {
        loadImages: true,//The script is much faster when this field is set to false
        loadPlugins: true,
        userAgent: 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36'
    }
});
casper.options.viewportSize = {width: 1600, height: 950};//Set bigger screen

casper.start('http://outlook.live.com/owa/?path=/mail/inbox', function() {
     this.echo('Done.')
});

casper.run(function() {
    this.echo('Done.').exit();
});


```
I run, this js, it's error , I change to other url, it is right, only outlook this url will run, I do not know why?

![image](https://cloud.githubusercontent.com/assets/3073370/21927167/e14795d8-d9bf-11e6-980f-47af80a496a6.png)

**Comment by noinlijin** [comment]
I try uninstall and reinstall phantomjs and casperjs , also error

**Comment by mickaelandrieu** [comment]
@noinlijin as notified, please file a bug report to phantomJS organization :)

**Comment by noinlijin** [comment]
@mickaelandrieu ok I have done it

**Comment by jefleponot** [comment]
version of casperJS ?

**Comment by noinlijin** [comment]
![image](https://cloud.githubusercontent.com/assets/3073370/21930250/f18bb1b2-d9cf-11e6-9866-78df2d1293d0.png)

**Comment by noinlijin** [comment]
I try to use --engine=slimerjs that will be no error, I think it is really phantomJs bug

**Comment by jefleponot** [comment]
Try with phantomJS 1.9.7

**Comment by noinlijin** [comment]
thanks
