### ISSUE TITLE
Too many Pull Requests

### ISSUE THREAD

**Issue by jefleponot** [casperjs/casperjs#1748]
@mickaelandrieu 
There are too many PR now, it could be nice to have a new release, do you agree to merge all that is ready ? Do you prefer that I personally merge PR ?

jef

**Comment by mickaelandrieu** [comment]
I have contacted the two last "release managers" to get some information about how to do it.

My point here is to release the *last version* of CasperJS and declare the project "unmaintained".
I don't know if we should look for new maintainers: I think CasperJS2 should rely on node and his selenium-standalone package and there is a LOT of others well-established solutions right now :)

Finally, it's also time for me to say "good bye" as I don't use CasperJS since 2 years.

Sorry and thanks - again - to all users and contributors of CasperJS!

**Comment by mickaelandrieu** [comment]
@jefleponot yes, you can merge all reviewed pull requests :+1:

**Comment by mlalpho** [comment]
Wow. How can we get some more maintainers set up for the site, github project etc? I'd be willing to help.

Could you share the information you've got on how to release?

**Comment by mickaelandrieu** [comment]
> Could you share the information you've got on how to release?

@mlalpho I'll share a guide in the WIKI when I will have all information to release a new version of CasperJS

> How can we get some more maintainers set up for the site, github project etc?

I don't know :/

**Comment by jefleponot** [comment]
@mickaelandrieu , 

I would like to thank you for your brilliant advices and above all your contributions. 
You allowed me to make great progress in project management with git hub.

For me, I have to maintain the project because all my supervision scripts use CasperJS to check government web services. CasperJS is fully efficient and enduring for massive tests injection (on the opposite to selenium tools). And it doesn't bother me to continue maintenance and improvements.

I tried to contact the other contributors but it looks like they had disappeared.
Again thanks a lot :-)

**Comment by jefleponot** [comment]
@mlalpho , do you really want to contribute because you never send any PR ?

**Comment by mlalpho** [comment]
Linking #1350

**Comment by jefleponot** [comment]
@mickaelandrieu , do you agree to give me more rights like a real member (not only a contributor) 
It allows me to add bguerin  and  mlalpho as a contributors to review my commits.

**Comment by mickaelandrieu** [comment]
@jefleponot I can't I don't have the required rights to give rights :D

**Comment by n1k0** [comment]
@jefleponot @mickaelandrieu I've just made you org owners. handle with care :)

**Comment by jefleponot** [comment]
Salut Nicolas, 

Merci pour ta confiance. 

Très cordialement, 
Jef 

----- Mail original -----

De: "Nicolas Perriault" <notifications@github.com> 
À: "casperjs/casperjs" <casperjs@noreply.github.com> 
Cc: "jef" <jefleponot@laposte.net>, "Mention" <mention@noreply.github.com> 
Envoyé: Mardi 17 Janvier 2017 11:32:09 
Objet: Re: [casperjs/casperjs] Too many Pull Requests (#1748) 



@jefleponot @mickaelandrieu I've just made you org owners. handle with care :)
