### ISSUE TITLE
not rendering SVG images.

### ISSUE THREAD

**Issue by khalistan** [casperjs/casperjs#1749]
I want to unveil event from pics its not working.
http://luis-almeida.github.io/unveil/
I tried to evaluate $('img').unveil();
but its not working.

**Comment by BIGjuevos** [comment]
This very much seems like a PhantomJS issue.

I encourage you to look at the debugging toolkits provided to you by CasperJS, PhantomJS/SlimerJS.

CasperJS: http://docs.casperjs.org/en/latest/debugging.html
PhantomJS: http://phantomjs.org/troubleshooting.html
SlimerJS: https://docs.slimerjs.org/current/configuration.html#about-debug

In the event you can convert this into a reproducible bug that traces it's way back to CasperJS, I encourage you to re-open this issue with details on how to reproduce the bug.  We'd be happy to look into it.

**Comment by khalistan** [comment]
I have this code:

```
module.exports = function(casper, scenario, vp) {

    console.log("BACKSTOP: unveil event");
    casper.evaluate(function() {
        $('img[title="MasterCard"]').unveil(200, function() {
            $(this).load(function() {
              this.style.opacity = 1;
            });
          });
       
    });
    casper.wait(2000,function(){
       var sel = 'img[title="MasterCard"]';
        casper.waitForSelector(sel);
        casper.mouse.move(sel);
        casper.waitUntilVisible(sel, function(){
            console.log("BACKSTOP: Img is there!");
        });


    });
    
};
```

But still image is not in ref.

**Comment by jefleponot** [comment]
PhantomJS must be compiled with svg library. Are you sure that is the case ?
you have to rather use SlimerJS

**Comment by BIGjuevos** [comment]
Same as #1751, Can we keep the conversation in that thread?
