### ISSUE TITLE
enveil event not working

### ISSUE THREAD

**Issue by khalistan** [casperjs/casperjs#1751]
please don't close this issue without resolving it.
I am using lazy load on images. There are some images on footer which not get loaded even they are on view port. My site have so many images that it normally time-out if I will wait for footer images. As for ref. I just need footer images. So I thought I can manually use 'enveil' event.(http://luis-almeida.github.io/unveil/)
Here is my code:-
```
module.exports = function(casper, scenario, vp) {

    casper.evaluate(function() {
       console.log("going to fire  unveil event");
        $('img[title="MasterCard"]').unveil(200, function() {
            $(this).load(function() {
              this.style.opacity = 1;
              console.log("event fired");
            });
          });
       
    });
 
    
};
```
In console I can just see going to fire enveil event but not 'event fired'. Also in ref image there are not these footer images. I tried debug mood but its not helping.
My viewport is: "width": 1280, "height": 1024
In ref you can see footer but not footer images.

Thanks

**Comment by jefleponot** [comment]
You code looks good
Are you sure that your selector exists : img[title="MasterCard"] 
Could you send me more details (version of CasperJS / PhantomJS / Url of your page)

I test your code on http://luis-almeida.github.io/unveil/ is works perfectly 

don't forget to add remote.message
```
casper.on('remote.message', function printConsole(message){
    casper.echo(message);
}
```
