### ISSUE TITLE
jquery not work correctly for some methods

### ISSUE THREAD

**Issue by DiegoTonini** [casperjs/casperjs#1760]
I know there is not support for tap event on DOM. SO I decided to use jquery.

` casper.page.injectJs('/jquery-3.1.1.min.js');
  casper.waitUntilVisible(btnCompositionCareSel, function() {
  casper.evaluate(function() {
      $('.popup.itemDescription_composition .text').tap();

      casper.wait(2000);
      casper.waitUntilVisible(popupSel,function(){});
    });
`

And tap does not seem to work. If is use .css(), or also .hide() or .show() work great

**Comment by jefleponot** [comment]
it seams to be a problem of phantomJS , which is your version ? Have you try with phantomJS 2.5 beta ?
