### ISSUE TITLE
Ability to use latest ES6 features via latest Node or Babel

### ISSUE THREAD

**Issue by tgoldenberg** [casperjs/casperjs#1761]
It would be nice to be able to leverage ES6 syntax (`=>`, `...`, etc.) in casperJS. 

Is it possible to specify the Node version when testing? Or to use `babel-node`?

These would be really great features to make it more developer-friendly. Thanks.

**Comment by tgoldenberg** [comment]
Also, does CasperJS work with `node_modules`? I tried `require`-ing some modules, but they threw errors.

**Comment by mickaelandrieu** [comment]
Hello,

you may be interested by this FAQ =>http://docs.casperjs.org/en/latest/faq.html#is-casperjs-a-node-js-library

Regards,
