### ISSUE TITLE
Error on casper-master (f48d0d6) with headless slimerjs: onClosing: [TypeError] win is null

### ISSUE THREAD

**Issue by corford** [casperjs/casperjs#1762]
When running any script with casper-master (f48d0d6) and Slimerjs 0.10.2 in headless mode via xvfb (with Firefox 50.1.0) I get the following error printed immediately after script execution:

> Error onClosing: [TypeError] win is null (resource://slimerjs/addon-sdk/toolkit/loader.js -> resource://slimerjs/slimer-sdk/webpage.js ; line:417 col:9)

Any script triggers this. Example (save as '/tmp/test.js'):

`var casper = require('casper').create();
casper.start('http://slimerjs.org', function() {
    this.echo(this.getTitle());
});
casper.run();`

Executed as:
/usr/bin/xvfb-run -a -s "-screen 0 1366x768x24" /opt/slimerjs/slimerjs-0.10.2/slimerjs /opt/casperjs/casperjs-master/bin/bootstrap.js --casper-path=/opt/casperjs/casperjs-master --cli /tmp/test.js

Prints:

> SlimerJS
>Error onClosing: [TypeError] win is null (resource://slimerjs/addon-sdk/toolkit/loader.js -> resource://slimerjs/slimer-sdk/webpage.js ; line:417 col:9)

Running the same script with casperjs-1.1.3 does not produce this error (only "SlimerJS" is printed to stdout).

**Comment by jefleponot** [comment]
Hi @corford ,

I notice that regression. Thank for your contribution. I will commit a patch :-)

**Comment by jefleponot** [comment]
@corford 
please , git fetch / git pull  /
it is ok ?

**Comment by corford** [comment]
Fixed :) 🥇

**Comment by corford** [comment]
Fixed :) 🥇
