### ISSUE TITLE
Can't print backstopJS config values

### ISSUE THREAD

**Issue by khalistan** [casperjs/casperjs#1763]
Hallo,
for some reason I have to print config values. Currently I want to print report ('report type if its browser or CI').
My backstopJS file looks like this:
```
var instance = require("./inc/instance.js");
var scenarios = require("./inc/scenarios.js");
var viewports = require("./inc/viewports.js");
var reporting = require("./inc/reporting.js");
var casperFlags = require("./inc/casper.flags.js");
var app = require("./inc/app.js");
var paths = require("./inc/paths.js");

module.exports = {

    "id": "test_" + app.id,

    "viewports": viewports.getViewports(),

    "scenarios": scenarios.getScenarios(),

    "paths": {
        "bitmaps_reference": paths.getBitmapReferencePath(),
        "bitmaps_test": paths.getBitmapTestPath(),
        "casper_scripts": paths.getCasperScriptPath(),
        "html_report": paths.getHtmlReportPath(),
        "ci_report": paths.getCIReportPath()
    },
    "casperFlags": casperFlags.getCasperFlags(),
    "engine": "casperjs",
    "report": [reporting.reportType],
    "ci": {
        "format": "junit",
        "testSuiteName": app.id + " - backstopJS"
    },
    "debug": false

};
```
Now inside of onReadyScript I have 

```
var reporting = require("./inc/reporting.js");
 console.log("Report type is",reporting.reportType);  //says undefined
module.exports = function(casper, scenario, vp) {   // here script failed 
  console.log("onReadyScript");
  console.log("Report type is",reporting.reportType);
};
```
its not working.

My reporting js file looks like this:
`
exports.reportType=process.env.REPORT_TYPE ? process.env.REPORT_TYPE : "browser";`

Its fine working project, now we need to print config values and its not working.

I am not sure if its a bug or there is anyother way to do it. I google it but can't find any help.

Thanks

**Comment by jefleponot** [comment]
Hi @khalistan 
It seams to be a trouble of backstopJS

it is better to fill require method with absolute path.

Regards

**Comment by kensoh** [comment]
@khalistan this might be a BackstopJS related question, have you try posting to their repo issue page? I believe there should be users there with your use case. The only other thing in my mind is maybe BackstopJS code lies directly in the browser so need to user casper.evaluate to do the stuffs in DOM context instead of default casper context.

**Comment by kensoh** [comment]
@khalistan closing this issue for now but do reopen if there is anything you think we can try to assist!
