### ISSUE TITLE
the capture is not my wish 

### ISSUE THREAD

**Issue by kanxue660** [casperjs/casperjs#1764]
Please provide any additional information below.
casper.start("https://appleid.apple.com/account");

casper.then(function _wait() {
this.wait(30*1000);
});

casper.then(function _jietu(){
this.capture('appleid.jpg');
});

The capture image is not as same as a normal browser show,why?

**Comment by mickaelandrieu** [comment]
When asking for help, please ask your question [on the mailing list ](http://groups.google.com/group/casperjs) first.

If you feel that you need to report an issue against CasperJS (and you are sure that it is not a problem specific to your installation), please include at least:
- the platform you are running on (like here: CentOS)
- the CasperJS version you are using
- the engine type and version you are using
- a minimal example script and/or description of the specific situation that helps to *reproduce* your problem

Thank you.

(Feel free to re-open this issue if you come back with more specific information and asking on the mailing list did not lead to a solution)
