### ISSUE TITLE
Issues using with routing in next.js

### ISSUE THREAD

**Issue by tgoldenberg** [casperjs/casperjs#1765]
I'm using [Next.js](https://github.com/zeit/next.js), which has its own router. I was able to get a user signup flow test working with `react-router`, but am unable to get it working with the `next.js` example. Any ideas on why that might be so? Not sure if this belongs in the `next.js` issues as well, but having the ability to use `casperjs` would be a big benefit. Thanks!

**Comment by kensoh** [comment]
Hi @tgoldenberg I believe CasperJS is actually not a Node.js library, only using npm for distribution. Not sure if SpookyJS can help your use case -
http://docs.casperjs.org/en/latest/faq.html#is-casperjs-a-node-js-library

**Comment by kensoh** [comment]
Also adding on, do you have a sample script which shows what is the error and where it happens? I've come across issues which are related to the dynamic rendering not yet ready and fail. But this issue sounds like something fundamentally is not working with using Next.js with CasperJS.

**Comment by kensoh** [comment]
Hi @tgoldenberg closing this for now but please reopen if anything. Thanks for raising this!
