### ISSUE TITLE
Help Help 

### ISSUE THREAD

**Issue by xiangdong1987** [casperjs/casperjs#1767]
I use caserperjs crawling page ,but return content is garbled.

var casper = require('casper').create();
//casper.start('http://www.baidu.com');
casper.start('http://www.pcauto.com.cn/nation/949/9490115.html');
casper.then(function() {
    this.echo(this.getTitle());
});
casper.run();
return 
È«ÐÂ±¦ÂíX3¹úÄÚµýÕÕ ÄÚÊÎÊ×ÆØ/½«¹ú²ú¡¾Í¼¡¿_ÐÂ³µµýÕÕ_Ì«Æ½ÑóÆû³µÍø
Is there someone help me ?  thanks

**Comment by mickaelandrieu** [comment]
Hello,

when asking for help, please ask your question [on the mailing list ](http://groups.google.com/group/casperjs) first.

If you feel that you need to report an issue against CasperJS (and you are sure that it is not a problem specific to your installation), please include at least:
- the platform you are running on (like here: CentOS)
- the CasperJS version you are using
- the engine type and version you are using
- a minimal example script and/or description of the specific situation that helps to *reproduce* your problem

Thank you.

Tried by myself, and couldn't reproduce your error:

![capt](https://cloud.githubusercontent.com/assets/1247388/23060408/de17e3d2-f4fd-11e6-9fd5-a71724ba5a6d.PNG)

**Comment by xiangdong1987** [comment]
Thank you very much for you @mickaelandrieu
I think I know why. My platform is Mac Ox, i'm using brew to install casperjs. I will try another way to install it. Thanks again.
