### ISSUE TITLE
Problem with message length when using casper.log()

### ISSUE THREAD

**Issue by ISKU** [casperjs/casperjs#1768]
If you use casper.log() to output messages to the console, 
and spawn.stdout.on() to read messages from the console.
 
**if the messages are very long, the message is divided. **
Is the problem that casper.log() splits the message?
If the casper.log() is correct to divide the message, Can I fix all the messages so I can read them?

**Comment by jefleponot** [comment]
Hi @ISKU 

Could you please tell us which version of phantomJS, slimerJS and CasperJS you used ?

the "casper.log" method use the console.log function to write text. So please, tell us the length you try to write. Else you can use another way to write system.stdout.write("text");

It will be nice to propose a PR to make evolute casper.log :-)

**Comment by kensoh** [comment]
Hi @ISKU bumping this, as this looks like a great opportunity to evolve and improve casper.log :)

**Comment by kensoh** [comment]
Closing the issue but do reopen if there's anything!

**Comment by ISKU** [comment]
This was the default buffer size problem of console.log()
Thank you for your reply.

**Comment by kensoh** [comment]
Thanks @ISKU for updating with your finding! :)
