### ISSUE TITLE
on mac i  get this error :  CasperError: Can't find module fs

### ISSUE THREAD

**Issue by jpca999** [casperjs/casperjs#1771]
![image](https://cloud.githubusercontent.com/assets/1026325/23202296/6089aa3e-f8ab-11e6-9ec5-48d1518bedf4.png)

![image](https://cloud.githubusercontent.com/assets/1026325/23202275/4c05c7a0-f8ab-11e6-809d-98ebdad6fb13.png)

var casper = require('casper').create();
casper.start('http://casperjs.org/');

casper.then(function() {
    this.echo('First Page: ' + this.getTitle());
});

casper.thenOpen('http://phantomjs.org', function() {
    this.echo('Second Page: ' + this.getTitle());
});

casper.run();

**Comment by jpca999** [comment]
@mickaelandrieu  how do i resolve this issue ?

**Comment by mickaelandrieu** [comment]
I don't know but create multiples issues won't help
