### ISSUE TITLE
Windows incorrectly splitting options with spaces when using testing framework.

### ISSUE THREAD

**Issue by emosquito** [casperjs/casperjs#1776]
It seems that when I try and run the casperjs test environment with an option that has spaced on windows, casperjs is taking the space as a new argument.

Here is what I've tried:

Input with single quotes
`casperjs test casper.js --option1='hello world'`
Output:
`ΓÜá┬á┬áCasperError: Invalid test path: world'`

Input with double quotes
`casperjs test casper.js --option1="hello world"`
Output:
`ΓÜá┬á┬áCasperError: Invalid test path: world'`

Input: eliminating the space allows the option to pass through
`casperjs test casper.js --option1="helloworld"`
Output:
`casper.echo(casper.cli.get('option1')); // outputs helloworld`

**Comment by emosquito** [comment]
The solution on windows is to escape the double quotes!
`casperjs test casper.js --option1=\"hello world\"`

Output:
`casper.echo(casper.cli.get('option1')); // outputs hello world`

**Comment by mickaelandrieu** [comment]
@emosquito would you mind to contribute to the docs?

**Comment by emosquito** [comment]
I hope I did that correctly.
