### ISSUE TITLE
casperjs not finished before node.js finished process, and have to press enter(windows7 64)

### ISSUE THREAD

**Issue by finalcreator** [casperjs/casperjs#1777]
C:\Users\mike>cd D:\automate_project

C:\Users\mike>d:

D:\automate_project>npm start

> automate_project@1.0.0 start D:\automate_project
> casperjs main.js

D:\automate_project>[info] [phantom] Starting...
[info] [phantom] Running suite: 2 steps
[debug] [phantom] opening url: http://www.baidu.com/, HTTP GET
[debug] [phantom] Navigation requested: url=http://www.baidu.com/, type=Other, willNavigate=true, isMainFrame=true
[debug] [phantom] url changed to "http://www.baidu.com/"
[debug] [phantom] Successfully injected Casper client-side utilities
[info] [phantom] Step anonymous 2/2 http://www.baidu.com/ (HTTP 200)
[debug] [phantom] Capturing page to D:/automate_project/img/baidu.png
[info] [phantom] Capture saved to D:/automate_project/img/baidu.png
shit
[info] [phantom] Step anonymous 2/2: done in 1004ms.
[info] [phantom] Done 2 steps in 1005ms
[debug] [phantom] Navigation requested: url=about:blank, type=Other, willNavigate=true, isMainFrame=true
[debug] [phantom] url changed to "about:blank"

(You have to press enter!)

D:\automate_project>

**Comment by finalcreator** [comment]
node.js : v6.10.0
    "casperjs": "^1.1.3",
    "phantomjs-prebuilt": "^2.1.14"

**Comment by mickaelandrieu** [comment]
When asking for help, please ask your question [on the mailing list ](http://groups.google.com/group/casperjs) first.

If you feel that you need to report an issue against CasperJS (and you are sure that it is not a problem specific to your installation), please include at least:
- the platform you are running on (like here: CentOS)
- the CasperJS version you are using
- the engine type and version you are using
- a minimal example script and/or description of the specific situation that helps to *reproduce* your problem

Thank you.

(Feel free to re-open this issue if you come back with more specific information and asking on the mailing list did not lead to a solution)
