### ISSUE TITLE
How do I pass custom arguments into a testscript

### ISSUE THREAD

**Issue by tarjei** [casperjs/casperjs#1787]
Hi, is there a way for me to pass custom arguments to a casperjs test? 

I want to pass in the base url for the page I'm testing.

I tried using envitonment variables but process.env was not available. What is the suggested way?

**Comment by jefleponot** [comment]
**/home/jef/dev/casperjs$** toto="tata" bin/casperjs test script.js --param1="value"

var cli = require('cli')

**Comment by tarjei** [comment]
AH! Thanks!
