### ISSUE TITLE
Handle just opened window by clicking at link with target="_blank"

### ISSUE THREAD

**Issue by Bakharevich** [casperjs/casperjs#1797]
Hello.

I'm using CasperJS (1.1.4) with SlimerJS (0.10.3) at Mac OS X.

If I open new window by clicking at link with target="_blank" (function click()), how can I get the object of that new page? For example, to evaluate opened page to scroll at the bottom of it or get text from it?

I don't know the URL of that link (it will new every time).

Thank you in advance.

**Comment by jefleponot** [comment]
```js
// catch event
casper.on('popup.created', function(page) {

});

``
http://docs.casperjs.org/en/latest/modules/casper.html#withpopup
