### ISSUE TITLE
Is there a way to run CasperJS using an npm script?

### ISSUE THREAD

**Issue by jfkhoury** [casperjs/casperjs#1798]
I know CapserJS is not a NodeJS library, but is there a way to call the `node_modules/.bin/casperjs` script directly from npm by adding a script:

```
script: {
    test: casperjs ...
}
```

and then `npm run test` from the terminal?

**Comment by kozhin** [comment]
I installed CasperJS with npm and I can run scripts with:
`npm run task`

My package.json is as follows:
```json
{
  "name": "some_project_name",
  "version": "1.0.0",
  "description": "na",
  "main": "index.js",
  "scripts": {
    "task": "casperjs index.js"
  },
  "author": "me",
  "license": "ISC",
  "dependencies": {
    "casperjs": "^1.1.3",
    "phantomjs": "^2.1.7"
  }
}

**Comment by jfkhoury** [comment]
Are you 100% CasperJS is not installed globally?

I was able to fix my problem my writing a simple Node script that spawns CasperJs as a child process. Let me know if you need more details.

Thanks.

**Comment by kozhin** [comment]
Yes, I'm sure.

```sh
kkozhin@macbookpro:~$ node -v
v7.8.0
kkozhin@macbookpro:~$ npm -v
4.4.4
kkozhin@macbookpro:~$ npm list -g | grep phantom
kkozhin@macbookpro:~$ npm list -g | grep casper
kkozhin@macbookpro:~$ cd Sandbox/insta_grabber/
kkozhin@macbookpro:~/Sandbox/sample_project$ npm list | grep casper
├── casperjs@1.1.3
kkozhin@macbookpro:~/Sandbox/sample_project$ npm list | grep phantom
└─┬ phantomjs@2.1.7

**Comment by BartoszBaczek** [comment]
@kozhin Your solution is fine, but only if you do not need to send any parameters.

**Comment by kensoh** [comment]
This is interesting topic, just wanted to add a thread about Node.js bridge to this thread - https://github.com/casperjs/casperjs/issues/1524

**Comment by kensoh** [comment]
@jfkhoury may we check with you on your implementation? Looks like you got the answer to this issue, will benefit other node users to reference your solution before closing.

**Comment by jfkhoury** [comment]
Hi @kensoh, I ended up spawning `casperjs` as a child process in a simple Node script, which ended up working great!

Here's the code:

NOTE: `funkTest.js` is our little wrapper library that starts the server and attached listeners on casperjs. I also have another module that implements a custom event that signals the receiving of all responses so we can run tests against them.

```
var spawn = require('child_process').spawn;

var tests = ['./test/functional/spec/'];
var casperjs = spawn('casperjs', ['--engine=slimerjs', '--includes=./test/functional/funkTest.js', 'test'].concat(tests));

casperjs.stdout.on('data', function (data) {
  console.log('Log: ' + data);
});
```

We are using this at Adobe. Let me know if you need more details, good luck.

**Comment by kensoh** [comment]
Thanks @jfkhoury for generous sharing! Yes using your script above I can run below bare-bone script from node and test.js is executed /output properly. I guess there is sufficient info for this issue to close now and for future reference when people search. Thank you again :smile:

```
var spawn = require('child_process').spawn;

var casperjs = spawn('casperjs', ['test.js']);

casperjs.stdout.on('data', function (data) {
  console.log('Log: ' + data);
});
```
