### ISSUE TITLE
New CasperJS 1.1.4 Windows installation failed

### ISSUE THREAD

**Issue by vclenet16** [casperjs/casperjs#1800]
Hi, 

I'm developping a CasperJS's test suite on Windows 7, and 1.1.0 version works fine but I had a popup stuff issue so I've checked if this issue has been fixed.

Apparently it is in the 1.1.4 version so I decided to use it, but when I download it and replace 1.1.0 by the newest, casperjs doesn't run and return me the error below : 

"Unhandled Exception: System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at casperjs.Main(String[] args)"

It works fine on linux but failed to run on Windows, any idea ? 

(And here is my screen)
![casper_issue](https://cloud.githubusercontent.com/assets/6152687/24496691/378e266e-1539-11e7-942a-a5ccbe1f75bd.png)

If you need any additional informations, do not hesitate to ask.

Regards.

**Comment by jefleponot** [comment]
Hi @vclenet16 

CasperJS.exe needs a recent version of ".Net Framework". It works for me with Microsoft .NET Framework 4.6

Which version do you used ?

**Comment by vclenet16** [comment]
I'm on .NET Framework 4.5.2, I'll try to update and see if it works..

Thanks for your answer

**Comment by jefleponot** [comment]
@vclenet16 
it is a bug of mono C#

Do you success ?

**Comment by vclenet16** [comment]
That works PERFECTLY !! Thanks a lot

**Comment by jefleponot** [comment]
you are welcome

**Comment by LiGhTenn** [comment]
Please add this to the pre-requirement, this frameworks 4.6

I have the same issue on test environment works well.

but on the production server it is running on the machine exchange server 2010 which does not allow you to install frameworks 4.6 the highest I can go is frameworks 4.5 

Is there a version of casperJS that support frameworks 4.5 ?

**Comment by jefleponot** [comment]
@LiGhTenn 
the launcher "casper.exe" is just a c# code compiled with mono.
it is not important. Only CasperJS modules are important. So if you want you can use older compile exe of version 1.1.0 with modules of the 1.1.4 (that is really better than 1.1.0)

Regards

**Comment by jefleponot** [comment]
@LiGhTenn 
I will recompile casperjs.exe with an older version of mono.
Could you please tell me which version of .NET is installed on your system ?

**Comment by LiGhTenn** [comment]
Wow, thanks for all the support I was pretty shocked at first receiving a reply. 
it is true CasperJS is a friendly ghost,

the highest version of frameworks I manage to install is 4.0.

in an unrelated matter, is there away to place to post Demo code for casperJS, as I built a ebay "download order history to CSV" and while I was researching for a solution myself I notice a lot of people online has requested this time of model.

plus it would be cool to have a place with all this "ready made" solutions.

Yair.

**Comment by jefleponot** [comment]
@LiGhTenn 
Could you please test the new version 1.1.4-1 ?

**Comment by LiGhTenn** [comment]
Thanks !
Tested works well...

**Comment by LiGhTenn** [comment]
@jefleponot 
Sorry to message this here, but not sure how to do private message here.  
do you do also Job, I have some online banking system I need to get some data form, can I pay you to have a look and see if you can come up with an issue my email is yairtee@gmail.com
