### ISSUE TITLE
Error: cannot access member `parent' of deleted QObject

### ISSUE THREAD

**Issue by 1d10t** [casperjs/casperjs#1801]
after calling `popup.close();`
`casper.popups.clean();` triggering error:
`Error: cannot access member 'parent' of deleted QObject
  /var/www/html/mars/docs/parsers/data/23/phantomjs:/platform/pagestack.js:64
  /var/www/html/mars/docs/parsers/data/23:0 in forEach
  /var/www/html/mars/docs/parsers/data/23/phantomjs:/platform/pagestack.js:62 in clean
`

**Comment by jefleponot** [comment]
@1d10t 

Please, could you tell us which version of phantomJs and CasperJs do you used ?

**Comment by 1d10t** [comment]
$ casperjs --version
1.1.3
$ phantomjs --version
2.1.1

**Comment by jefleponot** [comment]
@1d10t 
We improve CasperJS popup management with the 1.1.4 version. So it could be better to test it to see if the trouble has been yet solved .

**Comment by jefleponot** [comment]
We have also one next PR that improves closing popup  #1794

**Comment by 1d10t** [comment]
thanx, in 1.1.4 all is ok
