### ISSUE TITLE
Npm version is old 

### ISSUE THREAD

**Issue by mirzazeyrek** [casperjs/casperjs#1804]
Today I was trying to install the latest release via npm but package is updated 8 months ago. Is there any particular reason for not to updating to latest version?

**Comment by jefleponot** [comment]
Hi @mirzazeyrek 
the project has a new core team so we don't know all commands to do.

Could you please tell us the process to update npm from github ?

**Comment by mirzazeyrek** [comment]
I don't know actually :) Do you have credentials for npm package ? 

I have found  a workaround by using casperjs/casperjs while installing:

![screenshot 2017-04-02 19 10 18](https://cloud.githubusercontent.com/assets/6233650/24588818/9ad3649a-17d8-11e7-9666-decf03de4c12.png)

**Comment by amerikan** [comment]
@jefleponot I *think* the person who registered it on npmjs has to do it, which seems to be @BIGjuevos https://www.npmjs.com/package/casperjs

**Comment by JuanCaicedo** [comment]
@jefleponot  If you're not able to get access, you can write to NPM explaining the situation and they'll go through some steps to give you permissions to the module. It takes a few weeks, so it would be nicer if @BIGjuevos could help 😃

**Comment by jefleponot** [comment]
@JuanCaicedo 

I will write to BIGjuevos first ! After I would contact the NPM team .

**Comment by BIGjuevos** [comment]
Let me see what I can do to help. Not sure why I'm the only one left with NPM.

**Comment by BIGjuevos** [comment]
@jefleponot I can't seem to find a way in npmjs to modify or grant permissions.

I'm listed as a user of it for so, so I can publish versions. Which I just did for 1.1.4.

Please let me know if that doesn't work. I'll publish again,

**Comment by BIGjuevos** [comment]
In the future, I'm much easier to reach on Slack as this gets hidden in my mail.

You can join the slack at: http://ryannull.com:3000/

**Comment by jefleponot** [comment]
@BIGjuevos 
Thanks a lot

**Comment by jefleponot** [comment]
@mirzazeyrek @JuanCaicedo @amerikan  @rubysolo 

Could you please verify that the packager works with casperJS ?

Thanks by advance

**Comment by kensoh** [comment]
Thanks @jefleponot @BIGjuevos works for me! I've updated CasperJS v1.1.4 to the tagui package that I'm working on. And the CasperJS Node.js download works as expected for me.
