### ISSUE TITLE
scrollToBottom for a scrollable DIV

### ISSUE THREAD

**Issue by kozhin** [casperjs/casperjs#1807]
Hi there!

Is there a way to scroll not the whole document but a certain div with CasperJS?
Docs describe scrollToBottom function which applies only to a whole document.

Currently I did "scrolling" by pressing PageDown button. I guess it's not the best solution probably.

**Comment by jefleponot** [comment]
Hi @kozhin 

just do
```js
casper.evaluate(function(selector){
   var elm = __utils__.findOne(selector);
   if (!!elm) {
        elm.scrollTo(0,elm.scrollHeight);
   }
}, 'yourSelector');
```

If it works, please close this issue...

**Comment by rsudip90** [comment]
Hi @jefleponot, the solution you provided is not working in casper test cases.

Apart from above, I also tried with `docuement.querySelector(id).scrollTo(0, height)`. I'm capturing screen shot (after waiting for 1 second) in both trial examples but image does not show scrollable div ever reach to the height I've provided. 

Any suggestions? Thanks.
