### ISSUE TITLE
Is there a way to procedurally call a script from within another script?

### ISSUE THREAD

**Issue by Delallen** [casperjs/casperjs#1811]
I'm almost positive this question has been asked somewhere before, but I can't seem to locate anything referencing what I'm attempting to do.

For instance I want to kick off script 2 after script 1 has run and tested some site data. If the script 1 completes and passes, it will set an object with reference data to be used in script 2.

Is there a method and/or way to allow this without having to store data somewhere? Like trying to pass through and argument or using a cli option, like --someOption=thisData?

**Comment by hlr1983** [comment]
Have you looked at:

1) "Using the command line"  - http://docs.casperjs.org/en/latest/cli.html

2) "waitForExec() http://docs.casperjs.org/en/latest/modules/casper.html#waitforexec
or
and Child Process Module http://phantomjs.org/api/child_process/.

?

**Comment by Delallen** [comment]
@hlr1983 Not sure how I missed this and I'm partially using the cli options, and the child process module will help also. Thanks.
