### ISSUE TITLE
Any plans on supporting headless chromium?

### ISSUE THREAD

**Issue by sradu** [casperjs/casperjs#1813]
It's out and stable. Just wondering.

https://github.com/cyrus-and/chrome-remote-interface

**Comment by jefleponot** [comment]
@sradu It could be nice idea.
Need to create a chromeJS layer that contains PhantomJS equivalence calls (as slimerJS does)
Do you think it is possible ?

**Comment by sradu** [comment]
@jefleponot I'd have to do more digging. Might look into it over the next couple of months.

**Comment by hlr1983** [comment]
https://github.com/ariya/phantomjs/issues/14954 might be interesting for this issue...
