### ISSUE TITLE
Cannot Dispatch Mousedown event on nonexistent selector: despite exisiting

### ISSUE THREAD

**Issue by PSJMcNeill** [casperjs/casperjs#1814]
I have used getElementsInfo to retrieve a class.

Checking this it correctly returns all the HTML I am expecting.

I then try to click on the html and I get the error in the title.

Any ideas what would be causing this or a solution?

`casper.then(function(){
	var matches = this.getElementsInfo(x(".//*[@class='matchStats']"));
	this.click(matches[0].html);
})`

**Comment by jefleponot** [comment]
Hi @PSJMcNeill 

"Click" event are forbidden on hidden elements.

**Comment by PSJMcNeill** [comment]
Bit confused by that as it isn't hidden, I've used a different method to click on the same HTML and it is working. I used nth:child selector to fix it in case anyone else has this issue.

`this.click(.matchstats:nth-child(2))`

**Comment by jefleponot** [comment]
Could you tell me which version of phantomJS / SlimerJS and CasperJS do you used ?

try ouse.click(".matchstats:nth-child(2)");

**Comment by PSJMcNeill** [comment]
1.9 PhantomJS and 1.1.0 CasperJS.

Can confirm though using the nth-child approach instead works

**Comment by jefleponot** [comment]
PhantomJS v 1.9 doesn't accept css selector 3

**Comment by PSJMcNeill** [comment]
Ah interesting. Do later version support it or just a case of it doesn't accept them at all?

**Comment by jefleponot** [comment]
use PhantomJS >= 2.1.1 AND CasperJS >= 1.3

**Comment by PSJMcNeill** [comment]
Unfortunately that made no difference. There is more divs inside the div I am selecting maybe that causes problems.

I can go with the Nth Selector instead.
