### ISSUE TITLE
The is no inbuild function or API for a dropdown menu 

### ISSUE THREAD

**Issue by NK-NeelK** [casperjs/casperjs#1815]
I am Neel Khalade, I really love the idea of web scrapping and casperjs and phantomjs does it really well and is the best web scrapping application ever available.
I am currently creating something really big application for automation in social media handling,
but there is no inbuild API for working with the dropdown menu or working with any.
Instead I have to this.evaluate() which works in the DOM Explorer but it is quite tricky and complicated to use because casperjs is headless and we can't actually see the processing and execution of our program except - this.capture() but it ain't that handful to have hundreds of screenshots.
Please develop a method to see the process of casperjs execution over a website and make something for a dropdown menu, writing only one API is not difficult!

**Comment by jefleponot** [comment]
Hi @NK-NeelK 

CasperJS is just a framework that allows to program schedule interactive actions in order to test web applications. You can have an immediate render using CasperJS with SlimerJS.
