### ISSUE TITLE
scrollToBottom inside a div with infinite scroll

### ISSUE THREAD

**Issue by stanfaire** [casperjs/casperjs#1817]
Hello,

I'm trying to scroll to the bottom of a div which is has infinite scroll in it. `ScrollToBottom` only works for the whole window, and can't work inside a div, right ?

So I tried using `objDiv.scrollTop = objDiv.scrollHeight;`, which works inside the Chrome console when I repeat it several times.

However my casperJs script doesn't seem to understand it has to do it multiple times. Here is my code snippet : 

```
var getContent = function() {
casper.wait(1000, function() { 
       this.evaluate(function(){
        var objDiv = document.getElementById("result_carto_listing");
        objDiv.scrollTop = objDiv.scrollHeight;
        }); 
        var newScrolled = casper.evaluate(function() {
            return objDiv.scrollTop; 
        });
        scrollDelta = newScrolled - scrolled;
        scrolled = newScrolled;
        console.log("Now scrolled", scrolled);
    });
    casper.then(function() { 
        if (scrollDelta != 0) {
            getContent(); 
        } else {
            casper.then(function() { 
               findNext()
            });
        }
    });
};

```

Any ideas ?

Thanks !

**Comment by jefleponot** [comment]
Hi @stanfaire

just do

casper.evaluate(function(selector){
   var elm = __utils__.findOne(selector);
   if (!!elm) {
        elm.scrollTo(0,elm.scrollHeight);
   }
}, 'yourSelector');

If it works, please close this issue...

**Comment by stanfaire** [comment]
Hey,

Thanks but I don't get how it would work, because there isn't any new selector that appears at the end of the infinite scroll.

**Comment by jefleponot** [comment]
Hey,

    Thanks but I don't get how it would work, because there isn't any new selector that appears at the end of the infinite scroll.

selector is for you the <div id="result_carto_listing"></div>

**Comment by stanfaire** [comment]
Thanks but it doesn't scroll at the end of the div unfortunately. But I think it's more a JavaScript question than a CasperJs one.

**Comment by kensoh** [comment]
@stanfaire I'm a CasperJS user for couple of years now browsing through open issues to learn more. May I check with you on your view why you think it is a JS question than CasperJS one? Is it you mean that the difference in behavior in this case is because Chrome JS engine and PhantomJS JS engine differs in behavior?

**Comment by kensoh** [comment]
Closing this for now but please reopen if anything. Thanks for raising this!
