### ISSUE TITLE
CasperJs doesn't load html elements of Angular2 web application

### ISSUE THREAD

**Issue by buwaneka1** [casperjs/casperjs#1819]
When a screenshot was taken of the application, it shows the app has not loaded, it works fine with usual browsers like Chrome and Firefox. Is this an issue with Phantomjs?

**Comment by jefleponot** [comment]
@buwaneka1 
Please Tell us your CasperJS version and PhantomJS version (and/or SlimerJS version) ?

**Comment by buwaneka1** [comment]
casperjs - 1.1.4 and phantomJs - 2.1.1 , I think the issue is with Angular2's bootstrap not loading the components in Phantomjs. I'm not sure though.

**Comment by buwaneka1** [comment]
By adding polyfills this issue can be solved. It seems to be an issue with Angular2 not supporting Phantomjs browser.

**Comment by TylorShin** [comment]
@buwaneka1 what is the polyfills you added? babel-polyfill?
