### ISSUE TITLE
this.click not work  href is function

### ISSUE THREAD

**Issue by whooyun** [casperjs/casperjs#1821]
Hi all.

Trying to click the below element via casperjs, but it's not working for me.

casperjs-1.1.4,phantomjs-2.1.1

blow is my html code.
![20170428155923](https://cloud.githubusercontent.com/assets/9583594/25519764/baa54754-2c2b-11e7-831d-7fdc6be0d4a9.png)

js code
<pre><code>
this.wait(3000, function () { // it is loaded ,im sure
		var mySelector = xp('//*[@id="nocaptcha"]/div[1]/span[1]/a[1]');
        if (this.exists(mySelector) {
			this.click(mySelector);
          // this.mouse.click('#nocaptcha a'); //never work
            this.echo('found #nocaptcha', 'INFO');
        }
        
    });
</code></pre>
the tag A is special with href is function?

any help is grateful.

thanks in advance!!!

**Comment by jefleponot** [comment]
Hi @whooyun 

Just try this

```js
casper.start('https://yourchinese.site');

casper.waitForSelector('#nocaptcha a', function() {
    this.click('#nocaptcha a');
},function(){
    this.echo('failed founding #nocaptcha', 'INFO');
});

casper.run();
```

**Comment by whooyun** [comment]
@jefleponot 
thanks a lot.
the click method is executed.
But my html page changes nothing,I think my function  **noCaptcha.reset(1)** doesn't execute.
Here is my debug info
![20170502171822](https://cloud.githubusercontent.com/assets/9583594/25611921/5fecae64-2f5b-11e7-9146-54274d31bf1e.png)

is there any way I can use to let my **noCaptcha.reset(1)** execute?
Thank you again!!!

**Comment by jefleponot** [comment]
@whooyun 

Your link must be visible : click doesn't work on no-visible element

You can also execute javascript code as : 
```js
casper.start('https://yourchinese.site');

casper.waitForSelector('#nocaptcha a', function() {
    this.evaluate(function(){
      noCaptcha.reset(1);
    });
},function(){
    this.echo('failed founding #nocaptcha', 'INFO');
});

casper.run();

```

**Comment by whooyun** [comment]
@jefleponot  Thanks so much.
My link is visible.
Here is my js file
[https://github.com/whooyun/zhuanzhuan/blob/master/why.js](url)

**Comment by whooyun** [comment]
@jefleponot Thanks so much.
My link is visible.
Here is my js file
https://github.com/whooyun/zhuanzhuan.git

**Comment by jefleponot** [comment]
@whooyun 

I saw your script and there are many troubles.

```js
var casper = require('casper').create({
    "verbose": true,
    "logLevel": "debug",
    "viewportSize" : {
        "width": 1024,
        "height": 768
    }, 
    "pageSettings": {
        "userAgent": 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0',
        "javascriptEnabled": true,
        "resourceTimeout": 2000
    }
});
````

after login I can't find any #nocaptcha selector.

I don't understand what you expect with multiple mouse.move calls .
Could you please send me screen-shots of that you want to do ?

**Comment by whooyun** [comment]
@jefleponot 
1.sometimes i can login successfully. So you cant find any #nocaptcha selector. It is up to application.

2.multiple mouse.move calls
The application can identify the operator by the mouse movement. It is just like google's man-machine authentication. So my code has many multiple mouse.move calls .

3.man-machine authentication successful
mouse down the small square, and drag to the right until the slider turn to green.
![20170503235815](https://cloud.githubusercontent.com/assets/9583594/25670799/6f98dc24-3060-11e7-8fbe-bdb425114152.png)
![20170503235903](https://cloud.githubusercontent.com/assets/9583594/25670810/78b22edc-3060-11e7-8842-32fbf918f28e.png)
![20170504002725](https://cloud.githubusercontent.com/assets/9583594/25670824/86cd30a2-3060-11e7-9370-a2f948d1d141.png)

4.man-machine authentication failed
the div will show '哎呀，出错了，点击刷新再来一次' means 'oops,verification failed, hava a try, click refresh link '.
![20170504002835](https://cloud.githubusercontent.com/assets/9583594/25670873/b109cb14-3060-11e7-8c1c-a4cf2dd80d01.png)
![20170504002920](https://cloud.githubusercontent.com/assets/9583594/25670896/ca4ef310-3060-11e7-8faf-ee20be035539.png)

5.my problem
So i should click refresh link for getting new authentication. But nothing changed when i click the 'refresh' link 
here is the code for getting new authentication
<pre>casper.waitUntilVisible('#nocaptcha a', function () { //if slide checkcode is wroing,i should refresh ,and get a new slide checkcode
	//this.click('#nocaptcha a');
	this.evaluate(function () {
		//document.querySelector('#nocaptcha a').click();
		noCaptcha.reset(1);
	});
	casper.click('#nocaptcha a');
	console.log('======>' + this.getElementAttribute('#nocaptcha a', 'href'));
	this.capture('0000.png');
}, function () {
	this.echo('failed founding #nocaptcha', 'INFO');
});</pre>

I uploaded my html code
https://github.com/whooyun/zhuanzhuan.git

**Comment by whooyun** [comment]
@jefleponot 
I solved the problem.
The noCaptcha.reset(1) can not work,because of the application prevent  refresh link click event.
Thanks so much.
My English is very bad,It's too ashamed.
感谢大神，辛苦大神了

**Comment by jefleponot** [comment]
Hi @whooyun 
 I just see your reply : good job.

Your code that drag&drop tag is not very nice 
You can use casper.getElementBounds()
with "#nc_1_n1t" and "#nc_1_n1z"

you could easily calculate the position to drag & drop

Regards jef
