### ISSUE TITLE
is the 'popup.closed' event never thrown?

### ISSUE THREAD

**Issue by KlausNie** [casperjs/casperjs#1822]
I'm running an application where i open a lot of popups. While the events 'popup.created' and 'popup.loaded' are thrown whenever i open a popup, the event 'popup.closed' is never thrown. Now if I understood it correctly, the popups never have to be closed, since they are regularly cleaned up [#1345](https://github.com/casperjs/casperjs/pull/1490). So should the closed event not be triggered when cleaning up popups?
I only stumbled upon this because my app seems to have a memory leak, and the unclosed popups seem to be the cause of it.

Is there a way to force a cleanup of popups? 'casper.popups.clean();' does not seem to be public api

PhantomJs: 1.9.8
Tested with Casperjs: 1.1.3 & 1.1.4

**Comment by jefleponot** [comment]
Hi @KlausNie 

You can use casper.page.close() to force closing event.

**Comment by KlausNie** [comment]
Thank you very much! That solved the issue and made it easy to close popups!

**Comment by jefleponot** [comment]
Hi @KlausNie 

your are welcome

**Comment by KlausNie** [comment]
Follow up:
casper.popups.clean() does remove the popups from casper.popups, but does not free their resources, is this intended?

**Comment by KlausNie** [comment]
Nevermind, my bad! It does free the popups resources!
