### ISSUE TITLE
Click doesn't work for Twitter's follower follow / unfollow button in CasperJS environment

### ISSUE THREAD

**Issue by WiwiC** [casperjs/casperjs#1824]
Hi everyone,

Well first, please let me tell you that I'm started in code, I've been coding for 1 month so don't judge me if my questions seems stupid. 

I actually want to follow Twitter accounts in a CasperJS environment. I have a list of twitter's account url and I want to automate the following. Indeed I have an excel with a list of user's names and user's url accounts I would like to follow but I didn't find any tool to follow a list of users from a csv file or txt file. I decided to try to code my own script as I'm trying to learn it is also a good training.

My Script is in 4 Steps:

I have an array of account's url that I want to follow. (In this example you'll just see a string with a single user's url)

- I pick the account's url I want to follow and open it in the browser. I start with the first one of the array
- I login to my Twitter by filling the form.
- I click on the following button of the user account.

For example, I log in to Twitter through this URL "https://twitter.com/googledrive". I move the mouse over the "Follow / Unfollow" button and right click in order to inspect the button element.
Then I right click on the element (in the HTML code) and select "Copy Unique Selector" which is : 
"_button.user-actions-follow-button.js-follow-btn.follow-button.btn_"

Then I just have to write the following line in the Console bar :
function () {
casper.thenClick(button_selector, ...)
};

to follow the account at the very end of my script. To be sure that all the elements of the page are loaded and every Step of my script are working, I'm saving a screenshot at every step. Basically everything is working well until the click on the Following button.
Indeed, when I go then to my followings list, the Google Drive account hasn't been added.

**Here is my script:** 

    var url_connexion = 'https://twitter.com/googledrive';  // _(This will be an array then, and the script will iterate ++ and loop until the end of the list)_

    var credentials = {email:"xxxxxxx@hotmail.fr",password:"xxxxxxxx"};

    var identifiant = 
    {input_email:'input[name="session[username_or_email]"]',
     input_password:'input[name="session[password]"]',
    valider_connexion:'input.submit.btn.primary-btn.js-submit'};

    var button_follow = "button.user-actions-follow-button.js-follow-btn.follow-button.btn";

     var Log_in = "a#signin-link.dropdown-toggle.js-dropdown-toggle.dropdown-signin";
  
     casper.start(url_connexion, function() {       // Casper open the link in the Browser

       casper.thenClick(Log_in, function () {        //The script clicks on the button to open the login pop up
       
          this.sendKeys(identifiant.input_email,credentials.email);   // fill the form with e-mail
       
          this.sendKeys(identifiant.input_password,credentials.password);   // fill the form with password
           
          casper.thenClick(identifiant.valider_connexion,function(){    // Click on "log in" and the user account displays

                 casper.wait(6000,function(){ 
                      casper.thenClick(button_follow, function () {       // Click on Follow (it is not working here !)
                            casper.wait(2000, function () {
                                  casper.capture("./screenshots.png");       // screenshot to check the following (I voluntary deleted others screenshots to make the code clearer)
             });
           });
         });
       });
     });
    });
    casper.run();

So here we are, I don't know why it's not working, I checked on Twitter and the unique selector of the following button isn't changing while the mouse scrolls over it or anything. I'm sure that all the element of the page are loaded and I tried with a _waitFor_ function to be sure but i didn't work as well. 
As I told you I started 1 month ago to code so all of your advices and good tips will be more than welcome.

Thank you very much. :)

**Comment by jefleponot** [comment]
Hi @WiwiC

Your approach is not correct

````js

var casper = require('casper').create();
casper.start('https://twitter.com/googledrive');

casper.then(function() {
   var login = {
        type: 'xpath',
        path: '//a[contains(text(),"login")]'
    };
    if (this.exists(login) {
        this.click(login);
    }
});

casper.then(function() {
    this.fill('form.signin', {
        'session[username_or_email]':    'xxxxxxx@hotmail.fr',
        'session[password]':                    'xxxxxxxx'
    }, true);
});

casper.then( function() {
    this.echo('Page: ' + this.getTitle());
});

casper.then( function() {
    casper.waitForSelector('button.user-actions-follow-button.js-follow-btn.follow-button.btn', function() {
        this.click('button.user-actions-follow-button.js-follow-btn.follow-button.btn');
    });
});

 casper.then(function () {
});

casper.run();
````

**Comment by WiwiC** [comment]
Hi @jefleponot 

Thank you for your answer. Your code is definitely nicer than mine thanks ! 
However It is still not following the account. The problem is that it seems that there is no way to click on the Follow button in the Casperjs environment.  The code runs well but when I go on my twitter account, the user hasn't been followed. Even the function casper.waitForSelector is not working.

Do you have any idea about where the problem comes from ?

**Comment by jefleponot** [comment]
@WiwiC 

Please send me a screen-shot where you want to click . I can't connect to twitter for my network ...

**Comment by jefleponot** [comment]
Salut @WiwiC 

it is the capture you have before the "waitForSelector" ?

   casper.capture('page.png');

**Comment by WiwiC** [comment]
@jefleponot 

Non, this is the capture of the button I want to click. The capture before the "waitForSelector" is this one: 

![step_4_twitter_connecte](https://cloud.githubusercontent.com/assets/22153690/25657469/4ae7e5c6-2ffe-11e7-828e-4c7a7450785d.png)

As you can see I'm connected to my account, but the click is not working. The capture after le "waitForSelector" is the same. When i go to check my account, I can see that it didn't follow the account.

**Comment by jefleponot** [comment]
Hi @WiwiC 

Everything seams ok
You can try a Xpath selector

```js
   var suivre = {
        type: 'xpath',
        path: '//span[contains(text(),"Suivre")]'
    };
casper.then( function() {
    casper.waitForSelector(suivre, function() {
        this.click(suivre);
    });
}, function(){
   casper.echo('Suivre non trouvé');
});
```

**Comment by jefleponot** [comment]
could you give me your phantomjs / slimerJS / casperJS version ?

**Comment by WiwiC** [comment]
@jefleponot 

Ok I'll try.

Are you French ?

Phantomjs : 2.1.1
Casperjs : 1.1.3
I don't have slimerJS...

Thank you.

**Comment by kensoh** [comment]
Hi @WiwiC I'm able to automate clicking the follow button using this XPath as the selector
`(//*[text()="Follow"])[1]`

To use XPath in CasperJS you can use `var x = require('casper').selectXPath;` and then replace the button_follow by `x('(//*[text()="Follow"])[1]')` or the way Jef showed you. I tested using CasperJS to drive the automation through SlimerJS/Firefox and it should work the same for PhantomJS (the headless invisible browser). Hopefully this works for you.

However, I discourage running automation on Twitter unless you are doing purely to practice CasperJS automation. This is because Twitter will monitor user behavior that seems automated and then block your account from making the interaction for some time. So you might end up with some semi-automated solution or adding long delays between each run. I experienced it when automatically replying tweets - https://twitter.com/tebelorg/status/835751300532838400

**Comment by kensoh** [comment]
Hi @WiwiC closing this for now but do reopen if it is still an issue to you and there's something we can assist!

**Comment by intrd** [comment]
Why it didn't work anymore? 
something about Content Security Policy?
