### ISSUE TITLE
Popup window doesn't have access to window.opener

### ISSUE THREAD

**Issue by awilson28** [casperjs/casperjs#1826]
First, thanks for this awesome library; it's a dream. 

I've nearly accomplished my web scraping goal but my scraper fails on the final step and I'm pretty sure it fails because the popup window is unable to access data from the originating window via `window.opener`.

Is data sharing among windows a known issue? 

Here's my code: 

``` javascript.js
'use strict';
var creds = {
    lru: "username", 
    pw: "password"
};

var casper = require('casper').create({
    verbose: true, 
    logLevel: 'debug', 
    clientScripts: ['./jquery-3.2.1.min.js']
});

casper.on('remote.message', function(msg) {
    this.echo('remote message caught: ' + msg);
});

casper.on("page.error", function(msg, trace) {
    this.echo("Page Error: " + msg, "ERROR");
});

casper
.on('popup.created', function() {
    this.echo("url popup created : " + this.getCurrentUrl(),"INFO");
})
.on('popup.loaded', function() {
    this.echo("url popup loaded : " + this.getCurrentUrl(),"INFO");
});

var url = 'https://main-url';

casper.start(url, function() {
   this.waitForSelector('form#loginform', function(){
        this.evaluate(function(username, password){
            document.querySelector('input[name="un"]').value = username;
            document.querySelector('input[name="pw"]').value = password;
            document.querySelector('#login-button').click();
        }, creds.lru, creds.pw);
    });
});


casper.then(function(){
    this.open('https://a-sub-url');
});

casper.then(function(){
    this.evaluate(function(){
        var box = document.getElementById('administrationrecorddata');
        var inputs = box.querySelectorAll('input');
        inputs[0].checked = true; 
        inputs[1].checked = true;
        inputs[2].checked = true;
        
        // THIS TRIGGGERS OPENING OF POPUP WINDOW
        // THE POPUP WINDOW invokes `window.opener.doSubmit` to load the data needed for the page 
        // AND it access data on the originating window 
        document.getElementById('runButton').click();     
    });
});


// ERROR OCCURS BECAUSE POPUP DOES HAVE DATA FROM ORIGINATING WINDOW
casper.wait(10000, function(){
    this.evaluate(function(){

        // DOWNLOAD PAGE HERE
        var download = document.getElementById('download');
        download.click();
    });
}); 
```

**Comment by awilson28** [comment]
Oh, also, I'm using an `waitForPopup` but it never fires even though the popup event listener fires: 

``` javascript.js
/// This code logs the url of the popup
casper
.on('popup.created', function() {
    this.echo("url popup created : " + this.getCurrentUrl(),"INFO");
})
.on('popup.loaded', function() {
    this.echo("url popup loaded : " + this.getCurrentUrl(),"INFO");
});

/// But this inexplicably times out 
casper.then(function(){
    this.waitForPopup({url: 'https://url.com'}, function(){
        console.log('popips ', this.popups)
        this.evaluate(function(){
            console.log('window opener !!!!!!!!!!!!!!!!!!!!!!: ', window.opener);
        });
    });
});

```

**Comment by jefleponot** [comment]
@awilson28 
Could you please precise version of CasperJS / SlimerJS /PhantomJS ?

data sharing between windows is often a security trouble so modern web browser doesn't support it. 
It is recommended to use "post message" https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage
Regards,

jef

**Comment by awilson28** [comment]
@jefleponot  Thanks for responding! CasperJS - 1.1.0-beta3; PhantomJS - 2.1.7

Would you mind drawing up how I might be able to use `postMessage` in the code I've provided?

Also, I think I'd want to use it when the popup opens -- any idea why `waitForPopup` times out even though the `popup.created` and `popup.loaded` events fire?

**Comment by awilson28** [comment]
@jefleponot bump : )

**Comment by jefleponot** [comment]
@awilson28 
I have no idea about your trouble. it is difficult to help you without have the true urls site.

**Comment by awilson28** [comment]
@jefleponot 
This makes sense. I bet you could figure out the issue rather quickly if you were able to run my program. Unfortunately, I can't share the program here because there are login credentials and other specifics that I feel uncomfortable posting to a public forum. May I email you? My email address is listed on my github profile. I'd greatly appreciate it if you could ping me. Like I said, I bet you could tell me what's wrong in no time if I sent you the program to run.

**Comment by kensoh** [comment]
@awilson28 this is an interesting automation scenario :) Btw for waitForPopup if you try using this.echo directly without invoking inside evaluate, and use regex instead (eg this.waitForPopup(/keyword/, ) to specify a keyword to look for in the popup URL, does it work that way?

**Comment by awilson28** [comment]
@kensoh hey Ken, thanks for responding! I've been having trouble with a particular page for a long time now. @jefleponot has provided invaluable help to me with regards to debugging and improving the program. There's one final step that's stumping us. Are you interested in a challenge? My email is on my profile page -- ping me and I'll send you the program for you to run

**Comment by kensoh** [comment]
@awilson28 I see.. Sure I've just emailed you. Please set login password to some temporary password or use a dummy userid if possible. I work on web automation so I am interested to take a quick look at this unique scenario which I have never encountered before.

However, certain websites are designed such that it can't be automatable. For eg the underlying technologies (PhantomJS/SlimerJS) used by CasperJS can't support that scenario. Then maybe can look into other ways such as SikuliX + Xvfb to let the computer automate purely through visual recognition, as a last resort.

**Comment by kensoh** [comment]
@awilson28 as emailed the other day, it looks like this case may not be automatable due to difference in behavior between headless PhantomJS browser and a real browser. Also, the website prevents access from non-US IP addresses which is treading on a grey line if Jef or I troubleshoot from Europe. 

Some of the suggestions to try are checking if Nightmare (through Electron) maintainer can advise via an issue, checking with web-developer friend to reverse-engineer the JS code, considering using Selenium WebdriverIO or SikuliX which works with real visible browsers. I hope maybe some CasperJS user from US sees this and able to take a look at your use case!

**Comment by awilson28** [comment]
@kensoh @jefleponot I'll close this issue since it looks like we've reached a conclusion about CasperJS's capabilities here. Also, I was mistaken - the new window does have access to the originating window via`window.opener`.

**Comment by kensoh** [comment]
@awilson28 thanks for raising this and walking through with us. I hope once headless Chrome is supported by CasperJS, scenarios like this can be done. Also, your persistence in exploring breadth of solutions for this scenario is admirable! Closing this issue for now, unless Jef has some other ideas to investigate further. In any case you have our emails ;)
