### ISSUE TITLE
casperjs options viewportSize work strange

### ISSUE THREAD

**Issue by ghfengg** [casperjs/casperjs#1829]
hi,i am confused to the options 'viewportSize'
if i only set width,eg.
`viewportSize: {
      width: 1000,
      //height: 300
    }
`
the screenshot's width is not 1000,If you want to let the effective width，must set height,height can be any value.eg
`viewportSize: {
      width: 1000,
      //height: 100-1000（the same effect ）
    }
`

can you tell me why this?

**Comment by ghfengg** [comment]
if i not set height ,it will use phantomjs default config {width:400,height:300}，and height will auto

**Comment by jefleponot** [comment]
Hi @ghfengg 

"viewportSize" property sets the size of the viewport for the layout process. It is useful to set the preferred initial size before loading the page, e.g. to choose between 'landscape' vs 'portrait'.

ViewportSize effectively forces the size of the PAGE. it is not the size of the window so height can't be fix except if you forces a scrolling bar style.
