### ISSUE TITLE
Feature Request: Scroll wheel control for the mouse module

### ISSUE THREAD

**Issue by QwertyZW** [casperjs/casperjs#1830]
Sometimes the javascript on a webpage can potentially break scrolling with the mouse (but not with the scrollbar)

Providing scroll wheel control opens doors for writing appropriate tests.

**Comment by kensoh** [comment]
Hi @QwertyZW does the existing [scrollTo()](http://docs.casperjs.org/en/latest/modules/casper.html#scrollto) and [scrollToBottom()](http://docs.casperjs.org/en/latest/modules/casper.html#scrolltobottom) methods work for your use case? I don't use them myself but I saw users mentioning them to handle scrolling on a webpage.

**Comment by kensoh** [comment]
Btw thought this is an [interesting gist](https://gist.github.com/aresnick/2035f8e3bae0cfe66eec) by a CasperJS user @aresnick on infinite scroll.

**Comment by QwertyZW** [comment]
Hi Ken, 

I'm looking to simulate the mouse's scroll wheel functionality to see if I can recreate/test scenarios where the javascript breaks the scroll wheel. scrollTo, and scrollToBottom and the scroll bar on the side woudn't be affected if some javascript listened on the mousewheel and simply prevented the default event. To this extend I would like to be able to test this effect.

I'm pretty sure the gist will be useful for those who seek its functionality.

**Comment by kensoh** [comment]
@QwertyZW I see.. I get it now. You are saying some websites use JavaScript and tap onto the mouse scroll wheel events. And for those websites what CasperJS can provide now won't be enough to interact with them.

Thanks for sharing this interesting use case, hope CasperJS maintainers review this suggestion and maybe find a way to implement this. When I look through the issues, it looks like downloading of files and scrolling is a recurring theme that comes back from time to time.

**Comment by jefleponot** [comment]
@QwertyZW 
I'm also interested in this feature 
Have you a site name where I could test this kind of event ?

**Comment by QwertyZW** [comment]
@jefleponot, Unfortunately the last time I was running into it was before doing a code cleanup pass on frontend source. The platform has moved on to production and the issue has been mitigated.

I'm not aware of any websites off the top of my head that exhibit this issue but here's an exhibiting snippet:

```
<html>
    <body>
        <div class="long-div">

        </div>
        <style>
            .long-div{
                height:3000px;
                width:400px;
                background: linear-gradient( 0deg, blue, green 50%, red );
            }
        </style>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script>
            (function(jquery){
                $(window).bind('mousewheel DOMMouseScroll', function(event){
                    if (event.originalEvent.wheelDelta > 0 || event.originalEvent.detail < 0) {
                        console.log('up')
                        event.preventDefault()
                    }
                    else {
                        console.log('down')
                        event.preventDefault()
                    }
                })
            })($)
        </script>
    </body>
</html>
```

**Comment by kensoh** [comment]
Bumping -

**Comment by kensoh** [comment]
Archiving issue using ARCHIVE label as CasperJS, like PhantomJS, is not actively maintained for now.
