### ISSUE TITLE
Unable to set custom headers

### ISSUE THREAD

**Issue by Jaimesg** [casperjs/casperjs#1832]
Hi, i'm trying to change some headers but nothing is working:
`var casper = require('casper').create({   
   // stepTimeout: 15000,
    verbose: false, 
    logLevel: 'error',
    pageSettings: {
         loadImages:  true,       
         loadPlugins: true,         
         userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.364',
         customHeaders: {
            Connection: 'keep-alive',
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
        }
    }
});`

I also tried:
`phantom.page.customHeaders = {
    "User-Agent" : "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:26.0) Gecko/20100101 Firefox/26.0",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.5",
    "Accept-Encoding": "gzip, deflate",
    "Connection" : "keep-alive"
};`

And for a single connection:
`this.open('http://localhost/post.php', {
        method: 'post',
        headers: {
            'Accept': 'application/json'
        }
    });`

None of them are working or am i doing something wrong?
Thanks

**Comment by kensoh** [comment]
Hi @Jaimesg have you tried something like this from the documentation?
http://docs.casperjs.org/en/latest/modules/casper.html#open

```js
casper.open('http://some.testserver.com/post.php', {
    method: 'post',
    data:   {
        'title': 'Plop',
        'body':  'Wow.'
    },
    headers: {
        'Accept-Language': 'fr,fr-fr;q=0.8,en-us;q=0.5,en;q=0.3'
    }
});
```

I'm CasperJS user for couple of years. Looking through open issues to see if anything I can help. Can't tell why your code didn't work. Saw something similar being used in below example.

https://holsson.wordpress.com/2016/02/04/adding-a-custom-http-header-using-casperjs/

**Comment by kensoh** [comment]
Hi @Jaimesg I was looking at your code yesterday and cannot see anything wrong. Do you have an example website or script to test this? I'm a CasperJS user for couple of years, now looking through open issues to see if anything I can help and also learn at the same time.

**Comment by kensoh** [comment]
Adding on, using this example from [documentation](http://docs.casperjs.org/en/latest/modules/casper.html#getpagecontent) seems to work for me. I have modified to get an API request from a Singapore government data API on weather forecast and it works. Below is the code and output (api key is masked).

```js
var casper = require('casper').create();

casper.start().then(function() {
    this.open('https://api.data.gov.sg/v1/environment/24-hour-weather-forecast', {
        method: 'get',
        headers: {
        'api-key': 'my-api-key'
        }
    });
});

casper.run(function() {
    require('utils').dump(JSON.parse(this.getPageContent())); this.exit();
});
```

```
{
    "items": [
        {
            "update_timestamp": "2017-05-29T05:51:15+08:00",
            "timestamp": "2017-05-29T05:37:00+08:00",
            "valid_period": {
                "start": "2017-05-29T06:00:00+08:00",
                "end": "2017-05-30T06:00:00+08:00"
            },
            "general": {
                "forecast": "Thundery Showers",
                "relative_humidity": {
                    "high": 95,
                    "low": 65
                },
                "temperature": {
                    "high": 32,
                    "low": 24
                },
                "wind": {
                    "speed": {
                        "high": 25,
                        "low": 10
                    },
                    "direction": "SSE"
                }
            },
            "periods": [
                {
                    "time": {
                        "start": "2017-05-29T06:00:00+08:00",
                        "end": "2017-05-29T12:00:00+08:00"
                    },
                    "regions": {
                        "east": "Thundery Showers",
                        "central": "Thundery Showers",
                        "south": "Thundery Showers",
                        "north": "Thundery Showers",
                        "west": "Thundery Showers"
                    }
                },
                {
                    "time": {
                        "start": "2017-05-29T12:00:00+08:00",
                        "end": "2017-05-29T18:00:00+08:00"
                    },
                    "regions": {
                        "east": "Thundery Showers",
                        "central": "Thundery Showers",
                        "south": "Thundery Showers",
                        "north": "Thundery Showers",
                        "west": "Thundery Showers"
                    }
                },
                {
                    "time": {
                        "start": "2017-05-29T18:00:00+08:00",
                        "end": "2017-05-30T06:00:00+08:00"
                    },
                    "regions": {
                        "east": "Cloudy",
                        "central": "Cloudy",
                        "south": "Cloudy",
                        "north": "Cloudy",
                        "west": "Cloudy"
                    }
                }
            ]
        }
    ],
    "api_info": {
        "status": "healthy"
    }
}
```

**Comment by Jaimesg** [comment]
Hi, thank you very much for your reply, the only thing that worked was this:

`casper.on('started', function () {
  this.page.customHeaders = {
    "User-Agent" : "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:26.0) Gecko/20100101 Firefox/26.0", 
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", 
    "Accept-Language": "en-US,en;q=0.5",
    "Accept-Encoding": "gzip, deflate",
    "Connection" : "keep-alive"
  }
});`

Placed right before casper.start()

**Comment by kensoh** [comment]
Cool @Jaimesg thanks for updating and sharing what works for you!

Other users can benefit from this thread in future when they search on custom headers :smile:
