### ISSUE TITLE
casperjs test highcharts data, return variable from casper.evaluate() go wrong

### ISSUE THREAD

**Issue by daorren** [casperjs/casperjs#1833]
Recently I'm working on using casperjs to test webpages  which render highcharts.

And I found that sometimes objects returned from `casper.evaluate()` could go wrong.

I will use highcharts' own demo as my example, and you can run these scripts below directly

> casperjs@1.1.4
> phantomjs@2.1.1
> python@2.7.10
---

When I test simple charts of highcharts, like line-basic, everything's OK, below is the code

```js
casper.test.begin('tests', function suite(test) {
  casper.start("https://www.highcharts.com/demo/line-basic", function() {
    test.assertExists('#container', " container is found");
  });

  casper.then(function() {
    var highcharts_data = this.evaluate(function() {
      return jQuery('#container').highcharts().series;
    });
    console.log(highcharts_data);
  })

  casper.run(function() {
    test.done();
  });
});
``` 

```shell
# output
PASS  container is found
[object Object],[object Object],[object Object],[object Object],[object Object]
PASS tests
```
You can see here it's all OK, `highcharts_data` returned from `evaluate()` is an array of 5 objects

However, things went wrong when I test some complicate charts like waterfall, it's not that complicated btw

```js
casper.test.begin('tests', function suite(test) {
  casper.start("https://www.highcharts.com/demo/waterfall", function() {
    test.assertExists('#container', " container is found");
  });

  // casper.wait(4000, function() {
  //   this.echo("I've waited for 4 seconds.");
  // });

  casper.waitFor(function check() {
    return this.evaluate(function() {
      return jQuery('#container').highcharts().series[0].data instanceof Array && jQuery('#container').highcharts().series[0].data.length == 7;
    });
  }, function then() {
    console.log('check OK');

    var highcharts_data = this.evaluate(function() {
      return jQuery('#container').highcharts().series[0].data;
    });
    console.log(highcharts_data);
    console.log(highcharts_data.length);

  }, function timeout() {
    console.log("I can't haz my screenshot.");
    this.exit();
  });

  casper.run(function() {
    test.done();
  });
});

```

```shell
# output
PASS  container is found
check OK

0
PASS tests
```
The `highcharts_data` returned from `evaluate()` is something like `[]`, but it's supposed to be a array of 7 elements
and I'm sure that I have waited as long as I can, so chart's rendering performance shouldn't cause this.

**Comment by daorren** [comment]
I think highcharts caused this, and I have done something to work around.

I'm closing this issue, hope it doesn't bother you guys

**Comment by jefleponot** [comment]
Hi @daorren

**Comment by daorren** [comment]
Yeah, I think you are right about this, and maybe it should be mentioned in the documentation?
