### ISSUE TITLE
casper.existsText

### ISSUE THREAD

**Issue by QwertyZW** [casperjs/casperjs#1840]
This is a feature request.

Implement `casper.existsText`. It would return true if the page contains a certain string of text. The function would be analogous to `casper.waitForText` and `casper.exists`

**Comment by mickaelandrieu** [comment]
Hi,

you are everywhere :)

I don't think this feature will be added, you can access ``tester`` module using casper.test, and the access to http://docs.casperjs.org/en/latest/modules/tester.html#asserttextexists.

PS: was one of the main contributor of casperjs ;)

**Comment by mickaelandrieu** [comment]
sorry for closing, bad manipulation

**Comment by QwertyZW** [comment]
Hey @mickaelandrieu !

I could say the same about you :)

The reason I need a function that returns a boolean is because I'd like to use it within a waitFor; a function that can be repeatedly executed without failing the current scope of the program.

I'm currently doing 

```
casper.waitFor(function check() {
	return this.evaluate(function() {
		return /.*customer\/account\/$/.test(document.location.pathname) || (document.body.textContent.indexOf('There is already an account') > 0)
	})
}
```

But instead I'd like to be able to do 

```
casper.waitFor(function check() {
	return this.evaluate(function() {
		return /.*customer\/account\/$/.test(document.location.pathname)
	}) || casper.existsText('There is already an account')
}
```

PS: well in that case thank you for contributing to this awesome tool :)

**Comment by jefleponot** [comment]
Hi @QwertyZW and @mickaelandrieu 

why don't you use the method getpagecontent or getHTML to test your text ?

http://docs.casperjs.org/en/latest/modules/casper.html#getpagecontent

**Comment by jefleponot** [comment]
You can also propose a PR :-°

**Comment by QwertyZW** [comment]
I wasn't aware of that method. Would I still have to manually search the buffer if I did?

**Comment by jefleponot** [comment]
I suppose, but it will be a nice thing to create a method that can search data or text into all Frames / Iframes and opened Windows :-)

**Comment by QwertyZW** [comment]
I agree

**Comment by kensoh** [comment]
Closing the issue for now, but do reopen if there's anything! Or if a PR proposal :smile:
