### ISSUE TITLE
phantomjs 1.9.8 TypeError: 'undefined' is not a function (evaluating  'b.bind(this,d,i,f)')

### ISSUE THREAD

**Issue by nimishseraphim** [casperjs/casperjs#1842]
I am using casperjs with phantomjs 1.9.8 ( I know it's old version, but somehow my team is using it). When I click a button I see below error:

```
phantomjs 1.9.8 TypeError: 'undefined' is not a function (evaluating 
'b.bind(this,d,i,f)')
```
I used casper.click() and this.mouse.click() and even creating mouse event with javascript, but none of them actually clicks the button , but gives above error. Same script works fine if I have phantomjs 2.0, so I know there is no problem with the selectors. By the screenshot, I can make that that the element is clicked, but may be due to above error, it doesn't do anything else.

So, is there any work around to handle this case for phantomjs 1.9.8

Below is the element which I am trying to click.

`<div ng-repeat="value in choice.Value" class="variation-choice" ng-bind="value" ng-click="selectChoice(choice.Name, value, $parent.$index, $index)" ng-mouseenter="variationMouseEnter(value, choice.Name, $parent.$index, $index)" ng-mouseleave="variationMouseLeave(value, choice.Name, $parent.$index, $index)" ng-attr-id="{{ getVariationElementID($parent.$index, $index) }}" ng-class="{'unselectable': !isValueSelectable(value, choice.Name, $parent.$index, $index)}" id="aspectChoice_0_0">S</div>`

and below is my simple code to click the element. When I take the screenshot, it does show that the element is clicked, but it just doesn't do what it is supposed to do after button is clicked.

```
var variationFirstRow='#variationsScrollContainer> div div div:nth-child(X)';
casper.waitForSelector(variationFirstRow.replace("X", 3)).then (function (){
            casper.click(variationFirstRow.replace("X", 3));            
            console.log('clicking button');
        });
```

**Comment by jefleponot** [comment]
Hi @nimishseraphim 

I don't think that phantomJS 1.9 could understand css3selectors

you'd better use a XPath selector like '//*[@id="variationsScrollContainer"]//div/div/div[X]"

http://docs.casperjs.org/en/latest/selectors.html

Regards
