### ISSUE TITLE
Is it possible to define modules that make tests?

### ISSUE THREAD

**Issue by jcguarinpenaranda** [casperjs/casperjs#1843]
Hi,

I'm trying to test my app and I have had several problems. What I'm trying to do is to define modules that test several things without having to copy/paste everytime the same tests.

For example, in my index page I want to validate that I have the menu displayed:
**index.e2e.js**
```js
var isVisibleMenuAndFooter = require('./functions/isVisibleMenuAndFooter');

var url = "http://localhost:12345";
// i could import here other modules that would help me test other things of the app
isVisibleMenuAndFooter(casper, url);
```

And in isVisibleMenuAndFooter I wrote
**/functions/isVisibleMenuAndFooter.js**
```js
module.exports = function(casper, url){
    casper.test.begin("Menu and footer", 2, function(test){
        casper.start(url, function(){
            test.assertVisible('#navMain','Shows the menu');
            test.assertVisible('#footerMain', 'Shows the footer');
        })
        .then(function() {
            test.done();
        })
        .run();
    })
}
```

When I execute this code it runs, but as I start getting some more complicated tests, Casper exits without logging any issue

![captura de pantalla de 2017-06-29 12-33-312](https://user-images.githubusercontent.com/7200821/27701789-a16161d4-5cc7-11e7-9083-20ad987358a3.png)

I am getting a little crazy with this because I don't know if the approach I am taking is a wrong usage of the tool or if it should work

**Comment by kensoh** [comment]
Hi @jcguarinpenaranda I don't use CasperJS for testing, but I think I saw some issues mentioning handling this by specifying multiple files or directories so that more than 1 test is executed in the run. Not sure if doing this way can achieve your intended purpose?

http://docs.casperjs.org/en/latest/testing.html#test-command-args-and-options

**Comment by jcguarinpenaranda** [comment]
Thank you Ken,

The way I am executing my tests is ``` casperjs test --auto-exit=no
e2e/*.e2e.js  ```, which i understand should get only the .e2e.js files. I
added that auto-exit=no flag to see if it prevented the test from exiting
but had no luck

2017-06-30 6:05 GMT-05:00 Ken <notifications@github.com>:

**Comment by kensoh** [comment]
I see.. I have not come across other people using tests in this modularized way. From your issue description it sounds like for more complicated tests then it fail.

You can try creating complete working CasperJS .js files and run with *.e2e.js to see if the same error happens. Also run with --verbose option and set casper.options.logLevel = 'debug' to see if any clues from PhantomJS that might be causing pre-mature exit.

Copying current main maintainer @jefleponot to see if he or other maintainers/users have more inputs on this. You can reply with your current CasperJS + PhantomJS version (this is often his first question on issues).

**Comment by jcguarinpenaranda** [comment]
Thank you so much,

My versions are:
- "casperjs": "^1.1.4"
- "phantomjs-prebuilt": "^2.1.14"


2017-07-01 6:38 GMT-05:00 Ken <notifications@github.com>:

**Comment by kensoh** [comment]
Bumping -

**Comment by kensoh** [comment]
Closing this for now as CasperJS, similar to PhantomJS is not actively maintained.
