### ISSUE TITLE
Possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by kensoh** [casperjs/casperjs#1844]
Posting this issue on behalf of David @djwales who raised this in CasperJS mailing list. He's open to sending PRs for this and I thought here would be better for maintainers @jefleponot to have a look.

---

Hi,

I have been using CasperJS with PhantomJS for a number of weeks and everything was working as expected. However, I encountered a problem yesterday that took a lot of investigating before I could resolve the problem. I started receiving the following message after some more tests were added (added to the same file as other tests):

```
(node) warning: possible EventEmitter memory leak detected. %d listeners added. Use emitter.setMaxListeners() to increase limit.
```
I spent a lot of time googling for information on the issue but kept getting results for the equivalent problem in node based applications. I could not find anything for CasperJS/PhantomJS. I eventually decided to look into the CasperJS source and managed to find where the message was being raised. It was coming from the events.js file in modules directory. After a bit more searching around the source I discovered that I could increase the max listeners by calling the setMaxListeners method on the casper prototype. This then resolved my problem. 

Just for reference, I pulled CasperJS and PhantomJS into my project from NPM and invoke casper from an NPM script. The mention of node in the console output along with this fact added more confusion because I wasn't sure if it was something to do with node (via NPM) or CasperJS/PhantomJS.

The point I would like to raise in here is that though the error message was correct, the suggestion was misleading and didn't help me to resolve the problem. This is how the error message presented itself in my console output:

```
(node) warning: possible EventEmitter memory leak detected. %d listeners added. Use emitter.setMaxListeners() to increase limit. 11
  <rest of path>/src/client/phantomjs:/platform/events.js:184 in addListener
FAIL (node) warning: possible EventEmitter memory leak detected. %d listeners added. Use emitter.setMaxListeners() to increase limit. 11
Failed on url: http://localhost:8080/criminal/case-details
#    type: error
#    file: <rest of path>/src/client/test/e2e/dist/scenarios/test.scn.js
#    subject: false
#    error: "(node) warning: possible EventEmitter memory leak detected. %d listeners added. Use emitter.setMaxListeners() to increase limit. 11"
#    stack: in addListener() in phantomjs://platform/events.js:184
```

It tells the user to use emitter.setMaxListeners, but I was not able to determine how to do this. All attempts to search through google just showed how to do it in a node based application. The line starting with "stack" also confused me because I couldn't determine where the file was located, though this is probably down tomy lack of experience with PhantomJS.

I would like to propose two things and would welcome your thoughts. 

1. Change the error message in modules/events.js to indicate that you can up the limit using casper.setMaxListeners.
2. Update the online documentation to show that this method exists on the casper prototype and when/why it should be used.

I appreciate that upping this limit may be masking a problem, but it would be good to reference it in the documentation and explain the consequences of changing this value. I am happy to create a pull requests for both points if the community think it is the right thing to do.

Just to add to my original post. I have since discovered what was the underlying cause of the error. I found out by modifying the error message in event.js to write out the type of listener it was trying to add. On seeing it I was quickly able to diagnose the problem.

I would like to amend point 1 in my original post to say that the error message should also indicate what type of listener it was attempting to add when the threshold was met. I think this would save others a lot of time if they encounter the same problem.

**Comment by jefleponot** [comment]
Hi @kensoh 

I thank you a lot for all the time you take to answer and close all issues.
@n1k0 added the EventEmitter library because PhantomJS can't manage events. 
We never upgrade this library , so it could be nice to do it.

What do you think about that ?

**Comment by kensoh** [comment]
Hi @jefleponot it is my privilege and pleasure to be able to contribute to CasperJS in small ways. The remaining open issues are mostly in three categories. 1. issue still happens (can't be proven to be resolved from my limited experience) 2. issue for review by maintainers (for eg reviewing an enhancement request suggestion), 3. issue for discussion by maintainers (raised by maintainers to discuss a feature or future direction). If there is something I can help with for that let me know, for example tagging the issues with certain labels, so that it is easier for you or other maintainers to maximize the use of your time on higher level tasks.

I see, thanks for sharing, that is really cool the event library. This suggestion is raised by David @djwales in the CasperJS mailing list and he's open to submitting PRs for this. I'll email him to ask him subscribe to this issue so that he receive updates. From my own view, I believe making improvements on existing features is good, but the bigger impact for CasperJS users may be to integrate with Chrome + Chrome headless. That probably has the largest impact on CasperJS users, but it is however a mammoth task that requires unimaginable amount of time by maintainers.

I should be 1-2 weeks away from integrating with Chrome for the web tool I doing base on CasperJS. But the approach I am taking may be irrelevant to CasperJS project (I used a separate PHP thread to manage the websocket communications with Chrome). I did that way to avoid Node.js dependency if chrome-remote-interface is used and also avoiding promise/await features that I believe is not yet supported for CasperJS. https://github.com/tebelorg/TagUI/issues/24#issuecomment-312361674

**Comment by jefleponot** [comment]
Ho @kensoh 

I'm working to allows CasperJS to run with Chrome headless or standard mode.

I don't think that casperJS could use the chrome-remote-interface because it is more for remote tools like Selenium hq. So I began to recreate all the phantomJS API with webExtension. 
It works very well.
But I'm not used to develop this kind of script so I have many issues. Do you think you could help me ?

**Comment by kensoh** [comment]
Cool news and approach @jefleponot :smile: Wow, that must be a lot of effort that you have already put in.

I see.. Thanks for sharing your approach. My php approach is taking up 50% CPU time on my 3 year-old macbook air and making the laptop hot. Polling frequency can be adjusted but for optimal performance I am checking every 50 ms now.

I am not from qualified web developer background, but can you give me a sample of the type of issues you are encountering so I can see if there is anything I can contribute? To here or my email ken@tebel.org whichever is more convenient for you.

**Comment by djwales** [comment]
Hi @jefleponot / @kensoh

I just want to start off by saying thank you to all those that have put effort into building CasperJS. I have found it to be an easy to use tool that has really helped me.

With regards to the EventEmitter library, I assume it hasn't needed much attention because it works well and is pretty mature now. The issue I faced was down to an error in my tests that caused the listener limit to be reached resulting in the error that I was seeing. I don't think the EventEmitter functionality needs any changes other than modifying the error message it was giving me. As someone relatively new to CasperJS/PhantomJS I felt the error message was miss-leading because it was implying it was a node based problem. All attempts at googling the problem just showed up node based problems. 

I am happy to create a PR to update the error message in the addListener and prependListener functions in event.js. I would propose the message should be:

> Warning: Possible EventEmitter memory leak detected. _x_ listeners of type _y_ added. Use casper.setMaxListeners() to increase the limit if you are expecting the current limit of _z_ to be exceeded. Please refer to online documentation for more information. 

x - would be the current number of listeners.
y - would be the type of listener.
z - would be the current max listeners limit.

Does that seem like a sensible message? I think the inclusion of the type of listener it was trying to add is key. Once I knew what it was trying to add I could quickly identify the problem in my code.

I would also like to add some information to the online documentation to show that the setMaxListeners function exists on the casper prototype. The text would include additional context that would allow the user to determine if upping the listener limit is the correct thing to do, or not.

**Comment by jefleponot** [comment]
Hi @djwales 

Thanks for contribution, we are waiting for your PR :smile:

**Comment by djwales** [comment]
@jefleponot 

I have just forked the repo and pulled it down to my machine. I wanted to run the tests and lint before I started to make sure they all passed before I made any changes, but they are failing. Here are the failures:

Selftest with PhantomJS:
FAIL Default system shell exited on timeout (TERM signal) with exit code 0
FAIL shell script to trap TERM signal returned exitCode 0

Selftest with SlimerJS:
FAIL Find "A Clockwork Orange" within the selector "#content-editable-div"
FAIL Casper.viewport() can change the height of page viewport
FAIL Casper.viewport() popup changes height asynchronously

ESLint against modules/casper.js is showing 231 warnings. 

Is this normal, or should all tests be passing and lint have no warnings? For info, I am working on a Mac running macOS Sierra 10.12.5. I am running ZSH in iTerm. I have PhantomJS version 2.1.1, SlimerJS version 0.10.3

**Comment by jefleponot** [comment]
Hi @djwales 

I haven't test on Mac so your errors are a real mystery for me.
Does the selftest run before any change ? 

You can also test your code on Travis Ci in pushing your branch ...

**Comment by djwales** [comment]
Hi @jefleponot,

I decided to spin up a linux VM and try them in there. The tests all passed so I am assuming it is either something on my mac or they just fail on macs in general. I created the change, pulled them into the linux VM, re-ran the tests and they still passed so I created the pull request.

Yes, this was before I made any changes. I wanted to make sure they worked before I started so I would know that any failures following my change would be the result of something I did.

**Comment by djwales** [comment]
@jefleponot 

I have just asked a colleague to try it on his mac. We cloned the main repo from github and then did a selftest and he gets the same two failures that I get on my mac for the phantom based run. 

Can I just check we are doing it correctly. We are executing the following command from the root of the repo:

`./bin/casperjs selftest`

We have installed phantomjs-prebuilt from npm into the global space.

**Comment by jefleponot** [comment]
@djwales 

use : 
https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-macosx.zip

standard tests command
>  bin/casperjs selftest

**Comment by djwales** [comment]
@jefleponot 

Removed phantomjs-prebuilt from npm and tried using the link you suggested - still get the same failures. 

FAIL Default system shell exited on timeout (TERM signal) with exit code 0
#    type: assertEquals
#    file: <rest of path>/casperjs/tests/suites/casper/wait.js
#    subject: 0
#    expected: 15

FAIL shell script to trap TERM signal returned exitCode 0
#    type: assertEquals
#    file: <rest of path>/casperjs/tests/suites/casper/wait.js
#    subject: 0
#    expected: 9

**Comment by jefleponot** [comment]
@djwales 

Could you please run the command ?

> bin/casperjs selftest tests/suites/casper/wait.js

**Comment by djwales** [comment]
Two fail. Here is the complete output:

> $ ./bin/casperjs selftest tests/suites/casper/wait.js
> Test file: tests/suites/casper/wait.js
> # wait() tests
> PASS Casper.wait() can wait for a given amount of time
> PASS wait() tests (1 test)
> # waitFor() tests
> PASS Casper.waitFor() can wait for something to happen
> PASS waitFor() processes onTimeout callback
> PASS waitFor() can run test function when timeout is set to 1
> PASS waitFor() can run a last test function after timeout
> PASS waitFor() tests (4 tests)
> # waitForResource() tests
> PASS Casper.waitForResource() waits for a resource
> PASS Casper.waitForResource() waits for a resource using RegExp
> PASS waitForResource() tests (2 tests)
> # waitForSelector() tests
> PASS Casper.waitForSelector() waits for a selector to exist
> PASS waitForSelector() tests (1 test)
> # waitForText() tests
> PASS Casper.waitForText() can wait for text
> PASS Casper.waitForText() can wait for regexp
> PASS Casper.waitForText() can wait for decoded HTML text
> PASS waitForText() tests (3 tests)
> # waitForSelectorTextChange() tests
> PASS Casper.waitForSelectorTextChange() can wait for text on a selector to change
> PASS waitForSelectorTextChange() tests (1 test)
> # waitUntilVisible() tests
> PASS Casper.waitUntilVisible() waits for a selector being visible
> PASS Casper.waitUntilVisible() waits for a selector being visible
> PASS waitUntilVisible() tests (2 tests)
> # waitForUrl() regexp tests
> PASS Casper.waitForUrl() waits for a given regexp url
> PASS waitForUrl() regexp tests (1 test)
> # waitForUrl() string tests
> PASS Casper.waitForUrl() waits for a given string url
> PASS waitForUrl() string tests (1 test)
> # waitForExec() tests
> PASS Casper.waitForExec() can call the default system shell and kills it on timeout: {"command":"/bin/zsh","parameters":[],"pid":19345,"stdout":"","stderr":"","exitCode":0,"elapsedTime":2065,"isChildNotFinished":0}
> PASS Default system shell exited on timeout (TERM signal) and used PID 19345
> PASS Default system shell returned "isChildNotFinished" 0 on timeout
> FAIL Default system shell exited on timeout (TERM signal) with exit code 0
> \#    type: assertEquals
> \#    file: tests/suites/casper/wait.js
> \#    subject: 0
> \#    expected: 15
> PASS Casper.waitForExec() tried to call non existing executable: {"command":"/casperjs/run0.exe","parameters":[],"pid":0,"stdout":"","stderr":"","exitCode":null,"elapsedTime":null,"isChildNotFinished":0}
> PASS Non existing executable returned "pid" 0
> PASS Non existing executable returned "isChildNotFinished" 0
> PASS Non existing executable returned exitCode null
> PASS Non existing executable returned elapsedTime null
> PASS Casper.waitForExec() can call "lsExecutable" on "workingDirectory": {"command":"/bin/ls","parameters":["-a","/casperjs"],"pid":19347,"stdout":".\n..\n.eslintignore\n.eslintrc\n.git\n.gitattributes\n.gitignore\n.gitmodules\n.idea\n.travis.yml\nCHANGELOG.md\nCONTRIBUTING.md\nCONTRIBUTORS.md\nLICENSE.md\nMakefile\nREADME.md\nbin\ncasperjs.gemspec\ndocs\nmodules\npackage.json\nrpm\nsamples\nsrc\ntests\n","stderr":"","exitCode":0,"elapsedTime":7,"isChildNotFinished":0}
> PASS "lsExecutable" on "workingDirectory" used PID 19347
> PASS "lsExecutable" on "workingDirectory" returned "isChildNotFinished" 0
> PASS "lsExecutable" on "workingDirectory" returned exitCode 0
> PASS "lsExecutable" on "workingDirectory" returned stdout ".\n..\n.eslintignore\n.eslintrc\n.git\n.gitattributes\n.gitignore\n.gitmodules\n.idea\n.travis.yml\nCHANGELOG.md\nCONTRIBUTING.md\nCONTRIBUTORS.md\nLICENSE.md\nMakefile\nREADME.md\nbin\ncasperjs.gemspec\ndocs\nmodules\npackage.json\nrpm\nsamples\nsrc\ntests\n"
> PASS Casper.waitForExec() can call "lsExecutable" on "notExecutable": {"command":"/bin/ls","parameters":["/casperjs/run0.exe"],"pid":19348,"stdout":"","stderr":"ls: /casperjs/run0.exe: No such file or directory\n","exitCode":1,"elapsedTime":3,"isChildNotFinished":0}
> PASS "lsExecutable" on "notExecutable" used PID 19348
> PASS "lsExecutable" on "notExecutable" returned "isChildNotFinished" 0
> PASS "lsExecutable" on "notExecutable" returned exitCode 1
> PASS "lsExecutable" on "notExecutable" returned stderr "ls: /casperjs/run0.exe: No such file or directory\n"
> PASS Casper.waitForExec() can call shell script to trap TERM signal and then kills it: {"command":"/bin/sh","parameters":["-c","trap \"echo TERM trapped!\" TERM ; sleep 60"],"pid":19349,"stdout":"","stderr":"","exitCode":0,"elapsedTime":1642,"isChildNotFinished":0}
> PASS shell script to trap TERM signal used PID 19349
> PASS shell script to trap TERM signal returned "isChildNotFinished" 0
> FAIL shell script to trap TERM signal returned exitCode 0
> \#    type: assertEquals
> \#    file: tests/suites/casper/wait.js
> \#    subject: 0
> \#    expected: 9
> PASS waitForExec() tests (24 tests)
> FAIL 39 tests executed in 9.933s, 37 passed, 2 failed, 0 dubious, 0 skipped.
> 
> Details for the 2 failed tests:
> 
> In tests/suites/casper/wait.js
>   waitForExec() tests
>     assertEquals: Default system shell exited on timeout (TERM signal) with exit code 0
> In tests/suites/casper/wait.js
>   waitForExec() tests
>     assertEquals: shell script to trap TERM signal returned exitCode 0

**Comment by jefleponot** [comment]
Thank you @djwales 

The trouble occurs because of a recent update adding, by @hlr1983,  waitForExec Method. waitForExec had never been test on Mac.

**Comment by jefleponot** [comment]
@djwales , Could You comment the waitForExec tests in the file "tests/suites/casper/wait.js" and rerun all tests

**Comment by djwales** [comment]
@jefleponot 

I commented them out and the remaining tests passed. 

PASS 1223 tests executed in 33.767s, 1223 passed, 0 failed, 0 dubious, 5 skipped.

**Comment by zhaiduo** [comment]
It works with require('events').EventEmitter.prototype._maxListeners.

**Comment by djwales** [comment]
@zhaiduo 

Should I include your suggestion in the error message and online documentation?

**Comment by jefleponot** [comment]
Casper object inherits of EventEmitter so it could be better to communicate about
 "casper.setMaxListeners" method

**Comment by zhaiduo** [comment]
@djwales 
It maybe just work in my situation, better after the full test.
:)

**Comment by kensoh** [comment]
Thanks @djwales and guys! It looks like the related PRs and commits have been merged. But do reopen if anything!Thanks @djwales and guys! It looks like the related PRs and commits have been merged. But do reopen if anything!
