### ISSUE TITLE
TypeError: null is not an object (evaluating 'names[0]')                        

### ISSUE THREAD

**Issue by milosb793** [casperjs/casperjs#1849]
Hello everyone! 
I'm sorry for opening new issue, but i don't know other way to ask. I'm currently newbie using CasperJS. I'm trying few examples now, but i can't get this working. I want to grab all values from html table, and put it in var named `names`. But, it's always null. I hardcode it, and still.. Please help. There is source:

```javascript
var casper = require('casper').create();
var names = [];
var namesLink = "http://www.world-english.org/boys_names_list.htm";

function getNames() {
    // var fields = document.querySelectorAll("tr>font");
    var arr = [1,2,3,4].split(",");
    // return Array.prototype.map.call(fields,function (e) {
    //     return e.innerText.trim();
    // })
    return arr
}

casper.start(namesLink, function () {
   console.log("started...")
    this.echo(this.getTitle());
});

casper.wait(1000,function () {
    this.echo("Waiting to load...");
});

casper.then(function () {
        this.echo("Loaded.");
        this.echo("Getting names...");
});

casper.then(function () {
        names = this.evaluate(getNames)
});

// casper.then(function() {
//     // aggregate results for the 'phantomjs' search
//     names = names.concat(this.evaluate(getNames));
// });

casper.run(function () {
    this.echo("Gotcha!");
    this.echo("Found names: ");
    this.echo(names[0])
    //this.echo('-' + muskaImena.join("\n")).exit();
    this.exit();
});
```

**Comment by kensoh** [comment]
This looks like a JavaScript typo, at least for the part that you meant to hard-code above. When I change to below line it works, as .split() is meant to split a string into an array, not an array as the source variable.

```js
var arr = "1,2,3,4".split(",");
```

```
started...
List of English Names and their Meaning - Boys
Waiting to load...
Loaded.
Getting names...
Gotcha!
Found names: 
1
```

**Comment by kensoh** [comment]
Also, the CSS selector looks incorrect and it is quite hard to reference the table elements because there are no unique identifiers. I'm able to get result by declaring XPath at start of script, then use a while loop to do the selection via XPath. n is incremented by 2 to skip the 2nd column which is the meaning of the name (assuming you only want to extract the names in column 1).

```js
var x = require('casper').selectXPath;
...
var n = 1;
while (this.exists(x('((//table)[4]//font)['+n+']'))){
    this.echo(this.fetchText(x('((//table)[4]//font)['+n+']'))); n+=2;}
```

**Comment by milosb793** [comment]
Thanks a lot @kensoh ! You made it!

**Comment by kensoh** [comment]
Welcome Milos @milosb793 ! Let us know again if you run into any issues / bugs etc.
