### ISSUE TITLE
Document Error for the Function "Casper.options.onResourceRequested"

### ISSUE THREAD

**Issue by pastchick3** [casperjs/casperjs#1850]
Hello everyone. I am learning JavaScript and CasperJS using CasperJS v1.1.4-1 (PhantomJS v2.1.1). The document tells me the signature of "onResourceRequested" function is `onResourceRequested(Object Casper, Object resource)`. However this function really takes 3 arguments, like `onResourceRequested(Object Casper, Object requestData, Object networkRequest)`.

If we try to print the last 2 objects out with the following script:
```
var casper = require('casper').create({
    verbose: true,
    logLevel: "warning",
    onResourceRequested: function (casper, requestData, networkRequest) {
        casper.log("**************  RequestData   **************", "warning")
        for(var i in requestData) {
            casper.log(i, "warning")
        }
        casper.log("************** NetworkRequest **************", "warning")
        for(var j in networkRequest) {
            casper.log(j, "warning")
        }
        casper.log("**************    Log End     **************", "warning")
    }
})

casper.start("http://casperjs.org/", function() {
    this.echo(this.getTitle())
})
    
casper.run()
```
The output looks like this:
![screenshot from 2017-07-13 13-22-03](https://user-images.githubusercontent.com/19465540/28152308-566e1ef8-6765-11e7-957c-14980f52090b.png)

Comparing with the document of PhantomJS, I also found some new methods are available in the CasperJS `networkRequest` object.

I hope the document could be updated and it will be helpful if someone could add more explanations about those new methods into the document.

**Comment by kensoh** [comment]
Actually, the documentation matches with the CasperJS implementation of [onResourceRequested](https://github.com/casperjs/casperjs/blob/master/modules/casper.js) with only 2 parameters. As CasperJS is a wrapper around PhantomJS, its API probably will not be an exact match of PhantomJS.

However, I don't know if this is by design choice or some technical reason for excluding networkRequest. Copying current main maintainer Jef @jefleponot to see if he or other folks have more inputs on this :)

```js
        page.onResourceRequested = function onResourceRequested(requestData, request) {
            casper.emit('resource.requested', requestData, request);
            var checkUrl = ((phantom.casperEngine === 'phantomjs' && utils.ltVersion(phantom.version, '2.1.0')) ||
                       (phantom.casperEngine === 'slimerjs' && utils.ltVersion(slimer.version, '0.10.0'))) ? utils.decodeUrl(requestData.url) : requestData.url;
            if (checkUrl === casper.requestUrl) {
                casper.emit('page.resource.requested', requestData, request);
            }
            if (utils.isFunction(casper.options.onResourceRequested)) {
                casper.options.onResourceRequested.call(casper, casper, requestData, request);
            }
            casper.requestData[requestData.id] = requestData;
        };
```

**Comment by jefleponot** [comment]
HI @pastchick3 and @kensoh 

CasperJS Documentation is not really clear. 

All PhantomJS callbacks methods "onResourceRequested, onResourceError ..."  are converted or transformed into casperJS events : casper.on ("resource.requested", function(){}); ..."
Then event is created the "casper" object is called before other parameters.
 
So documentation could be evolve into

```comment
``resource.requested``
~~~~~~~~~~~~~~~~~~~~~~

**Arguments:** ``requestData, networkRequest``

You can also abort or change requests and alse update Headers ::

    casper.on('page.resource.requested', function(requestData, networkRequest) {
        if (requestData.url.indexOf('http://adserver.com') === 0) {
            networkRequest.abort();
        }
    });

Properties of requestData are:

- ``id``: the number of the requested resource
- ``method``: the http method (“get”, “post”..)
- ``url``: the url of the resource
- ``time``: a Date object
- ``headers``: the list of headers (list of objects {name:'', value:''})
- ``postData``: a string containing the body of the request, when method is “post” or “put” (SlimerJS 0.9)

The networkRequest object has two methods:

- ``abort()``: call it to cancel the request. onResourceReceived and onLoadFinished will be called.
- ``changeUrl(url)``: abort the current request and do an immediate redirection to the given url.
- ``setHeader(key, value, merge)``: allows you to set an header on the HTTP request. If value is null or an empty string, the header will be removed. The merge parameter (only available on SlimerJS), is a boolean: true to merge the given value with an existing value for this header. If false, the old value is replaced by the new one. (Introduced: SlimerJS 0.9)
```

**Comment by kensoh** [comment]
Thanks @jefleponot for your quick reply :smile:, I see.. I add Documentation label to this issue.

**Comment by jefleponot** [comment]
It will be nice to modify also resource.received and resource.timeout

```comment
``resource.received``
~~~~~~~~~~~~~~~~~~~~~~

**Arguments:** ``responseData``

    casper.on('.resource.received', function(responseData) {
       this.echo(responseData.url);
    });

Properties of responseData are:

- ``id``: the number of the requested resource
- ``url``: the url of the resource
- ``time``: a Date object
- ``headers``: the list of headers (list of objects {name:'', value:''})
- ``bodySize``: the size of the received content (may increase during multiple call of the callback)
- ``contentType``: the content type of the resource
- ``contentCharset``: the charset used for the content of the resource  (slimerjs only).
- ``redirectURL``: if the request has been redirected, this is the redirected url
- ``stage``: “start”, “end” or “” for intermediate chunk of data
- ``status``: the HTTP response code (200..)
- ``statusText``: the HTTP response text for the status (“Ok”...)
- ``referrer``: the referer url (slimerjs only)
- ``body``: the content, it may change during multiple call for the same request (slimerjs only).
- ``httpVersion.major``: the major part of the HTTP protocol version (slimerjs only).
- ``httpVersion.minor``: the minor part of the HTTP protocol version (slimerjs only).


``resource.timeout``
~~~~~~~~~~~~~~~~~~~~~~

**Arguments:** ``resourceError``

Emitted when the execution time of any resource has exceeded the value of settings.resourceTimeout.

you can configure timeout with ``settings.resourceTimeout`` parameter.

Properties of responseData are:

- ``id``: the number of the requested resource
- ``url``: the url of the resource
- ``errorCode``: an error code: 408
- ``errorString``: the error message.
- ``time``: a Date object
- ``headers``: the list of headers (list of objects {name:'', value:''})
- ``method``: the http method (“get”, “post”..)

```

**Comment by jefleponot** [comment]
@kensoh 

Another thing realy important that I don't understand : 
PhantomJS (and CasperJS) are configure to work on HTTP 1.0 because of minimalist headers : no keep-alive, no hostname ... so flows are slow and not identical with other web-browsers.

Do you thing we could set a default configuration that would communicate in HTTP1.1 ?

Regards

**Comment by kensoh** [comment]
Hi @jefleponot, wow that's fast your new commit. That sounds like a great idea, it probably improves performance and usability. Also, some websites such as LinkedIn will not work if headers are not set.

It should be good thing to use best-practice headers. However, even with documentation, the downside maybe is breaking some existing user scripts which work on the minimal headers. Another catch is different users may think their default config is the best and want it to be implemented as the default for CasperJS.

**Comment by pastchick3** [comment]
Hi @kensoh and @jefleponot. Thank you all for your rapid replies!
