### ISSUE TITLE
Usage with material-ui

### ISSUE THREAD

**Issue by tgoldenberg** [casperjs/casperjs#1852]
Material-ui is a very popular front-end library for ReactJS. I would love to use CasperJS for testing, but I'm afraid it doesn't work with some of the components.

For example, I am unable to programmatically select an option on the DropDownMenu component. Is there anyone that is using CasperJS with material-ui? Would love some suggestions.

Thanks.

**Comment by kensoh** [comment]
Hi @tgoldenberg I'm not familiar with frontend development, but I am aware that at the moment CasperJS does not support dropdown options natively. Below issue has more details about this and there is already a function in that issue that's provided by a stackoverflow user which works for me. Can you have a look to see if that casper.selectOptionByValue function works for you? https://github.com/casperjs/casperjs/issues/1390

**Comment by jefleponot** [comment]
Hi @tgoldenberg 

Could you please give an example of code to reproduce the trouble ?

**Comment by tgoldenberg** [comment]
So I was able to get this working by providing hidden `<input />` fields. Otherwise, not sure how you would operate the material-ui DropDown programmatically. Closing this.
