### ISSUE TITLE
CasperError: Can't find module fs

### ISSUE THREAD

**Issue by wahengchang** [casperjs/casperjs#1855]
Casperjs is suddently not working since few npm packages is installed
`CasperError: Can't find module fs` is showed, but `fs` is not used in the code 

 - I have tried installing both `casperjs` and `phantomjs`
 - uninstalling fs

but same error is still showing.

## Run example
[example.js](https://gist.github.com/wahengchang/56c44ac901907ab075384185dcf18591)
```
$ casperjs example.js 
CasperError: Can't find module fs

  phantomjs://code/bootstrap.js:307 in patchedRequire
  phantomjs://platform/colorizer.js:35
CasperError: Can't find module fs

  phantomjs://code/bootstrap.js:307 in patchedRequire
  phantomjs://platform/casper.js:36
TypeError: undefined is not a constructor (evaluating 'require('casper').create()')

  phantomjs://code/example.js:2 in global code
  :0 in injectJs
  phantomjs://code/bootstrap.js:456

```

 
## Phantomjs version
```
$ phantomjs -v
2.1.1
```
## Casperjs Version
```
$ casperjs -v
Unable to open file: -v

  phantomjs://code/bootstrap.js:113 in __die
Unable to load script -v; check file syntax

  phantomjs://code/bootstrap.js:113 in __die
```

## Nodejs Version
```
$ node -v
v8.1.2
```

## NPM Version
```
$ npm -v
5.0.3
```

**Comment by jefleponot** [comment]
@wahengchang 

npm is not uptodate 
CasperJs current version is 1.1.4-1

@BIGjuevos please, could you update or give us command to change npm repo ?

**Comment by wahengchang** [comment]
I just did update `npm` to 5.3.0, and still now working.

```
$ npm -v
5.3.0

```

error happened when runing [example.js](https://gist.github.com/wahengchang/56c44ac901907ab075384185dcf18591)

```
$ casperjs./ example.js 
CasperError: Can't find module fs

  phantomjs://code/bootstrap.js:307 in patchedRequire
  phantomjs://platform/colorizer.js:35
CasperError: Can't find module fs

  phantomjs://code/bootstrap.js:307 in patchedRequire
  phantomjs://platform/casper.js:36
TypeError: undefined is not a constructor (evaluating 'require('casper').create()')

  phantomjs://code/example.js:2 in global code
  :0 in injectJs
  phantomjs://code/bootstrap.js:456
```

And 
```
$ casperjs -v
Unable to open file: -v

  phantomjs://code/bootstrap.js:113 in __die
Unable to load script -v; check file syntax

  phantomjs://code/bootstrap.js:113 in __die
```

**Comment by wahengchang** [comment]
bcz I am using nvm, I have tried different version of `node.js` and `npm`, the same error is happened:

node
```
$ node -v
v6.11.0
```

npm
```
$ npm -v
3.10.10
```

casperjs
```
$ node_modules/casperjs/bin/casperjs ./example.js 
CasperError: Can't find module fs

  phantomjs://code/bootstrap.js:307 in patchedRequire
  phantomjs://platform/colorizer.js:35
CasperError: Can't find module fs

  phantomjs://code/bootstrap.js:307 in patchedRequire
  phantomjs://platform/casper.js:36
TypeError: undefined is not a constructor (evaluating 'require('casper').create()')

  phantomjs://code/example.js:2 in global code
  :0 in injectJs
  phantomjs://code/bootstrap.js:456
```

**Comment by jefleponot** [comment]
please try  using "git clone https://github.com/casperjs/casperjs.git"

**Comment by wahengchang** [comment]
@jefleponot , I tried clone to both `npm global` and `local node_modules`, same error.

btw, my phantomjs project works well like normal, what does it mean 'fs' not found?

**Comment by jefleponot** [comment]
current version is 1.1.4-1

**Comment by wahengchang** [comment]
problem fixed by deleting `node_modules` and reinstall.

`casperjs` and `fs` modules are not in `node_modules`, so I think the error is resulted by other dependencies, which dose not seem like using `fs`
