### ISSUE TITLE
please help,i cant get any page with https

### ISSUE THREAD

**Issue by orlandoabreu221** [casperjs/casperjs#1858]
Hi guys,im using phantomsjs 2.1.1, php 5.6, casperjs 1.1.0, and im running localhost. im ok getting pages with http,but i cant get anything with https, i have read about this everywhere,i have tried another versions of casperjs and phantomjs ,and everything ive seen,but anything is working for me . Oh,also im usign the github.com/jonnnnyw/php-phantomjs version. So Im leaving you here the debug code and my script code,because thats better than 1000 words,lmao. Thank u very much guys!
/*********** Debug Code im getting ************/
array (size=22)
0 => string '[info] [phantom] Starting...' (length=28)
1 => string '[info] [phantom] Running suite: 3 steps' (length=39)
2 => string '[debug] [phantom] Successfully injected Casper client-side utilities' (length=68)
3 => string '[debug] [phantom] opening url: https://www.cubamaltrato.com/, HTTP GET' (length=70)
4 => string '[debug] [phantom] Navigation requested: url=https://www.cubamaltrato.com/, type=Other, willNavigate=true, isMainFrame=true' (length=122)
5 => string '[info] [phantom] Step anonymous 1/3: done in 73ms.' (length=50)
6 => string '[warning] [phantom] Loading resource failed with status=fail: https://www.cubamaltrato.com/' (length=91)
7 => string '[info] [phantom] Step _step 2/3: done in 1295ms.' (length=48)
8 => string '[info] [phantom] wait() finished waiting for 10000ms.' (length=53)
9 => string 'timeout occured' (length=15)
10 => string '[CURRENT_URL]about:blank' (length=24)
11 => string '[CURRENT_TITLE]' (length=15)
12 => string '[CURRENT_PAGE_CONTENT]' (length=61)
13 => string '[CURRENT_HTML]' (length=53)
14 => string '[CURRENT_HEADERS][]' (length=19)
15 => string '[CURRENT_STATUS]null' (length=20)
16 => string '[CURRENT_STATUS_TEXT]null' (length=25)
17 => string '[CURRENT_COOKIES][]' (length=19)
18 => string '[info] [phantom] Step anonymous 3/3: done in 11301ms.' (length=53)
19 => string '[info] [phantom] Done 3 steps in 11317ms' (length=40)
20 => string '[debug] [phantom] Navigation requested: url=about:blank, type=Other, willNavigate=true, isMainFrame=true' (length=104)
21 => string '[debug] [phantom] url changed to "about:blank"' (length=46)

/***** my script code ***/
use Browser\Casper;
$casper = new Casper();
$casper->setPath2Casper('my path to casperjs/bin/');
//some people said this is the answer but it wasnt for me :(
$casper->setOptions(array('ignore-ssl-errors' => 'yes','ssl-protocol' => 'any','debug' => 'true'));
$casper->setUserAgent('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36');
//some page with https
$casper->start('https://www.cubamaltrato.com');
$casper->wait(10000);
$output = $casper->getOutput();
$start = $casper->run();
//this one returns the debug code from above
var_dump($start);
//and this one just an empty array
var_dump($output);
//this one returns the html only when the page is using http
$html = $casper->getHtml();

**Comment by kensoh** [comment]
@orlandoabreu221 this looks like a PHP library invoking CasperJS/PhantomJS. Another info missing from above is it looks to be executed from a [PHP wrapper library for CasperJS](https://github.com/alwex/php-casperjs).

I am able to get output without making any special changes to ignore SSL errors. Can you check with newer version of CasperJS and try again? I'm using v1.1.4 but there's already v1.1.4-1 now.
 
Below is snippet of my code in CasperJS script - 
```js
casper.options.pageSettings = {
loadImages: true,
loadPlugins: true,
webSecurityEnabled: true,
ignoreSslErrors: false,
localToRemoteUrlAccessEnabled: false
};
...
this.echo(this.getHTML());
```

**Comment by orlandoabreu221** [comment]
@kensoh i already tried with that casper version,and now i tried with those options for casperjs bur unfortunately nothing changed :(

**Comment by kensoh** [comment]
It sounds like running directly using CasperJS works but running through the wrappers break. I saw that you have already raised issues to the 2 PHP wrappers repos for CasperJS (https://github.com/alwex/php-casperjs/issues/47) and PhantomJS (https://github.com/jonnnnyw/php-phantomjs/issues/196). I guess gotta see their maintainers response. You may want to leave this issue open here for some time to see inputs from other users or maintainers.

Adding on, looking at the code at [PHP wrapper repo php-casperjs](https://github.com/alwex/php-casperjs/blob/master/src/Casper.php), the following line is used to get the page html. I tried running the same line in normal CasperJS script and it works for above webpage. If CasperJS script directly works and the code at php-casperjs looks ok, then it might be environmental issues in your setup. Will need the maintainers for php-casperjs / php-phantomjs to advise more.
```js
this.getHTML().replace(new RegExp('\\r?\\n','g'), ''))
```

**Comment by kensoh** [comment]
Closing the issue for now - this looks like an issue with the wrappers as using CasperJS directly works for both http and https websites. But do reopen if there's anything else we can help with! I just saw that there are no response yet from the wrappers projects. Also copying CasperJS maintainer @jefleponot for info.
