### ISSUE TITLE
proxy doesn't work

### ISSUE THREAD

**Issue by debug529** [casperjs/casperjs#1860]
Hi @jefleponot ,it seems doesn't work what ever I set the proxy to pageSettings
I am sure the proxy support https, a part of my code below:
```
var casper = require('casper').create({
    verbose: true,
    logLevel: "debug",
    pageSettings: {
        proxy: '117.24.xx.xx:27220',
        loadImages: true,
        loadPlugins: true,
        webSecurityEnabled: true,
        ignoreSslErrors: true,
        localToRemoteUrlAccessEnabled: false
    }
});
```
then I launch the command: casperjs  test.js
```
[info] [phantom] Starting...
[info] [phantom] Running suite: 14 steps
[debug] [phantom] Successfully injected Casper client-side utilities
[info] [phantom] Step _step 1/14: done in 44ms.
[debug] [phantom] opening url: https://www.baidu.com/s?ie=utf-8&f=8&rsv_bp=1&tn=91762569_hao_pg&wd=ip&oq=casperjs%2520%25E8%25AE%25BE%25E7%25BD%25AE%25E4%25BB%25A3%25E7%2590%2586&rsv_pq=ecb562820006213d&rsv_t=eb4fZHI6dn7a%2FZpXYI58oWSXzgCh3yNHGYjG%2Be4p4TI082xKzTdoBv%2BRVwPzyaiMu%2B9du%2F3n&rqlang=cn&rsv_enter=1&rsv_sug3=2&rsv_sug1=1&rsv_sug7=100&rsv_sug2=0&inputT=894&rsv_sug4=894, HTTP GET
[debug] [phantom] Navigation requested: url=https://www.baidu.com/s?ie=utf-8&f=8&rsv_bp=1&tn=91762569_hao_pg&wd=ip&oq=casperjs%2520%25E8%25AE%25BE%25E7%25BD%25AE%25E4%25BB%25A3%25E7%2590%2586&rsv_pq=ecb562820006213d&rsv_t=eb4fZHI6dn7a%2FZpXYI58oWSXzgCh3yNHGYjG%2Be4p4TI082xKzTdoBv%2BRVwPzyaiMu%2B9du%2F3n&rqlang=cn&rsv_enter=1&rsv_sug3=2&rsv_sug1=1&rsv_sug7=100&rsv_sug2=0&inputT=894&rsv_sug4=894, type=Other, willNavigate=true, isMainFrame=true
[warning] [phantom] Loading resource failed with status=fail: https://www.baidu.com/s?ie=utf-8&f=8&rsv_bp=1&tn=91762569_hao_pg&wd=ip&oq=casperjs%2520%25E8%25AE%25BE%25E7%25BD%25AE%25E4%25BB%25A3%25E7%2590%2586&rsv_pq=ecb562820006213d&rsv_t=eb4fZHI6dn7a%2FZpXYI58oWSXzgCh3yNHGYjG%2Be4p4TI082xKzTdoBv%2BRVwPzyaiMu%2B9du%2F3n&rqlang=cn&rsv_enter=1&rsv_sug3=2&rsv_sug1=1&rsv_sug7=100&rsv_sug2=0&inputT=894&rsv_sug4=894

```

when I remove the setting of `proxy: '117.24.xx.xx:27220'` 
launch the command: casperjs  --proxy="117.24.xx.xx:27220" test.js
is useful, but I want to set proxy in js file, have any idea?

Regrads

**Comment by kensoh** [comment]
@debug529 try this? Adding some inputs while seeing Jef's advice. This is taken from https://github.com/casperjs/casperjs/issues/1445

```js
phantom.setProxy('IP', 'port', 'manual', '', '');
```
The last 2 parameters are username and password, if the proxy you use requires credentials.

**Comment by jefleponot** [comment]
@kensoh 
Thanks for reply

**Comment by jefleponot** [comment]
phantom.setProxy('10.48.2.254','8080','manual','userx','passx');


QNetworkProxy::NoProxy | 2 | No proxying is used
-- | -- | --
QNetworkProxy::DefaultProxy | 0 | Proxy is determined based on the application proxy set using setApplicationProxy()
QNetworkProxy::Socks5Proxy | 1 | Socks5 proxying is used
QNetworkProxy::HttpProxy | 3 | HTTP transparent proxying is used (This value was introduced in 4.3.)
QNetworkProxy::HttpCachingProxy | 4 | Proxying for HTTP requests only (This value was introduced in 4.4.)
QNetworkProxy::FtpCachingProxy | 5 | Proxying for FTP requests only (This value was introduced in 4.4.)

**Comment by debug529** [comment]
em, it's worked!
`phantom.setProxy('117.24.xx.xx', '27220', 'manual', '', '');`
Thank you for your assistance @kensoh @jefleponot
