### ISSUE TITLE
Canvas Fingerprint Spoofing ?

### ISSUE THREAD

**Issue by fipso** [casperjs/casperjs#1861]
Hello,
Is there any way to have some Canvas Fingerprint Spoofing in CasperJS ?

Like this:
https://addons.mozilla.org/de/firefox/addon/no-canvas-fingerprinting/

More Info:
https://multiloginapp.com/how-canvas-fingerprint-blockers-make-you-easily-trackable/

My Code to test:

```
var casper = require('casper').create({
    verbose: true,
    logLevel: "debug"
});

casper.userAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36');

casper.on('remote.message', function(msg){
    this.echo('Console: ' + msg, 'INFO');
})
casper.on('page.error', function(msg, trace){
    this.echo('Error: ' + msg, 'ERROR');
});

casper.start('https://browserleaks.com/canvas', function(){
    this.echo('Loaded BrowserLeaks/Canvas', 'GREEN_BAR');
    this.capture('canvasLeak.png');
    this.exit();
});

casper.run();
```
![canvas2](https://user-images.githubusercontent.com/8930842/28776069-3fc0fd12-75f5-11e7-818c-264f20b02768.png)

Any Ideas ?

**Comment by jefleponot** [comment]
hi @fipso 

what do you really want to do ? Casperjs does that web browser PhantomJs ans SlimerJS supposes to do.

**Comment by fipso** [comment]
You are right. This is not a CasperJS Problem.

**Comment by fipso** [comment]
#closed

**Comment by kensoh** [comment]
Thanks @fipso , closing the issue but do reopen if there's anything!
