### ISSUE TITLE
Have a good Holidays

### ISSUE THREAD

**Issue by jefleponot** [casperjs/casperjs#1862]
Hi everybody . I will be back the 20 august. 
Thanks for using CasperJS

Many news for september
Like new browsers .... 

Regards jef

C You @ken

**Comment by kensoh** [comment]
Thanks @jefleponot for note and maintaining CasperJS, enjoy your holidays! 🏖

**Comment by kensoh** [comment]
Hi @jefleponot I've looked through all open issues again. Have followed-up on those that I can follow-up, and closed quite a number which hasn't got replies or progress for few years. Copied some of the issues to you for info. Will also be on the lookup if any subscribers want to reopen any of the issues.

**Comment by jefleponot** [comment]
Back from Italia
