### ISSUE TITLE
Selftest fail

### ISSUE THREAD

**Issue by ovidiul** [casperjs/casperjs#1863]
I am running casperjs 1.1.4, and the selftest seems to have 1 fail

PASS Node exists
PASS Handles markup in failure node
PASS Handles markup in error node
PASS Handles markup in error node
PASS XUnitReporter() can handle markup in nodes (4 tests)
FAIL 1226 tests executed in 31.495s, 1225 passed, 1 failed, 0 dubious, 5 skipped.

Details for the 1 failed test:

In /usr/lib/node_modules/casperjs/tests/suites/casper/wait.js:2513
  waitForExec() tests
    uncaughtError: TypeError: undefined is not an object (evaluating 'command.split')

anybody knows how to fix this? Thanks

**Comment by katp4** [comment]
The tests run fine for me. Can you give us some more details?
OS
Phantomjs version

**Comment by ovidiul** [comment]
Sure, please check below

# cat /proc/version
Linux version 3.13.0-74-generic (buildd@lcy01-07) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #118-Ubuntu SMP Thu Dec 17 22:52:10 UTC 2015

# phantomjs --version
2.1.1

**Comment by katp4** [comment]
I'm on 16.04 and it works fine for me and can't really test it on your version. If anyone else can replicate it please let us know.

**Comment by kensoh** [comment]
Bumping up the thread and also copying maintainer @jefleponot

**Comment by nnnikolay** [comment]
The same for me, I have the following picture

```
# XUnitReporter() can handle markup in nodes
PASS Node exists
PASS Handles markup in failure node
PASS Handles markup in error node
PASS Handles markup in error node
PASS XUnitReporter() can handle markup in nodes (4 tests)
FAIL 1248 tests executed in 37.459s, 1246 passed, 2 failed, 0 dubious, 5 skipped.

Details for the 2 failed tests:

In /.../tests/node_modules/casperjs/tests/suites/casper/wait.js
  waitForExec() tests
    assertEquals: Default system shell exited on timeout (TERM signal) with exit code 0
In /.../tests/node_modules/casperjs/tests/suites/casper/wait.js
  waitForExec() tests
    assertEquals: shell script to trap TERM signal returned exitCode 0
```

Here is my casperjs version v1.1.4, phantomjs is v2.1.1 and Python 2.7.10
I'm using OSX 10.13.1 and have installed casper and phantom in a certain folder with help npm

**Comment by akashthapa** [comment]
@nnnikolay did you fix test failed issue?

Same failed message for me and I have exactly same casperjs, phantomjs and OSX 10.13.3

```
FAIL 1248 tests executed in 37.349s, 1246 passed, 2 failed, 0 dubious, 5 skipped.

Details for the 2 failed tests:

In /usr/local/lib/node_modules/casperjs/tests/suites/casper/wait.js
  waitForExec() tests
    assertEquals: Default system shell exited on timeout (TERM signal) with exit code 0
In /usr/local/lib/node_modules/casperjs/tests/suites/casper/wait.js
  waitForExec() tests
    assertEquals: shell script to trap TERM signal returned exitCode 0
```

**Comment by kensoh** [comment]
Closing the issue as CasperJS, like PhantomJS, is not being actively maintained. But do continue discussion if any!

**Comment by kensoh** [comment]
waitForExec() should be able to work correctly on macOS, Linux, Windows, do try using it in your scripts and see how it goes. As CasperJS is not being actively maintained for now, I don't think there is anyone going to debug and fix the self-test error.
