### ISSUE TITLE
clarification: What does it mean to run casperjs with node?

### ISSUE THREAD

**Issue by bryanrasmussen** [casperjs/casperjs#1864]
In the documentation there are given various ways one can run the examples - one of which is using node as per the following
`node casperjs.js sample.js`

and I don't understand the point? Since node packages etc. won't work in a casperjs script is there a benefit to this? 
Is there an example of really making node and casperjs work together?

**Comment by katp4** [comment]
I believe the documentation is wrong. If you follow the instruction as it says and try to run it with the Node command or Phantomjs command it just doesn't work. 
Anyway, when calling a node/casperjs/phantomjs script the next argument must be a filename so it will just fail every time. Can someone please verify this and correct the documentation please?

**Comment by bryanrasmussen** [comment]
node can run casperjs, it just doesn't seem to provide any particular use (from the node end of things I mean)

For example if I have a script casperTester.js


```
var runner = function(config) {
  var casper = require('casper').create();
  var domain = config.domains.pop();
  console.log(domain);
 
  function getLinks() {
      var links = document.querySelectorAll('a');
      return Array.prototype.map.call(links, function (e) {
          var href = e.getAttribute('href');
          return href;
      });
  }

  // Opens casperjs homepage
  casper.start(domain);

  casper.then(function () {
      var linksLen;
      links = this.evaluate(getLinks);
      linksLen = links.length;
      if(linksLen > 0) {
        console.log(links);
      } else {
        this.wait(2000, function() {
          var links2 = this.evaluate(getLinks);
          console.log('after wait ' + links2.length);
          console.log(links2);
        });
      }
  });

  casper.run();
}

runner({
  domains: ['http://www.sundhed.dk']
})
```

and run it with 
 node .\node_modules\casperjs\bin\casperjs.js .\casperTest.js
it works (this is me being lazy and not setting up the casperjs.js 

At first I thought you couldn't do any requiring of any node modules, but I found that while
`var elasticsearch = require('elasticsearch');`
causes a crash with stuff like 

```
ReferenceError: Can't find variable: process


  phantomjs://platform/path.js:26

TypeError: undefined is not a constructor (evaluating '_.inherits(ErrorAbstract, Error)')


  phantomjs://platform/errors.js:38

Error: Cannot find module 'events'


  phantomjs://platform/bootstrap.js:299 in require

  phantomjs://platform/bootstrap.js:263 in require

  phantomjs://platform/log.js:4

Error: Cannot find module 'http'


  phantomjs://platform/bootstrap.js:299 in require
  phantomjs://platform/bootstrap.js:263 in require
  phantomjs://platform/http.js:13

TypeError: undefined is not a constructor (evaluating '_.inherits(AngularSerializer, JsonSerializer)')

```

you are able to require some modules (haven't tried actually using it ) because 
you are able to declare
` const urllib = require('url');`

at the top of the script and still have the script run. 

I'm guessing though from the earlier output and looking through the casperjs.js script that it really isn't the node module being loaded, instead I'm assuming either phantomjs or casperjs has some module it understands as being 'url' and my success in declaring the module and not failing is in this case an accident. 

So this anyway is my point about running with node - why would I do and what benefit does it give me to be able to do this?

**Comment by bryanrasmussen** [comment]
I guess if I want to find out what JavaScript features are supported I should look at QTWebkit? Or is there a good overview? I ask because while map is supported filter doesn't seem to be which made me waste some time.

**Comment by katp4** [comment]
I'm sorry i can't help you further, i didn't even know you can run a casper script via node. The only things i know for sure is that you can require modules but they are Casper specific modules and you cannot require node modules. Reference http://docs.casperjs.org/en/latest/writing_modules.html 

> CasperJS allows using nodejs modules installed through npm. Note that since CasperJS uses it’s own JavaScript environment, npm modules that use node-specific features will not work under CasperJS.

**Comment by bryanrasmussen** [comment]
Ok that makes sense, so the benefit of running in node is you can load node
modules that are just pure javascript.

**Comment by bryanrasmussen** [comment]
I guess I still find it not very useful. I think that clarification of what it means should be added to the documentation where it shows using node because it gave me some confusion when I first tried it and I guess I'm not the only one (out of the few who probably try)

**Comment by kensoh** [comment]
Yes support for Node.js is very limited or maybe non-existent, it's more for distribution purpose I guess. The reason is fundamentally PhantomJS (which CasperJS is based on) is not a Node.js module and not designed for execution as part of that environment. Below more info from the PhantomJS FAQ - http://phantomjs.org/faq.html

Also tagging @jefleponot who's maintaining CasperJS now for info on whether the [quick start documentation](https://github.com/casperjs/casperjs/blob/c0c3fc0ab5111cf62148cb29d53ba097875ef660/docs/quickstart.rst) needs to be updated. 

---

**Q: Why is PhantomJS not written as Node.js module?**

**A: The short answer: “No one can serve two masters.”**

A longer explanation is as follows.

As of now, it is technically very challenging to do so.

Every Node.js module is essentially “a slave” to the core of Node.js, i.e. “the master”. In its current state, PhantomJS (and its included WebKit) needs to have the full control (in a synchronous matter) over everything: event loop, network stack, and JavaScript execution.

If the intention is just about using PhantomJS right from a script running within Node.js, such a “loose binding” can be achieved by launching a PhantomJS process and interact with it.

**Comment by kensoh** [comment]
Hmmm running `node casperjs.js sample.js` actually works for me. First I install PhantomJS according to the setup guide on home page (http://casperjs.org). Then I run npm install casperjs. After that I go to node_modules/casperjs/bin directory. Create a sample.js like below - 

```js
var casper = require('casper').create();

casper.start('http://casperjs.org/', function() {
    this.echo(this.getTitle());
});

casper.thenOpen('http://phantomjs.org', function() {
    this.echo(this.getTitle());
});

casper.run();
```

Then `node casperjs.js sample.js` will give below output - 

```
CasperJS, a navigation scripting and testing utility for PhantomJS and SlimerJS

PhantomJS | PhantomJS
```

As it works, closing this issue for now, but do reopen or shout out if there's issues! Hi @jef I wanted to edit [quickstart.rst](https://github.com/casperjs/casperjs/blob/master/docs/quickstart.rst) before submitting a PR but I accidentally committed directly to master, can you have a look if that's ok?

Source quickstart doc - https://github.com/casperjs/casperjs/blob/master/docs/quickstart.rst
Update now live at run with node section - http://docs.casperjs.org/en/latest/quickstart.html
