### ISSUE TITLE
Casperjs in conjunction with events not working

### ISSUE THREAD

**Issue by klausbayrhammer** [casperjs/casperjs#1867]
Given a project with casperjs and an [events](https://www.npmjs.com/package/events) as a dependency the [patchRequire(require)('events')](https://github.com/casperjs/casperjs/blob/master/modules/casper.js#L34) will pick up the events library instead of the local [events implementation](https://github.com/casperjs/casperjs/blob/master/modules/events.js). Is that intentional or would it be possible to just use a relative require for overwriting the standard libraries [events, fs, http](https://github.com/casperjs/casperjs/blob/master/modules/casper.js#L34-36).

This issue is quite tricky because especially if you have events as a transitive dependency there is very little you can do about it (if you want to use yarn's flat dependency structure). We have this issue with [backstopjs](https://github.com/garris/BackstopJS) (which has a casperjs dependency) and the [aws-sdk](https://github.com/aws/aws-sdk-js) (which has an events dependency). The workaround we are currently using is a postInstall script which moves the events dependency into aws-sdk's node_modules, but obviously this is not a long-term solution.

**Comment by kensoh** [comment]
Hi @klausbayrhammer I think I get the issue that you are saying (have encountered some other issues with conflicts with the default PhantomJS fs module versus the Node.js module) but I'm not advanced enough to comment.

CasperJS main maintainer is on holiday until 20th Aug but I'll just tag him @jefleponot, and see if other maintainers / users can respond in the meantime. I'm a CasperJS user for couple of years, browsing through open issues to see if anything I can help with.

**Comment by jefleponot** [comment]
@klausbayrhammer 

try to put your library into the "node_modules" directory.
and run "require('events.js')"
