### ISSUE TITLE
Failure of the client side utilities TypeError: undefined is not a constructor (evaluating 'new window.ClientUtils')

### ISSUE THREAD

**Issue by kumardevendra26** [casperjs/casperjs#1868]
I am using phantom js version 2.1.1 and casper js version 1.1.4.
**Code sample:-**
```
casper.test.begin('Test Scenario from login to device registration', function(test) {
    casper.on("remote.message", function(msg) {
        this.echo("Console: " + msg);
    });

    casper.on("page.error", function(msg, trace) {
        this.echo("page.error: " + msg);
    });
    casper.on("resource.error", function(resourceError) {
        this.echo("resource.error: " + JSON.stringify(resourceError, undefined, 4));
    });
    casper.options.verbose = true;
    casper.options.logLevel = "debug";
    casper.start(config.URL, function() {
        this.echo('Web page is loaded');
        this.echo('First Page: ' + this.getTitle());
    });
    casper.waitForSelector('[ng-model="loginDetails.username"]',
       function success() {
           test.assertExists('[ng-model="loginDetails.username"]');
           this.click('[ng-model="loginDetails.username"]');
       },
       function fail() {
           test.assertExists('[ng-model="loginDetails.username"]');
    });
    casper.waitForSelector('[ng-model="loginDetails.password"]',
       function success() {
           test.assertExists('[ng-model="loginDetails.password"]');
           this.click('[ng-model="loginDetails.password"]');
       },
       function fail() {
           test.assertExists('[ng-model="loginDetails.password"]');
    });
    casper.run(function() {
        test.done();
    });
});
```

**Error :-**
[debug] [phantom] Successfully injected Casper client-side utilities
page.error: TypeError: undefined is not a constructor (evaluating 'new window.ClientUtils')

Please help me out from this issue.

When I am trying with different angular website, it works. 
I am not able to find the issue related with this webpage (https://ec2-52-77-129-106.ap-southeast-1.compute.amazonaws.com)

**Comment by kensoh** [comment]
Hi @kumardevendra26 when I try to run your script above with config.URL as https://ec2-52-77-129-106.ap-southeast-1.compute.amazonaws.com I get below output. But I do not have the page.error: TypeError. I run by casperjs test a.js, is that the URL to test on that has the issue?

```
Test file: a.js                                                                 
# Test Scenario from login to device registration
[info] [phantom] Starting...
[info] [phantom] Running suite: 4 steps
[debug] [phantom] opening url: https://ec2-52-77-129-106.ap-southeast-1.compute.amazonaws.com/, HTTP GET
[debug] [phantom] Navigation requested: url=https://ec2-52-77-129-106.ap-southeast-1.compute.amazonaws.com/, type=Other, willNavigate=true, isMainFrame=true
resource.error: {
    "errorCode": 6,
    "errorString": "SSL handshake failed",
    "id": 1,
    "status": null,
    "statusText": null,
    "url": "https://ec2-52-77-129-106.ap-southeast-1.compute.amazonaws.com/"
}
[warning] [phantom] Loading resource failed with status=fail: https://ec2-52-77-129-106.ap-southeast-1.compute.amazonaws.com/
[debug] [phantom] Successfully injected Casper client-side utilities
Web page is loaded
First Page: 
[info] [phantom] Step anonymous 2/4: done in 181ms.
[info] [phantom] Step _step 3/4: done in 201ms.
[warning] [phantom] Casper.waitFor() timeout
FAIL Find an element matching: [ng-model="loginDetails.username"]
#    type: assertExists
#    file: a.js
#    subject: false
#    selector: "[ng-model=\"loginDetails.username\"]"
PASS Test Scenario from login to device registration (NaN test)
[info] [phantom] Step _step 4/4: done in 5226ms.
FAIL 1 test executed in 5.234s, 0 passed, 1 failed, 0 dubious, 0 skipped.       

Details for the 1 failed test:

In a.js
  Test Scenario from login to device registration
    assertExists: Find an element matching: [ng-model="loginDetails.username"]
[debug] [phantom] Navigation requested: url=about:blank, type=Other, willNavigate=true, isMainFrame=true
[debug] [phantom] url changed to "about:blank"
```

**Comment by kumardevendra26** [comment]
Please try to run with this `casperjs test a.js --ignore-ssl-errors=true`.
You will get this issue... 
_Error: TypeError: undefined is not a constructor (evaluating 'new window.ClientUtils')_

**Comment by badrinathpathak** [comment]
I am getting the same issue with angular website when web page is loading slow. I had tried with this.wait('5000') also, But no luck.

**Comment by kensoh** [comment]
I tried with the ignore-ssl switch and can replicate the issue. Yes I notice the website loads very slowly. There is another issue with this error, but it is related to popup window and appears to be fixed now.

https://github.com/casperjs/casperjs/issues/1091

I'm now trying to set timeout options to 2 minutes to see if it works.

**Comment by uguessmyid** [comment]
@kensoh I am getting the same issue when I am using higher version of casperjs and phantomjs.

**Comment by kensoh** [comment]
Still cannot even with 5 minutes timeout (casper.options.waitTimeout = 300000;).. Strange... no idea why. I'm a CasperJS user for couple of years.. Looks like some compatibility issues somewhere broken between CasperJS + PhantomJS + the website.

Copying @jefleponot main maintainer for CasperJS to see if he got other ideas to check. And He's on holiday until 20th Aug, see other maintainers / users if have found a solution for this.

**Comment by kumardevendra26** [comment]
@kensoh If you have any clues I can work on it for temporary fix.
Waiting for your response...

**Comment by kensoh** [comment]
@kumardevendra26 I'm afraid no other clues I can think of.. If the problems happens on this website but not other websites then it should be some compatibility issue with existing CasperJS + PhantomJS with that website, and unlikely something that can be changed in script for it to work.

I also can't find this error message reported in PhantomJS repo.

**Comment by kensoh** [comment]
Adding on, I tried explicitly waiting for 2 minutes but this is still not helping. The error message looks like for some reason the webpage is not loaded properly by CasperJS/PhantomJS. And it keeps trying to reload and throwing the error even though it says the CasperJS injection is successful. It's as if the injection cannot achieve persistence on the webpage...

**Comment by jefleponot** [comment]
Hi @kumardevendra26 

I try also you script with PhantomJS and SlimeJS : errors occurs on ignore-ssl-erros
@kensoh have done a good expertise. There are too many javascript errors on download pages

Same with Firefox : 
``` firefox
stylesheet couldn't be loaded 
step1  ec2-52-77-129-106.ap-southeast-1.compute.amazonaws.com:170:4
step2 1503317540660  ec2-52-77-129-106.ap-southeast-1.compute.amazonaws.com:171:4
undefined ec2-52-77-129-106.ap-southeast-1.compute.amazonaws.com:144:5
enterederror  ec2-52-77-129-106.ap-southeast-1.compute.amazonaws.com:219:12
"Google Maps API warning: SensorNotRequired https://developers.google.com/maps/documentation/javascript/error-messages#sensor-not-required"  util.js:222:12

```

**Comment by kumardevendra26** [comment]
Adding on, I am able to fix it by adding below script before page initialization:-

`casper.on( 'page.initialized', function(){
        this.evaluate(function(){
            var isFunction = function(o) {
              return typeof o == 'function';
            };

            var bind,
              slice = [].slice,
              proto = Function.prototype,
              featureMap;

            featureMap = {
              'function-bind': 'bind'
            };

            function has(feature) {
              var prop = featureMap[feature];
              return isFunction(proto[prop]);
            }

            // check for missing features
            if (!has('function-bind')) {
              // adapted from Mozilla Developer Network example at
              // https://developer.mozilla.org/en/JavaScript/Reference/Global_Objects/Function/bind
              bind = function bind(obj) {
                var args = slice.call(arguments, 1),
                  self = this,
                  nop = function() {
                  },
                  bound = function() {
                    return self.apply(this instanceof nop ? this : (obj || {}), args.concat(slice.call(arguments)));
                  };
                nop.prototype = this.prototype || {}; // Firefox cries sometimes if prototype is undefined
                bound.prototype = new nop();
                return bound;
              };
              proto.bind = bind;
            }
        });
    });`

**Comment by jefleponot** [comment]
Hi @kumardevendra26 

Could you please propose a PR ? and a test ?

**Comment by kumardevendra26** [comment]
Using updated version of phantom 2.1.7

Error response was : 
>  undefined is not a constructor (evaluating 'new window.ClientUtils')

The original issue is Function.prototype.bind is not supported in phantom. Error message is not properly given by phantom. so we diverted from the actual issue.
We need to add a shim for that. In CasperJS it goes into the page.initialized event handler.

`casper.test.begin('Test Scenario from login to device registration', function(test) {
    casper.on("remote.message", function(msg) {
        this.echo("Console: " + msg);
    });

    casper.on("page.error", function(msg, trace) {
        this.echo("Error: " + msg);
    });

    casper.on("resource.error", function(resourceError) {
        this.echo("ResourceError: " + JSON.stringify(resourceError, undefined, 4));
    });

    casper.on('page.resource.received', function(responseData) {
       this.echo(responseData.url);
    });

    casper.on( 'page.initialized', function(){
        this.evaluate(function(){
            var isFunction = function(o) {
              return typeof o == 'function';
            };

            var bind,
              slice = [].slice,
              proto = Function.prototype,
              featureMap;

            featureMap = {
              'function-bind': 'bind'
            };
            function has(feature) {
              var prop = featureMap[feature];
              return isFunction(proto[prop]);
            }
            if (!has('function-bind')) {
              bind = function bind(obj) {
                var args = slice.call(arguments, 1),
                  self = this,
                  nop = function() {
                  },
                  bound = function() {
                    return self.apply(this instanceof nop ? this : (obj || {}), args.concat(slice.call(arguments)));
                  };
                nop.prototype = this.prototype || {}; // Firefox cries sometimes if prototype is undefined
                bound.prototype = new nop();
                return bound;
              };
              proto.bind = bind;
            }
        });
    });

    casper.options.verbose = true;
    casper.options.logLevel = "debug";

    casper.start('https://ec2-52-77-129-106.ap-southeast-1.compute.amazonaws.com', function() {
        this.echo('Web page is loaded');
        this.echo('First Page: ' + this.getTitle());
        this.wait(5000);
    });

    casper.then(function() {
        this.capture('1.login-page.png');
    });

    casper.then(function() {      
        casper.waitForSelector('[ng-model="loginDetails.username"]',
            function success() {
                this.capture('1.name-page.png');
                test.assertExists('[ng-model="loginDetails.username"]');
                this.click('[ng-model="loginDetails.username"]');
            },
            function fail() {
                this.capture('1.name-page.png');
                test.assertExists('[ng-model="loginDetails.username"]');
        });
        casper.waitForSelector('[ng-model="loginDetails.password"]',
            function success() {
                this.capture('1.password-page.png');
                test.assertExists('[ng-model="loginDetails.password"]');
                this.click('[ng-model="loginDetails.password"]');
                this.wait(1000);
            },
            function fail() {
                this.capture('1.password-page.png');
                test.assertExists('[ng-model="loginDetails.password"]');
        });
    })
})`
