### ISSUE TITLE
casper.done is undefined , copy paste example from quick start. ?

### ISSUE THREAD

**Issue by a-eid** [casperjs/casperjs#1869]
![](https://i.imgur.com/ATcCniB.png)

**Comment by kensoh** [comment]
Hi @a-eid try this script format https://github.com/casperjs/casperjs/issues/1866#issuecomment-320508745 shown in another issue to see if that works? I think the docu is outdated, casper.done() is used when running in test mode. Tagging documentation label and copying Jef @jefleponot who's maintaining CasperJS.

Also, don't think CasperJS works well with Node.js (technical design and requirements of PhantomJS to be a separate process). In any case, some more info here - https://github.com/casperjs/casperjs/issues/1864

**Comment by kensoh** [comment]
Jef's back, let me see if I can put in a PR to update this in docs.

**Comment by kensoh** [comment]
Hi @jefleponot I looked at the documentation and the [quickstart.rst](http://docs.casperjs.org/en/latest/quickstart.html) looks ok and not using casper.done() inside casper.run(). But the CasperJS homepage http://casperjs.org is outdated. Do you know who has access to casperjs.org to update the example?

The homepage doesn't look like part of CasperJS repo, can't find anything when searched for '// Opens casperjs homepage'. For the scraping example to work, it can be modified to the following - 

```js
var casper = require('casper').create();
var links;

function getLinks() {
// Scrape the links from top-right nav of the website
    var links = document.querySelectorAll('ul.navigation li a');
    return Array.prototype.map.call(links, function (e) {
        return e.getAttribute('href')
    });
}

// Opens casperjs homepage
casper.start('http://casperjs.org/');

casper.then(function () {
    links = this.evaluate(getLinks);
    for(var i in links) {
        console.log(links[i]);
    }
});

casper.run();
```

**Comment by kensoh** [comment]
(also cc Ryan @BIGjuevos who created the new casperjs.org site as he may have access to update)

**Comment by kensoh** [comment]
Copying @jefleponot and @BIGjuevos again on documentation update for casperjs.org website.

**Comment by kensoh** [comment]
Bumping -

**Comment by mcskinner** [comment]
bumping again.

**Comment by kensoh** [comment]
Closing the issue as CasperJS, like PhantomJS, is not being actively maintained. But do continue discussion (and bumping) if any!
