### ISSUE TITLE
Need help to use Istanbul for casperJS

### ISSUE THREAD

**Issue by wushuangdaidai** [casperjs/casperjs#1872]
casper testcase   can't get branch and function

=============================== Coverage summary ===============================
Statements : 8.82% ( 3/34 )
Branches : 0% ( 0/2 )
Functions : 0% ( 0/18 )
Lines : 8.82% ( 3/34 )

/***/step-1.js:9
__cov_X54oLzWEyc5EZtW05xGjqg.s['1']++;var config=require('../config');__cov_X54oLzWEyc5EZtW05xGjqg.s['2']++;var url=config.origin+'/pages/v2/account/step1';__cov_X54oLzWEyc5EZtW05xGjqg.s['3']++;casper.userAgent(config.useragent);__cov_X54oLzWEyc5EZtW05xGjqg.s['4']++;casper.test.begin('********',function(test){__cov_X54oLzWEyc5EZtW05xGjqg.f['1']++;__cov_X54oLzWEyc5EZtW05xGjqg.s['5']++;phantom.clearCookies();__cov_X54oLzWEyc5EZtW05xGjqg.s['6']++;config.userCookie.forEach(function(val){__cov_X54oLzWEyc5EZtW05xGjqg.f['2']++;__cov_X54oLzWEyc5EZtW05xGjqg.s['7']++;phantom.addCookie(val);});__cov_X54oLzWEyc5EZtW05xGjqg.s['8']++;casper.start(url,function(){__cov_X54oLzWEyc5EZtW05xGjqg.f['3']++;__cov_X54oLzWEyc5EZtW05xGjqg.s['9']++;switch(config.userType){case 0:__cov_X54oLzWEyc5EZtW05xGjqg.b['1'][0]++;__cov_X54oLzWEyc5EZtW05xGjqg.s['10']++;casper.waitForResource('/mobile/common/getUserLogin',function(){__cov_X54o

ReferenceError: casper is not defined
at Object. (/***/step-1.js:9:195)
at Module._compile (module.js:570:32)
at Object.Module._extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/istanbul/lib/hook.js:107:24)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Function.Module.runMain (module.js:604:10)
at runFn (/usr/local/lib/node_modules/istanbul/lib/command/common/run-with-cover.js:122:16)
at /usr/local/lib/node_modules/istanbul/lib/command/common/run-with-cover.js:251:17
at /usr/local/lib/node_modules/istanbul/lib/util/file-matcher.js:68:16

**Comment by kensoh** [comment]
Don't think CasperJS works with Istanbul test coverage tool, at least haven't seen somebody successfully implementing it. Below is a thread with discussion on Istanbul integration with CasperJS. Doesn't look like there's any resolution after a year - https://github.com/casperjs/casperjs/issues/1502

**Comment by kensoh** [comment]
Closed the older ticket (https://github.com/casperjs/casperjs/issues/1502) in favor of this newer ticket, as that issue hasn't moved for over a year.

**Comment by kensoh** [comment]
Also inheriting the 'Enhancement' + 'Help Request' labels from that older issue

**Comment by kensoh** [comment]
Closing the issue as CasperJS, like PhantomJS, is not being actively maintained. But do continue discussion if any!
