### ISSUE TITLE
Notice - moving on to full-time job

### ISSUE THREAD

**Issue by kensoh** [casperjs/casperjs#1875]
I've been working full-time on open-source related stuffs past 1 year, and since May been actively helping out on CasperJS GitHub issues and [mailing list questions](https://groups.google.com/forum/#!forum/casperjs). After having no income for a year, gotta move on to full-time work with income. After all, the world runs on money and passion can't pay for rent. Won't be able to help out as fast or as much like before, but will contribute whenever I can!

**Comment by jefleponot** [comment]
Thank you a lot Ken :+1:

**Comment by kensoh** [comment]
Thanks @jefleponot 👍 I've just started my first week at new full-time job. It is working for Singapore government on an AI initiative to build up local AI capabilities - https://www.aisingapore.org
