### ISSUE TITLE
Casperjs not load all content of page !

### ISSUE THREAD

**Issue by mrcoderhazem** [casperjs/casperjs#1878]
i try to create app that download twitter status link to .html file but when status have voting -- the voting not downloaded and not appear all page content appear except voting area

` casper.start(url, function() {
//this.clearCache();//Clear Cache So I Will Be Safe From Twitter Suspended Accounts
//this.clearMemoryCache();//cleared the memory cache.
this.echo(this.getTitle());
console.log('Starting location is ' + this.getCurrentUrl());

 casper.then(function(){
     fs.write('status.html',this.getHTML(),'w');

**Comment by jefleponot** [comment]
plesae precise PhantomJS SlimerJS and CasperJS 's version
