### ISSUE TITLE
Get Headers after login western-union with casperjs

### ISSUE THREAD

**Issue by ziflar** [casperjs/casperjs#1879]
heloo all freind 
i need to login western-union with casperjs and get all headers after login .
Trying to run my script i got on debug consol this error:

> [warning] [remote] unable to submit form

here my code:

```
var casper = require('casper').create({
    verbose: true,
    logLevel: 'debug',
    waitTimeout: 5000,
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5) AppleWebKit/537.4 (KHTML, like Gecko) Chrome/22.0.1229.94 Safari/537.4',
    viewportSize:{width: 1600, height: 900}
})
.on('error', function(msg) {
    this.echo('Error: ' + msg, "ERROR");
})
.on('remote.message', function(msg) {this.echo('The error from evaluate: ' + msg, "ERROR");})
.start('https://www2.westernunion.com/fr/fr/send-money/app/login/', function() {
    //this
    //.click('#signin_link');
    this.wait(0,function(){var i=0;
    function snap(){i++;casper.capture('foo_'+i+'.jpg', undefined,{format: 'jpg',quality: 75});if(i<4){setTimeout(snap,1000)}}snap();
    })
    .fillSelectors('form', {
        '#txtEmailAddr' : 'tatatmarta@gmail.com',
        '#txtKey':  'tictac@2009'
    }, true)
    .waitForSelector("#btn-do-login",
    function success() {
        this
            
	    .echo('logged in!', 'INFO')
            .capture('in.png')
    },
    function fail(){
        this
            .capture('failed.png')
            .echo('failed to login', 'ERROR');
    })
})
//Header
.then(function dumpHeaders(){
  console.log("getting headers");
	this.currentResponse.headers.forEach(function(header){
    console.log(header.name +': '+ header.value);
  })
})
.run()
```
any help

**Comment by kensoh** [comment]
Hi @ziflar I am able to run your code and the headers get returned correctly. I'm using CasperJS v1.1.4 and PhantomJS v2.1.1. However, notice the error below on fingerprinting? This is likely because PhantomJS does not support fingerprinting like a real browser.

So this likely means that you cannot use CasperJS (which uses PhantomJS underneath) to automation on Western Union website. Fingerprinting is done by some websites to track users and for security reasons, and also to prevent automated users from access. Another issue with fingerprinting - https://github.com/casperjs/casperjs/issues/1861

```
The error from evaluate: Getting region code from global countryConfig object...
The error from evaluate: Region code found to be: emea
The error from evaluate: 
***************************
WUAnalyticEventCapture	Sun Sep 17 2017 04:37:12 GMT+0800 (+08)
The error from evaluate: country : FR
The error from evaluate: language : fr
The error from evaluate: IF 1.1
The error from evaluate: ***************************
The error from evaluate: whats next service is loaded..
The error from evaluate: Skipping WebGL fingerprinting because it is not supported in this browser
```

**Comment by ziflar** [comment]
@kensoh thank for your replay.
i folow the way of casperjs to generate 2 headers value : 
X-Nyupe9cs-b
X-Nyupe9cs-a

these values are generated after login or singup western-union by this js file : (see the end of the js )

[https://www2.westernunion.com/etc/clientlibs/westernunion/wu_common.js](url)

I need these two values to put as hederas  on a post curl-php function
i can't found the algorithm to decrypt the js founction

**Comment by kensoh** [comment]
Not sure if that will work, from above it looks like western union website doesn't want to work with PhantomJS. Otherwise for normal situations you can use casper.download to download a file if you know the URL. Also copying maintainer Jef @jefleponot to see if he has other inputs to add.

**Comment by ziflar** [comment]
@kensoh 
hello freind 
thanks and big thanks for your replay .
i think there is a way to baypass the fingreprinting.
[here](https://github.com/Valve/fingerprintjs) a best code to add as require('fingerprint')
see the code

**Comment by kensoh** [comment]
Thanks @ziflar for sharing! Closing the issue for now.

Yes probably as they are all part of javascript ecosystem and coding environment :)
