### ISSUE TITLE
WaitForSelector is normal on windows10, but it is timeout on Linux

### ISSUE THREAD

**Issue by wangdesheng** [casperjs/casperjs#1880]
WaitForSelector is normal on windows10, but it is timeout on Linux.

[warning] [phantom] Casper.waitFor() timeout

At first, I thought it was a different version of phantomjs or casperjs on Linux and windows, but I still have this problem when I installed the same version on Linux.
phantomjs version: 1.9.8 , casperjs version: 1.1.1

here my code:

`
casper.start('http://www.somesite.com/login.php');
casper.then(function(){
	this.waitForSelector(".W_login_form",function(){
		this.click('.login_innerwrap a[action-data="type=normal"]');
		this.fill(
			'.W_login_form',
			{ "username": "myname", "password": "*******" },
			false
		);
		this.click('.login_btn a');
	});	
}); `

**Comment by jefleponot** [comment]
Hi @wangdesheng 

Could you please try , With newest version PhantomJS 2.1.1
and CapserJS 1.1.4-1 ?
