### ISSUE TITLE
German umlauts causing incorrect output

### ISSUE THREAD

**Issue by ccman32** [casperjs/casperjs#1881]
While trying to automate the process of logging in to a website using TagUI (https://github.com/tebelorg/TagUI) which internally uses casperjs, I noticed that casperjs seems to print out invalid characters when german umlauts like ä ö or ü are used in the script (I tested this on Windows 7).
The issue can be replicated with this simple code:
```
var casper = require('casper').create();

casper.start('https://github.com');

casper.then(function() {
text = 'ä ö or ü'
this.echo('ä ö or ü');
this.echo(text);
});

casper.run();
```

When executing that script, I get the following output:
![problem](https://user-images.githubusercontent.com/17458377/30442075-a1f84a18-997b-11e7-8f67-42b990242eef.PNG)

**Comment by jefleponot** [comment]
Hi @ccman32 

Which version of CasperJS and PhantomJS do you use ?

every thing works for me

     bin/casperjs ccman32.js | tee -a "test.log" 
     ä ö or ü

**Comment by ccman32** [comment]
@jefleponot according to the package.json file in the release it is 1.1.4

**Comment by kensoh** [comment]
Hi Jef :) adding on that this minimum code works for me on macOS (10.12) and Linux (Centos 6) but somehow does not work for @ccman32 on Windows 7. Not sure if anyone else with Windows 7 or Windows 10 can test to see if it is an isolated language issue with Win 7 (or Windows in general).

**Comment by kensoh** [comment]
Adding on, I had a number of issues when trying to display foreign languages on Windows. It may require changing system locale, using chcp command, and selecting a font to display native language correctly. Check this URL for more info and it can probably fix the issue - 

http://www.walkernews.net/2013/05/19/how-to-get-windows-command-prompt-displays-chinese-characters/

It fixes for me when trying to view chinese characters on windows command prompt.
