### ISSUE TITLE
stdout issue with Casper Event to Runner File

### ISSUE THREAD

**Issue by ikeorizu** [casperjs/casperjs#1882]
I'll getting an empty array when I try to get phantomjs to read data from casperjs via a runner file. This is how I wrote it in the runner file

```
    ps.stdout.on('data', function(data) {
        console.log(data);
        outputData.push(data);
    });
```
- Casper JS file 
```
casper.on('data.received', function(data) {
    console.log(data.url);
});
```

Can you please direct me on how to do this event handling, thanks

**Comment by awilson28** [comment]
@ikeorizu to log to stdout inside of `evaluate`, use utils - `utils.dump(data);`. If you are inside of a .then, just use `console.log`. You don't need `casper.on(...)` to achieve this. Let me know if this doesn't make sense. I'm going a very similar thing.

**Comment by awilson28** [comment]
@ikeorizu to log to stdout inside of `evaluate`, use utils - `utils.dump(data);`. If you are inside of a .then, just use `console.log`. You don't need `casper.on(...)` to achieve this. Let me know if this doesn't make sense. I'm doing a very similar thing.

**Comment by ikeorizu** [comment]
Thanks, thanks

**Comment by kensoh** [comment]
Thanks @awilson28 ! =)
