### ISSUE TITLE
How to upload image from url instead of server path

### ISSUE THREAD

**Issue by SashaDesigN** [casperjs/casperjs#1883]
I'm using CasperJS to do my automation things. But for file uploading, I upload images from other website using exec() and wget to my server, then use CasperJS and casper.uploadFile() to post images on website.

Now I trying to post image using website image URL, I mean:

```
casper.then(function(){
    this.uploadFile("input[type='file']", '/var/tmp/img.jpg');
})
```
but I want to do:

```
casper.then(function(){
    this.uploadFile("input[type='file']", 'http://mywebsite.com/images/img.jpg');
})
```
and when I did that Casper just fails.

I have an access to server on which holds website on which stored image, so maybe can I do:

```
casper.then(function(){
    this.uploadFile("input[type='file']", '192.184.33.45:/images/img.jpg');
})
```

**Comment by jefleponot** [comment]
hi @SashaDesigN 

Withe the uploadFile method, you can transfert local resource to distant server.
If you want to transfert a web resource, you must download it before on your hard disk and you uploadFile with local path.

**Comment by SashaDesigN** [comment]
Thanks a lot)
