### ISSUE TITLE
CasperJS doesn't render whole page 

### ISSUE THREAD

**Issue by akaroot** [casperjs/casperjs#1885]
Hi, 

hi
CasperJS doesn't render page correctly, it miss content that i suppose is generated by javascript.
[Screenshot](https://imagebin.ca/v/3dPsLENW71sL)

My script
```
var casper = require('casper').create({
    verbose: true,
    logLevel: 'debug',
    exitOnError: false,
    ignoreSslErrors: true,
    pageSettings: {
        javascriptEnabled: true,
        loadImages: true,
        loadPlugins: true,
        localToRemoteUrlAccessEnabled: true,
        userAgent: 'Mozilla/5.0 (X11; CrOS x86_64 8172.45.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.64 Safari/537.36',
        XSSAuditingEnabled: false,
        logLevel: 'debug'
    }
});

casper.start("https://iforgot.apple.com/password/verify/appleid");

casper.then(function(){
    casper.wait(5000, function(){
        this.capture('screenshot.png');
    });
});

casper.run();
```

Console output:
```
[info] [phantom] Starting...
[info] [phantom] Running suite: 3 steps
[debug] [phantom] opening url: https://iforgot.apple.com/password/verify/appleid, HTTP GET
[debug] [phantom] Navigation requested: url=https://iforgot.apple.com/password/verify/appleid, type=Other, willNavigate=true, isMainFrame=true
[debug] [phantom] url changed to "https://iforgot.apple.com/password/verify/appleid"
[debug] [phantom] Successfully injected Casper client-side utilities
[debug] [phantom] start page is loaded
[info] [phantom] Step anonymous 3/3 https://iforgot.apple.com/password/verify/appleid (HTTP 200)
[info] [phantom] Step anonymous 3/3: done in 1890ms.
[info] [phantom] Step _step 4/4 https://iforgot.apple.com/password/verify/appleid (HTTP 200)
[info] [phantom] Step _step 4/4: done in 1906ms.
[info] [phantom] wait() finished waiting for 5000ms.
[debug] [phantom] Capturing page to screenshot.png
[info] [phantom] Capture saved to screenshot.png
[info] [phantom] Done 4 steps in 7037ms
[debug] [phantom] Navigation requested: url=about:blank, type=Other, willNavigate=true, isMainFrame=true
[debug] [phantom] url changed to "about:blank"
```
Casprer version: 1.1.4
Phantom version: 2.1.1

**Comment by jefleponot** [comment]
Hi @akaroot 

Your code works perfectly with SlimerJS. But it can't run on PhantomJS because PhantomJS can't render SVG resources.

SlimerJS screenshot : 

![screenshot](https://user-images.githubusercontent.com/5547697/31460360-7230b9cc-aec6-11e7-85f4-acb8e1f6bb11.png)

**Comment by akaroot** [comment]
Thanks @jefleponot, but I need headless framework to run on server without GUI, that's why I used phantomJS. In my case casper doesn't render not only svg but the whole form

**Comment by jefleponot** [comment]
hi @akaroot,

Why can't you use SlimerJS ? it is headless too ...

Just read slimerJS documentation.

    casperjs --engine=slimerjs yourscript.js

**Comment by akaroot** [comment]
it doesn't work for me on ubuntu 16.04 server (without GUI)

**Comment by jefleponot** [comment]
@akaroot 

I works on Ubuntu Server with headless SlimerJS module


    Having a headless SlimerJS

    There is a tool called xvfb, available on Linux. It allows to launch any “graphical” programs without 
    the need of an X-Windows environment. Windows of the application won’t be shown and will be
     drawn only in memory.
    Install it from your prefered repository (sudo apt-get install xvfb with debian/ubuntu).
    Then launch SlimerJS like this:

    xvfb-run ./slimerjs myscript.js

To use it with casperJS , you have to create an executable script that runs xvfb
You could also use the firefox parameter --headless

**Comment by akaroot** [comment]
Thanks again @jefleponot. I'll give it a try, but it requires older version of firefox that is not very convinient. 
For now I experimented with [chromedp](https://github.com/knq/chromedp), it use chrome headless and does not require xvfb

**Comment by kensoh** [comment]
Adding on, in future CasperJS probably can work with Firefox headless.

Not sure if Firefox headless is now working in stable with SlimerJS / CasperJS - https://github.com/laurentj/slimerjs/issues/659

**Comment by kokno** [comment]
@akaroot did you find a solution ? I have the same problem, I only get some html elements that are not Javascript.

**Comment by kensoh** [comment]
Hi @akaroot can you paste your minimum script that can reproduce the issue?

**Comment by kensoh** [comment]
EDIT - sorry I mean @kokno

**Comment by akaroot** [comment]
@kokno I didn't find any solution so I switch to golang github.com/knq/chromedp

**Comment by kensoh** [comment]
Ok got it... Chrome-based web automation tools are getting better. Nevertheless PhantomJS is also actively maintained now. So that's good for CasperJS which is based on PhantomJS.

For myself, I made a tool called TagUI that is based on CasperJS but also integrates natively with Chrome visible / Chrome headless - https://github.com/tebelorg/TagUI
