### ISSUE TITLE
Casperjs can not upload photo to Facebook

### ISSUE THREAD

**Issue by baobaosan** [casperjs/casperjs#1886]
Hi
I want to upload photo file to facebook to test Ad photo. I use casperjs+phamtomjs2.1, the code as below:
`var fs = require('fs');
var casper = require('casper').create({
    clientScripts:  [
        'includes/jquery.js',      // These two scripts will be injected in remote
    ],
    pageSettings: {
        loadImages:  true,        // The WebPage instance used by Casper will
        loadPlugins: true,       // use these settings
		userAgent: 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:46.0) Gecko/20100101 Firefox/46.0'
    },
    logLevel: "debug",              // Only "info" level messages will be logged
    verbose: true                  // log messages will be printed out to the console
});
casper.options.waitTimeout = 30000;
var PhotoPath = 'D:/photo/product001.jpg';

casper.start('https://www.facebook.com/ads/tools/text_overlay',function(){
	this.then(function() {
		this.wait(10000);

	});
	this.waitForSelector('div._3jk', function then() {

		this.click("div._3jk");

	});

   //this.page.uploadFile("._3jk input[type='file']", "F:/pic/NFL_L_4.jpg");
});

casper.then(function() {
    this.fill('._3jk', {
        'image': PhotoPath
    }, true);
});

The code work fine before. But can not work now. I really appreciate if someone can help.

**Comment by jefleponot** [comment]
Hi @baobaosan 

just use : 

```js
casper.page.uploadFile("._3jk input[type='file']", PhotoPath);
```

**Comment by baobaosan** [comment]
@jefleponot 
I use: casper.page.uploadFile("div._3jk input[type='file']", PhotoPath); 
But it still can not work.

**Comment by baobaosan** [comment]
I don't known where is problem.
I try both method.
1, 
casper.then(function() {
    casper.page.uploadFile("._3jk input[type='file']", PhotoPath);
	
});
this method is failed and no error message be given.
 2, 
casper.then(function() {
    this.fill('._3jk', {
        'image': PhotoPath
    }, true);
});
this method is failed as well, and given the error message like this:
submitting form to unknown, HTTP GET[warning] [remote] unable to submit form[info]

**Comment by kensoh** [comment]
I believe the issue is because of facebook blocking automated actions. You may want to try automation solutions based on other browsers - for eg headless Firefox or Chrome. Not sure if Firefox headless is now working in stable with SlimerJS / CasperJS - https://github.com/laurentj/slimerjs/issues/659
