### ISSUE TITLE
CasperError scrolling webpage 

### ISSUE THREAD

**Issue by robertlogos** [casperjs/casperjs#1888]
Hi all,
I get an error for any scroll operation (scrollTo(), scrollToBottom()) on http://www.lavozdegalicia.es

`CasperError: callUtils(scrollToBottom) with args  thrown an error: undefined`

Sample code (works fine for any URL except this):
```
var casper = require("casper").create();
casper.start('http://www.lavozdegalicia.es', function() {});
casper.then(function(){
    this.scrollToBottom();
});
casper.run();
```
I have tried without success different workarounds like using the page object, evaluating the window etc. but the error still persists.

Thanks in advance for your help

**Comment by jefleponot** [comment]
Hi @robertlogos ,

ScrollToBottom doesn't work for me too 
I will have a look to fix it
Regards

jef

**Comment by StephenYang1989** [comment]
ScrollToBottom and ScrollTo doesn't work for me too.
have your problem solved? @jefleponot @robertlogos

**Comment by robertlogos** [comment]
No solution yet .. but sincerely I didn't spent much time on it.

**Comment by robertlogos** [comment]
After messing around with the URL using directly the PhantomJS engine to isolate the problem, I found the cause of the error: the JavaScript on the page overloads the scrollTo() function which is called by PhantomJS to do the scroll:
```
function scrollTo(dest){
    var target=$(dest);
    if(target.length){
        $('html, body').animate({scrollTop:target.offset().top-100},1000)
    }
}
```
For any reason, the JQuery $ is not loaded at that moment causing the 'undefined' error.

This workaround did the job:
```
function myScrollTo(top){
    this.evaluate(function(t){
        window.document.body.scrollTop = t;
    }, top);
}
```
