### ISSUE TITLE
crazy "null is not an object (evaluating 'url.toLowerCase') "

### ISSUE THREAD

**Issue by alexsonnay** [casperjs/casperjs#1889]
Hello, I'm getting crazy here. How is it possible that this function works in my script (returning only the first link of the webpage) : 

```
function getLinks() {
    return document.querySelector('.title > a').getAttribute('href');
    });
}
```

BUT NOT THIS ONE ⬇️

```
function getLinks() {
    var links = document.querySelectorAll('.title > a');
    return Array.prototype.map.call(links, function (e) {
        return e.getAttribute('href');
    });
}
```

This one returns one empty url, and therefore the `null is not an object (evaluating 'url.toLowerCase') `

There are 20 links to get on the webpage I'm scraping. It's the first time this happens to me. It always works usually.

Any idea ?

**Comment by jefleponot** [comment]
HI @alexgibson 

What happens when an anchor hasn't any href attribute ? => it crashs.

Just adds a test into your callback.
Regards,

jef

**Comment by alexsonnay** [comment]
I managed to find a solution with XPath.
