### ISSUE TITLE
tester.assertSelector only checks first found element

### ISSUE THREAD

**Issue by Hipska** [casperjs/casperjs#1890]
Consider following code:
```html
<div id=container>
    <p></p>
    <p>teststring</p>
</div>
```
and this test:
```js
// shows both elements
require('utils').dump(this.getElementsInfo('#container p'));
// fails
test.assertSelectorHasText('#container p', 'teststring');
```
Should the tester not do its test for all the found elements based on the selector?
Or is there a better way to achieve this?

**Comment by kensoh** [comment]
Not sure why, it works for my website with below html. It is also consistent with [documentation](http://docs.casperjs.org/en/latest/modules/tester.html#assertselectorhastext).

```js
test.assertSelectorHasText('#header p', 'software');
```

```html
<header id="header">
<p>
<a href="gist/interface_automation" target="_blank">?~@?&nbsp; Interface automation</a></p>
<p>
<a href="gist/open-source_software" target="_blank">?~@?&nbsp; Open-source software</a></p>
<p>
<a href="gist/automation_projects" target="_blank">?~@?&nbsp; Automation projects</a></p>
<canvas id="animation-canvas"></canvas>
</header>
```

What if you use #container ? It also works for me when I use #header as the selector without p.

**Comment by Hipska** [comment]
I don't know either why it doesn't work as expected, which is why I created this ticket.

Maybe the fact that the first `<p>` is empty?

> What if you use #container ? It also works for me when I use #header as the selector without p.

That's how I'm using it currently. But in my opinion this is only a workaround, as I want to test if a `p` under `#header` has that text.

**Comment by kensoh** [comment]
This is strange behavior.. Copying CasperJS maintainer @jefleponot . Do share here if there is a website which this can be replicated and tested on, and your CasperJS / PhantomJS version.

**Comment by Hipska** [comment]
I'll try to replicate it in a separate test file.

* CasperJS: 1.1.4
* PhanthomJS: 2.1.1

**Comment by Hipska** [comment]
Really strange, suddenly it works as expected. I guess the weekend did something good..
