### ISSUE TITLE
phantomjs not found

### ISSUE THREAD

**Issue by dipeshcct** [casperjs/casperjs#1892]
Hi,
I have installed phantomjs for window and set environmental variable. After that, when I print phantomsjs --version then it show version of phantomjs.

But when I run casperjs --version it is showing an error like "fatal: the system cannot find the file specified; did you install phantomjs?"

Can you please suggest me?

**Comment by kensoh** [comment]
This documentation section may be helpful - phantomjs installation directory needs to be included in windows path variable - http://docs.casperjs.org/en/latest/installation.html#casperjs-on-windows

The path should avoid spaces in the folder names, I think it can break the functioning of phantomjs / casperjs. Lastly, for windows, run in normal cmd command prompt, not linux shells.

**Comment by kensoh** [comment]
The above should help, but give a shout if there is still issue!
