### ISSUE TITLE
Test fails to load https page

### ISSUE THREAD

**Issue by Hipska** [casperjs/casperjs#1894]
Debugging only shows that loading has failed with "status=fail", but no more extra info:
```
[debug] [phantom] opening url: https://example.com/, HTTP GET
[debug] [phantom] Navigation requested: url=https://example.com/, type=Other, willNavigate=true, isMainFrame=true
[warning] [phantom] Loading resource failed with status=fail: https://example.com/
```
How can I debug this further? I tried already changing `webSecurityEnabled` and `ignoreSslErrors`, but that didn't have much effect.

The test works fine on my local machine, but not on the server where the test finally will need to run. On the same server accessing the page with `curl` works perfectly.

**Comment by kensoh** [comment]
@Hipska I assume you already run with `casper.options.logLevel = 'debug';`. If yes then I don't think there are other ways because debug messages come from PhantomJS, outside of CasperJS's control.

**Comment by Hipska** [comment]
So, no way to get the reason why https loading fails?

**Comment by kensoh** [comment]
I don't think possible to get more info than what PhantomJS exposes. Nevertheless copying maintainer @jefleponot who was maintaining CasperJS previously.

**Comment by jefleponot** [comment]
Hi @Hipska  and @kensoh 

Please tells us the version of PhantomJS / CasperJS and SlimerJS you use.
Could you paste the script, you used.

**Comment by Hipska** [comment]
CasperJS version 1.1.4
PhantomJS version 2.1.1
```js
casper.test.begin('Some example', function(test) {
    casper.start('http://example.com');

    casper.options.pageSettings = {
        loadImages: true,
        loadPlugins: true,
        webSecurityEnabled: true,
        ignoreSslErrors: true,
        localToRemoteUrlAccessEnabled: false
    };
    
    casper.then(function() {
        test.assertUrlMatch(/^https:\/\/example\.com/);
    }

    casper.run(function() {test.done()});
})
```

**Comment by Hipska** [comment]
With PhantomJS, I get the following:
> [DEBUG] Network - SSL Error: "The issuer certificate of a locally looked up certificate could not be found"
[DEBUG] Network - SSL Error: "The root CA certificate is not trusted for this purpose"

By adding the `--ignore-ssl-errors=true` options, the page loads fine with PhantomJS. So why doesn't this work by adding similar option to CasperJS?

**Comment by kensoh** [comment]
The script looks to be accessing the http version of the sample website. Assuming that is a typo, if PhantomJS works while CasperJS does not then it is really strange. Copying @jefleponot who is maintaining CasperJS.

```js
casper.start('http://example.com');
```

**Comment by Hipska** [comment]
The http page redirects to https, but even when starting with https it does not work. (Jef was already in the thread)

**Comment by kensoh** [comment]
Sounds like some incompatibility with PJS and this website, though I don't know what can be changed at PJS or perhaps CasperJS to make it work for such websites.

**Comment by Hipska** [comment]
Still looks like a CJS bug to me, as PJS is loading it perfectly with ignore SSL errors enabled.

**Comment by kensoh** [comment]
Oh @Hipska I'm sorry, yes you are correct

**Comment by kensoh** [comment]
Closing the issue as CasperJS, like PhantomJS, is not being actively maintained. But do continue discussion if any! I'm not sure if anyone would be able to update CasperJS code base to check and fix this issue.
