### ISSUE TITLE
Misleading error message; JSON.stringify cannot serialize cyclic structures

### ISSUE THREAD

**Issue by matthewbal** [casperjs/casperjs#1895]
In case anyone else comes up against this error, hopefully this can save you some time!
Recently spent a few hours debugging an error I was consistently getting for a casper test:

This error made me imagine something was wrong with the page itself, such as a cyclic include statement or a double up of a script somewhere in HTML/JS.

I was able to find the cause of this issue, if you pass a reference of casper "this" into a function when you are already using this at the start of the call, it will result in this error.

My poorly written code:
```
        casper.then(function(){
            this.test.assertExists(this, '#unique_selector', "foo exists");
            this.test.assertVisible(this, '#unique_selector', "foo is visible");
        });
```

The error:
```
#    type: uncaughtError
#    file: Foo.js:376
#    error: JSON.stringify cannot serialize cyclic structures.
#           stringify@[native code]
#           evaluate@phantomjs://platform/webpage.js:376:38
#           evaluate@phantomjs://platform/casper.js:782:48
#           callUtils@phantomjs://platform/casper.js:288:31
#           exists@phantomjs://platform/casper.js:814:26
#           assertExists@phantomjs://platform/tester.js:615:42
#           phantomjs://code/Foo.js:279:35
#           runStep@phantomjs://platform/casper.js:1685:31
#           checkStep@phantomjs://platform/casper.js:414:28
#    stack: not provided
```

**Comment by jefleponot** [comment]
@matthewbal 

Thanks for return.

the test module must be use like that :
```js

casper.then(function(){
            this.test.assertExists( '#unique_selector', "foo exists");
            this.test.assertVisible( '#unique_selector', "foo is visible");
        });
```

    Signature: assertExists(String selector[, String message])

    Asserts that an element matching the provided selector expression exists in remote DOM environment:

**Comment by yogeshR5** [comment]
@jefleponot  Same issue happened here while using

wheelCanvas = this.updateCanvas();

ctx.drawImage(wheelCanvas, wheelCanvas.width / 2, wheelCanvas.height / 2);

updateCanvas() {
var outsideRadius = 120;
var textRadius = 100;
var insideRadius = 30;
var canvas = this.refs.canvasRoulette;
let ctx = canvas.getContext("2d");
canvas.width = canvas.height = outsideRadius * 2 + 6;

var x = outsideRadius + 3;
var y = outsideRadius + 3;

ctx.font = "bold 18px Helvetica, Arial";

for (var i = 0; i < rouletteSize; i++) {
  var angle = i * arc;
  ctx.fillStyle = colors[i];
  ctx.beginPath();
  ctx.arc(x, y, outsideRadius, angle, angle + arc, false);
  ctx.arc(x, y, insideRadius, angle + arc, angle, true);
  ctx.strokeStyle = "#fff";
  ctx.lineWidth = 1;
  ctx.stroke();
  ctx.fill();
  ctx.save();
  ctx.shadowOffsetX = -1;
  ctx.shadowOffsetY = -1;
  ctx.shadowBlur = 0;
  ctx.shadowColor = "rgb(220,220,220)";
  ctx.fillStyle = "#fff";
  ctx.translate(
    x + Math.cos(angle + arc / 2) * textRadius,
    y + Math.sin(angle + arc / 2) * textRadius
  );

  ctx.rotate(angle + arc / 2 + Math.PI);
  var text = numbers[i];
  ctx.fillText(text, -ctx.measureText(text).width / 2, 5);
  ctx.restore();
}
return canvas;
}

**Comment by kensoh** [comment]
@yogeshR5 not sure what is this, it doesn't look like a CasperJS script. It looks like a generic JavaScript error and probably not related to the issue here. The OP issue was using CasperJS test method incorrectly.
