### ISSUE TITLE
customHeaders get removed for popups

### ISSUE THREAD

**Issue by Plinpod** [casperjs/casperjs#1896]
Hey,

I noticed if you have custom headers set only the userAgent header gets passed down to popups. 

I believe the issue is this bit of code in **modules/casper.js**

line 3223
`if (page.isPopup) {
            casper.emit('popup.created', page);
            if (casper.options.pageSettings.userAgent !== defaultUserAgent) {
                page.customHeaders = {"User-Agent": casper.options.pageSettings.userAgent};
            }`

Wondering if it could be modified to allow customeHeaders to pass through maybe if a page setting is set to true in case people don't want customeHeaders passed.

**Comment by kensoh** [comment]
Closing for time being as there is no progress -

**Comment by itamargero** [comment]
Encountered the same issue, popup doesn't get custom headers that was set on the onset, what can I do about it?

**Comment by Plinpod** [comment]
@itamargero It's been awhile but I think I fixed this issue in my fork here. https://github.com/Plinpod/casperjs take a look may work for you

**Comment by itamargero** [comment]
Thanks will check it out, in the meanwhile, I found that you can re-set the headers on popup create.
