### ISSUE TITLE
click() not working (sometimes work)

### ISSUE THREAD

**Issue by Rzeszow** [casperjs/casperjs#1897]
```javascript
casper.then(function () {
    console.log("Login using username and password");

    this.evaluate(function () {
        document.getElementById("login-user").value = "user";
        document.getElementById("login-password").value = "pass";
    });
});

(...)

casper.then(function () {
    this.waitForSelector('.footer-vote', function () {
        this.click('.footer-vote'); // HERE NOT WORKING !
    });
});
```
CasperJS: 1.1.4
PhantomJS: 2.1.1

**Comment by jefleponot** [comment]
Hi @Rzeszow 

Could you try with 

```
casper.then(function() {
    this.fill('form.login-form', {
        'username':    'user',
        'password':    'password',
    }, false);
});

```

**Comment by Rzeszow** [comment]
Thanks @jefleponot  for help, but my program login in without a problem. Only voting does not work (sometimes it will work but very rarely).

**Comment by jefleponot** [comment]
Hi @Rzeszow 

I open your website. Your vote seems inactivate when page is loaded. Activation appears after that all comments are displayed. So you could add a wait time in your script or wait for the button activation.

Regards 
jef

**Comment by Rzeszow** [comment]
Hi @jefleponot,
Thanks for everything, everything works perfectly.

Regards,
Rzeszow
