### ISSUE TITLE
how can casperjs include js code like phamtonjs

### ISSUE THREAD

**Issue by beyondbycyx** [casperjs/casperjs#1902]
I want include/insert outer js source or include/insert js code to current html (not are use evaluate method to run js code in html)  ,in phamtonjs ,there are code like this ` page.includeJs('url',function(){});`,but in casperjs ,i can not find any like 'include' method.

**Comment by kensoh** [comment]
Would something like casper.evaluate work for your use case? I use that to run JS code in DOM.

http://docs.casperjs.org/en/latest/modules/casper.html#evaluate
