### ISSUE TITLE
Why does document.hasFocus() return false?

### ISSUE THREAD

**Issue by PonderingGrower** [casperjs/casperjs#1903]
I'm testing some code which depends on `document.hasFocus()` being `true`. But it's always `false`.

I tried running `evaluate` to set `window.document.hasFocus` to my own function that always returns `true`,  but it always happens too late, so I have to `reload()` before really starting the tests.

Is there some other way to make the page be focused by default, from the beginning of page load?

**Comment by kensoh** [comment]
Hi @PonderingGrower this property is part of the DOM, didn't see any code that explicitly changes this in CasperJS codebase. It is likely a behavior of the underlying browser, in this case maybe PhantomJS for your example. You can try running in Firefox through SlimerJS or possibly some other browsers to see if that also happens.

**Comment by PonderingGrower** [comment]
Ah, I see, so it's dependant on the underlying browser. That explains a lot. Yes, I am using PhantomJS, so I guess this question would be better for their issue tracker. Thanks for explaining this, I appreciate it.

**Comment by kensoh** [comment]
No probs @PonderingGrower, CasperJS is a wrapper around the underlying browser engines, so may be not obvious what type of issues is from the underlying engine and which part is managed by CasperJS.
