### ISSUE TITLE
Issue from PJS

### ISSUE THREAD

**Issue by pixiuPL** [casperjs/casperjs#1904]
Take a look at [this](https://github.com/ariya/phantomjs/issues/15236)
Our user opened this some time back and I have a strong feeling this belongs here.

**Comment by kensoh** [comment]
Thanks @pixiuPL! Closing this as @Lucas-C confirmed it is an PJS issue here - https://github.com/ariya/phantomjs/issues/15236#issuecomment-355854535

His replication test case is purely a PhantomJS script and the issue he raised happens directly in PJS, as CasperJS is mostly a wrapper around PhantomJS functions, unless it is CasperJS specific add-ons.

(Adding some notes for internal reference -
 https://github.com/casperjs/casperjs/blob/master/modules/casper.js#L957)
