### ISSUE TITLE
[query] How strong are CasperJS's interoperability goals?

### ISSUE THREAD

**Issue by kwill** [casperjs/casperjs#1905]
My understanding is that SlimerJS support in CasperJS is currently experimental (CasperJS 1.1.0-beta1, SlimerJS 0.8). And there are differences between the SlimerJS and CasperJS APIs.

Before I found this out, I assumed that the ultimate goal of CasperJS was to be a single framework that could run the same script against either Gecko (with SlimerJS) or WebKit (with PhantomJS), and I wouldn't need to "learn" Slimer or Phantom.

It now looks like there is limited abstraction, in which case I might as well use each underlying frameworks directly. Is the point that some abstraction is better than none, and things are likely to improve?

_I am not asking "is CasperJS good enough", I want to understand the (documented, possibly aspirational) goals of CasperJS._

Also posted as https://stackoverflow.com/questions/48092831

**Comment by kensoh** [comment]
Hi @kwill, CasperJS is into its v1.14ish release, and SlimerJS is into its v1.0ish. The original goals of CasperJS is make it easier for navigation and testing. Although it is great to be able to harmonize across different browser, in practice it is really hard.

For example, PhantomJS is based on the older JS standard while control of Chrome is mostly through NodeJS libraries or having direct communications via WebSocket protocol. Also copying maintainer @jefleponot 

If something you want to be done can be done directly and easily using the browser automation engine, then that's great and it is better to do that. If there are complicated steps of code and you find that CasperJS's API simplifies some of the hard work for you, then you can consider using CasperJS.

**Comment by kwill** [comment]
I understand, thanks! I've updated the StackOverflow question with your answer.

**Comment by kensoh** [comment]
Thanks @kwill ! :smile:
