### ISSUE TITLE
Casperjs : Can anyone please let me how to check the link open in new tab?

### ISSUE THREAD

**Issue by subhaduraisamy** [casperjs/casperjs#1907]
I used below method
 casper.waitForPopup({url: 'https:www.google.com'}, function() {
    this.test.assertEquals(this.popups.length, 1);
    this.echo(this.getTitle());

      });

This is not working.Any help is appreciated.

**Comment by kensoh** [comment]
casper.withPopup() might be what u r looking for -

http://docs.casperjs.org/en/latest/modules/casper.html#withpopup

**Comment by subhaduraisamy** [comment]
Thanks ken.I just figureout, test case is not passing bacuse of this 
![image](https://user-images.githubusercontent.com/18709232/35065031-c9092d0e-fb80-11e7-9977-49c1db950ccb.png)
PASS 1 test executed in 4.709s, 1 passed, 0 failed, 0 dubious, 0 skipped.       
**[debug] [phantom] Navigation requested: url=about:blank, type=Other, willNavigate=true, isMainFrame=true
[debug] [phantom] url changed to "about:blank"** 

Anyone know why casperjs is naviagted to blank url after test case is passed?

**Comment by kensoh** [comment]
That's cool @subhaduraisamy ;)

**Comment by subhaduraisamy** [comment]
@kensoh I see the same issue for other link.I am getting timeout.
**[debug] [phantom] Successfully injected Casper client-side utilities
[warning] [phantom] Casper.waitFor() timeout**

And I am using   "casperjs": "^1.1.4",
    "phantomjs-prebuilt": "^ 2.1.1"

**Comment by kensoh** [comment]
You can paste your script here so others can try to replicate. Maybe it is popup cannot be opened by PhantomJS.
