### ISSUE TITLE
PhantomJS 1.9 or 2.1?

### ISSUE THREAD

**Issue by daniel-lucio** [casperjs/casperjs#1908]
I remember that casperjs 1.1.3 requires phantomjs 1.9 to work properly,
what phantomjs does casperjs 1.1.4 requires?

**Comment by kensoh** [comment]
I use v2.1.1 and seems to work well for me. Although you can see that the latest is v2.1.3 - http://phantomjs.org

The latest PhantomJS release was 18 days ago, that is surprise to me because the last I know, the project was no longer maintained. Great news for many!
