### ISSUE TITLE
casperjs does not load content of iframe

### ISSUE THREAD

**Issue by JohnMerlino2** [casperjs/casperjs#1916]
I load a web page. Inside the web page, it has an iframe like this:

`<iframe name="pdfview" id="CONTENT_pdfview" src="pdf.aspx?page=1" frameborder="0" scrolling="auto" style="border: 0px; width: 398px; height: 395px;"></iframe>`

When I load web page in URL, I can actually see the content of the iframe in the DOM. But when I use this.getPageContent() the contents is not there. So I try to navigate into the iframe:

```
casper.thenOpen(myUrl, function () {
    casper.withFrame("pdfview", function() {
        this.test.assertUrlMatch(/pdf\.aspx\?page=1/, 'i am on inside of iframe');
        this.test.assertSelectorExists('#page1', 'The canvas exists!');
    });
})
```

However, both tests fail:

```
FAIL i am on inside of iframe
#    type: assertUrlMatch
#    subject: false
#    currentUrl: "about:blank"
#    pattern: "/pdf\\.aspx\\?page=1/"
FAIL The canvas exists!
#    type: assertExists
#    subject: false
#    selector: "#page1"   
```

It says the current url is "about:blank". Why does it say this? When I am on page, I can see the contents of iframe. What is going on here?

**Comment by kensoh** [comment]
Hi @JohnMerlino2 can you provide a minimal replication script with a URL that shows this error?

I've used withFrame before but it seems to work for me, and I'm sure for many users as well.
