### ISSUE TITLE
Segmentation Fault 11

### ISSUE THREAD

**Issue by dmgig** [casperjs/casperjs#1917]
Hi,

When running the selftest, I always get:

`Segmentation fault: 11`

- I've tried separately to install CasperJs using `npm` and `brew`
- I've tried with both slimerjs and phantomjs:
- I'm able to run both slimerjs and phantomjs on their own without issue.

examples:

```
$ brew install casperjs
$ casperjs selftest
Segmentation fault: 11
```

and

```
$ mkdir casper
$ cd casper/
$ npm init
$ npm install slimerjs
$ npm install casperjs
$ node_modules/casperjs/bin/casperjs selftest
Segmentation fault: 11
```

I'm on high Sierra 10.13.2

Thanks

**Comment by kensoh** [comment]
I saw a thread at PJS with this error - https://github.com/ariya/phantomjs/issues/14036

Not sure if reinstalling PhantomJS helps. For my environment I install directly via the zip files on their websites (PhantomJS, CasperJS). Works for my 10.13.3 macOS.

**Comment by dmgig** [comment]
I'll try installing from the zips and report back. Thank you.

**Comment by dmgig** [comment]
It does appear to be a phantomjs issue. Installing from the zips did work. Thank you.

**Comment by kensoh** [comment]
Cool, thanks for your update Dave @dmgig
