### ISSUE TITLE
different in UI style view in casperjs

### ISSUE THREAD

**Issue by IslamYounes** [casperjs/casperjs#1918]
when i open this url 
https://www.facebook.com/search/str/cairo/stories-keyword/stories-public
with chrome gives me this ui style
![chrome](https://user-images.githubusercontent.com/10909737/37875631-6f6e316c-3042-11e8-9f42-2a85cbad154a.png)
and the screenshot from casperjs give me different view
![afterloginkjkj](https://user-images.githubusercontent.com/10909737/37875645-a419a3b0-3042-11e8-92a7-9cd59328d67e.png)

**Comment by kensoh** [comment]
@IslamYounes that is expected. CasperJS underlying browser is PhantomJS, while Chrome or Puppeteer underlying browser engine is Chromium. They are simply not the same browsers, this rendering will turn out different.

**Comment by IslamYounes** [comment]
@kensoh thanks for reply but what is the solution when i inspect elements it gives me different classes names because of different styles

**Comment by kensoh** [comment]
I don't have a solution, Facebook is very strict on automated browsing of data. You can try Google Puppeteer or Safari browser for inspection, to see if that helps.

**Comment by kensoh** [comment]
You can also try adjusting the CasperJS browser resolution or user to see if it can let FB treat it the same way as Chrome browser.

**Comment by IslamYounes** [comment]
thanks @kensoh
