### ISSUE TITLE
Ho do I build a new casperjs version?

### ISSUE THREAD

**Issue by nirpeled** [casperjs/casperjs#1920]
Hey everyone,

I have forked the repo and working on an improvement, how do I build the files so I can test it out?

Thanks!

**Comment by jefleponot** [comment]
Hi nirpeled

You have to propose a PR on a new branch.

Regards

**Comment by kensoh** [comment]
Yeah, adding on, CasperJS isn't a binary built for various processors or operating systems. Its core is various JS modules. That wraps around PhantomJS (which is the engine that requires building if you are making an implementation for certain processors or operating systems).

PS - it uses executable script (eg Python) as entry point and has an .exe for Windows

**Comment by kensoh** [comment]
Closing this for now but do continue the discussion if there's new inputs!
