### ISSUE TITLE
Live debug in casperjs or use another tool?

### ISSUE THREAD

**Issue by RidaAyed** [casperjs/casperjs#1932]
Hi

Since countless hours I'm stuck with my debug workflow below in order to fetch bank transactions.

1. Try codeline in console
2. Translate codeline to casperjs e.g. surround with `evaluate` method
3. Run casperjs test with `debug` and `verbose` flag
4. Many steps (e.g. multi-factor login) are executed
5. Don't see any useful information in the log, except that my change e.g. selector fails
6. Start from point 2

Does anyone know an **non google/chromium** alternative to casperjs that offers instant testing of a particular step in a logged-in website? After digesting a vast amount of articles on webdriverio, selenium, scrapy, codeceptionjs, chimp.js yadayadayada, I simply lost sight of the wood for the trees.

#### Expected workflow:  

1. Make change in script
2. Change is watched and **only the changed step** is immediately executed. Session and preliminary steps (login) remain untouched
3. Repeat step 1 until test passes

**Comment by kensoh** [comment]
I've developed a framework based on CasperJS that has a live debugging mode. When the live step is used, you can enter commands to run on the fly. But running in default PhantomJS mode you won't see any web browser to validate the results. Also, the framework uses a different syntax from CasperJS so you will end up having to learn something new - https://github.com/kelaberetiv/TagUI
