### ISSUE TITLE
Error running with slimerjs: "this.filter is not a function"

### ISSUE THREAD

**Issue by Jtkantor198** [casperjs/casperjs#1933]
I had a bizarre issue while attempting to run casperjs with --engine=slimerjs option. I got numerous errors that this.filter is not a function and casper.filter is not a function. A filter method is called within both the Casper (modules/casper.js) and Tester (modules/tester.js) modules and both caused errors for me. Many calls to the filter method attempt to handle the function returning a false or undefined value usually as (this.filter(...,value,...) || value). So I simply created a this.filter function within the constructor that returns undefined on a fork on the repo. All tests are passing when I run "casperjs selftest" but I imagine this method has some purpose and I don't know if bypassing the issue naively would cause problems on other systems so I haven't submitted a pull request. Any tips on what this function does and handling this more tactfully?

**Comment by kensoh** [comment]
Interesting thanks for sharing this @Jtkantor198 !

Never come across this issue.. What's your CasperJS, SlimerJS and Firefox version?

**Comment by kensoh** [comment]
I see.. Yes it could. By the way there is an [open issue on incompatibility with Firefox 60 with SlimerJS](https://github.com/laurentj/slimerjs/issues/694).

Are there other operating system which you can try running it on? I have no issue using on macOS and Windows.

```
TA:src kensoh$ slimerjs --version
Innophi SlimerJS 1.0.0, Copyright 2012-2018 Laurent Jouanneau & Innophi
TA:src kensoh$ casperjs --version
1.1.4
```

**Comment by kensoh** [comment]
Closing this for now as CasperJS, similar to PhantomJS is not actively maintained.
