### ISSUE TITLE
Download fails for redirect response

### ISSUE THREAD

**Issue by kbanman** [casperjs/casperjs#1937]
I have run into an issue where `download(url, 'local_file')` results in a zero-length `local_file` when `url` responds with a `301 Redirect`.

This issue would be resolved with one of the following solutions:
1. `download()` follows redirects
2. It accepts an argument to enable following redirects.

My use case includes making an assertion on the downloaded file, so in my case I use `casper.on('resource.received')` to listen for the final url and then download it, but this results in a mess.

**Comment by kensoh** [comment]
Hi @kbanman is it possible for you to directly get the redirected URL and perform a download on it instead? Can you share more what is the mess when you implement it that way?

**Comment by kbanman** [comment]
In this case the linked url is something like ‘/download-file’. It generates a signed S3 URL and redirects to it, so the end URL cannot be predicted

**Comment by kensoh** [comment]
Oic... Shucks... Got it. I don't know if there is a technical solution that can be implemented at CasperJS by the maintainers (if you know the state of CasperJS and PhantomJS now).

But I have developed a project base on CasperJS and it can automate visible and headless Chrome. You can [take a look here](https://github.com/kelaberetiv/TagUI) to see if it can meet your scenario. It basically converts human-language-syntax into CasperJS JavaScript code and automates Chrome using a direct websocket connection. Downloading a file can be as easy as this command `click element_id_of_download_link`

**Comment by kensoh** [comment]
Closing this for now as CasperJS, similar to PhantomJS is not actively maintained.

**Comment by fcovicente** [comment]
I had a similar problem, it was resolved [disabling web security](http://docs.casperjs.org/en/latest/faq.html#faq-web-security).

```
var casper = require('casper').create({
    pageSettings: {
        webSecurityEnabled: false
    }
});
```

**Comment by kensoh** [comment]
Oh cool, thanks @fcovicente for sharing your solution!

Copying @kbanman in case he has unsubscribed.
