### ISSUE TITLE
How to change  window.screen.width?

### ISSUE THREAD

**Issue by tianzhaotong2012** [casperjs/casperjs#1938]
I have set casper.options.viewportSize = {width: 360, height: 640}; then I excute window.screen.width;
The result is 1024. How to change window.screen.width? Please help me. Thanks

**Comment by tianzhaotong2012** [comment]
I am using casperjs@1.1.4

**Comment by kensoh** [comment]
I'm not sure why the window.screen.width is not updated, but when I do image using .capture() after setting screen resolution, the captured image is in the correct resolution.

**Comment by tianzhaotong2012** [comment]
Yes captured image works ok，but the window.screen.width is not updated.   And  I found a solution, casper.options.onPageInitialized = function(){
        casper.page.injectJs("includes/util.js");
}
change the window.screen in util.js

**Comment by tianzhaotong2012** [comment]
You can fix this little bug in future

**Comment by kensoh** [comment]
Oh cool, thanks @tianzhaotong2012 ! Copying @jefleponot

**Comment by tianzhaotong2012** [comment]
hi @kensoh  excuse me .   I am using the code 
casper.options.onPageInitialized = function(){
casper.page.injectJs("includes/util.js");
}

includes/util.js is 'window.screen = {width: 360 , height: 480};'

It works well.

but I  want change the code 'casper.page.injectJs("includes/util.js");'  to '"window.screen = {width: 360 , height: 480};'  

can u help me how to write, I try and failed

**Comment by kensoh** [comment]
Hi @tianzhaotong2012 I'm not sure what you mean, normally for changing DOM properties I use casper.evaluate to send the commands to be executed in the HTML DOM. For util.js I am not familiar to advise.

**Comment by tianzhaotong2012** [comment]
thanks @kensoh  I have finish the problem in the code 
"casper.options.onPageInitialized = function(){
	//casper.page.injectJs("includes/util.js");
  casper.page.evaluate(function(language,iwidth,iheight) {
        navigator.systemLanguage = language
        navigator.language = language
        window.screen = {width: iwidth, height: iheight};
      },ilanguage,width,height);
};"

excuse me . can i ask another question?  I want to change the http header 'Accept-Language': 'en-US,en;q=0.9'  I found the code useful 

casper.open('http://127.0.0.1/request.php',{
     headers: {
         'Accept-Language': 'en-US,en;q=0.9'
     }
 }).then(function() {  
      this.echo('GOT it.');  
});

But I want to change  at casper create or start.  Not just in open. can u help me?

**Comment by kensoh** [comment]
Saw your new issue, i'll reply there!
