### ISSUE TITLE
Make CasperJS work with newer Ecamascript versions

### ISSUE THREAD

**Issue by EnterRavement** [casperjs/casperjs#1941]
Hey, it would make many things easier, if I would be able to use the functionality of newer ES versions

**Comment by kensoh** [comment]
CasperJS is a wrapper around PhantomJS. The JavaScript version in CasperJS is the JavaScript engine packaged within PhantomJS, and PhantomJS has suspended development for now - https://github.com/ariya/phantomjs/issues/15344

**Comment by kensoh** [comment]
Cool @nitish173 thanks for sharing your solution to use ES6 features!
