### ISSUE TITLE
selftest crashes right after install (Windows 10, underlying phantomjs issue) 

### ISSUE THREAD

**Issue by gloomypenguin** [casperjs/casperjs#1942]
I started playing with PhantomJS a few days ago (never before installed 2.1.1) and decided I wanted to make my life easier.  Today I downloaded CasperJS (1.1.4) and ran the selftest because the website told me to do it and it crashed.  I am running Windows 10.  

This looks like my exact issue from PhantomJS: https://github.com/ariya/phantomjs/issues/14512

The solution that looks right: 

> The crash might be originating in the QT WebSocket handling code. Try setting the Karma transports setting to polling to disable the communication through WebSockets:
> 
> transports: ['polling']

End of my output... 

```
PASS Casper.waitForSelectorTextChange() can wait for text on a selector to change
PASS waitForSelectorTextChange() tests (1 test)
# waitUntilVisible() tests
PASS Casper.waitUntilVisible() waits for a selector being visible
PASS Casper.waitUntilVisible() waits for a selector being visible
PASS waitUntilVisible() tests (2 tests)
# waitForUrl() regexp tests
PASS Casper.waitForUrl() waits for a given regexp url
PASS waitForUrl() regexp tests (1 test)
# waitForUrl() string tests
PASS Casper.waitForUrl() waits for a given string url
PASS waitForUrl() string tests (1 test)
# waitForExec() tests
Fatal Windows exception, code 0xc0000005.
PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.
```

I am just playing around for fun.  Do I care that selftest crashes?  I don't plan on using Karma but I don't know how integrated Karma is with Casper - can I just not use those features?  Phantomjs didn't (seem to) crash when I used it to do simple web scraping so can I just stick to that w/o testing?  Should I just pretend I never ran that self test...? 

I'll keep looking it into myself but I'm super inefficient because I'm not sure what's going on

**Comment by kensoh** [comment]
I recommend to ignore the self-test fail error, most important is for your automation use cases your script works 👍 Due to many OS variations and lack of active maintenance for PhantomJS and CasperJS, it will be unlikely to have all the self-test errors resolved.
