### ISSUE TITLE
Can not resolve "child_process" module with slimerjs

### ISSUE THREAD

**Issue by barreradevops** [casperjs/casperjs#1945]
OS: Ubuntu 16.04 Subsystem (Windows 10)

CasperJS Version: 1.1.4
SlimerJS: 1.0

Getting this error when using casper.waitForExec with SlimerJS engine on CasperJS, it is a simple sleep
`casper.waitForExec('sleep 3', null, function(response) {this.echo('sleep 3 done')})`

`
Module: Can not resolve "child_process" module required by casper located at file:///usr/lib/node_modules/casperjs/modules/casper.js
`

Is it an error coming from slimerjs or casperjs?

**Comment by kensoh** [comment]
Hi @barreradevops can you try running with the default PhantomJS engine to see if the same error happens? I am able to use this function without problem for PhantomJS.

For SlimerJS there is some incompatibility issue with the latest Firefox, there is still an open issue for it - https://github.com/laurentj/slimerjs/issues/694

I'm closing the issue for now but do continue the discussion if any new inputs!
