### ISSUE TITLE
[2.0] Consider using colors.js

### ISSUE THREAD

**Issue by brianmhunt** [casperjs/casperjs#271]
Just a suggestion: Instead of writing and maintaining a colorizer, perhaps it would be easier to use e.g. Marak Squires's [colors.js](https://github.com/Marak/colors.js).

**Comment by kensoh** [comment]
Closing this issue for now as it hasn't gotten new replies or discussion for 3+ years. But do reopen if anything! Also copying maintainer @jefleponot
