### ISSUE TITLE
[2.0] Switch to mocha & chai testing frameworks

### ISSUE THREAD

**Issue by n1k0** [casperjs/casperjs#278]
[Mocha](http://visionmedia.github.com/mocha/) and [Chai](http://chaijs.com/) are neat unit/bdd testing frameworks, and we should probably use them for 2.0.

**Comment by BIGjuevos** [comment]
Based on current discussions on the new 2.0 thread, it looks like this is going to happen.  Closing this issue due to it's age. #1524
