### ISSUE TITLE
Support encoding of (deeply) nested objects for POST requests

### ISSUE THREAD

**Issue by widged** [casperjs/casperjs#347]
Assuming `var items = [{a: 1, b:1}, {a: 2, b:2}];` and a post of this array of objects to a php webservice.

``` js
casper.open(service.url, {
    method: 'post',
    data:   {
        'items[]'   : items,  // brackets added as per documentation
    }
}
```

PHP receives an array of empty string:

``` php
array(2) {
    [0]=>
    string(0) ""
    [1]=>
    string(0) ""
}
```

With

``` js
items = [
    JSON.stringify({a: 1, b:1}),
    JSON.stringify({a: 2, b:2})
];
```

The objects make it through.

``` php
array(2) {
    [0]=>
    string(13) "{"a":1,"b":1}"
    [1]=>
    string(13) "{"a":2,"b":2}"
}
```

And it is possible to decode them within php using `json_decode($json, true);` However this behavior deviates from the usual ajax post where this would go through and be read as associative array in PHP. 

``` js
data:   { 
    'items'   : items,  // no need for brackets
}
```

**Comment by istr** [comment]
If you have a look at https://github.com/n1k0/casperjs/blob/master/modules/casper.js#L1419 you will notice that currently only two types of POST requests are supported:
- objects that could be serialized as JSON if you set your content-type appropriately in options  (NOTE: you _cannot_ serialize an array without a wrapping object using JSON.stringify) 
- (nearly flat) objects that could be serialized by the ```querystring``` library (NOTE: this does not support the kind of objects requested here, and this is why @n1k0 mentioned that it could be an option to use a library that supports encoding of deeply nested objects)

**Comment by kensoh** [comment]
Archiving issue using **ARCHIVE** label as CasperJS, like PhantomJS, is not actively maintained for now.
