### ISSUE TITLE
Selector formatting in failure messages (for xpath selectors)

### ISSUE THREAD

**Issue by p** [casperjs/casperjs#366]
I use xpath selectors a lot and when they do not match as expected, the failure message is rather unhelpful:

```
FAIL Cannot dispatch click event on nonexistent selector: [object Object]
```

I started on a patch to make this output more useful. With the patch I now receive:

```
FAIL Cannot dispatch click event on nonexistent selector: [selector type=xpath, path=//missing]
```

I only did this for one instance so far and did not even bother fixing the other occurrence in the same function. Interested in feedback.

Diff: https://github.com/p/casperjs/compare/format-selector

Example: https://github.com/p/test-repo/tree/master/casperjs/format-selector

**Comment by istr** [comment]
The feature would be nice to have and simple to integrate. Could you please create a proper PR against current master for this and apply to every occurrence that might need it?

If you're going to create a proper PR, please:
- put your ```formatSelector``` into ```modules/utils.js```
- reference it with a short alias (e.g. ```fsel```) within ```casper.js```
- use ```if (utils.isObject(selector) && selector.type === 'xpath')``` to perform your check within your formatting function (cf. line 810 https://github.com/n1k0/casperjs/blob/master/modules/casper.js)

Bumped milestone to 1.1.

**Comment by p** [comment]
I probably will not be creating a "proper PR" since I have not used casperjs since 2013.

**Comment by istr** [comment]
Ok, thanks for your update.

**Comment by jkatzer** [comment]
![it's a trap](https://images.duckduckgo.com/iu/?u=http%3A%2F%2F3.bp.blogspot.com%2F-KS4hvAI8Bkg%2FUJRtNbG4qJI%2FAAAAAAAADXY%2FF5j_K60fDLM%2Fs640%2Fitsatrap.jpg&f=1)

**Comment by istr** [comment]
Ok, maybe this is really obviously abandoned. ;-)

Anybody wanting to implement this please re-open and provide a PR. Dropping the milestone target for now.
