### ISSUE TITLE
Implement drag()

### ISSUE THREAD

**Issue by n1k0** [casperjs/casperjs#379]
Looks like emulating drag 'n drop is now possible as of PhantomJS 1.7 (1.8?) https://github.com/n1k0/casperjs/issues/147#issuecomment-13377052

See that gist https://gist.github.com/Johnny000/4751813

Simplest possible API:

``` js
// using selector
casper.drag('#source', '#target');
// using coordinates
casper.drag([100, 100], [200, 200]);
// mixed usage
casper.drag('#source', [200, 200]);
casper.drag([100, 100], '#target');
```

Thoughts?

**Comment by istr** [comment]
I would propose to move the milestone from 1.1 to 2.0 to shorten the list of TODO items for 1.1.
@paazmaya @hexid ?

**Comment by paazmaya** [comment]
Agreed @istr

**Comment by kensoh** [comment]
Archiving issue using **ARCHIVE** label as CasperJS, like PhantomJS, is not actively maintained for now.
