### ISSUE TITLE
Totally decouple tester from casper

### ISSUE THREAD

**Issue by n1k0** [casperjs/casperjs#407]
There shouldn't be `casper.test` property anymore, rather setup a tester instance, so we'd just keep:

``` js
/*global casper test*/
test.begin('make it foo', 2, function(test, casper) {
    // ...
    test.done();
});
```

While it's a lot cleaner to my eyes, this now also totally breaks BC, so I'm not sure. Also I'm not sure about the `test` global name. `tester`, `runner`, `testRunner` maybe?

Decisions.

**Comment by kensoh** [comment]
Archiving issue using **ARCHIVE** label as CasperJS, like PhantomJS, is not actively maintained for now.
