### ISSUE TITLE
Redirects not followed

### ISSUE THREAD

**Issue by danielnitsche** [casperjs/casperjs#442]
``` js
casper.start('http://www.casperjs.org', function(response) {
  this.test.assertEquals(response.status, 200);
});

casper.thenOpen('http://www.casperjs.org', function(response) {
  this.test.assertHttpStatus(200);
});

casper.run(function() {
  this.test.done();
});
```

Result:

```
FAIL Subject equals the expected value
#    type: assertEquals
#    subject: 301
#    expected: 200
FAIL HTTP status code is: 200
#    type: assertHttpStatus
#    subject: false
#    current: 301
#    expected: 200
```

I would expect that casper should follow the redirect and return a 200 (or, provide some option on what to do with redirects). I added the first test using response.status, because for certain redirects, this seems to work for me.

Reference: https://groups.google.com/forum/#!searchin/casperjs/redirect/casperjs/W0BsRe_i6aI/z3z1Gw4r73QJ

**Comment by kensoh** [comment]
@danielnitsche I'm a CasperJS user for couple of years now looking through open issues.. It looks like something along the way changed? And seems to pass for the 2 tests in your test script.

```
PASS Subject equals the expected value
PASS HTTP status code is: 200
```

**Comment by kensoh** [comment]
Thanks guys for your inputs! Closing this issue as it appears to work ok with current releases. In any case, kindly ping here if there is and issue. I'm on GitHub almost everyday these days. Or my personal email at ken@tebel.org
