### ISSUE TITLE
Content-Security-Policy prevents resource loading

### ISSUE THREAD

**Issue by arielschwartz** [casperjs/casperjs#478]
When trying to load http://github.com , I get the following warning for several resources:

```
[info] [remote] Refused to load style from 'https://a248.e.akamai.net/assets.github.com/assets/github-fdebe8d3f60746fb87c763a59741ff520ae3d8e8.css' because of Content-Security-Policy.
```

It seems to be related to the CSP header in the server's response:

```
Content-Security-Policy:default-src *; script-src https://github.com https://a248.e.akamai.net https://jobs.github.com https://ssl.google-analytics.com https://secure.gaug.es https://collector.githubapp.com https://gist.github.com; style-src https://github.com https://a248.e.akamai.net 'unsafe-inline'; object-src https://github.com https://a248.e.akamai.net
```

Interestedly, the CSP header should allow loading resources from the domains specified in the CSP header, but for some reason, they can't be loaded.
https://github.com/blog/1477-content-security-policy

I'm using phantomjs 1.9, casperjs 1.0.2. Also, setting `--web-security=no` does not help as well.

Is there any way to remove/filter a response header (i.e. remove the CSP header), or any other advice to mitigate this?

**Comment by kensoh** [comment]
@arielschwartz I didn't see any confirmation from the PhantomJS thread. But I recently am able to run through an automation flow on GitHub, clicking through some elements and try downloading a zip. Not sure if the issue is still happening now for you.

**Comment by kensoh** [comment]
@arielschwartz I would like to close this issue as it appears to be fixed now, but please reopen if you are still experiencing it. Thanks for raising this issue! I'm on GitHub most days but can also be reached at ken@tebel.org if somehow I miss your response on replication script.
