### ISSUE TITLE
Retrieve CSP report and the list of blocked Mixed Content elements

### ISSUE THREAD

**Issue by DavidBruant** [casperjs/casperjs#494]
Webkit implements [CSP](http://www.w3.org/TR/CSP/). It would be nice if the report info could be gathered by Casper for continuous integration purposes.

Also, Chrome [blocks active mixed content](http://googleonlinesecurity.blogspot.com/2011/06/trying-to-end-mixed-scripting.html). I'm not entirely sure it's a Webkit feature, but if it is, it would be good if Casper had access to this information to have it reported in continuous integration.

I imagine this may require some work on PhantomJS beforehand.

**Comment by kensoh** [comment]
@DavidBruant I've just looked at PhantomJS's 2 issues, it looks like both may not have been implemented yet, but am not sure.

**Comment by kensoh** [comment]
Closing this issue for now as it hasn't gotten new replies or discussion for 4 years. But do reopen if anything! Also PhantomJS has 2k open issues without a successor to its maintainer as of now.
