### ISSUE TITLE
Simplier loops (not like dynamic.js)

### ISSUE THREAD

**Issue by rafis** [casperjs/casperjs#499]
There is a well known sample dynamic.js, which no mortal can understand and means less usable and means less popular (concurent to CasperJS may arise). And some people tried to make it more simple https://github.com/yotsumoto/casperjs-goto. And it is almost works, but I need other then-class function like waitForSelector() and they are not working in casperjs-goto. Could please author of CasperJS look into his project and implement similar feature in CasperJS?

**Comment by BIGjuevos** [comment]
See #1513 and #1514 closing this.
