### ISSUE TITLE
New "regex" selector

### ISSUE THREAD

**Issue by UlysseM** [casperjs/casperjs#520]
I found out there were no way of using real regex for selecting things.
I'm aware of such a feature is not a standard (as opposed to CSS selector and XPATH), but in some case, they can be quite useful.

I wrote a patch that uses a 'regex' selector, which looks pretty much like this:

``` js
var selector = {
  type: 'regex',
  tag: 'a',
  attributes: {
    href: 'yourRegex',
    style: '#33[0-9a-fA-F]{4}'
  }
};
```

If it's not clear enough, the selector will look for the any item of the tag 'a', which contains at least the attributes 'href' and 'style' matching the regex.

**Comment by istr** [comment]
Would you mind adding a test case and turning this into a PR on a separate feature branch that is up-to-date with current master?

**Comment by BIGjuevos** [comment]
I quite like this idea, marking it as part of the 1.2 milestone.  Can @picandocodigo or @UlysseM please pick up the PR so we can include it in 1.2?

**Comment by kensoh** [comment]
@UlysseM and @picandocodigo bumping up this interesting enhancement suggestion.

**Comment by UlysseM** [comment]
I haven't used casperjs in years, but I'll try to bump it this weekend.

**Comment by kensoh** [comment]
Thanks @UlysseM ! Also copying maintainer @jefleponot

**Comment by kensoh** [comment]
Archiving issue using **ARCHIVE** label as CasperJS, like PhantomJS, is not actively maintained for now.
