### ISSUE TITLE
Uncaught error message displays wrong line of user's code (1.1-beta1)

### ISSUE THREAD

**Issue by rootpd** [casperjs/casperjs#570]
Line number displayed in "file: ..." part of output when uncaughtError message is shown is displaying line from tester.js stack which is always below in callstack instead of line number of my script.

This is the example of some uncaught error messages:

```
FAIL Errors encountered while filling form: form not found
07-Aug-2013 11:21:46    #    type: uncaughtError
07-Aug-2013 11:21:46    #    file: /test/casperjs/customer_zone.js:779
07-Aug-2013 11:21:46    #    error: Errors encountered while filling form: form not found
07-Aug-2013 11:21:46    #           CasperError: Errors encountered while filling form: form not found
07-Aug-2013 11:21:46    #               at fillForm (/opt/casperjs-1.1.0dev/modules/casper.js:779)
07-Aug-2013 11:21:46    #               at fillNames (/opt/casperjs-1.1.0dev/modules/casper.js:839)
07-Aug-2013 11:21:46    #               at /test/casperjs/customer_zone.js:562
07-Aug-2013 11:21:46    #               at runStep (/opt/casperjs-1.1.0dev/modules/casper.js:1523)
07-Aug-2013 11:21:46    #               at checkStep (/opt/casperjs-1.1.0dev/modules/casper.js:368)
07-Aug-2013 11:21:46    #    stack: not provided
```

```
07-Aug-2013 11:21:52    ???????wait timeout of 5000ms reached
07-Aug-2013 11:21:52    FAIL Wait timeout occured (5000ms)
07-Aug-2013 11:21:52    #    type: uncaughtError
07-Aug-2013 11:21:52    #    file: /test/casperjs/customer_zone.js:231
07-Aug-2013 11:21:52    #    error: Wait timeout occured (5000ms)
07-Aug-2013 11:21:52    #           TimedOutError: Wait timeout occured (5000ms)
07-Aug-2013 11:21:52    #               at test_onWaitTimeout (/opt/casperjs-1.1.0dev/modules/tester.js:231)
07-Aug-2013 11:21:52    #               at _check (/opt/casperjs-1.1.0dev/modules/casper.js:2029)
07-Aug-2013 11:21:52    #    stack: not provided
```

Basically my errors are not on customer_zone.js:779 or customer_zone.js:231. They are in tester.js:779 and tester.js:231.

**Comment by kensoh** [comment]
Adding on that this may have commonality with https://github.com/casperjs/casperjs/issues/1230 and issue seems to still happen. I'm running v1.1.4 + v2.1.1.

**Comment by kensoh** [comment]
@rootpd bumping up. Closing the 1230 issue as it is a duplicate. Updating this issue with similar comment as that thread. This still exists although the correct line # is also included in the test result above - `at /test/casperjs/customer_zone.js:562`.

I guess people are living with this workaround with the misleading header/footer line # when running in test mode. When not in test mode there is no such header/footer to be misleading.

**Comment by kensoh** [comment]
Also copying @mefiblogger who raised the issue 1230.

**Comment by kensoh** [comment]
Bumping up and copying maintainer @jefleponot

**Comment by kensoh** [comment]
Archiving issue using **ARCHIVE** label as CasperJS, like PhantomJS, is not actively maintained for now.
