### ISSUE TITLE
Make `casper.download` target argument function compatible

### ISSUE THREAD

**Issue by oncletom** [casperjs/casperjs#580]
The use case would be to generate a target based on response headers, like this

``` javascript
var url = "http://distilleryimage2.s3.amazonaws.com/924d444804f011e3a2f022000a9e0b54_5.jpg";

casper.download(url, function(response, request){
  var modified = new Date(response.headers.get("Last-Modified"));
  return [modified.getUTCFullYear(), modified.getUTCMonth()+1, modified.getUTCDate()].join("") + "/" + url.split("/").pop();
});
```

It is live in this [Instagram Hashtag Archiver](https://gist.github.com/oncletom/6245811) where the image needs to be loaded with a `thenOpen` to get access to the response headers.
As an alternative, I could certainly create a map of `resource.url` on `resource.received` events, to be able to save the extra request.

Requires to modify:
- [x] `clientutils.js#getBase64`
- [ ] `clientutils.js#sendAJAX`
- [ ] `clientutils.js#getBinary`
- [ ] `casper.js#download`

Ideally a `addEventListener("load")` could enable to plug some event and let that bubbling up.

I also wonder how the sendAJAX works in async mode, as there is no callback and it returns a `xhr.responseText`.

**Comment by kensoh** [comment]
Tagging on a new pull request which adds a new event 'fileDownload' which may be relevant to this issue - *allows to alter the path for the file that must be downloaded* - https://github.com/casperjs/casperjs/pull/1835

**Comment by kensoh** [comment]
Closing this issue for now as it hasn't gotten new replies or discussion for 4 years. But do reopen if anything!
