### ISSUE TITLE
Strange behavior of require in conjunction with --includes option

### ISSUE THREAD

**Issue by ValeriiVasin** [casperjs/casperjs#585]
Assume that we have a project features for testing stored inside of `features` folder. Also if feature is big - it could have subfolders.

Currently our project features (tests) structure is something like that:
features
```
features
├── feature_1.js
├── feature_2.js
└── feature_3
    ├── feature_3.1.js
    └── feature_3.2.js
```

Also we have some shared functionality that should be available for all features. For example: login, logout, url constructor (for logged in / logged out users).

We have `shared.js` file that is stored in one level with `features` folder. This file also depends on some configuration data that is required in it.

In general we use `casper test features --includes=shared.js` command for testing our project.

Now, CasperJS 1.1-dev breaks requiring functionality inside of included file. Each require command is resolved according to feature file. For example, if we are testing `features/feature_3/feature_3.1.js` file, we should use `require('../../config')` in `shared.js`. But if we are testing `features/feature_1.js` we should use `require('../config')`.

In 1.0.2 `require` depends on included file location, not feature location we are testing.

I suppose it's a bug? or what way we should store our common functionality for all tests we have?

**Comment by BIGjuevos** [comment]
I'm considering this issue stale.  Closing.  Please re-open if you would like to have this pursued further.
