### ISSUE TITLE
evaluate() returns null object property values as empty string

### ISSUE THREAD

**Issue by simplysh** [casperjs/casperjs#608]
Simple replication of the issue:

``` javascript
casper.test.begin('Inconsistent', 1, function(test) {
    casper.start().then(function() {

        this.test.assertEquals(
            this.evaluate(function() {

                return {"something": null}

            }), {"something":null} )

    }).run(function() {
        test.done();
    });
});
```

Output

```
# Inconsistent
FAIL Subject equals the expected value
#    type: assertEquals
#    file: C:\TEMP\phantom\casper-suite\inconsistent.js:9
#    code: }), {"something":null} )
#    subject: {"something":""}
#    expected: {"something":null}
FAIL 1 test executed in 0.059s, 0 passed, 1 failed, 0 dubious, 0 skipped.
```

**Comment by BIGjuevos** [comment]
Verifies this still happens in latest version.

**Comment by istr** [comment]
Note that this might be an engine bug, see https://github.com/baudehlo/node-phantom-simple#known-issues

**Comment by istr** [comment]
@simplysh please verify your test case with the engine you are using directly. Please tell us the versions of CasperJS, PhantomJS and/or SlimerJS you are using. Thanks.

**Comment by simplysh** [comment]
Guys, I've raised this almost three years ago, I'm afraid I don't have the code nor environment set up any more.

**Comment by istr** [comment]
> I'm afraid I don't have the code nor environment set up any more.

Ok, thanks for your feedback anyway... :-)

**Comment by simplysh** [comment]
I'd still like to help though, let me know if there's something I can do. At this point there's no way to use the version I was using back then so I guess it's a case of testing against the latest version.

**Comment by kensoh** [comment]
@simplysh bumping and adding on with CasperJS v1.1.4 and PhantomJS v2.1.1 the same error output happens by running your test script.

**Comment by freckletonj** [comment]
This is a bug on Phantomjs, and I got around it by using `undefined` instead of `null`.

**Comment by kensoh** [comment]
Thanks @freckletonj for sharing your findings :) Sounds like this is something that can't be mitigated from CasperJS side. Also cc current main maintainer @jefleponot besides Ryan and Ingo. I'm not sure whether to add Documentation label or whether to consider this as something that should be closed.

**Comment by shanewey** [comment]
I'm having this issue with "CasperJS version 1.1.4" and "phantomjs version 2.1.1".

**Comment by kensoh** [comment]
Archiving issue using **ARCHIVE** label as CasperJS, like PhantomJS, is not actively maintained for now.
