### ISSUE TITLE
Selector-scoped blocks of commands

### ISSUE THREAD

**Issue by mcamiano** [casperjs/casperjs#632]
This is a request for a feature similar to the Capybara "within" construct:
Example of what it might look like in coffeescript:

``` coffeescript
@within '#b2 form' -> 
     @test.assertField "bar" "Joe Schmoe" 
     @test.assertTextExists "Joe Schmoe" 
```

As far as I know casperjs does not provide way to make a set of commands and their selectors relative to a particular context.

The analogous block in Capybara is useful to reduce repetition of selectors. I can use temporary variables in some ways and xpath in other ways to do something similar, but neither is as concise or clean.

**Comment by jakobjp** [comment]
Has anything like this been implemented yet? I would like selector scopes as well!

**Comment by kensoh** [comment]
Bumping up this thread, but not yet implemented. Also copying @jefleponot

**Comment by kensoh** [comment]
Archiving issue using **ARCHIVE** label as CasperJS, like PhantomJS, is not actively maintained for now.
