### ISSUE TITLE
Logging of steps with function names is inconsistent

### ISSUE THREAD

**Issue by jpz** [casperjs/casperjs#651]
I've found it quite useful to declare non-anonymous step functions, so I can see what step is being executed.  

For a several step definitions, a step function is created which wraps the originally named function, and the "_step" function is logged as being called (which is the wrapping function name declared in the casper.js file.)  

This function name being logged has very little utility to the user.

I've made a few minor changes to casper.js to provide improved logging of function names, on a branch in my fork of the repository.

thanks

**Comment by kensoh** [comment]
Closing this issue for now as it hasn't gotten new replies or discussion for 3+ years. But do reopen if anything!
