### ISSUE TITLE
the 'open' method post data not utf-8 encode

### ISSUE THREAD

**Issue by binbin** [casperjs/casperjs#685]
``` js
casper.open('http://some.testserver.com/post.php', {
    method: 'post',
    data:   {
        'title': 'Plop',
        'body':  'Wow.',
        'name':'灵感搭'
    }
});
```

The server need  the name field is `%C1%E9%B8%D0%B4%EE` (GBK),but the post's field is `%E7%81%B5%E6%84%9F%E6%90%AD` (UTF-8), how can i to set it? thx

**Comment by quizzicus** [comment]
PhantomJS supports setting the 'encoding' as of version 1.9. But I think casperjs would have to be updated to pass the setting along.

http://phantomjs.org/api/webpage/method/open.html

**Comment by paazmaya** [comment]
This is how the given `open` method is called via CasperJS
https://github.com/n1k0/casperjs/blob/master/modules/casper.js#L1436

It would seem somewhat trivial to add the `encoding` options, but there might also be value of allowing to pass other settings as well.

**Comment by teragoon** [comment]
try like this..
```javascript
casper.then(function() {
    this.page.openUrl('http://localhost:3000/save', {
        operation: 'post',
        encoding: "utf-8",
        data: '{"result": "한글"}',
        headers: {
            'Content-type': 'application/json; charset=utf-8'
        }
    }, this.page.settings);
});
```

**Comment by kensoh** [comment]
Closing this issue for now as it hasn't gotten new replies or discussion for 2+ years. But do reopen if anything!
