### ISSUE TITLE
IE support through TrifleJS?

### ISSUE THREAD

**Issue by n1k0** [casperjs/casperjs#688]
[TrifleJS](http://triflejs.org/) is _A headless Trident engine (Internet Explorer) with a Javascript API. Port of PhantomJS_.

It may worth investigating the possibility to provide support for this engine. @hexid, would you like to spend some time on it?

**Comment by chino** [comment]
Hi @sdesalas, curious how this has come along since the last update?

**Comment by vinci-mz** [comment]
It would be great to have one tool for testing WebKit, FF and MSIE in the way proposed by casperjs.  Is there a roadmap?  How to help to provide this functionality?

**Comment by kensoh** [comment]
Bumping up the interesting idea in this thread :)

**Comment by kensoh** [comment]
Closing this issue for now as it hasn't gotten new replies or discussion for about 2 years. But do reopen if anything! It seems that more pressing is managing transition away to support Chrome, as PhantomJS seems to be going unmaintained as of now. Also copying @jefleponot
