### ISSUE TITLE
Improve visible test

### ISSUE THREAD

**Issue by clochix** [casperjs/casperjs#720]
When scraping websites, the `visible` method isn't always relevant, because it only use the style of the element (`visibility` and `display`). But websites have at least 3 ways to hide content:
- set `display` or `visibility`;
- move the element outside of the viewport;
- set `height` and `width` to 0;

For now, I have added methods to Casper to test if an element is inside another and if its height and width are not null. Plus the wait until and while. Are you interested in this methods, or are this edge cases too rare to care ?

**Comment by kensoh** [comment]
Archiving issue using **ARCHIVE** label as CasperJS, like PhantomJS, is not actively maintained for now.
