### ISSUE TITLE
Custom runner problems

### ISSUE THREAD

**Issue by speg** [casperjs/casperjs#741]
At the bottom of http://docs.casperjs.org/en/latest/testing.html#testing we see:

> Extending Casper for Testing
> This command:
> 
> $ casperjs test [path]
> is just a shortcut for this one:
> 
> $ casperjs /path/to/casperjs/tests/run.js [path]

So I copy `run.js` so that I can modify it, but get the following error:

```
casperjs original_run.js cow-test.js 
⚠  CasperError: casper.test property is only available using the `casperjs test` command
```

Whereas the other way worked fine:

```
casperjs test cow-test.js 
Test file: cow-test.js                                                          
# Cow can moo
PASS Subject equals the expected value
PASS Subject is strictly true
PASS 2 tests executed in 0.023s, 2 passed, 0 failed, 0 dubious, 0 skipped.
```

So perhaps something changed to make test not just a shortcut to the runner?

**Comment by istr** [comment]
Removing the milestone target as it seems stale now.

**Comment by kensoh** [comment]
Closing this for now as there hasn't been new discussion for 3+ years. But do reopen if anything!
