### ISSUE TITLE
Reconsider deprecating planned assertions argument in test.done()

### ISSUE THREAD

**Issue by philmander** [casperjs/casperjs#744]
In my Casper test suite, each test case is modelling a particular user journey within my webapp. Each user journey may replicate common parts, so to avoid code duplication, I have a setup where common tests are imported as modules. Here's a simple example, logging in to the app at the start of a test case:

``` javascript
var login = require("../modules/login");
casper.test.begin('Make a payment', function(test) {

    casper.start();

    casper.then(function() {
        login.loginAsUser("lisa", "password");
    });
    casper.then(function() {
        //do some other stuff
    });

    casper.run(function() {
        test.done();
    });
});
```

This seems to be good practice to me. My problem is that it's difficult to know the number of planned assertions in this code, since it is made up of many imported functions which each have their own assertions. And changing the number of assertions in a module will break the tests cases downstream.

My solution is to return the number of planned assertions from each imported test function and accumulate them, then pass the planned total to done(), like this:

``` javascript
var login = require("../modules/login");
casper.test.begin('Make a payment', function(test) {

        //just one assertion
    var total = 1;
    test.pass("blah");

    casper.start();

    casper.then(function() {
        //more assertions happen in here:
        total += login.loginAsUser("lisa", "password");
    });
    casper.then(function() {
        //do some other stuff
    });

    casper.run(function() {
        test.done(total);
    });
});
```

However, as passing the planned assertions to test.done is now deprecated it means that, obviously, this won't be possible in the future. Is it possible to un-deprecate this feature or is there, perhaps, a more obvious solution to my problem?

**Comment by istr** [comment]
We should mention this trick along with the deprecation notice.

**Comment by kensoh** [comment]
Archiving issue using **ARCHIVE** label as CasperJS, like PhantomJS, is not actively maintained for now.
