### ISSUE TITLE
JSON configuration file for tests?

### ISSUE THREAD

**Issue by n1k0** [casperjs/casperjs#745]
Would it be useful to allow users to configure the test runner using a JSON configuration file like this:

``` json
{
  "auto-exit": false,
  "concise": false,
  "fail-fast": false,
  "includes": ["inc1.js", "inc2.js"],
  "log-level": "debug",
  "no-colors": false,
  "paths": ["a.js", "b.js", "c.coffee", "sub1", "sub2"],
  "post": ["post1.js", "post2.js"],
  "pre": ["pre1.js", "pre2.js"],
  "verbose": true,
  "xunit": "results.xml"
}
```

So you could run a test suite simply using:

```
$ casperjs test config.json
```

Please +1 if you want/need this feature.

**Comment by kensoh** [comment]
Bumping up this thread and copying @jefleponot

**Comment by kensoh** [comment]
Archiving issue using **ARCHIVE** label as CasperJS, like PhantomJS, is not actively maintained for now.
