### ISSUE TITLE
Allow --post tests to proceed even if --fail-fast is specified

### ISSUE THREAD

**Issue by kostajh** [casperjs/casperjs#750]
I am doing some teardown functionality (deleting content, deleting test users) in a test loaded using `--post=teardown.js`. I need this to proceed regardless of whether the tests I am running succeed or fail. If I run my tests without `--fast-fail`, then my teardown methods in `--post=teardown.js` get called. But with `--fast-fail`, they don't. 

Of course I could just run my tests without the `--fast-fail` option, but it's much quicker and more convenient to use fast fail.

So, I think it would be nice to either (1) always run tests that are passed using the `--post=` option, even if `--fast-fail` is specified and a test fails, or (2) add another option like `--post-require=TRUE` so that the user can specify that the `--post` tasks are always run.

**Comment by istr** [comment]
Makes absolutely sense for me, too. Removing milestone target due to lack of volunteers to implement this.

**Comment by kensoh** [comment]
Archiving issue using **ARCHIVE** label as CasperJS, like PhantomJS, is not actively maintained for now.
