### ISSUE TITLE
casperjs download file character encoding utf8 issue

### ISSUE THREAD

**Issue by hsnelamir** [casperjs/casperjs#777]
I'm trying to download the following csv file using casperjs

``` js
var casper = require('casper').create({});
casper.start('http://69.50.252.196/');
casper.then(function(){
    this.download('http://69.50.252.196/download.csv', 'downloaded.csv');
});
casper.run(function() {
    this.exit();
});
```

download.csv

```
إختبار  Arabic
آزمایشی Persian
测试  Chinese
測試  Chinese
испытание   Russian
परीक्षा Hindi
δοκιμή  Greek, Modern (1453-)
테스트 Korean
טעסט    Yiddish
テスト Japanese
பரிட்சை Tamil
```

but the downloaded file always corrupted and got corrupted characters

downloaded.csv

```
"%.*('1 Arabic" 
"2E'ج4ج Persian
Kص  Chinese
,f  Chinese
8A?KB0=85   Russian
*0@M7> Hindi
´؟؛¹¼®  Greek"   Modern (1453-)"
"L¤¸    Korean" 
"طâلط   Yiddish"    
"ئ¹ب    Japanese"   
"ھ°؟ںحڑب    Tamil"  
```

```
casperjs --version
1.1.0-beta3
phantomjs --version
1.9.2
```

**Comment by rpacheco-aa** [comment]
Has this been merged?

**Comment by paazmaya** [comment]
Still seems to be the "old" https://github.com/n1k0/casperjs/blob/master/modules/casper.js#L596

@yujiroarai and @r8k seem to have something done, but would there be anything for a PR (with tests included)?

**Comment by yujiroarai** [comment]
@paazmaya what is old ?

**Comment by paazmaya** [comment]
The current code:
```
fs.write(targetPath, cu.decode(this.base64encode(url, method, data)), 'wb');
```
as discussed above

**Comment by qknight** [comment]
so no fix yet? this is really broken as it is now. please fix ;-)

**Comment by mickaelandrieu** [comment]
@qknight a "workaround"  is provided,  but feel free to make a pull request :)

**Comment by bolonio** [comment]
Have you tried to run the script with the output encoding command line parameter?

casperjs --output-encoding=cp866 [params] [filename]

**Comment by celine-m-s** [comment]
+1
I'm having big troubles with the encoding. Are you planning to merge the PR? Thanks!!

**Comment by jefleponot** [comment]
Hi @celine-m-s 
Which PR are you talking about ?

**Comment by celine-m-s** [comment]
Hi!
Sorry, I was mistaken because I read the label "PR" so I thought there was a PR linked with this issue. I'm not a crack in Javascript so unfortunately I will not be able to do a PR to fix this problem. Here is what I did to (temporarily) have the values I wanted: 
```javascript
a.replace(/(&lt;)/g,"<").replace(/(&gt;)/g,">").replace(/(<p>&gt;<\/p>)/g, "").replace(/(<p>&lt;<\/p>)/g, "");
```
Not pretty but it does the job.
Anyway, thank you so much for your great work!

**Comment by kensoh** [comment]
It looks like there's no outstanding follow-up? Do reopen if anything!
