### ISSUE TITLE
--proxy option doesn't work

### ISSUE THREAD

**Issue by birbird** [casperjs/casperjs#781]
Here is my test js code:

``` js
var casper = require('casper').create({
    pageSettings : {
        loadImages : true,
        loadPlugins : false
    },
    logLevel : 'info',
    verbose : false,
    viewportSize : {
        width : 1280,
        height : 1024
    },
    waitTimeout : 5000
});

var url = "http://www.iprivacytools.com/proxy-checker-anonymity-test";
casper.start(url, function() {    
    casper.captureSelector('proxy-check.png', 'html', {
        format : 'png',
        quality : 25
    });
});

casper.run();
```

I used both right and wrong --proxy option, neither of them fetch the page through proxy according to the snapshot.

```
casperjs --proxy="117.21.209.109:80"  proxy-check.js
casperjs --proxy="abc"  proxy-check.js
```

I use casperjs-1.1-beta1

**Comment by kensoh** [comment]
@birbird it's been a while. Not sure if this works for you now. I recently heard and verified that using below in your code will allow access through proxy.

But I almost certainly don't want to use. I want to respect the website owners explicit intention not to serve certain IP ranges or countries.

```
phantom.setProxy('IP', 'port', 'manual', '', '');
```

**Comment by kensoh** [comment]
@birbird closing this issue for now but do reopen if it is still happening for you using latest version. Thanks for raising the issue! Above example works for me, also it works for other users is this issue - https://github.com/casperjs/casperjs/issues/1445
