### ISSUE TITLE
waitFor - Performance - Call testFx immediately before doing setInterval

### ISSUE THREAD

**Issue by brandon-bethke-neudesic** [casperjs/casperjs#791]
It seems that waitFor will wait for a minimum of 2x the interval. It doesn't call testFx until the setInterval fires and then it waits another interval to check the condition and clear the interval. 

It seems that perhaps waitFor could immediately call the testFx and then if the condition is false, perform the setInterval. This would increase performance.

**Comment by BIGjuevos** [comment]
Related PR is closed.  Closing this issue.
