### ISSUE TITLE
[2.0] Add phantomjs REPL support

### ISSUE THREAD

**Issue by n1k0** [casperjs/casperjs#80]
This is [currently blocked](http://code.google.com/p/phantomjs/issues/detail?id=453) because there's no way to explicitly call the REPL interactive interface directly from code.

**Comment by kensoh** [comment]
I'm doing this way in a tool I'm making base on CasperJS. For SlimerJS there is ability to read from input now but there seems to be some issue. Raise this issue to SlimerJS repo - https://github.com/laurentj/slimerjs/issues/188

```js
{var live_input = ''; var sys = require('system');
sys.stdout.write('LIVE MODE - type done to quit\n \b');
// evaluate input in casperjs context until done is entered
while (true) {live_input = sys.stdin.readLine();
if (live_input.indexOf('done') == 0) break;
eval(tagui_parse(live_input));}}
```

**Comment by kensoh** [comment]
An update that I raised a new issue to SlimerJS repo on this. But not sure of the status of the project as the last reply to issues was 3 months ago. - https://github.com/laurentj/slimerjs/issues/639

**Comment by kensoh** [comment]
Also copying maintainer @jefleponot
