### ISSUE TITLE
Xunit XML Not Written on Timeout

### ISSUE THREAD

**Issue by seriallos** [casperjs/casperjs#805]
When a test times out, no XML it written out when specifying the --xunit CLI option.  This makes it difficult to quickly determine why a build has failed when using a system like Bamboo or Jenkins.

**Comment by kensoh** [comment]
@seriallos @mlb5000 @davidlinse bumping this, it looks to be still happening.

**Comment by kensoh** [comment]
Archiving issue using **ARCHIVE** label as CasperJS, like PhantomJS, is not actively maintained for now.
