### ISSUE TITLE
strange behaviour of captureSelector and getElementBounds

### ISSUE THREAD

**Issue by djfun** [casperjs/casperjs#810]
captureSelector and getElementBounds give "wrong" results after the web page gets moved around.

Example:

```
var casper = require('casper').create();

casper.start('http://google.com', function() {
    this.captureSelector('logo_before.png', '#lga');

    console.log("logo coordinates before scrolling");
    require('utils').dump(this.getElementBounds('#lga'));

    this.scrollToBottom();

    console.log("logo coordinates after scrolling");
    require('utils').dump(this.getElementBounds('#lga'));

    this.captureSelector('logo_after.png', '#lga');

    console.log("logo coordinates after scrolling and taking another screenshot");
    require('utils').dump(this.getElementBounds('#lga'));
});

casper.run();
```

Before the scrolling top is 49 and casperjs takes the correct screenshot. After scrolling top is -96 and the position of the screenshot is also off.
After the second screenshot is taken however, the top coordinate is 49 again.

**Comment by kensoh** [comment]
@djfun I'm a CasperJS user for 2 years and browsing through open issues.

I've tried your code and it seems that the screenshot issue is now resolved. I tried for both cases when viewport is defined and using default. A total of 4 screenshots are created and looks correct.

When default viewport which is very small is used, the top is -86 after scrolling, with screenshots ok. When viewport is width: 1366, height: 768, the top looks to be 48 consistently, with screenshots ok.

**Comment by kensoh** [comment]
@djfun closing this issue for now as the screen capture now appears to be working using latest CasperJS v1.1.4 and PhantomJS v2.1.1. The top is negative but I guess that is similar behavior when we try to scroll up on Safari for example, we can see part of the top in translucent going above the address bar. Thanks for raising this! But please reopen if you are still having issue on it :)
