### ISSUE TITLE
casperjs cache 

### ISSUE THREAD

**Issue by hasanyousuf** [casperjs/casperjs#845]
Hi!

I am having a issue with cache I think. How can I clear the cache using casperjs? As we have fixed a bug in the current system but casperjs is still loading the buggy page. 

I have also passed the phantomjs command line parameters to my grunt file '--disk-cache=false','--local-storage-path=/home/mydir' and nothing is working. I am totally stuck here.

**Comment by BIGjuevos** [comment]
I'm going to assume this issue is stale at this point, if you still need help on this, please re-open.
