### ISSUE TITLE
screenshot fails to save when using `waitFor` and specific selector but saves when using `body` as selector

### ISSUE THREAD

**Issue by jcollum-hcg** [casperjs/casperjs#853]
Failing code: 

```js
  this.waitFor((function() {
    return this.evaluate(function() {
      return document.querySelectorAll("DIV.choices").length > 0;
    });
  }), (function() {
    return this.captureSelector("./test/screencaps/DIV-choices.png", "DIV.choices");
  }), (function() {
    this.capture('./test/screencaps/failure-report-view.png');
    return this.echo("I can't haz my screenshot.").exit();
  }));
```

Error: 

```
[error] [phantom] Failed to save screenshot to /home/dev/projects/proj/test/screencaps/DIV-choices.png; please check permissions
```

Working code: 

```js
  this.waitFor((function() {
    return this.evaluate(function() {
      return document.querySelectorAll("DIV.choices").length > 0;
    });
  }), (function() {
    return this.captureSelector("./test/screencaps/DIV-choices.png", "body");
  }), (function() {
    this.capture('./test/screencaps/failure-report-view.png');
    return this.echo("I can't haz my screenshot.").exit();
  }));
```

The error is a bit misleading -- it's not a permissions issue, it appears to be a capturing issue. But the capture can't have failed, logically, since I'm waiting for the `DIV.choices` to be present before calling the capture. 

The workaround is fine (capture `body` instead) but I wanted to put this here in case anyone else runs into this. I think the error message could be improved.

**Comment by dgreene1** [comment]
If I'm understanding this correctly, then that means that captureSelector is a broken feature since it's purpose is to capture something lower in the dom tree than body, right?

**Comment by mickaelandrieu** [comment]
When asking for help, please ask your question [on the mailing list ](http://groups.google.com/group/casperjs) first.

If you feel that you need to report an issue against CasperJS (and you are sure that it is not a problem specific to your installation), please include at least:
- the platform you are running on (like here: CentOS)
- the CasperJS version you are using
- the engine type and version you are using
- a minimal example script and/or description of the specific situation that helps to *reproduce* your problem

Thank you.

(Feel free to re-open this issue if you come back with more specific information and asking on the mailing list did not lead to a solution)

**Comment by dgreene1** [comment]
@mickaelandrieu the right reason for closing this might be because of https://github.com/ariya/phantomjs/issues/11632
