### ISSUE TITLE
new version tries to require node modules...

### ISSUE THREAD

**Issue by xShirase** [casperjs/casperjs#858]
I migrated my working node.js app to a new server today. The app spawns casperjs processes to do stuff.

Problem :

It doesn't run anymore

Why?

output casperjs --version from any folder but the one where my node app is installed :

```
root@xxxxx:/var# casperjs --version
1.1.0-beta3
```

now from the folder where my node app is installed :

```
root@xxxxx:/var/nodeapp# casperjs --version
Error: Cannot find module 'sys'

  phantomjs://bootstrap.js:289
  phantomjs://bootstrap.js:254 in require
  /var/nodeapp/node_modules/system/engines/node/system.js:8
  /var/nodeapp/node_modules/system/engines/node/system.js:45
1.1.0-beta3
```

Isn't that weird? :D Thanks for any insights

Edit : Tried uninstalling casper, then reinstalling from npm (I used github before). Same error.

**Comment by istr** [comment]
Seems that this needs some re-ordering of the bootstrap code. Maybe it could help to not ```require``` in the outer part (bootstrap.js, last line) of the init code, but use the patched require after it is set, to nail down the path preferences.

Investigating along that line.

**Comment by kensoh** [comment]
Archiving issue using **ARCHIVE** label as CasperJS, like PhantomJS, is not actively maintained for now.
