### ISSUE TITLE
casperjs.exe does not work with phantomjs installed from npm

### ISSUE THREAD

**Issue by mlb5000** [casperjs/casperjs#872]
If you install phantomjs from npm it drops a phantom.bat file in your PATH, but casperjs.exe won't find it due to line 160 in the .NET runner:

```
psi.UseShellExecute = false;
```

Is there a reason why this is set to false?  Will it not work in Mono if it tries to execute through the Shell?

**Comment by kensoh** [comment]
@mlb5000 it looks like that line of code is still in current version. Not sure if the issue is still happening for you using CasperJS v1.1.4 and PhantomJS v2.1.1?

**Comment by kensoh** [comment]
Closing this issue for now as it hasn't gotten new replies or discussion for 3 years. But do reopen if anything!
