### ISSUE TITLE
CasperJS sometimes fails to submit a form (Windows only)

### ISSUE THREAD

**Issue by zirtec** [casperjs/casperjs#887]
I have a simple casperjs test that submits a form. It always works on my computer (OSX) but fails _most of the time_ on Windows 7/8 when executed with other tests.

```
casper.test.begin('Search', function(test) {

  casper.start('http://localhost:8080/site', function() {
    this.fill('#search-form, { query: 'good' }, false);
    this.click('#search-form button');
  });

  casper.waitForUrl('http://localhost:8080/site/search', function() {
    test.assertUrlMatch('http://localhost:8080/site/search?query=summary')
  });
});
```

Yields (most of the time):

```
subject: false
currentUrl: 'http://localhost:8080/site/search?query='
pattern: 'http://localhost:8080/site/search?query=good'
```

The server logs show casperjs/phatomjs tried to access `search` with an empty query.
The test works fine when run alone on Windows 7/8.
It also works on OSX, even in a test "suite".
Another test with a few simple assertExists can break the form submit test.

```
$ casperjs --version
1.1.0-beta3
$ phantomjs --version
1.9.7
```

Something wrong with my script? In the affirmative, any workaround? Any testcase needed?

Thanks

(was originally posted on https://groups.google.com/forum/#!topic/casperjs/6-6PqM1K--8)

**Comment by kensoh** [comment]
@zirtec this has been a while.. If you add an explicit wait for a couple of seconds after filling the form, will it still fail? My own experience is somehow CasperJS/PhantomJS runs slower on Windows. Maybe the website elements need some lag time to register the form-filling action or some validation-events, and not ready by the time search is clicked.

**Comment by kensoh** [comment]
Hi @zirtec not sure if this issue is resolved for you with above suggestion and latest CasperJS v1.1.4 + PhantomJS v2.1.1? Closing this for now as haven't seen other reports of this issue, but please reopen if it is still happening. Thanks for raising this!
