### ISSUE TITLE
casperjs needs a pty?

### ISSUE THREAD

**Issue by jedi4ever** [casperjs/casperjs#901]
I'm trying to run a casperjs script as a daemon. https://github.com/jedi4ever/gars
- When running the script from a shell this works fine
- using nohup/forever just gives a generic error on File Read in event.js
- Then I've tried running the command inside pty.js and nohup/forever works fine.

I'm assuming it tries to read stdin somewhere to possibly read a script from it.
Maybe we should check the tty/pty and no read anything from stdin?

Using https://www.npmjs.org/package/ttys

**Comment by kensoh** [comment]
Hi @jedi4ever not sure if this issue is resolved for you with latest CasperJS v1.1.4 and PhantomJS v2.1.1? Closing this for now as it seems to work for Mickael and I haven't see other reports of this issue, but please reopen if it is still happening. Thanks for raising this!
