### ISSUE TITLE
Sample tests failing

### ISSUE THREAD

**Issue by davidlinse** [casperjs/casperjs#915]
I think we might have some issues in the `samples/`.
e.g. when running the `steptimeout` example on latest `HEAD` (SHA1: e14544abfae194c4b2061fe10824051cc0fe68dc) .

Without `test` sub-command.

```
$ bin/casperjs --verbose=true --log-level=debug samples/steptimeout.js 
Testing with timeout=1000ms, please be patient.
[info] [phantom] Starting...
[info] [phantom] Running suite: 10 steps
[debug] [phantom] Successfully injected Casper client-side utilities
CasperError: casper.test property is only available using the `casperjs test` command
  /Users/user/git/casperjs/modules/casper.js:179
casper
```

With `test` sub-command:

```
$ bin/casperjs test --verbose=true --log-level=debug samples/steptimeout.js 
Test file: samples/steptimeout.js                                               
Fatal: you can't override the preconfigured casper instance in a test environment.
Docs: http://docs.casperjs.org/en/latest/testing.html#test-command-args-and-options
```

I wonder if the samples shouldn't be included somehow in either the test or build process ? 

PS: I'm not familiar with _coffeescript_ so i can't fix them, but i'll try to have a look at the `.js` examples at least and see if i can fix some.

~david

**Comment by BIGjuevos** [comment]
@mickaelandrieu Is this still a mergeable thing?  Got a bit to look at it?

**Comment by kensoh** [comment]
Closing this issue for now as it might not be relevant now, but do reopen if anything, thanks guys!
