### ISSUE TITLE
downloading files - please qualify homepage and documentation with size/time limits

### ISSUE THREAD

**Issue by pilavdzic** [casperjs/casperjs#938]
One of the main features of casperjs, touted on the homepage, and very useful for automation, is the ability to download files. 

Please qualify on the home that casper can only download small files that take less than a few seconds to download. A 50MB file (tested in my app through https GET yields a file of 0 bytes in size, yet says successful, sorry I cannot give that link) however I also put together this simple test case, see the following example for a 100MB file yields runtime error R6016 - not enough space for thread data. 

Please qualify the claim on the homepage that claims CasperJS can do this, it causes a lot of wasted time and frustration because this does not work although everyone from reading the homepage would expect that it does exactly this, its one of the major features. As of now, it is completely broken, for more than one reason. 

I tried the latest beta casperjs, and use the following command:

```
casperjs --ignore-ssl-errors=yes --web-security=no --verbose --log-level=debug --direct downloadsamplefile.js
```

using the following code:

``` js
var casper = require('casper').create({
    pageSettings: {
        webSecurityEnabled: false
    },
    settings: {
        resourceTimeout: 60000
    }
});

casper.start('http://www.wswd.net/testdownloadfiles.php', function () {
        this.echo(this.getTitle());
});

casper.then(function() {
    this.download('http://www.wswd.net/testdownloadfiles/100MB.zip', 'c:\\mytestfile.txt', 'get');
});

casper.run();
```

Even once these two issues are fixed, the homepage and documentation should still qualify with "download files up to 2GB in size" please.

**Comment by sekel** [comment]
+1 for this.

**Comment by pilavdzic** [comment]
I have tested trying to downloading a file of type .bak (a database file) through https after logging into a website. The file is 100MB. It starts the download then I get a zero byte file as a result. I have increased the timeout limit. From looking through phantomjs bug reports, there are a variety of issues ranging from what file types can be download through to what sizes, most of the bug reports have a lot of action but still remain unfixed. 

Can anyone chime in about things they did manage to download successfully so we have some indication of what file types/sizes DO work?

**Comment by maxko87** [comment]
I don't believe setting `settings.resourceTimeout: 60000` actually does anything -- `resourceTimeout` is a flag on the `pageSettings` option in PhantomJS, but CasperJS doesn't allow for it to be set.

**Comment by kensoh** [comment]
Tagging on a related new pull request which adds a new event for 'fileDownloadError' - #1835

**Comment by kensoh** [comment]
Closing this issue for now as it hasn't gotten new replies or discussion for almost 2 years. But do reopen if anything!
