### ISSUE TITLE
variables in casper object are not documented.

### ISSUE THREAD

**Issue by crocket** [casperjs/casperjs#942]
Currently, casper seems to have

``` defaults
options
cli
colorizer
mouse
popups
checker
currentResponse
currentUrl
currentHTTPStatus
history
loadInProgress
navigationRequested
browserInitializing
logFormats
logLevels
logStyles
page
pendingWait
requestUrl
resources
result
started
step
steps
waiters
_test
_events
startTime
mainPage
```

For now, only options variable is documented on http://docs.casperjs.org/en/latest/modules/index.html

Since casper.page was not documented, I had to spend a significant sum of time on searching.

Can you please document casper object variables on API documentation?

**Comment by kensoh** [comment]
Bumping up this thread. I'm a CasperJS user for couple of years. Now looking through open issues.

**Comment by kensoh** [comment]
Closing this issue for now as it hasn't gotten new replies or discussion for 2+ years. But do reopen if this is still important to you or any subscribers to this issue!
