### ISSUE TITLE
Calls to test.setup() should be queued along with calls to test.begin()

### ISSUE THREAD

**Issue by abelnation** [casperjs/casperjs#949]
easy source of bugs.  one might want to call setup more than once over the course of a test suite, e.g.

```
// PSEUDOCODE
var hosts = ["host1.com", "host2.com", "host3.com"];
for (var i = 0; i < hosts.length; i++) {
   test.setup(function() {
    connect(hosts[i]);
  });
  test.begin(function(test) {
    // do test #1
  }
  test.begin(function(test) {
    // do test #2
  }
}
```

by the time we run the tests for host2, setup() will have already been overwritten by the setup for test 3

**Comment by kensoh** [comment]
Bumping up and copying maintainer @jefleponot

**Comment by kensoh** [comment]
Archiving issue using **ARCHIVE** label as CasperJS, like PhantomJS, is not actively maintained for now.
