### ISSUE TITLE
proxy-type on windows

### ISSUE THREAD

**Issue by hdf** [casperjs/casperjs#952]
Can't access phantomjs **proxy-type** option from within code run by casperjs, and this is a problem, as on windows connecting to a site is incredibly slow, if no proxy is being used.
An alternative solution would be for casperjs to specify **proxy-type="none"** as default if run on windows.
(I know I can start casperjs with the --proxy-type option, but sometimes that is not an option.)

**Comment by kensoh** [comment]
@hdf is this issue still happening for you? I'm looking through open issues.

**Comment by hdf** [comment]
It seems to be working fine now. On Windows it starts with the default of no proxy, as it should. Also, I think you can set the **proxy-type** parameter thusly at run-time:
```
... require('casper').create({
  { parameters: { 'proxy': 'none' } },
  ...
```

**Comment by kensoh** [comment]
Thanks @hdf for your quick reply, and adding on this additional detail to the issue! I haven't used this parameter before but it is good to be tracked here for future reference.
