### ISSUE TITLE
Bind polyfill doesn't work when testing Ember.js apps

### ISSUE THREAD

**Issue by ErisDS** [casperjs/casperjs#953]
I'm in the process of switching over all of [Ghost's Casper.js tests](https://github.com/TryGhost/Ghost/tree/115865010eb65b3155da652e12e1a489137a070f/core/test/functional/admin) for our admin panel from working with the old backbone.js admin, to the shiny new Ember admin.

Some parts of the Ember admin use `.bind`, and this causes errors like:

> TypeError: 'undefined' is not a function (evaluating 'this.sendAction.bind(this, 'uploadStarted')')

I know that Phantom.js doesn't support `.bind` and that Casper.js includes a polyfill, so I'm a bit unsure as to why it isn't working. I guess something to do with how Ember is loaded vs how Casper is loaded. Short term I'm just going to switch to using lodash's `.bind` function, but I would like to investigate this further and find a better solution if possible.

**Comment by dioptre** [comment]
This is such an awful bug - did you ever close this?

**Comment by kensoh** [comment]
Bumping up this thread

**Comment by kensoh** [comment]
And also copying @jefleponot

**Comment by kensoh** [comment]
Archiving issue using **ARCHIVE** label as CasperJS, like PhantomJS, is not actively maintained for now.
