### ISSUE TITLE
Make the ``concise`` don't display the ``echo(s)``

### ISSUE THREAD

**Issue by mickaelandrieu** [casperjs/casperjs#954]
This PR https://github.com/TryGhost/Ghost/pull/2987 from @ErisDS make sense.

I don't know how to for now, but ``--concise`` option should remove ``echo`` calls from testsuite ouput.

What do you think @n1k0 ?

**Comment by BIGjuevos** [comment]
Closing. Please feel free to re-open or put up the PR @mickaelandrieu
