### ISSUE TITLE
Hover events not working? Mouseover not firing.

### ISSUE THREAD

**Issue by KingScooty** [casperjs/casperjs#959]
I'm trying to run some hover tests, to ensure the right classes get applied to the right elements when hovered over, but all the tests are constantly failing. It doesn't look like mouseover seems to be doing anything?

Excuse the syntax, i'm using mocha casperjs for assertions.

```javascript
        casper.then(function(){
          this.mouseEvent('mouseover', '.proto-item');
        });

        casper.then(function() {
          this.exists('.proto-item--hover').should.be.true;
        })
```

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:** 
Looks to be a stale help request. Assuming you've moved on to better and cooler things.  Please feel free to re-open if this is still an active issue for you.
