### ISSUE TITLE
Not able to reuse casper instance in casper test module once popup/window is closed.

### ISSUE THREAD

**Issue by suratsurat51** [casperjs/casperjs#963]
I am running a casper test suite using casper version 1.1.0 beta 3 to test my application.
In the process of testing , if any pop-up/window is closed in my application, then I am not able to proceed further because of the issue below.

#    error: cannot access member `customHeaders' of deleted QObject

When browsed further on this issue , I came to the understanding that this is because of the page object being closed and need new page object to be created like,
 "this.page = require('webpage').create() ;"
After this I am not getting that error, but I am not able to open any page it seems like Casperjs got stuck or waiting for something.

Could anyone please help me understand this?

**Comment by BIGjuevos** [comment]
We released a patch to the problem of popups in #1354 .  Please feel free to update to 1.1.1 and see if you still have the issue.
