### ISSUE TITLE
Clicking serious issue!

### ISSUE THREAD

**Issue by ciprian-laitz** [casperjs/casperjs#964]
Hi, guys!

Before you close my issue hinking it's been solved previously, please hear me out. I'm trying to click on an anchor located in a cell from a DHTMLX grid row. But i'm not managing to do so. The ```href``` of the anchor contains a javascript function that opens a new popup window. 

I've tried all the answers I could find on the web, including evaluating the function from the href, generating a click event object and dispatching it, adding a ```onclick``` attribute, clicking from casper, clicking from javascript and clicking with ```casper.mouse.click```.

Nothing helped! Instead of clicking on the link, it clicks on the ```td```, the parent of the anchor, and selects the row. I've attached a small capture, hope it helps. 

Let me know if you can help and what code would you like me to post here. @n1k0 , would really appreciate your help on this one, as it beat me and my colleagues...

Thanks in advance!
Ciprian
![afterwait](https://cloud.githubusercontent.com/assets/6741165/3456214/3f8cb244-01ec-11e4-8dc1-3851edde4d6b.png)

UPDATE: forgot to mention that casper is 1.1.0beta3 and PhantomJS is 1.9.7

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:** 
Looks to be a stale help request. Assuming you've moved on to better and cooler things.  Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
