### ISSUE TITLE
waitForResource: how to get the resource i've waited for

### ISSUE THREAD

**Issue by apelliciari** [casperjs/casperjs#965]
``` javascript
casper.test.begin('Test foo', 1, function suite(test) {
    casper.start("http://www.foo.com", function() {
        casper.waitForResource("bar", function(resource) {
            casper.echo(resource.url);
        });
    });

    casper.run(function() {
        test.done();
    });
});
```

`casper.echo` returns www.foo.com resource (the one in `casper.start`), not the one with "bar".

How can I get the resource i've waited for with `waitForResource`?

Thanks,
Alessandro

PS: I've posted the same question on stackoverflow
https://stackoverflow.com/questions/24559234/casperjs-waitforresource-how-to-get-the-resource-ive-waited-for

**Comment by B2F** [comment]
Hello,

I experienced the exact same problem. The waitForRessource seem to detect the correct request url but it's callback argument (ressource in the above example) will alway have the page url (in casper.start or thenOpen) and the ressource data is null.

Any clue why this is happening ?

I can't load external images due to this.

**Comment by peter-mouland** [comment]
I have a similar use case.  I'm testing the analytics code on our page - so the waitForResource event is brilliant for this.   Unfortunately, the callback is a standard CasperJS callback so doesn't give us the resource we've just waited for.  It would be nice to write some assertions based on the resource returned.

I have a work around using global side-effects, but it would be really nice not to have to do this.

```JS
var metrics = {};
var config = require('../../src/config');

function resetMetrics() {
    metrics = {};
}

function setMetrics(requestData, resource) {
    if (!isAnalytics(requestData)) { return ; }
    requestData.url.split('?')[1].split('&').forEach(function(key) {
        metrics[key.split('=')[0]] = decodeURIComponent(key.split('=')[1]);
    });
}

function isAnalytics(resource) {
    return resource.url.indexOf('metrics.url.com') > 0 &&
    resource.url.indexOf('account-name') > 0;
}

function trackedVar(variable) {
    var eVarOrProp = config.maps.variables[variable][0].replace('prop','c').replace('eVar','v')
    return metrics[eVarOrProp];
}
function trackedEvent(event) {
    var value = metrics.events;
    return value === config.maps.events[event];
}

casper.test.begin('Link clicks work', 6, function(test) {
    casper
        .start('http://localhost:9292/links')
        .on('resource.requested', setMetrics)
        .thenClick('#standard-link')
        .waitForResource(isAnalytics)
        .then(function() {
            test.assertEquals(trackedVar('linkDetails'), '||click|||standard-link|shop:prdslt:evo');
            test.assertEquals(trackedVar('pageName'), 'shop:prdslt:evo');
            test.assert(trackedEvent('linkClick'));
        })
        .then(resetMetrics)
        .thenClick('#apostrophe-link')
        .waitForResource(isAnalytics)
        .then(function() {
            test.assertEquals(trackedVar('linkDetails'), '||click|||apostrophe-link:prdslt:evo');
            test.assertEquals(trackedVar('pageName'), 'shop:prdslt:evo');
            test.assert(trackedEvent('linkClick'));
        })
        .then(resetMetrics)
        .run(function() {
            test.done();
        });
});

```

**Comment by kensoh** [comment]
Hi @apelliciari, I tried running your sample script and it is still returning the URL of the original page. I'm a CasperJS user for couple of years. Browsing through open issues..

```
# Test Vodafone ADSL e Telefono page
http://www.vodafone.it/portal/Privati/Tariffe-e-Prodotti/IperFibra--ADSL-e-Telefono/adsl-e-telefono
{
    "contentType": "text/html;charset=ISO-8859-1",
    "headers": [
```

**Comment by kensoh** [comment]
Archiving issue using **ARCHIVE** label as CasperJS, like PhantomJS, is not actively maintained for now.
