### ISSUE TITLE
capserjs can't render the pagination section

### ISSUE THREAD

**Issue by qiuqiang1985** [casperjs/casperjs#971]
url----http://wenda.taobao.com/thread/detail/678759063.htm

when opened this page, the pagination setction cann't be rendered.

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:** 
Looks to be a stale help request. Assuming you've moved on to better and cooler things.  Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
