### ISSUE TITLE
Access phantom through casperjs ?

### ISSUE THREAD

**Issue by mickaelandrieu** [casperjs/casperjs#972]
As you know we can access cli from phantom.cliArgs, but in casper Api we don't have free access to phantom.

Sometimes I need to access phantom because casper don't let me access to all phantom's properties or just I need to use some cools features of phantom like callbacks.

But I wonder if it's a good idea/practice to do it... for now I'm working on a forked repository where I've added `this.phantom = phantom;` in casper module.

What do you think @n1k0 @laurentj ?

**Comment by nigulasikk** [comment]
is there any access to set  page.paperSize in casperjs?

**Comment by mickaelandrieu** [comment]
@nigulasikk read my previous comment :)
