### ISSUE TITLE
Testing jQuery Geocomplete Plugin (Autocomplete)

### ISSUE THREAD

**Issue by crebuh** [casperjs/casperjs#976]
Hello Guys!

We have written several test cases with casperjs now. In comparison to other testing frameworks it works like charm. But there is one crucial part of our app, where we fail to write a suitable test case.

In our app we have integrated a type of autocomplete plugin which is called Geocomplete (http://ubilabs.github.io/geocomplete/) which makes it possible to fetch geodata from the Google Maps Api. 

There is the following workflow. On the start page of our site there is a form with one single input field, which is used for the autocomplete functionality. There the user can enter the name of a specific city and Google returns the data. In the background a backbone model is populated with that data.

Here is the code of the testcase:

```
casper.test.begin('Test User Login Form', 4, function suite(test) {

    casper.options.verbose = true;
    casper.options.logLevel = 'debug';
    var url = 'http://localhost:8889/';
    var session;

    casper.start(url);

    casper.test.comment('Start Testing');

    casper.waitFor(function check() {
        return this.evaluate(function() {
            return document.getElementById('page-wrap');
        });
    }, function then() {
        casper.waitForSelector('#landingForm', function() {
            this.echo('waiting');
        });
    });
    
    // input is populated with a some letters
    casper.then(function() {
        casper.sendKeys('#landingForm input[name="location.name"]', 'Klag', {
            keepFocus: true
        });
    });

    // .pac-item container whill show the autocomplete suggestions
    casper.then(function() {
        casper.waitUntilVisible('.pac-item', function() {
            
            // we have tried several methods here like mouse_over + click etc.
            this.sendKeys('#landingForm input[name="location.name"]', casper.page.event.key.Down, {
                keepFocus: true
            });
            this.sendKeys('#landingForm input[name="location.name"]', casper.page.event.key.Enter, {
                keepFocus: true
            });
            // form is submitted
            this.click('#landingForm > div > div > div > span > button');
        });
    });

    casper.then(function() {
        // wait until next page is visible
        casper.waitUntilVisible('div.activity-pic', function() {
            // get backbone session model
            session = casper.evaluate(function() {
                return require('model/session');
            });
            // test if model was populated correctly with the data from google
            test.assertEquals(session.filterModel.attributes.location.name, 'Klagenfurt', 'Name equals expected values.');
        });
    });

    casper.run(function() {
        casper.test.comment('Ending Testing');
        test.done();
    });

});
```

The test

            test.assertEquals(session.filterModel.attributes.location.name, 'Klagenfurt', 'Name equals expected values.');

always fails and tells me that the name-attribute is undefined. The input field is filled in correclty with the name of the city. We have used the evaluate-method in other testcases to check the values and attributes of our models too, there it worked. 

Does anybody has the same problem?

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:** 
Looks to be a stale help request. Assuming you've moved on to better and cooler things.  Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
