### ISSUE TITLE
Need access to specific browser tabs

### ISSUE THREAD

**Issue by CookieManager** [casperjs/casperjs#978]
When one clicks on a link with a target = _blank, a new tab is opened by the browser. These child tabs can be accessed in PhantomJS - phantom.pages and also via Selenium when using PhantomJS. However, when using CasperJS, the only option seems to be popups, but this is not perfect either. The webpage may also have a popup open up when the link is clicked, so there is no separation of a genuine popup and a window. 

Moreover even when there are no popups, the casper.popups array has each frame as a separate popup. So it is impossible to access the 3rd of 4 open tabs for example, because if each tab has 4 frames, we are dealing with upto 16 items in casper.popups array. 

Given that each advertisement on a page is in its own frame, this functionality is needed. 

OR

If there is a way to access the underlying Phantom object, then we can use the phantom.pages to cycle through the various tabs

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:** 
Looks to be a stale help request. Assuming you've moved on to better and cooler things.  Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
