### ISSUE TITLE
casperjs breaks `require` if it's installed by `npm install -g casperjs`

### ISSUE THREAD

**Issue by crocket** [casperjs/casperjs#980]
The issue occurs with phantomjs 1.9.7.

If I execute `casperjs` installed by `npm install -g casperjs`, casperjs can't require nodejs modules.

Let's assume that the directory that contains `node_modules` is `A`.
If casperjs is not in `A` or one of subdirectories of `A` and I execute `casperjs b/c.js` at `A`, `A/b/c.js` can't require node modules located at `A/node_modules` because patchRequire expects to find nodejs modules at `A/b/node_modules`, and phantomjs somehow fails to require node modules at `A/node_modules`.

If casperjs is in `A` or one of subdirectories of `A`, it can require nodejs modules. Thus, if casperjs is located at `A/node_modules/casperjs/bin/casperjs`, since it is in one of subdirectories of `A`, I can require nodejs modules.

In some not-yet reproducible cases, It also can't require `/a/b/c.js` with `require("../c")` in `/a/b/d/test.js`.

**Comment by kensoh** [comment]
Hi @crocket, bumping up. It's been a while and not sure if this is still happening for your use scenario?

**Comment by crocket** [comment]
Sorry, man. I stopped developing for the web a long time ago. I think this issue should be either cared for by someone else or closed.

**Comment by kensoh** [comment]
@crocket no probs! Thanks for your quick reply
