### ISSUE TITLE
Async return from evaluate

### ISSUE THREAD

**Issue by denis-sokolov** [casperjs/casperjs#985]
Currently `evaluate` only passes the synchronous return value.
In JavaScript it seems natural to use async functions everywhere and there is plenty of use for such functionality.
A usage example is better than a thousand words:

``` javascript
casper.evaluateAsync(function(done){
  doStuff(function(...){
    done(42);
  });
}, function(result){
  casper.log(result);
});

casper.then(function(){
  // This would hapen after 42 is printed to console
});
```

It can already be achieved with `waitFor`, but a default friendly API would be very appreciated.

**Comment by kensoh** [comment]
@denis-sokolov it's been a while, bumping up this suggestion :)

**Comment by kensoh** [comment]
Closing this issue for now as it hasn't gotten new replies or discussion for 2+ years. But do reopen if anything!
