### ISSUE TITLE
download() function do not complete randomly and no error was thrown.

### ISSUE THREAD

**Issue by eloitay** [casperjs/casperjs#990]
Basically below is how I replicate this case, just take any array of string that comprises of around 100 to 200 image links and let casper run through and download each file. I presume this is sync code so connection should not be killed because of the fetch, I am unclear of what is happening in the download function that may cause this to happen but I took a look at the source and it seems logically fine.
I did a trace using fiddler and notice that all of the fetch end up with http 200 so it should mean that the server is fine.

 var currentSavePath = savePath.concat("/").concat(this.getTitle().concat("_files"));
    filesForDownload.forEach(function (e) {
        //mainSite.echo(e);
        var fileSavePath = currentSavePath.concat("/").concat(e.split('/').pop());
        //mainSite.echo(fileSavePath);
        if (!fs.exists(fileSavePath)) {
            mainSite.download(e, fileSavePath);
        } else {
            mainSite.echo("Skipping file, already existed. " + fileSavePath)
        }
    });

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:** 
Looks to be a stale help request. Assuming you've moved on to better and cooler things.  Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
