### ISSUE TITLE
About casper.thenopen()   asynchronous request question

### ISSUE THREAD

**Issue by design365** [casperjs/casperjs#993]
i have code follow:
for (var i = 1; i < =5; i++) { 
     console.log("run count:" + i);
     casper.thenOpen("xxxxxx.com",function(){
         //process the result
          console.log("result " + i);
    });
}
console.log("run finished!");

when run it, it show like :
"
run count:1
run count:2
run count:3
run count:4
run count:5
run finished!

result6
result6
result6
result6
result6
"

it seem like the “thenOpen" is a async request, but i do not want this , i want it work one by one ,  it should like this 
"
run count:1
result1

run count:2
result2

run count:3
result3
........

"

how can i do this? thanks for your help

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:** 
Looks to be a stale help request. Assuming you've moved on to better and cooler things.  Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
