### ISSUE TITLE
how to synchronous run

### ISSUE THREAD

**Issue by aivinray** [casperjs/casperjs#995]
I have a code as below:
```javascript
   function main() {
    casper.start();
    status = "A";
    while(true){
       if(status == "C"){
           casper.then(function(){
               status = "stop";  // the value status is stop  in second loop
           });
       }else{
           casper.then(function(){
               status = "C";  // modify status value in first loop
           });
       }
       if(status == "stop"){
           console.log("stop");
           break; // the loop should  break in second loop
       }
       console.log("run");
    }
    casper.run(function () {
        this.exit();
    });
}
```
 The excepted result should be as follows:
```
  C
  run
  stop
```
But the program falls  into an **infinite loop** in fact . the output is just run.
how do I do so that casper.then  can  execute in sync after  next statement?
I'm doing this just to use casper in the state machine. casper.then is required to  modify the value of global variables.But now I am puzzeled by above problem.

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:** 
Looks to be a stale help request. Assuming you've moved on to better and cooler things.  Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
