### ISSUE TITLE
getPageConent() do not return response of the server...

### ISSUE THREAD

**Issue by alexander-kudinov** [casperjs/casperjs#998]
getPageConent() do not return response of the server as I expect, it returns modified DOM by JS. So it works the same as getHTML() for pages.

Here is a simple test to show this:

casper.test.begin('Verify if GA code is installed', function suite(test) {
        casper.start();

        //timedoctor.com will redirect us to other URL but it doesn't matter for this case
        casper.thenOpen('http://www.timedoctor.com/benefits_managers.html', function(){

            casper.echo("Url: " + casper.getCurrentUrl())
            var page = casper.getPageContent();
            var utils = require('utils');
            utils.dump(casper.page);
            var GA_code = "UA-16699326-1";          //this pattern must be on that page!!!
   
            //I epxect to see some positive number there but I see -1 (pattern not found).
            //if i use test.assertTextExists(), it be able to find pattern 
            casper.echo("Found GA code on page at: " +page.search(GA_code)+" position");
        });

    casper.run(function () {
        test.done();
    });
});

The same in google group: https://groups.google.com/forum/#!topic/casperjs/GeLd8BNff3I

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:** 
Looks to be a stale help request. Assuming you've moved on to better and cooler things.  Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.
